### ISSUE TITLE
/smart-home-api/device-connection/0 net::ERR_ABORTED - 504 (Gateway Time-out)

### ISSUE THREAD

**Issue by orcema** [actions-on-google/smart-home-nodejs#104]
the code part here below held within the file 

> smart-home-provider-cloud.js 

is causing on regular interval (+/- 30sec) a **504 (Gateway Time-out)** in the client web browser.
Seems like this function below do not deliver any response to the client.
What is the purpose of this function ?
```
/**
 * Creates an Server Send Event source for a device.
 * Called from a device.
 */
app.get('/smart-home-api/device-connection/:deviceId', function (request, response) {
  const deviceId = request.params.deviceId;
  // console.log('get /smart-home-api/device-connection/' + deviceId);
  deviceConnections[deviceId] = response;

  response.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'X-Accel-Buffering': 'no',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type'
  });
  response.connection.setTimeout(0);
  response.on('close', function () {
    delete deviceConnections[deviceId];
  });
});
```

**Comment by orcema** [comment]
I suppose it shouldn't be related to a network bottlenecked because i set a debug break point at the line 

> deviceConnections[deviceId] = response;

I then use the internet browser to navigate to `/smart-home-api/device-connection/0` and the debug break point is hit immediately. When i release the execution of the program i get in the browser the 

> 504 (Gateway Time-out)

**Comment by lucaswadedavis** [comment]
Due to more than 9 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
