### ISSUE TITLE
Add new modes for ThermostatModes and availableModes

### ISSUE THREAD

**Issue by NQuillon** [actions-on-google/smart-home-nodejs#106]
Hi,

I'm working on a project where my thermostats have many modes which I want to manage with my Smart Home Actions.
These are my current traits for my devices :

"type": "action.devices.types.THERMOSTAT",
"traits": ["action.devices.traits.TemperatureSetting", "action.devices.traits.Modes"]

I'd like to have more modes for my device, like : 
 - eco (en) / eco (fr)
 - comfort (en) / confort (fr)
 - antifrost (en) / hors-gel (fr)
 - boost (en) / boost (fr)
 - auto (en) / auto (fr)

Is it possible to add them in one of these traits ?

Thanks in advance !

**Comment by Fleker** [comment]
These have been submitted and should be working now
