### ISSUE TITLE
request-sync response 404 Not Found

### ISSUE THREAD

**Issue by beckmx** [actions-on-google/smart-home-nodejs#114]
Hello, does anyone know what else is needed for the sync to work properly?

**Comment by Fleker** [comment]
The flow in this sample is:

* Open the sample web app in your browser and log in. You'll see no devices.
* Link account in your phone
Otherwise the Smart Home cloud account will not exist and cause the linking to fail.

https://github.com/actions-on-google/smart-home-nodejs/issues/111#issuecomment-370025008

**Comment by dannynash** [comment]
Hello. After linking account on my phone, I can added the customized action on google project.

But I met some problem when I added the device:

server log:
```
GET /oauth?response_type=code&client_id=ZxjqWpsYj3&redirect_uri=https://oauth-redirect.googleusercontent.com/r/homedemo-77485&state=CsACQU1uRHRTRkRJZTREZFBsV3R0NXpHYm9vQ21MWWhFMkhydEx4RUZSaG9YaEJJRDN4RW5vMXJyZlJrQ0w5MXAzbnE4OUY1TG1ZWkZqaUprVktEX19sbG4wVGZyVTNycHZBRG91ZnJaUHlFWWJBNnYwUEZtalRYUXFPV3NCTjVQU0RzU0R3d2ZZeUhuUjBpNWc3dl9HLUpBREVNM1kyaml4TUdSalJyWURUZWI4YkJHZUpEM0FrUXNtWUdiOC1oaGJKeEZzWktHS0JHOUdTc25WZmktb2ZURTB6RWN5N0VIbGNnQzB2NjNhVVY5UUFvRGtfX3plWGdrVlZKQUc5Q1A2dEZXQzhKTENFOTk1cW9FMnFDYWgxZW5oVzl3dTZRX0N1Yk0yY0ZGY0pGQWdfbDV5VlZ4RnhNdFdpemJjUXZ4VVQSHWNocm9tZWNhc3Q6Ly9zZXR0aW5ncy9oYW5kb2ZmGAEiPWh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvaG9tZWRlbW8tNzc0ODUqFmRhbm55LmNoZW5AY2hlbHBpcy5jb20yEmhvbWVkZW1vLTc3NDg1X2Rldg 302 0.877 ms - 1488
/token query {}
/token body { grant_type: 'authorization_code',
  code: '24h5mv14hd3400000000000000',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/homedemo-77485',
  client_id: 'ZxjqWpsYj3',
  client_secret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
client { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
handleAuthCode {}
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getAccessToken =  { uid: '785',
  accessToken: '32i4no89z9k000000000000000',
  refreshToken: '32i4no89z9k000000000000000' }
return getAccessToken =  { token_type: 'bearer',
  access_token: '32i4no89z9k000000000000000',
  refresh_token: '32i4no89z9k000000000000000' }
respond success { token_type: 'bearer',
  access_token: '32i4no89z9k000000000000000',
  refresh_token: '32i4no89z9k000000000000000' }
POST /token 200 1.461 ms - 112
POST / 404 0.518 ms - 140
POST / 404 0.628 ms - 140
POST / 404 0.630 ms - 140
POST / 404 0.631 ms - 140

``` 

It seems passed the auth, but then get 404 for 4 times.

On my phone:
![image uploaded from ios 3](https://user-images.githubusercontent.com/3911380/38197659-fe0e675a-36bb-11e8-8952-78d0785747cf.png)

Open in safari:
![image uploaded from ios 2](https://user-images.githubusercontent.com/3911380/38197652-f2a640e0-36bb-11e8-9081-fd066f8144ae.png)

Did I do something wrong?

b.t.w. Should I set fulfillment Url with: `https://{domain}/`,  `https://{domain}/smarthome ` or `https://{domain}/smart-home-api`

Thanks for your help.

**Comment by Fleker** [comment]
Your fulfillment URL should be a valid HTTPS endpoint, such as `https://example.com/smarthome`

This means a device can send a `POST` request to that URL and get a response. Is that the case?

**Comment by beckmx** [comment]
I got some time, and yes looks like the linking account is finally working, I created a new device and using the mock tester is outputting the list of devices, however if I open the google assistant and write "turn the table light on" it says my test app is not reachable and I see my console of the app but nothing gets there. any ideas what can it be? would it serve if I record it?

**Comment by Fleker** [comment]
You will need to go to the [Actions console](http://console.actions.google.com) periodically and re-enable testing.
