### ISSUE TITLE
odd behavior for the web browser on manual page refresh 

### ISSUE THREAD

**Issue by orcema** [actions-on-google/smart-home-nodejs#117]
I have an odd behavior for the web browser when i hit the page refresh button.
If there are less than 3 devices, the refresh executes without issues.
Starting from the 3th device and more if i hit refresh button the browser sticks until i abort the refresh and manually request a new refresh. The second time it executes every time.
This happens only to the Chrome Webbrowser. Firefox has not such an issue.
How could i figure out the origin of the problem ?

![image](https://user-images.githubusercontent.com/12600222/37500012-5b1a1fe6-28c7-11e8-8505-65a995779d2c.png)

**Comment by Fleker** [comment]
I've seen this problem occasionally. Unfortunately I have not identified where it's happening.

**Comment by orcema** [comment]
Ii realized that removing a device without page refresh is an issue ( based on master branch).
Here on the picture below you can see that i added 2 devices, removed the 2nd device and added a new device that took the space of the deleted device.
The issue is that for the newly created device, the server was not notified ! Thus the server hasn't any clue about this device created by the user.
Combined with the odd explorer behavior on page refresh, i think this is a no go for me continuing to use the Polymer web components.

![image](https://user-images.githubusercontent.com/12600222/37551298-95621b14-299d-11e8-9552-4764aa7c5524.png)

**Comment by lucaswadedavis** [comment]
Due to more than 12 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the issue with fresh information.
