### ISSUE TITLE
Electrical fan speed mode create

### ISSUE THREAD

**Issue by vava24680** [actions-on-google/smart-home-nodejs#121]
Hi i want to control the speed of a electrical fan, but I don't sees any mode related to it so ask here may I have one custom mode and its settings? 

By the way, I want to speed mode has three settings, fast , medium, slow respectively

Thank you very much

**Comment by Fleker** [comment]
Mode "fan speed" already exists.
value: "fan speed", "speed"

Setting "medium" exists.

I'll add in fast and slow.

**Comment by vava24680** [comment]
Thank You.
Does it means I can use it now?

**Comment by Fleker** [comment]
I'll update the thread when the new grammars are rolled out.

**Comment by vava24680** [comment]
Hi Mr. Fleker
After I applied those values you mentioned above,
the Google Home just replayed me with "That mode is not available for my fan"
Do you know what's going on?

**Comment by Fleker** [comment]
We've added the [`FanSpeed`](https://developers.google.com/actions/smarthome/traits/fanspeed) trait for smart fans.
