### ISSUE TITLE
Scene activation - Italian

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#122]
Hi - 
can you confirm that activating scenes is working with Italian now? If so, what's the correct phrase?
I've got some users complaining that they don't work - 

Thanks :)

**Comment by Fleker** [comment]
I am unsure whether scenes are working in Italian specifically. Saying something like "Activate party mode" should cause the scene named "Party Mode" to activate.

**Comment by p3g4asus** [comment]
I can confirm that scenes are working in english and are NOT working in italian. You'd better to convert  action.devices.types.SCENE into action.devices.types.LIGHT to use them in italian.

**Comment by Fleker** [comment]
Right now scenes are not supported in Italian.

**Comment by madgeni** [comment]
Thanks @Fleker  👍
