### ISSUE TITLE
TemperatureSetting will not report the correct value sometimes

### ISSUE THREAD

**Issue by p3g4asus** [actions-on-google/smart-home-nodejs#123]
It would be great if one can cntrol a device that requires numeric commands using action.devices.types.THERMOSTAT that supports action.devices.traits.TemperatureSetting that can understand any number told. This is actually possible but there is an issue. If I say "set devicename to **206**" it will answer "OK, setting the 'devicename' to **6** degrees." Same story with all the values >=200 and <=299. Greater or lower values are apparently all working fine. This odd behaviour happens in Italian and in English in the same way.
I think that it is not supposed to work like this, Correct me if I am wrong, please.
Thank you

**Comment by Fleker** [comment]
So this works fine if you try setting to *106* and works fine is you set to *306*, but not *206*?

**Comment by Fleker** [comment]
This is working as intended as if the user say "Set thermostat to 66" whether the speech-to-text would detect that as "to 66" or "266". As thermostats are not expected to go that high, this is not going to be resolved.

If you are looking for different ways to control your devices, you may want to look into the [Brightness trait](https://developers.google.com/actions/smarthome/traits/brightness) or [Modes](https://developers.google.com/actions/smarthome/traits/modes).
