### ISSUE TITLE
Google action does not access my fulfillment URL

### ISSUE THREAD

**Issue by koka18** [actions-on-google/smart-home-nodejs#124]
I have created a Smart Home Actions project in google actions console, and setup the OAuth2 and fulfillment to process the Smart Home intents and return responses. After I add my test action to Google Assistant, the Google Assistant App is able to redirect to my OAuth2 page and successfully get the tokens from my OAuth2 server after the authentication. However, after the authentication, the Google Assistant App always shows “Something went wrong. Try again.”

I have tried many times to use the command line (gactions update) on my server to update the fulfillment URL and each time it shows my project was successfully updated. I also checked the fulfillment URL on the Google Actions Console and found it is pointed to my server correctly. However, I found the Google server never access my fulfillment URL after authentication, as my fulfillment logic will record all the access activities for debug.

I have tried to test smart-home-nodejs on another server (server A) before and successfully got everything working well. After that, I have implemented the OAuth2 and fulfillment by my own code on that server (server A) and also everything working well with my own code including SYNC, QUERY and EXECUTE requests. Now, I just use the same code (my code) on a new server and all the configurations are the same, but I found the Google server does not access my fulfillment URL. Is there any step / procedure that I am missing?

**Comment by Fleker** [comment]
Can you check [Stackdriver](https://developers.google.com/actions/smarthome/logging) to see what errors may be happening during the account linking step? It could be an issue to your SYNC response.

**Comment by mostafaramadann** [comment]
> I have created a Smart Home Actions project in google actions console, and setup the OAuth2 and fulfillment to process the Smart Home intents and return responses. After I add my test action to Google Assistant, the Google Assistant App is able to redirect to my OAuth2 page and successfully get the tokens from my OAuth2 server after the authentication. However, after the authentication, the Google Assistant App always shows “Something went wrong. Try again.”
> 
> I have tried many times to use the command line (gactions update) on my server to update the fulfillment URL and each time it shows my project was successfully updated. I also checked the fulfillment URL on the Google Actions Console and found it is pointed to my server correctly. However, I found the Google server never access my fulfillment URL after authentication, as my fulfillment logic will record all the access activities for debug.
> 
> I have tried to test smart-home-nodejs on another server (server A) before and successfully got everything working well. After that, I have implemented the OAuth2 and fulfillment by my own code on that server (server A) and also everything working well with my own code including SYNC, QUERY and EXECUTE requests. Now, I just use the same code (my code) on a new server and all the configurations are the same, but I found the Google server does not access my fulfillment URL. Is there any step / procedure that I am missing?

How did you solve it? I am having the same problem. but instead, Google Cloud functions access the fulfillment route several times before giving "Something went wrong. Try again." my fulfillment function returns the json response and 200 status code. what could be wrong ?
