### ISSUE TITLE
Some Modes for Thermostat type are not working anymore

### ISSUE THREAD

**Issue by bobnmt** [actions-on-google/smart-home-nodejs#125]
Hi,

Since last week we can't use anymore some Modes added recently for Thermostat type.
We have a "mode not available" message as answer when we request these modes.

Here are the concerned modes:
- eco (en) / eco (fr)
- comfort (en) / confort (fr)
- antifrost (en) / hors-gel (fr)
- boost (en) / boost (fr)

Do you know why?

Here is the sync object we send:

`{
    "id": "***********************",
    "type": "action.devices.types.THERMOSTAT",
    "traits": ["action.devices.traits.TemperatureSetting", "action.devices.traits.Modes"],
    "name": {
        "name": "my name"
    },
    "willReportState": true,
    "attributes": {
        "availableThermostatModes": "off,heat,on",
        "thermostatTemperatureUnit": "C",
        "availableModes": [{
            "name": "mode",
            "name_values": [{
                    "name_synonym": ["mode"],
                    "lang": "en"
                },
                {
                    "name_synonym": ["mode"],
                    "lang": "fr"
                }
            ],
            "settings": [{
                    "setting_name": "auto",
                    "setting_values": [{
                            "setting_synonym": ["auto", "automatic"],
                            "lang": "en"
                        },
                        {
                            "setting_synonym": ["auto", "automatique"],
                            "lang": "fr"
                        }
                    ]
                },
                {
                    "setting_name": "eco",
                    "setting_values": [{
                            "setting_synonym": ["eco", "economic"],
                            "lang": "en"
                        },
                        {
                            "setting_synonym": ["eco", "economique"],
                            "lang": "fr"
                        }
                    ]
                },
                {
                    "setting_name": "comfort",
                    "setting_values": [{
                            "setting_synonym": ["comfort"],
                            "lang": "en"
                        },
                        {
                            "setting_synonym": ["confort"],
                            "lang": "fr"
                        }
                    ]
                },
                {
                    "setting_name": "antifrost",
                    "setting_values": [{
                            "setting_synonym": ["antifrost"],
                            "lang": "en"
                        },
                        {
                            "setting_synonym": ["hors-gel"],
                            "lang": "fr"
                        }
                    ]
                },
                {
                    "setting_name": "boost",
                    "setting_values": [{
                            "setting_synonym": ["boost"],
                            "lang": "en"
                        },
                        {
                            "setting_synonym": ["boost"],
                            "lang": "fr"
                        }
                    ]
                }
            ],
            "ordered": false
        }]
    }
}`

Thanks

**Comment by Fleker** [comment]
Do you see that error when requesting all of the modes? Which ones have you tried (and in which language?)

**Comment by bobnmt** [comment]
We tested them in french and they were working 2 weeks ago.
We have this error for eco, confort, hors-gel and boost (all in french). I will test in english.
"auto" is working in french.

**Comment by bobnmt** [comment]
It's working in english, except for "antifrost" but I think this is more due to the word itself... It should be "anti-frost" (or "frost protection")

**Comment by Fleker** [comment]
`antifrost` and `anti-frost` should be valid modes for English.

As far as I can tell, those modes should all exist in both languages.

**Comment by bobnmt** [comment]
I'm back on this issue. We found 2 reasons: 

1) **"Mode" and mode name are reversed** in French for all the modes except "Auto" mode.

In french the phrase should be : "_**Mets [name] en mode Eco**_" but only this phrase is understable by the assistant:  "**_Mets [name] en Eco Mode_**".

Could you request to make this correction?

2) For the antifrost mode in french, "**hors-gel**" is understood as 2 words "**hors gel**" by the assistant and so it doesn't understand the mode.

Could you request to replace in french "**hors-gel**" by "**hors gel**" in the modes list?

Thanks

**Comment by Fleker** [comment]
I'll follow up with these shortly

**Comment by bobnmt** [comment]
Hi,
I'd like to know if you have new information about this issue. The problem is still present.

We also found a new issue in french. When we ask to increase/decrease from x degrees. It seems the action doesn't send the new temperature, but the amount we asked to increase/decrease. In english, this action works well and send the new temperature.

The phrase in french we use is "**_Baisse [name] de 2 degrés_**", which mean "**_Decrease [name] from 2 degrees_**". 

Do you have information about this ?

Thanks

**Comment by Fleker** [comment]
I don't know off-hand, but I'll pass this issue along.

**Comment by Fleker** [comment]
We've been working on improving this behavior. It should be rolled out in the next few days.
