### ISSUE TITLE
New mode for modes traits - google home device

### ISSUE THREAD

**Issue by OlimpiaMM** [actions-on-google/smart-home-nodejs#126]
Hello

I want to provide a "function" setting for my thermostat and i wanted to map it on the modes trait, but from what i see, for now is not possible to describe my own mode. Which should be a solution for this?

**Comment by Fleker** [comment]
There is already a trait for [temperature setting](https://developers.google.com/actions/smarthome/traits/temperaturesetting). If you are looking for a specific mode, you can file an issue in this repository and I can add it. For now, custom modes are not supported and will need to be added specifically.

**Comment by OlimpiaMM** [comment]
The temperature settings trait does not provide something on which i can map my functionality. I want my sync response to look something like this:
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "payload": {
    "agentUserId": "1836.15267389",
    "devices": [{
      "id": "123",
      "type": "action.devices.types.THERMOSTAT",
      "traits": [
        "action.devices.traits.TemperatureSetting",
	"action.devices.traits.Modes"
      ],
      "name": {
        "defaultNames": ["Honeywell Thermostat T-1000"],
        "name": "Homer Simpson Thermostat",
        "nicknames": ["living room thermostat"]
      },
      "willReportState": false,
      "attributes": {
        "availableThermostatModes": "off,heat,cool,on",
        "thermostatTemperatureUnit": "F", 
	"availableModes": [{
          "name": "function",
          "name_values": [{
            "name_synonym": ["function"]
            "lang": "en"
          }],
          "settings": [{
            "setting_name": "heating",
            "setting_values": [{
              "setting_synonym": ["heating”,”heat”]
              "lang": "en"
            }]
          }, {
            "setting_name": "cooling ",
            "setting_values": [{
              "setting_synonym": ["cooling", "cool"],
              "lang": "en"
            }]
          }],
          "ordered": true
        }]

      },
      "deviceInfo": {
        "manufacturer": "hrxhgfst",
        "model": "t-1000",
        "hwVersion": "3.2",
        "swVersion": "11.4"
      },
      "customData": {
        "fooValue": 74,
        "barValue": true,
        "bazValue": "lambtwirl"
      }
    }]
  }
}
So i would need "function" to be added on modes

**Comment by Fleker** [comment]
I'm not sure why you'd want additional modes for heating/cooling when those are already provided as temperature modes.

**Comment by OlimpiaMM** [comment]
it's tricky ,but yes, i need additional modes. These heating and cooling modes are independent of temperature modes. For example, you can have function cooling and thermostat to be off. My cooling function sets something like generic values for temperature(something like ranges). In the summer you have cooling and in the winter you have heating but you can still set your thermostat off for eg.
