### ISSUE TITLE
Request Sync

### ISSUE THREAD

**Issue by aarontanzk** [actions-on-google/smart-home-nodejs#127]
Hi, following the steps listed out, at 8)
"
Copy the API key shown and insert it in smart-home-provider/cloud/config-provider.js Enable Request-Sync API using these instructions.
"
i did  the first part of config. However the second part LINK to curl ..."{agent_user_id: \"agentUserId\"}".../devices:requestSync?key=API_KEY", I had a problem of find where the agentUserId is located.

Without doing that, I attempted to test, which gave an error of "Sorry, this action is not available in simulation". On the server, there was an error "request-sync response 404 Not Found".

Can anyone help?

**Comment by Fleker** [comment]
The `agent_user_id` is the identifier on your cloud integration when you provide a SYNC response to the home graph. Until you do a SYNC the first time, when the user links their account, you will receive a 404 error as the home graph is has no knowledge of that identifier.

**Comment by aarontanzk** [comment]
I'm using Actions on Google with Firebase.

Where can I find the agent_user_id? Is it under Actions on Google > Project Settings > Project ID?

i tried running:
curl -i -s -k -X POST -H "Content-Type: application/json" -d "{agent_user_id: \"MY_PROJECTID
\"}"   "https://homegraph.googleapis.com/v1/devices:requestSync?key=MY_KEY_HERE"

but ended up with:
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

**Comment by aarontanzk** [comment]
My Google Cloud ID is the same as Actions on Google Project ID.

**Comment by Fleker** [comment]
You specify the `agent_user_id` when you return a `SYNC`

From [the docs](https://developers.google.com/actions/smarthome/create-app#actiondevicessync):

```
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "payload": {
    "agentUserId": "1836.15267389",
    "devices": [{
        ...
```

**Comment by Fleker** [comment]
If you store this in a database, with each user having an identifier, you would specify this identifier for this user.
