### ISSUE TITLE
Single command is executing on devices associated with different users.

### ISSUE THREAD

**Issue by usman-10pKhi** [actions-on-google/smart-home-nodejs#131]
Hi,
I am facing issues after following below steps:
1. Login with user rick. Add devices
2. Login with user summer (in a separate browser, I am using incognito mode of Chrome). Add devices
3. Now send the command from action console. This command will change the state of devices on both users. However I have linked my account with user rick only so expecting the devices associated with rick to be changed only.

**Comment by Fleker** [comment]
That could be a bug in the sample. I've usually used rick as a user.

**Comment by Fleker** [comment]
The sample has now been significantly updated. Devices should now be linked to a singular user.
