### ISSUE TITLE
Request Sync Error 500

### ISSUE THREAD

**Issue by RouNNdeL** [actions-on-google/smart-home-nodejs#132]
I'm facing an issue when calling the _requestSync_ endpoint. After a very long request time (Google Dev Console shows 30s) the server responds withe the following response: `{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
`. Changing the token to an invalid one returns 401 as expected. The _reportStateAndNotification_ endpoint works just fine. All other functionality also works flawlessly. Here's an example JSON being sent to _requestSync_ `{"agentUserId":"25"}`. The server then receives a `SYNC` intent, but the devices are not being updated in the Home App.

**Comment by Fleker** [comment]
Do you return that same `agentUserId` ("25") the first time that the user links their account?

**Comment by RouNNdeL** [comment]
Yes, also, when I try an invalid `agentUserId` i get the expected 404 error.

**Comment by Fleker** [comment]
There may be a server-side issue. Can you try again tomorrow and see if it's been resolved?

**Comment by RouNNdeL** [comment]
Well, that's what I assumed, so I did wait a day or two before posting this issue. But still, I'll let you know tomorrow

**Comment by RouNNdeL** [comment]
It works :smile:
