### ISSUE TITLE
Italian query samples wanted

### ISSUE THREAD

**Issue by OlimpiaMM** [actions-on-google/smart-home-nodejs#133]
Hello,
I am currently trying to use the Thermostat Settings commands in italian but I would need an guide. Can you provide something like this? Also the command to ask for temperature responds with something like"air conditioning is set to 0 degrees, and there are 27 degress" in italian

**Comment by Fleker** [comment]
From the perspective of a smart thermostat developer, you don't have to handle anything differently. If you implement the [TemperatureSetting](https://developers.google.com/actions/smarthome/traits/temperaturesetting) trait, then you can give commands in English or any other supported language to update the temperature or mode.

As you see from your response, it is correctly providing the current mode (air conditioning) and the current temperature (27 C).

**Comment by OlimpiaMM** [comment]
In english the response is "cooling is set to 7 with a temperature of 24" and in italian is "air conditioning is set to 0 degrees, and there are 24 degress". Why it says about air conditioning and the value is 0?

**Comment by OlimpiaMM** [comment]
The answer from the server is the same for both cases, italian and english. Is the way that is handled that is different...

**Comment by Fleker** [comment]
What is cooling actually set to?

**Comment by OlimpiaMM** [comment]
cooling setpoint set to 7°, ambient temp is 24 and when asking for the temperature the answer is "cooling is set to 7, temperature is 24" in english, and "cooling is set to 0, temperature is 24" in italian

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general grammar issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
