### ISSUE TITLE
Scenes in discoveries

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#134]
Hi - i have some users who are reporting issues with Scenes in their discovery - if a scene is added, the discovery fails. This was working fine - is there any issue around the Scene trait?

**Comment by Fleker** [comment]
By "discovery fails" do you mean it doesn't show up in the list of devices in the Assistant settings?

**Comment by madgeni** [comment]
The user gets an error in the Google home/assistant app that an error occurred, and no devices are shown.

**Comment by Fleker** [comment]
Has anything changed with the SYNC response that is causing an issue? You may want to check using the [SYNC validator](https://developers.google.com/actions/smarthome/tools/validator/).

**Comment by madgeni** [comment]
Nothing has changed my side. Have you changed any of the Scene trait behaviour? Or is it tied to the Italian scene trait release?

**Comment by Fleker** [comment]
Nothing has changed with the scene trait. Have you changed languages and seen this issue?

**Comment by madgeni** [comment]
I'll ask one of my Italian users. I'm getting reports from them that they no longer see the Home Control option at all, and that the issue is for other Smart Home apps also, where they no longer respond.

**Comment by madgeni** [comment]
It could be tied to this issue:
https://support.google.com/googlehome/forum/AAAAXWcshA0HP3tyRjGr6g/?hl=en

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
