### ISSUE TITLE
New data-specific Device/Trait

### ISSUE THREAD

**Issue by jgardynik** [actions-on-google/smart-home-nodejs#135]
I feel like there should be a device and trait that is more specific to data only. The device type would be "Sensor", or something similar. The trait could be "Data", which would have no execute clauses, but it could return any data type on query. So I could say "Hey Google, how much water is in my tank?" and it could return something like "10.5 gallons". It should be possible to have multiple data elements on a single device (like toggles and modes); something like a {dataSets: []} object in the attributes, as well as a dataUnit parameter for each of those. A Sensor's ideal traits would be Data, Toggles, and Modes (and maybe OnOff if you wanted to disable the sensor entirely).

Along with this, how are custom names coming for traits? I have sensor devices that can flag on multiple conditions, but I have no way to express them as toggles. Things like "Is my tank empty?" or "Is it raining?" are impossible to do right now. I can think of thousands of uses for this; it's pretty much the core of how IFTTT functions.

**Comment by Fleker** [comment]
Custom names are still in progress, although we welcome new feature requests.

**Comment by Fleker** [comment]
As this is not directly related to the sample, I've copied this request over to the public issue tracker.

https://issuetracker.google.com/issues/136103089
