### ISSUE TITLE
Change log on documentation

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#136]
Can you please add a change log for smart home documentation?
I see lots of pages being touched, but am very worried I'll miss changes that could impact current service, as well as new functionality.

**Comment by Fleker** [comment]
We do announce changes in our [Google+ community](https://plus.google.com/communities/105684267327487893574) when something big is added.

We have been adding new things but would not remove existing APIs and breaking existing projects without a lot of outreach.

**Comment by Fleker** [comment]
News and updates will be shared in the Reddit community with the [`smart-home` flair](https://www.reddit.com/r/GoogleAssistantDev/search?q=flair_name%3A%22smart-home%22&restrict_sr=1).
