### ISSUE TITLE
error 404 request entity not found

### ISSUE THREAD

**Issue by jarvisgaurav** [actions-on-google/smart-home-nodejs#137]
where do i find my agentuser-id
The reply is something like: 
HTTP/2 404
vary: X-Origin
vary: Referer
vary: Origin,Accept-Encoding
content-type: application/json; charset=UTF-8
date: Tue, 12 Jun 2018 06:19:49 GMT
server: ESF
cache-control: private
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
alt-svc: quic=":443"; ma=2592000; v="43,42,41,39,35"
accept-ranges: none

{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

**Comment by jarvisgaurav** [comment]
and the login page does not open properly, there is something wrong with it, I even enabled the javascript content in chrome.

**Comment by Fleker** [comment]
The `agentUserId` is `1234` for the default user in this sample.

Can you take a look at what errors are in the chrome developer tools when you open the login page?

**Comment by jarvisgaurav** [comment]
yeah, its working fine right now. thank you.
Can you please tell me how the flow of data happens, with the command prompt commands and the google assistant and the frontend, i'm not quite understanding how it all gets interconnected.

**Comment by jarvisgaurav** [comment]
thank you for the help, I appreciate your patience :)

**Comment by jarvisgaurav** [comment]
I just have another query, after all the setup:
Suppose I have a table lamp and i turn it on using google assistant. for a particular interval of time I do not perform any task(turn on/off), I let it be in the same state, but what is happening is after a particular time interval the smart-home itself keeps updating the status of the device even though it has not changed. ( I am actually using your code to map it to my device, for example I turn my device on when I say turn on the lights. So everytime the api sends the status(even though the device state is not changed) my device also gets a post request to turn on. So this is stacking up many post requests making my device to crash.
if you have any solution to this please do help.

**Comment by Fleker** [comment]
That's probably an issue with regards to the sample in of itself, where the browser and backend server send messages to update the status.

**Comment by jarvisgaurav** [comment]
Instead of using the ngrok url , i'm now using my own authentication, after logging-in onto my oauth url it redirects to google home app, here it says "couldn't update setting check your connection", I checked online about this, some people say that if you have not logged into "google chrome" with the same account as "google home" app then this issue might occur, I tried that too, but it doesn't seem to make any difference.
Do you have any idea about this?

**Comment by jarvisgaurav** [comment]
Ok thank you for everything.
sorry to bother but I just have another query
I started a custom project in action.google,  and then I created two intents switchon and switchoff.
in the fullfillment( firebase cloud functions) on matching a intent i'm calling the respective function.
**function switchon(agent){
    agent.add('Ok');
    req.post('URL for my post request',
			{ json: { "Name":"FanOn",
					"ResponseTimeout": "00:01:08",
					"ConnectionTimeout":"00:01:05",
					"JsonPayload": "{}",
					"Message" : "{\"Name\" : \"TurnFanOn\",  \"Parameters\" : {}}" 
					} 
			},
			function (error, response, body) {
				if (!error && response.statusCode == 200) {
						console.log(body);
			}
    }	
			);
			agent.add("all ok");
    
}**

But when I test it, the assistant responds with "OK" and "ALL OK" but the post request in between doesn't seem to be called. I checked if the post request is working(it works absolutely fine).
Do you have any idea about this?

**Comment by Fleker** [comment]
First it looks like you're using the Dialogflow fulfillment library, which is different than using the smart home fulfillment.

Second, it's because the post request is asynchronous. You will need to return something like a `Promise` to tell the fulfillment that it is not done until the post request is done.
