### ISSUE TITLE
Report State

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#138]
Hi there - 
I want to implement report state, however, when following the example in here, i get : 
`
"error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
`
Homegraph is enabled - the service account is created, the json downloaded etc.
I note that your example doesn't create the JWT payload per documentation:
`{
  "iss": "<service-account-email>",
  "scope": "https://www.googleapis.com/auth/homegraph",
  "aud": "https://accounts.google.com/o/oauth2/token",
  "iat": <current-time>,
  "exp": <current-time-plus-one-hour>
}`

What have i done wrong?

**Comment by Fleker** [comment]
The sample code does create a JWT based on the service account key.

It does seem like your issue is that the agent user id that you're using does not exist in the home graph.

**Comment by madgeni** [comment]
How, if it's a new user (it isn't, it's me), do i add it to HomeGraph?

**Comment by Fleker** [comment]
You should make sure you return the `agentUserId` property in your SYNC response.

**Comment by madgeni** [comment]
Hey @Fleker - thanks for responding. I do pass the same id (it's an internal Controlicz GUID).

**Comment by Fleker** [comment]
Are you using this sample project, which logs the request and responses?

**Comment by madgeni** [comment]
i'm not using the project, but I log the req/response for reportstate:
`Report State request 
{
  "requestId": "16474776143299347934",
  "agentUserId": "5a560dc80b8a8b25291fb63d",
  "payload": {
    "devices": {
      "states": {
        "123": {
          "on": true
        }
      }
    }
  }
}
{ access_token: '<TokenHere>',
  token_type: 'Bearer',
  expiry_date: 1529530817000,
  id_token: undefined,
  refresh_token: 'jwt-placeholder' }`

response as original post

**Comment by XciD** [comment]
Does the HomeGraph report is working ? Because I'm seeing only query to my devices and states reported to HomeGraph are not used...

**Comment by Fleker** [comment]
We're working on a tool to make the report state capability more transparent. If you are getting a 200 response code then you should be fine.

**Comment by madgeni** [comment]
I have that tool available, but don't need to check it, as I know i'm getting 404. Can you tell me why? Thanks

**Comment by XciD** [comment]
I have 200 response codes from home graph. 
However, when I ask google if the light is on, it always querying my server and don’t use home graph. 
It’s the normal behavior ?

**Comment by Fleker** [comment]
Yes the behavior is currently that general queries will still use a QUERY. For relative commands like brightness there is some transitioning over to using the stored data.

If you get a 404, that probably means the agent user id is not found.

**Comment by madgeni** [comment]
Hi, so request sync on my agent user id returns a 200, so I'm assuming homegraph knows it? 
But using the same agent user id for report state returns a 404. How do I work through that?

**Comment by madgeni** [comment]
Ok, it's started working - whilst my request sync was returning 200, not sure if it was storing the Agent User Id in homegraph? Slightly worrying if not? I did a manual curl, and it started reporting my stuff in the tool.

**Comment by Fleker** [comment]
It would be unexpected if the user id was not being stored.

**Comment by javiercuellar73** [comment]
Hi.
Please can somebody help me clarify this:

A user SYNC.  All his devices are properly loaded and ReportState saves without problem (for example using agentUserId as his email  abc@gmail.com).

Another member of his family also Sync without a problem. Some devices will be the same as the previous user. ReportState also runs without problems (using another email:  def@gmail.com)

In reportState database, there will be some devices with 2 different agentUserId.   

a) Is this situation correct? 

b) If one device is a light switch and it is switched on manually, with which agentUserId should it be reported?

Thanks for any help!!!!

**Comment by Fleker** [comment]
If two Gmail accounts have the same account on the smart home partner cloud, there should only be a single agentUserId for both.
