### ISSUE TITLE
Thermostat bug

### ISSUE THREAD

**Issue by XciD** [actions-on-google/smart-home-nodejs#139]
Hello,

I'm using the `action.devices.traits.TemperatureSetting` in order to report the temperature of my Pool.

It's working well, but the answer given by google is:
`The temperature is 24 degres and the thermostat Pool is off`

First could we do not report the state of the thermostat if we don't return the `thermostatMode` in the state ?

Then, I tried to play around and return if the filtration pump is on.
But the answers given by Google are weird:

Query State:
```
{
	"requestId": "10414535111288076787",
	"payload": {
		"devices": {
			"0e733ba6-033a-2b2b-ffffb7fe2005e936": {
				"thermostatMode": "off",
				"thermostatTemperatureAmbient": 24,
				"online": true
			}
		}
	}
}
```
Answer: `The temperature is 24 degres and the thermostat Pool is off`

And 
Query: 
```
{
	"requestId": "4947862819143607125",
	"payload": {
		"devices": {
			"0e733ba6-033a-2b2b-ffffb7fe2005e936": {
				"thermostatMode": "on",
				"thermostatTemperatureAmbient": 24,
				"online": true
			}
		}
	}
}
```
Answer: `The temperature Piscine is off and the ambiant temperature is 24 degres`

I also tried with `cool`, but google doesn't not answer the temperature.

Thanks for your help

**Comment by Fleker** [comment]
The [TemperatureSetting](https://developers.google.com/actions/smarthome/traits/temperaturesetting) trait it designed primarily for thermostats. If you look at the SYNC response that you'd send, are you sending the `availableThermostatModes` attribute to include "on" and "cool"?

You may also want to look at the more generalized [TemperatureControl](https://developers.google.com/actions/smarthome/traits/temperaturecontrol) trait, which is for controlling devices that can change temperature but are not thermostats.

**Comment by XciD** [comment]
Yeah I understand. But I’m trying to use every trait you have to connect my home. 

You should consider a trait with just the temperature sensor. 
That trait could be merge with a temperature control for thermostat or used alone like in my case. 

For instance, I’m returning `on` and `off`
I’ve tried also `cool` but it does not return the temperature

**Comment by madgeni** [comment]
I've had the same issue since day 1.
I've tried changing my device to a switch, with temp sensor, but as it isn't a thermostat i can't query it for temperature. "Sorry, it looks like that thermostat hasn't been set up yet". urgh.
