### ISSUE TITLE
Lights effects

### ISSUE THREAD

**Issue by Dome81** [actions-on-google/smart-home-nodejs#140]
Hi, I'm developing smart home integration for christmas lights that handle different effects.
For example I would like to say something like "apply rainbow to christmas tree" (or "activate snow on all the lights"), where "rainbow" is the name of the effect and "christmas tree" the alias of the light.
My light controller manages about 10 effects. How can I manage those custom effects on my SYNC response?
Thank you,
Domenico

**Comment by XciD** [comment]
Hello,

You could use the Toggle trait.

https://developers.google.com/actions/smarthome/traits/toggles

**Comment by Dome81** [comment]
Hy XciD,
toggle trait is exactly what I was trying to do, but If I try to set custom toggle names, google assistant can't recognize the command.
For example this SYNC response is correct:
"attributes": {
                    "availableToggles": [
                        {
                            "name": "quiet",
                            "name_values": [
                                {
                                    "name_synonym": [
                                        "quiet",
                                        "silent"
                                    ],
                                    "lang": "ENGLISH"
                                }
                            ]
                        }
                    ]
                }
But if I try to use this JSON:
"attributes": {
                    "availableToggles": [
                        {
                            "name": "rainbow",
                            "name_values": [
                                {
                                    "name_synonym": [
                                        "rainbow"
                                    ],
                                    "lang": "ENGLISH"
                                }
                            ]
                        }
                    ]
                }
the command is not recognized.

**Comment by Fleker** [comment]
Right now custom toggles are not supported. If you have specific requests you'd like to make I can add it to the grammar.

Alternatively, you may want to look at using [scenes](https://developers.google.com/actions/smarthome/traits/scene) for each effect you want to show.

**Comment by Dome81** [comment]
Hi Fleker,
we would like to use those custom keywords:
Rainbow
Twinkle
Snake
Waves
Collision
Can you please add them to the toggle trait?
Alternatively, is it possible to apply a specific scene to a specific device?
Thank you

**Comment by Fleker** [comment]
You, as the smart home service, can define your services and you'll have control over how they behave when activated.

**Comment by Dome81** [comment]
Hi @Fleker , 
did you add the commands that I have requested to the grammar?
Thank you

**Comment by Fleker** [comment]
I think in your case using a [scene](https://developers.google.com/actions/smarthome/traits/scene) makes more sense compared to toggles.

**Comment by Dome81** [comment]
Ok, I'm trying to use scenes, but I don't know how to set a single scene to a specific device.
For example, you can see in the attached image that I have multiple lights, and I have set 3 scenes.
But how can I do if I want to set rainbow on light1 AND snow on light2? I don't wont to apply a scene to all my devices but only on a specific device a time.
Am I missing something or I can do this only using toggles (or modes)?
![led screen](https://user-images.githubusercontent.com/11227544/42237820-3ce8ca34-7eff-11e8-85f0-ac35df82c77b.JPEG)

**Comment by Fleker** [comment]
So you have three lights. And you want to add a Snow effect to *light 1* but then later add a Snow effect to *light 2* and then do a Rainbow effect to *light 3* at the same time, all controlled by your voice?

**Comment by Dome81** [comment]
Yes, exactly. I have several lights, each one could be controlled separately. I would like to have the possibility to set different effect to each light. There are also other features that will be implemented in future, like setting an effect with a specific setting (maybe using modes trait?) but for now setting simple effects is enough

**Comment by Fleker** [comment]
You could create scenes for each light, ie. Scene **Rainbow light1**. That's probably not ideal. I'll look into adding toggles.

**Comment by Fleker** [comment]
Would it make sense to add this as a mode instead.

Set *pattern* to rainbow or set *pattern* to snow?
