### ISSUE TITLE
Turn on the light on the current room

### ISSUE THREAD

**Issue by XciD** [actions-on-google/smart-home-nodejs#141]
I'm switching from Alexa to Google Home,

For now, I quite surprising about how it work better...

One nice feature about Alexa was that when I was on my room and said turn on the light, only the light in the rooms where turned on.

All my lights in my house are connected, and when I say: Turn on the lights, all my home is turning home :D, quite useless.

Could be great if these kind of grouped action could be contextualized with the room where the smart home is 

What do you think about it ?

I'm planning to buy 5 more google mini to replace my dots if this kind of feature is planned

**Comment by Fleker** [comment]
Yes, it's a feature that is rolling out. Are you looking for a doc on the feature in our developer documentation?
