### ISSUE TITLE
Failed to request SYNC

### ISSUE THREAD

**Issue by orlytops** [actions-on-google/smart-home-nodejs#143]
I tried to implement the project everything works fine I followed all the steps from README. The problem is that after the account link in android it shows the error `Couldn't update settings. Check your connection.` I'm checking the logs but I think AoG failed to request SYNC from the fulfillment URL. Here's my logs

```
 login successful  rick
authCode successful  8jnpuc5erh8000000000000000
GET /oauth?response_type=code&client_id=ZxjqWpsYj3&redirect_uri=https://oauth-redirect.googleusercontent.com/r/avarionodetest&state=CrQCQUhKbXBLZnBFUEtBNHd6ZFVCY0VLQlN6bGR1R3I3dXRCMTZTcTFwVEJ4QnlqR0Z3M2NkOWhXME9HRlg4cHJPSW1MeW80VEF0RlY4NWhsRkJNcVYyM1JOQ3lvYjAwUk5MMlFsTm00dDJ4UExlTmc0NzBFSWpuQng4QUw2dHFYeEY5c3JMT05EZktjRjE0ZnpvaFYxMXJick00UmI4Z3RUN2w0ajg1YTJGY3g4blM0ekZ4Tldzc180ZTdyVlc4dXhCWTVZVTAxemV5RzdlbEU5Wi1YdDNEWHJVal9HaFFQU3lodE85MkJjeWJRZ21NdHRZQ1BEdnQ4Y1lhNDFMMXhiYWFYeHUwRGZPalA1SFNZYU0xR25La1JUWVpHaHdnMzc4TmdpdlZaRFdvY1NQSFcyaExwTEMSHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiPWh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvYXZhcmlvbm9kZXRlc3QqG29ybGFuZG95YW5zb24uZGV2QGdtYWlsLmNvbTISYXZhcmlvbm9kZXRlc3RfZGV2 302 1.108 ms - 1460
/token query {}
/token body { grant_type: 'authorization_code',
  code: '8jnpuc5erh8000000000000000',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/avarionodetest',
  client_id: 'ZxjqWpsYj3',
  client_secret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
client { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
handleAuthCode {}
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getAccessToken =  { uid: '1234',
  accessToken: 'psokmCxKjfhk7qHLeYd1',
  refreshToken: 'psokmCxKjfhk7qHLeYd1',
  userId: '1234' }
return getAccessToken =  { token_type: 'bearer',
  access_token: 'psokmCxKjfhk7qHLeYd1',
  refresh_token: 'psokmCxKjfhk7qHLeYd1' }
respond success { token_type: 'bearer',
  access_token: 'psokmCxKjfhk7qHLeYd1',
  refresh_token: 'psokmCxKjfhk7qHLeYd1' }
POST /token 200 1.720 ms - 100
```
Also I'm seeing error logs from the stackdriver here's the logs
```
{
 insertId:  "a9lie9f2wt8s3"  
 logName:  "projects/project_name/logs/actions.googleapis.com%2Factions"  
 receiveTimestamp:  "2018-07-12T04:20:11.818617554Z"  
 resource: {
  labels: {
   action_id:  "SMART_HOME_SYNC"    
   project_id:  "project_name"    
   version_id:  ""    
  }
  type:  "assistant_action"   
 }
 severity:  "ERROR"  
 textPayload:  "SYNC: Request ID 10293681341661526483 failed with code: OPEN_AUTH_FAILURE"  
 timestamp:  "2018-07-12T04:20:11.804417936Z"  
}
```

any solutions for this?

NOTE: I haven't change anything from the source code except adding the `jwt-key.json` and adding the API_KEY to `config.provider.js` which is should be done according to the instructions.

**Comment by Fleker** [comment]
It seems like you ran into an account linking issue

**Comment by orlytops** [comment]
any possible solutions?

**Comment by Rishabh606** [comment]
I am facing the same issue. Any solution?

**Comment by Kalevera** [comment]
@orlytops at @Rishabh606 are you using the same email linked on your console? The user logged in on the android device needs to be the same user that the AoG is registered too. Were you able to find the test on your google home app?

**Comment by orlytops** [comment]
@Kalevera yes it is the same.. I tried using firefox browser for the login and it worked.. looks like we have a browser issue here

**Comment by guzmanvig** [comment]
Same issue here, I can successfully link my account but no SYNC is sent to the server

**Comment by red-patch** [comment]
> Same issue here, I can successfully link my account but no SYNC is sent to the server

I have the same problem. Have you solved it

**Comment by RavenOfTime** [comment]
same issues any update?

**Comment by eric3zhao** [comment]
2019-01-21 08:43:58.555 香港時間
requestId 17652373530573620416 failed with code: OPEN_AUTH_FAILURE
全部展开 | 全部收起 {
 insertId:  "1qfuwb8fv2ufa1"   
 logName:  "projects/*****/logs/actions.googleapis.com%2Factions"   
 receiveTimestamp:  "2019-01-21T00:43:58.586960317Z"   
 resource: {
  labels: {
   action_id:  "SMART_HOME_QUERY"     
   project_id:  "*****"     
   version_id:  ""     
  }
  type:  "assistant_action"    
 }
 severity:  "ERROR"   
 textPayload:  "requestId 17652373530573620416 failed with code: OPEN_AUTH_FAILURE"   
 timestamp:  "2019-01-21T00:43:58.555793516Z"   
}

same issues. I have try to find some log in my tomcat, but get nothing, even more strange is that nginx also has no logs at 2019-01-21T00:43:58.586960317Z

**Comment by RavenOfTime** [comment]
okey i fixed it
the only fix is to logout from all the accounts from the phone your testing it with and only login with the one which your testing it
if that doesnt work your account has issues just mail them they will fix the account

**Comment by ctnha** [comment]
I have the same problem. token exchange end point result correct but it not request sync.

**Comment by manikdutta** [comment]
I have the same issue. Please help. I stuck for 3 days.
Here is my log:

login successful  8910911970
authCode successful  14u33pqd5o6800000000000000
GET /oauth?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fintelliosmarthome&client_id=ZxjqWpsYj3&response_type=code&state=AB8b_TOmZwiPK7B0DHICvSyfmO54XmN-wdDfMCh9cJz3HpMbx6etalz0y70IKtwKY9mmcDhK6sshxUWxXbo3n7FTdgAM-A1IgXILGZC1XOOseqwbjTqm0H1JmYqg0Ddup3GHES-yD-j51uZkevKDWNcYH_sKCG4KsUyRl30PJAFX1kHPKmWFAoy1HuVZDgVeIpMy3fhyjyNC1pakKVrZQF80y79-sGvC8ueXQ7Fz0eMFJqIGnWOAf_bMDf3pDMv8NvGK3EWrdXp_sBpX2MjSiQ6pYbAgHljq50OosBnoeadRHcclLmB8E8xmlfWey2U8ArOah5jl9r-kU8EbZZLewu4pg3mB3EgUMbscflVirBQy_G12Yzf6tKGo1CWqE9_N6Wuj5dq9DyxPweUMvG1QxlAWIp6g8uT_4bA8TM56FIPPGrbZ_Aa5P1jaEIHebSU0fmQnAe60LFcYSMaaLmoLS4F3TKKbQn0kMVqg3kRqzeYC-RMvOMdbKbN_jlyRML6zXljbGkxPwQspN7fBXChmdtykAgg954B7lg7h7uFfSyNH3syJZ0bA178rjQdCbbqHax_m2yZErfjT&user_locale=en-GB 302 1.260 ms - 1434
GET /service-worker.js 304 0.864 ms - -
/token query {}
/token body { grant_type: 'authorization_code',
  code: '14u33pqd5o6800000000000000',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/intelliosmarthome',
  client_id: 'ZxjqWpsYj3',
  client_secret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
client { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
handleAuthCode {}
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getAccessToken =  { uid: 'jEIFDigfqRDxs3g02RmjnQ',
  accessToken: '2wdj8wjy2qe000000000000000',
  refreshToken: '2wdj8wjy2qe000000000000000' }
return getAccessToken =  { token_type: 'bearer',
  access_token: '2wdj8wjy2qe000000000000000',
  refresh_token: '2wdj8wjy2qe000000000000000' }
respond success { token_type: 'bearer',
  access_token: '2wdj8wjy2qe000000000000000',
  refresh_token: '2wdj8wjy2qe000000000000000' }
POST /token 200 1.440 ms - 112
