### ISSUE TITLE
Customizing JS files to SYNC devices using REST API and EXECUTE using MQTT broker

### ISSUE THREAD

**Issue by amitavamighty** [actions-on-google/smart-home-nodejs#144]
The sample provided works perfectly fine in simulation mode. Now I want to use it with my devices and the device information are available from my database using REST API. I have also setup my own MQTT broker using which my devices are switched on and OFF. So i want to Execute the ON/OFF commands through this MQTT broker.
It will be very helpful if anyone can provide any sample or clue to implement the above.

**Comment by Fleker** [comment]
If you take a look at the console output during the usage of the sample, you will see the JSON responses that your server should receive in order to fit with the specification. Then, you'll have to develop the way to send on/off commands through your MQTT broker.

**Comment by manikdutta** [comment]
I have implemented the sample with google assistant and it showing in assistant app and i can also link with my project successfully. Now i am stuck and moving round and round here and there but no solution is found to control my own smart devices by assistant that are connected to my own mqtt server .I saw the request response from console but where to put them? I have my database for client and device registration. Where do i call the REST api to validate my client and showing devices according to the client.Please show me a proper guide line with proper example if you can.

**Comment by Fleker** [comment]
If you run this sample, you will have a server that pulls data from the equivalent of a database and responds to requests from the Assistant.

If you have your own smart home devices, you can interface with the Assistant using your own server. That may be reading from your database and generating a SYNC response by creating a JSON object.

**Comment by Fleker** [comment]
Check out [this Cloud IoT example](https://github.com/googlecloudplatform/iot-smart-home-cloud) for how to use it with smart home.
