### ISSUE TITLE
How to add custom mode of thermostats

### ISSUE THREAD

**Issue by nidhishbhavsar** [actions-on-google/smart-home-nodejs#145]
I have two additional mode like "fan only" and "Emergency Heat" in my thermostat.

How can I add support in my implementation that user can change it to that mode as well via google assistance?
I tried adding **availableThermostatModes: 'off,heat,cool,heatcool, fan only, emergency heat',** but not helped it.

**Comment by Fleker** [comment]
You cannot add additional `availableThermostatModes` other than the ones defined, but you should be able to add the [Modes trait](https://developers.google.com/actions/smarthome/traits/modes) for additional modes (as long as the modes are already defined).

**Comment by nidhishbhavsar** [comment]
Thanks, @Fleker  for the suggestion,

I am trying to add Auto mode as my customers are used to call heat-cool mode to Auto mode but google doesn't support it. I tried it by Mode trait but did not help would you please verify below JSON and let me know where I miss something?

```
availableModes: [
        {
          name: 'Auto',
          name_values: [
            {
              name_synonym: [
                'auto'
              ],
              lang: 'en'
            }
          ],
          settings: [
            {
              setting_name: 'Auto',
              setting_values: [
                {
                  setting_synonym: [
                    'auto'
                  ],
                  lang: 'en'
                }
              ]
            }
          ]
        }
      ]
```

Thanks in advance.

**Comment by nidhishbhavsar** [comment]
@Fleker Can you please share sample JSON if I need to add a custom mode like 'Auto', I read a documentation but looks somewhat confusing to me. Can you please help me to understand this?

**Comment by Fleker** [comment]
Good morning,
Since this issue was last updated, there's been a few new modes for the thermostat. _auto_ and _fan-only_ should sync as `availableThermostatModes`.

We're looking to add emergency heating.

**Comment by nidhishbhavsar** [comment]
@Fleker This is really awesome, Thanks a lot for adding modes. Please do let me know when you add emergency heat

When the device is in auto mode and when we QUERY its mode ('What is home set to') it just says "The Home is set to auto mode" unlike heat-cool response like "Heat-cool mode is set to keep the temperature between N and N degrees"
Can we make auto mode response like heat-cool like "auto mode is set to keep the temperature between N and N degrees"?

**Comment by nqd** [comment]
Hello,

Just want to +1 for the Em Heat.

Some of our supporting devices have this mode, for example, http://pdf.lowes.com/useandcareguides/085267182287_use.pdf, page 8.

Thanks.

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like a feature request with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
