### ISSUE TITLE
Controlling 3rd party devices

### ISSUE THREAD

**Issue by prasht63** [actions-on-google/smart-home-nodejs#146]
Can we use this API to access and control, through a google action, 3rd party devices which are added to Smart Home for a user , given account is linked. Or does it restrict me to only control devices which I have added/developed?

Detailed explanation:
I am building an action on Google Assistant which is basically a smart home assistant residing within google home. 
Sample invocations and commands:

- Nitto please turn on the Geyser(3rd party device)
-Nitto turn off the light in all rooms
I can do these with Ok google, turn on the Geyser
but the idea is to make it more personal and letting user use some of the regional dialects (powered by training on dialogflow).

I am stuck in controlling the device rest all flows around NLP part is already sorted. Please provide me some pointers on how to go about it.

**Comment by Fleker** [comment]
The Google Assistant is already a smart home assistant and supports a variety of languages and locales already.

The smart home API is designed to let a service be accessed and controlled through the Google Assistant, and it does not give a service any indication of other services that the user has connected. Basically, Philips may have your smart lights, but it has no knowledge of your Roomba.

You can kind of use the [Assistant SDK](https://developers.google.com/assistant/sdk/overview) to act as a way to control all of a user's devices by sending commands to the Assistant on their behalf, although you aren't going to get the same level of detail and control (you won't know which devices they have or have direct control over them.)

**Comment by prasht63** [comment]
Thanks for the reply. From what i found, Assistant SDK only allows to embed google assistant on custom built hardware. Correct me if I am missing anything.

Just to confirm, the use case is:
Controlling a Philips smart light with a _custom command_ (e.g. _Nitto light on karo_) given to a _custom agent_(e.g. Nitto) built on Dialogflow.
Philips smart light is currently added in my Google home app and working with Google home - _'Ok google, turn on the light_' command
How should I go about it?

**Comment by Fleker** [comment]
If you want to control your Philips light from your custom Dialogflow agent, you'll need to do your own work of connecting to the Philips API.

**Comment by prasht63** [comment]
Thanks for helping 👍
