### ISSUE TITLE
Modes/Toggles using custom names

### ISSUE THREAD

**Issue by Aravindz** [actions-on-google/smart-home-nodejs#147]
Modes and Toggles trait with custom names are not yet supported as per Google Actions Documentation. But I need to add custom names to trigger my device not just 'load' in case of Modes and 'sterilization' in case of Toggles.

**Comment by kirill3333** [comment]
@Fleker where developers can list information about available custom modes?

**Comment by Fleker** [comment]
@kirill3333 this information is not available.

**Comment by madgeni** [comment]
@Fleker can it be made available? Custom modes would be really useful to a lot of people, so some timescale on that, whilst making a list of currently accepted words would go a long way

**Comment by Fleker** [comment]
We've published the first set of reference documentation: https://developers.google.com/actions/reference/smarthome/traits/modes
