### ISSUE TITLE
Add `volume` to Modes trait

### ISSUE THREAD

**Issue by pbillen** [actions-on-google/smart-home-nodejs#148]
Hi,

We would like to control the volume via Smart Home. I understood that the different available modes are still fixed, so please consider this as a request to add the `volume` mode.

For your information, in our project, we have volume levels ranging from 0% to 100%, with increments of 10%. We would like to ask phrases such as:

* Set the volume of `name of device` to 60%.
* Increase/decrease the volume of `name of device`.
* _..._

Please let me know if you need further information. Thank you in advance!

**Comment by andrei-tatar** [comment]
That would be a nice feature to have. I also have an amplifier that I would like to control the volume via Google Home.
Maybe some kind of Gradual Trait? So we could use it not only for volume, but for example for the blinds... "Hey Google, open/set/close the blinds to 50%". It should be similar to brightnessControl but with a custom name (maybe from a list of supported ones).

**Comment by DiederikvandenB** [comment]
Dropping by for the +1. Same as @andrei-tatar, I would like to control my amplifier.

**Comment by gesaracino** [comment]
It would also be great if you could add a "channel" mode and numeric settings name to the list of supported mode names. It would help me to make my own developed smart remote control for TVs

**Comment by pergolafabio** [comment]
Is the volume trait already possible now?

**Comment by andrei-tatar** [comment]
Not officially yet: https://github.com/actions-on-google/smart-home-nodejs/issues/253#issuecomment-450634033

**Comment by pergolafabio** [comment]
Ok, but maybe it coming
I wonder how it works, would be nice if we .could say : volume up or volume down 
Instead of : set volume of receiver to xx %

**Comment by Fleker** [comment]
As this is not directly related to the sample, this issue has been moved to the public bug tracker. https://issuetracker.google.com/issues/136103828
