### ISSUE TITLE
Report State Failed error code 403

### ISSUE THREAD

**Issue by sky9971** [actions-on-google/smart-home-nodejs#149]
I'm reporting states for devices using http post with a jwt generated using service account. Below is the payload for jwt 

```
 {
   "iss": "<service-account-email>",
   "scope": "https://www.googleapis.com/auth/homegraph",
   "aud": "https://accounts.google.com/o/oauth2/token",
   "iat": <current-time>,
   "exp": <current-time-plus-one-hour>
 }
```

after this I sign the jwt using the private key for my service account using the python library `google.auth.crypt.RSASigner.from_service_account_file(path)`
and generate the jwt token.  I am further using this token to obtain the access token from https://accounts.google.com/o/oauth/token, which is also successful.
After obtaining the access token I am making a post request to 

https://homegraph.googleapis.com/v1/devices:reportStateAndNotification

with headers 
    `{"Authorization": "Bearer <token>", "X-GFE-SSL": "yes", "Content-Type": "application/json"}`

and json data
 
`{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "agent_user_id": "1234",
  "payload": {
    "devices": {
      "states": {
        "1458765": {
          "on": true
        },
        "4578964": {
          "on": true,
          "isLocked": true
        }
      }
    }
  }
}`

But this gives me 
` {'error': {'code': 403, 'message': 'The request is missing a valid API key.', 'status': 'PERMISSION_DENIED'}}`

I followed the steps from 
https://developers.google.com/actions/smarthome/report-state

is there anything i'm doing wrong? or am I missing any steps?
UPDATE:
I added the api key into the uri and now I am getting this response
`{'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED'}}`

**Comment by Fleker** [comment]
Did you enable the [Homegraph API](https://console.cloud.google.com/apis/api/homegraph.googleapis.com/overview) for your project?

**Comment by sky9971** [comment]
yes, the homegraph api is enabled for my project, yet it gives me this error.

**Comment by Fleker** [comment]
No you do not need an API key for report state since you're using the JWT. Are you trying to run this sample?

**Comment by Aymkdn** [comment]
I had the same kind of error.

I forgot to follow the step "Create a Service Account Key" from https://developers.google.com/assistant/smarthome/develop/report-state#service-account-key

Then I used https://github.com/lcobucci/jwt/issues/344#issuecomment-691163430 to generate the `access_token`.

Finally the call to https://homegraph.googleapis.com/v1/devices:reportStateAndNotification with the below headers worked:
> {"Authorization": "Bearer <token>", "X-GFE-SSL": "yes", "Content-Type": "application/json"}
