### ISSUE TITLE
Weird response from Google Home

### ISSUE THREAD

**Issue by vava24680** [actions-on-google/smart-home-nodejs#154]
Hi
I am using google home for home device control for a while, but I got very weird response from Google home. When I asked google home to turn on the lights, it responsed with "I couldn't reach Jax" or "Jax is not available now" (Jax is the display name in the AoG console setting)

I have tried to resync the devices but it didn't work.

Can somebody tell me how to solve this problem?
Thank you!

**Comment by Fleker** [comment]
Is that your action? This may be an issue on the server communication w/ Assistant.

**Comment by vava24680** [comment]
Yes, but the assistant still did all the requests I told it like turn on the lights and I received the json from the assistant but it just couldn't response with some normal sentence like "OK, turn on the lights". I am still confusing and I have tried the "re-sync devices" method but it didn't work out.

**Comment by Fleker** [comment]
Are you sending back a [valid JSON response](https://developers.google.com/actions/smarthome/create#actiondevicesexecute) for the execute intent, for example:

```
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "payload": {
    "commands": [{
      "ids": ["123"],
      "status": "SUCCESS",
      "states": {
        "on": true,
        "online": true
      }
    },{
      "ids": ["456"],
      "status": "ERROR",
      "errorCode": "deviceTurnedOff"
    }]
  }
}
```

**Comment by vava24680** [comment]
I found the problem, I sent back the wrong style JSON response for the execute intent.
Thank you Fleker!!
