### ISSUE TITLE
Can you please add generic mode like 'on'

### ISSUE THREAD

**Issue by nidhishbhavsar** [actions-on-google/smart-home-nodejs#156]
I am implementing the code to operate my water heater device from google smart home for that I am using "action.devices.traits.TemperatureSetting" trait.

My water heater has many modes which are not currently supported by this trait so while QUERY(what is water heater set to) it respond "water heater is off and it's currently N degrees". I found when it detects non-supported mode it considers as off mode

Can you please add some generic mode like 'on' so I can respond better response like "water heater is on and it's currently N degrees"

I tried 'on' mode and set thermostatMode: 'on' but it didn't help and gave above off mode response.

**Comment by Fleker** [comment]
You could set [the mode](https://developers.google.com/actions/smarthome/traits/temperaturesetting) to `heat`, as that would also make sense. But you may also want to consider the similar [TemperatureControl](https://developers.google.com/actions/smarthome/traits/temperaturecontrol) trait.
