### ISSUE TITLE
Clarification needed on execute commands in the sample code.

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#158]
Hi,
The question is related to increase brightness for Light in the example given.
.How the virtual device(smartlight.html) code receives the command to increase the brightness from the cloud ? Please clarify!

**Comment by Fleker** [comment]
It uses an [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource), which can be seen as similar to a socket.

**Comment by sakthisg** [comment]
Thanks Fleker!
