### ISSUE TITLE
Inputs needed...on this example.

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#160]
Hi.
I am trying to reuse this example for the https server i have created..
i have replaced the config with my server IP address and i have removed the ngrok connect, 
I am not getting the Smart Home Provider with login page...
Getting an error / GET login failed...
Logs after starting the node...
------------------------------------------
  isLocal: false,
  enableReset: true,
  smartHomeProviderCloudEndpoint: 'https://tpvdeveloper.xyz' }
smart-home-app registerAgent

Registered routes:
/smart-home-api/auth
/smart-home-api/register-device
/smart-home-api/reset-devices
/smart-home-api/remove-device
/smart-home-api/exec
/smart-home-api/execute-scene
/smart-home-api/status
/smart-home-api/device-connection/:deviceId
/getauthcode
/smart-home-api/report-state
/smarthome
/smarthome
/oauth
/login
/token
Enter oauth
GET /oauth?response_type=code&client_id=ZxjqWpsYj3&redirect_uri=https://oauth-redirect.googleusercontent.com/r/awsec2saphi&state=CqgCQUpXajQtYVdhS2VPLThpbzQwemVKSE1FZDNqMmY1T2lFeFhFVlJKak9NajZ4dl9BdU5seHJXRzEzbHFRNHpnMkE5RjRpRlpiTkQtVjJTTlhjN2d3UkhfZ2FKMUJocWV3TXFicnJNUThpNU5tT2VrSHAwZzZ1ZlY3a2ZaazJBMUlPUGF6TFJhMks2NE1tNWw2WUpUTGdUV3QyVElZWERWYVdueUdibFRwVzd3cTh2cTFqbWVPMTRWVU12YjM3ajMzb1BWQTBHSjJPTjEwNEN5YTZDeXJ0dW9sQjlfMmlmVm1IcnpPNmRJZDFnSXI4cXpHTDJJcDZ4R01OQm1QSVg5T2dtVERwRGcxYkhKRm0teDFwNEs3N3V3U29NX3J2TEJOWFZ5dHdubHASHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiOmh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvYXdzZWMyc2FwaGkqHXNha3RoaS5zdWJyYW1hbmlhbmdAZ21haWwuY29tMg9hd3NlYzJzYXBoaV9kZXY 302 11.529 ms - 1498
GET /login?client_id=ZxjqWpsYj3&redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fawsec2saphi&redirect=/oauth&state=CqgCQUpXajQtYVdhS2VPLThpbzQwemVKSE1FZDNqMmY1T2lFeFhFVlJKak9NajZ4dl9BdU5seHJXRzEzbHFRNHpnMkE5RjRpRlpiTkQtVjJTTlhjN2d3UkhfZ2FKMUJocWV3TXFicnJNUThpNU5tT2VrSHAwZzZ1ZlY3a2ZaazJBMUlPUGF6TFJhMks2NE1tNWw2WUpUTGdUV3QyVElZWERWYVdueUdibFRwVzd3cTh2cTFqbWVPMTRWVU12YjM3ajMzb1BWQTBHSjJPTjEwNEN5YTZDeXJ0dW9sQjlfMmlmVm1IcnpPNmRJZDFnSXI4cXpHTDJJcDZ4R01OQm1QSVg5T2dtVERwRGcxYkhKRm0teDFwNEs3N3V3U29NX3J2TEJOWFZ5dHdubHASHGFzc2lzdGFudC1oYW5kb2ZmOi8vY29tcGxldGUiOmh0dHBzOi8vb2F1dGgtcmVkaXJlY3QuZ29vZ2xldXNlcmNvbnRlbnQuY29tL3IvYXdzZWMyc2FwaGkqHXNha3RoaS5zdWJyYW1hbmlhbmdAZ21haWwuY29tMg9hd3NlYzJzYXBoaV9kZXY 404 3.089 ms - 144
GET /favicon.ico 404 0.855 ms - 150

**Comment by Fleker** [comment]
Does your server have a `/login` page where you manage the OAuth client flow?
