### ISSUE TITLE
set the thermostat to cooling - wrong execution command

### ISSUE THREAD

**Issue by vasid** [actions-on-google/smart-home-nodejs#161]
Hello,
I have noticed a strange behavior on set the thermostat to cooling.
When you send this command (set the thermostat to cooling) i get "action.devices.commands.ThermostatTemperatureSetpoint" on the execute call, but when I send "set thermostat to cooling" (without "the"), I am getting "action.devices.commands.ThermostatSetMode".

For "set the thermostat to heating" and "set thermostat to heating" I am getting the same execution command, "action.devices.commands.ThermostatSetMode", so only the cooling + the is with a problem.

I want to add that the response on the query before the execute is exactly the same for both commands (with or without "the").

Thank you

**Comment by vasid** [comment]
When u get ThermostatTemperatureSetpoint i also see a Query before that execute, is the same as in the case of  "set thermostat to cooling", and i respond with the same result. The temperature that i get in this ThermostatTemperatureSetpoint i think is the original one minus 3( i still have to double check this), but the problem is that i don't want to execute any setPoint for this commands ( I return "Mode not avaialbe error" for this commands).

**Comment by Fleker** [comment]
Okay, so it's probably a mismatch, thinking that you're trying to make the room "A little cooler" and not interpreting that as the name of the mode.

**Comment by Fleker** [comment]
Cannot reproduce.
