### ISSUE TITLE
my own endpoint

### ISSUE THREAD

**Issue by jarvisgaurav98** [actions-on-google/smart-home-nodejs#164]
how do I implement this for my own endpoint, instead of using ngrok url.

**Comment by jarvisgaurav** [comment]
I am using this on my smart plug, how do I remove the properties like brightness and color etc.

**Comment by Fleker** [comment]
In your SYNC response, you can return the [traits](https://developers.google.com/actions/smarthome/traits/) you want that device to have. For something like a [plug](https://developers.google.com/actions/smarthome/guides/outlet), you can just specify the OnOff trait.
