### ISSUE TITLE
command params != device states

### ISSUE THREAD

**Issue by paulschuetz** [actions-on-google/smart-home-nodejs#165]
Most of the trait's commands come with params which are equal to the states of the device. For example a device with the [OnOff](https://developers.google.com/actions/smarthome/traits/onoff) Trait has a State "on" and the action.devices.commands.OnOff command of that Trait also has an "on" field in its properties. The server works in a way, that it takes the params from the command and writes/overwrites it in the device's states. So in this example if the device has the the state `{on=false}`, now it is` {on = true}`. _Nothing special until this point._ This algorithm works great until one of the command params does not have an match/counterpart in the set of device states. An example would be the [StartStop](https://developers.google.com/actions/smarthome/traits/startstop) Trait. While the action.devices.commands.StartStop comand comes with a boolean called "start", the correspondig device state to be updated is called "isRunning". So the result of this:
`"commands": [{
                "devices": [{
                    "customData": {
                        "smartHomeProviderId": "FkldJVJCmDNSaoLkoq0txiz8Byf2Hr"
                    },
                    "id": "3"
                }],
                "execution": [{
                    "command": "action.devices.commands.StartStop",
                    "params": {
                        "start": true
                    }
                }]
            }]`
would be this:
`{"states":{"on":false,"online":true,"isRunning":false,"isPaused":false,"start":true}`

Instead of the `isRunning `state changing to `true`, a new state was added. This is definitely not the expected behavior. 

Is there maybe a plan to adjust the command params so they always match to the device state? I think it would not be confusing if the command in the above exaple would come with a `isRunning `field instead of a `start ` field. The mapping between command params and device states has to be implemented by every client in a similar way so it would be nice to abstract this out somehow.

Apart from that I am really enjoing this project, it helped me alot understanding how to implement my own smart home action. **Much Thanks!**

**Comment by Fleker** [comment]
The command parameters will not necessarily match the corresponding traits. The StartStop trait is one example in which it's not the case, and there can be many other traits like this in the future.

The mapping may end up being a bit non-trivial, and perhaps require a bit of effort in different cases, but it would be difficult to change the current implementation while maintaining backwards compatibility, and it's not clear that a command will or should always map directly to a single state in every case.

**Comment by paulschuetz** [comment]
Hi Fleker,
thanks for your response. Okay you are right. Changes will make backwards compability very hard. What do you think of an approach focusing only on device state? That would eleminate the effort of the clients mapping the docs into their code.

**Comment by Fleker** [comment]
What happens in situations where the command doesn't directly map to a state, like in the case of [CameraStream](https://developers.google.com/actions/smarthome/traits/camerastream#device-commands)? The device is expected to return a one-off response with the camera's stream URL, but shouldn't change its state as a result, as the URL is then sent to a cast-enabled surface.
