### ISSUE TITLE
Unable to report state for HSV based smart light

### ISSUE THREAD

**Issue by sky9971** [actions-on-google/smart-home-nodejs#168]
I'm sending report state for my sample smart light. I'm using python as my server language.
I'm can successfully authenticate my user with google.
My smart light has the following traits **ColorSpectrum (HSV), brightness, on/off.**
But when I send the report I get an error 400 which is bad request due to invalid syntax.
below is my json which I am sending to homegraph server:

`{"requestId": "c785ac58-dc96-4bd7-b475-2833a1775f70", "agentUserId": "ak8728", "payload": {"devices": {"states": {"ABC_90C6F4": {"on": true, "online": true, "spectrumHSV": {"hue": 120, "saturation": 1, "value": 1}, "brightness": 100}}}}}`

which results in  error 400
But when I try to report state with the json below it's working fine:

`{"requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf", "agentUserId": "b9a0d641-712e-4e28-b1cc-1d97736a1c43", "payload": {"devices": {"states": {"Mansaa_181960": {"on": true, "online": true, "brightness": 100}}}}}`

it will result in 200 success.
The report state does not work with spectrum HSV, I want to report the hsv values as well , what is the correct way to do so? Am I missing anything here?

**Comment by Fleker** [comment]
Why are you sending a `spectrumHSV` object? Is there some doc that you were following? Generally, the state you are reporting would be the same as the state that you'd return in a [QUERY](https://developers.google.com/actions/smarthome/traits/colortemperature#response).

So it'd be more like

```
"color": {
          "name": "warm white",
          "temperature": 25000
        }
```

**Comment by sky9971** [comment]
Thanks for your reply. 
I'm following  [https://developers.google.com/actions/smarthome/traits/colorspectrum](url)
under the device attributes you have color model. The reason i'm sending **spectrumhsv** is because I have hsv as a color model for my sample light so it's a lot easier for me to pass on the commands from google action to my device without any conversion.
The sync requests as well as all of the commands are working for me except for the report state.
As per the documentation it nowhere mentions QUERY for color spectrum. I also failed to find any information regarding the hsv spectrum in google action.
Could you please shed some light on this topic, like what is the correct format for sync, execute and report state if I am using hsv as my color model.

**Comment by sky9971** [comment]
Yes I have already tried various combinations to make it work, I even tried `spectrumHsv`  it doesn't work either. But the question still remains, are we supposed to send report state for spectrum hsv or not? or we only send report state for `on, online and brightness`  attributes?

And lastly can I expect something from your end a little sooner because we're already into production and we want to hit the market with a product which is google home compatible. So if there are any changes to be made we can do them before we go live.

**Comment by sky9971** [comment]
But that's just a work around, we were looking for a solid solution. Anyways will do that. 
One last query if we send RGB in report state, I hope it will not cause any problem in certification.

**Comment by Fleker** [comment]
A better solution is not going to be ready in the short-term. Sending the correct RGB state should not cause any issues in the certification process.

**Comment by sky9971** [comment]
Please keep the issue open for the mean time and update me whenever the support for `HSV spectrum` is ready. Thank you for your support.

**Comment by Fleker** [comment]
At some point it will be useful to migrate to the unified [ColorSetting](https://developers.google.com/actions/smarthome/traits/colorsetting) trait, which provides the ability to report in HSV directly.

**Comment by sky9971** [comment]
Migrated to ColorSetting trait. Thanks
