### ISSUE TITLE
AvailableModes for AC_Unit

### ISSUE THREAD

**Issue by matts4v** [actions-on-google/smart-home-nodejs#169]
Hello,
I'm trying to build an app to control an Air Conditioning Unit. I've seen that one of the available trait is the Modes (https://developers.google.com/actions/smarthome/traits/modes) one, but I couldn't find a complete list of these modes.
I would like to know if in this list there are the "Dry" mode and "Fan" mode, or if in the future they will be available.
Thank you

**Comment by Fleker** [comment]
You can take a look at the [FanSpeed](https://developers.google.com/actions/smarthome/traits/fanspeed) trait.

There is a mode called "Fan Speed" and "fan_position".

There is a mode setting called "Dry".

**Comment by matts4v** [comment]
Thank you!
Is there the possibility to have a complete list of all the possible modes?

**Comment by Fleker** [comment]
We've published the first set of reference documentation: https://developers.google.com/actions/reference/smarthome/traits/modes

**Comment by Takhion** [comment]
> There is a mode called "Fan Speed" as well as "**fan_position**".

@Fleker what happened to `fan_position`? I can't find any reference to it 🤔

**Comment by Fleker** [comment]
Oh, those may not currently be marked in the documentation, but they should work.
