### ISSUE TITLE
Problem with setting FanSpeed velocity

### ISSUE THREAD

**Issue by matts4v** [actions-on-google/smart-home-nodejs#170]
Hello,
during the testing on my AC_Unit application I've found this anomaly.
In the beginning I'm setting the AC states as follow:
```
{ states:
   { currentFanSpeedSetting: 'Auto',
     nameChanged: false,
     on: false,
     online: true,
     thermostatHumidityAmbient: 43,
     thermostatMode: 'heat',
     thermostatTemperatureAmbient: 27.5,
     thermostatTemperatureSetpoint: 23,
     thermostatTemperatureSetpointHigh: 25,
     thermostatTemperatureSetpointLow: 19 },
  properties:
   { attributes:
      { availableFanSpeeds: [Object],
        availableThermostatModes: 'off,heat,cool,on',
        reversible: false,
        thermostatTemperatureUnit: 'C' },
     deviceInfo:
      { hwVersion: '1.1',
        manufacturer: 'gl1',
        model: '1.0.0',
        swVersion: '1.0.11' },
     name:
      { defaultNames: [Array], name: 'sala', nicknames: [Array] },
     roomHint: '',
     traits:
      [ 'action.devices.traits.TemperatureSetting',
        'action.devices.traits.FanSpeed',
        'action.devices.traits.OnOff' ],
     type: 'action.devices.types.AC_UNIT',
     willReportState: false,
     id: '7' }
```
and after a fanspeed command when i query the states Google send me this
query response 

```
{
  "requestId":"7119407614065184561",
  "payload":{
    "devices":{
      "7": {
        "currentFanSpeedSetting":"Low",
        "nameChanged":false,
        "on":false,
        "online":true,
        "thermostatHumidityAmbient":43,
        "thermostatMode":"on",
        "thermostatTemperatureAmbient":25.1,
        "thermostatTemperatureSetpoint":23,
        "thermostatTemperatureSetpointHigh":25,
        "thermostatTemperatureSetpointLow":19,
        "fanSpeed":"Highest"
      }
    }
  }
}
```
So it looks like that Google update correctly the velocity of the fan, but it creates a new variable fanSpeed insead of updating the currentFanSpeedSetting, that it couldn't read when I ask for the query.
How can I change it in the correct behavour?
Thank you

**Comment by Fleker** [comment]
You're sending a `QUERY` to the homegraph to get the device's state? What available fan speeds do you have?

**Comment by matts4v** [comment]
Yes I'm sending the `QUERY` to the homegraph, and I've also tried to send a `SYNC` request to be sure that the device is setting correctly. I've implemented also lights and relays, and with this devices I have no problem when i query the state. I put as options "auto", "low", "high" and "highest" as fan speed velocity.

**Comment by Fleker** [comment]
When you give a command to control the fan speed, do you get a valid `EXECUTE` intent?

I don't know that the fan speed trait has interrogative queries right now (What is the speed of my fan) so this may be an intended although unusual behavior.

**Comment by matts4v** [comment]
Yes the `EXECUTE` command perform correctly, according to the `EXECUTE` sample of fan speed traits in the developers guide, and I can see the fan speed change on my device.
