### ISSUE TITLE
devices deleted on refresh

### ISSUE THREAD

**Issue by jarvisgaurav** [actions-on-google/smart-home-nodejs#171]
Hi,
I have disabled the resetDevice=false in config-provider.js file so that the devices remain intact for the logged in user even though the page is refreshed or closed, still the devices are deleted on refresh. Kindly help me with this
Thanks in advance.

**Comment by RT4U** [comment]
Yeah, I've the same issue!

**Comment by lucaswadedavis** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.

**Comment by Fleker** [comment]
I think this issue is still valid for now.

**Comment by Fleker** [comment]
The sample has now been significantly updated. Devices will be configured with a persistent datastore like Firestore to persist across sessions.
