### ISSUE TITLE
Add ECO Mode Settings

### ISSUE THREAD

**Issue by insrat** [actions-on-google/smart-home-nodejs#172]
setting_name: ECO
setting_synonym: eco, energy save

**Comment by Fleker** [comment]
`Eco` is an existing setting_name, and `energy saving` is another existing setting_name. I'll make sure this is added to the documentation.

**Comment by insrat** [comment]
How can I see the latest mode? except https://developers.google.com/actions/smarthome/traits/modes.
I can't find `energy saving`

**Comment by Fleker** [comment]
We did not update the documentation yet.
