### ISSUE TITLE
Please add `Comfort` and `Antifreeze` mode

### ISSUE THREAD

**Issue by insrat** [actions-on-google/smart-home-nodejs#173]
Please help add some content, thank you.

setting_name: **Comfort**
setting_synonym: **comfort**

setting_name: **Antifreeze**
setting_synonym: **antifreeze, anti freeze, anti-freeze**

**Comment by Fleker** [comment]
Hi, we currently have a mode name `comfort` with the synonym of `comfort`. We have as setting `comfortable` with the synonym `comfortable`.

We do not have an antifreeze mode. I'll add that in.

**Comment by Fleker** [comment]
You should expect to see the new modes available in a day or two.
