### ISSUE TITLE
Dutch language issues

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#177]
Some of my users have now switched to their native Dutch and have hit issues:
Scenes not being discovered;
Individual lights switch on/off, but can't be done en masse in a room;

This is a user who has switched from English to Dutch, data being sent hasn't changed.

**Comment by Fleker** [comment]
Can you put together a set of reproducible cases?

**Comment by madgeni** [comment]
going to close this, as these issues seem to be damping down. However it's worth noting the same was experienced when Italian went live
