### ISSUE TITLE
Exposing to multiple accounts

### ISSUE THREAD

**Issue by i8beef** [actions-on-google/smart-home-nodejs#181]
How can we expose our Google Action to multiple accounts, e.g., so that both I and my wife can execute things from our phones? I added her account with "View" permissions in the Google Actions console, but she still can't trigger commands from her phone.

**Comment by Fleker** [comment]
If you're setting up this project in a development/test environment, both users will need to go to the Actions console for the project, enable testing, and then link their accounts through the Assistant app on their phone.

**Comment by i8beef** [comment]
So it looks like the home app has a "invite" to bring other accounts into your "Home". I found that inviting her account to be a member on my home also enabled her to use the voice commands without having her create a gactions account, etc., so it's all managed under my account.

**Comment by Fleker** [comment]
That's great!
