### ISSUE TITLE
Please add following Modes (de)

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#182]
Hi,
please add following modes for German language:

Mode names
saugkraft|saugkraft, saugstärke
saugmodus|saugmodus, modus
mode|mode, modus
input source|input source, eingangskanal, eingangsquelle, quelle
output source|output source, ausgangskanal, ausgang
temperature|temperature, temperatur
level|level, stärke

Mode settings
quiet|quiet, leise
balanced|balanced, normal
turbo|turbo
maximum|maximum, max
zonenmodus|zonenmodus
manuell|manuell
heizen|heizen
kühlen|kühlen
eco|eco, eco modus
warm|warm
boost|boost
energiesparmodus|energiesparmodus

Thanks,
Dominik

**Comment by Fleker** [comment]
We'll probably keep all of the keys in English, with German synonyms/values, as these get added in.

**Comment by Fleker** [comment]
Docs are updated, it may take a day or two for the grammars to roll out.

**Comment by dominikkarall** [comment]
Great, thanks!
