### ISSUE TITLE
Please add following Modes

### ISSUE THREAD

**Issue by cly12345** [actions-on-google/smart-home-nodejs#183]
Hi,

I'm working on a project where my fan have some modes which I want to manage with my Smart Home Actions.
These are my current traits for my devices :

"type": "action.devices.types.FAN",
"traits": [ "action.devices.traits.OnOff","action.devices.traits.FanSpeed","action.devices.traits.Modes"]

I'd like to have more modes for my device, like :

swing(en) / swing(ja)
timer(en) / timer (ja)
sleep(en) / sleep (ja)

Is it possible to add them in one of these traits ?

Thanks in advance !

**Comment by Fleker** [comment]
We can add those additional modes

**Comment by Fleker** [comment]
We've updated the docs. The changes should be live in a day or two.

**Comment by Fleker** [comment]
It looks like they're rolling out now.
