### ISSUE TITLE
Docker Compose and LetsEncrypt Support

### ISSUE THREAD

**Issue by gurumeditator** [actions-on-google/smart-home-nodejs#185]
Is there any interest in running this project using _Docker Compose_ and _LetsEncrypt_? I have successfully tested initial implementation and would like to contribute.

**Comment by Fleker** [comment]
That definitely sounds interesting, although I'm not sure how valuable the changes would be to the wider audience of this sample. As things grow more niche, it may be more valuable for you to have a Docker version of this sample that you can host and point to.

**Comment by gurumeditator** [comment]
A _Docker_ file is included which eliminates the need for host Node dependencies and provides low friction deployment. The addition of a _Docker Compose_ file in addition to providing TLS support allows the easy addition of the parameters needed to personalize the sample via environment variables including the API key and OAuth credentials. While helpful for me, perhaps the addition of _LetsEncrypt_ may create a more niche solution. I am open to making any changes.

Fork is located [here](https://github.com/gurumeditator/smart-home-nodejs/tree/docker) for anyone interested.

**Comment by Fleker** [comment]
Thanks
