### ISSUE TITLE
Door sensor?

### ISSUE THREAD

**Issue by davidhurtig** [actions-on-google/smart-home-nodejs#187]
Hi!

I'm working on a project where I try to integrate a door sensor with google assistant. I would like to be able to ask the assistant "is the living room door open" or closed for example.

I'm aware that the devices does not really matter and I can choose whatever device type. But I'm having a hard time finding good traits for this type of device. To clarify the door sensor can only have two values, 1 or 0 open or closed.

What kind of traits do you recommend for this type of sensor?
I have tried both the toggles and modes traits but neither of them worked as expected. I couldn't get them to return if the door was open or closed. I tried with lots of different traits and modes.

**Comment by florianh1** [comment]
you can make a custom pcb and buy a sensor for it depending on what you want and what you want to spend:

you can buy a cheap ldr but this only works during the day
you can buy a cheap infrared sensor works all the time
you can buy a cheap distance sensor (this one is little bit more expensive still not above few bucks but this gives you more chance to expand

btw not buying a cheap easy custom pcb is also possible there are alot of choices depending on what you want to do with it

you can also buy something like a ESP8266 and expand it to much more than only a door sensor for everything together u should not pay more than 10 bucks (and that is the expensive ESP version of it)

**Comment by Fleker** [comment]
The best trait I'd recommend would be a toggle, or maybe OnOff. It's a bit weird to ask "is my door on", although there's no Sensor trait in the docs.

**Comment by davidhurtig** [comment]
> The best trait I'd recommend would be a toggle, or maybe OnOff. It's a bit weird to ask "is my door on", although there's no Sensor trait in the docs.

We did tried the toggle trait, but with no success to get it to understand a Query but only Execute. I assume the Query is what we want to do if we just want the status of something? The syncing also seems to work fine when we connect the device for the first time.

**Comment by Fleker** [comment]
What toggle would you be using? Looking at [the list of available toggles](https://developers.google.com/actions/reference/smarthome/traits/toggles), I don't see one that may be more useful.

**Comment by davidhurtig** [comment]
> What toggle would you be using? Looking at [the list of available toggles](https://developers.google.com/actions/reference/smarthome/traits/toggles), I don't see one that may be more useful.

We did tried different toggles. For example we just wanted to try if toogle name "Away" would work for a open door, and Hold for closed door. Just for testing we then asked the assistant "Is the door away?" And the expected results would be that the assistant fired our Query function but it did not. It did understand something in the way of "Turn the door away" and fired our Execute function but since we are talking about a sensor we cant execute anything on it, only read from it.

**Comment by Fleker** [comment]
I tried out a similar query and I was able to get the expected result.

"Is _quiet_ on the _kitchen vacuum_"

> Kitchen vacuum quiet is on

I imagine that a question of "Is away on the door" would work.

**Comment by zoic21** [comment]
+1 device type sensor is good idea  like : 
- door sensor : are there doors / windows open? yes the window of the kitchen
- temperature sensor : what is the temperature in the kitchen? It's 21°C

**Comment by davidhurtig** [comment]
> I tried out a similar query and I was able to get the expected result.
> 
> "Is _quiet_ on the _kitchen vacuum_"
> 
> > Kitchen vacuum quiet is on
> 
> I imagine that a question of "Is away on the door" would work.

Mhmm, yes maybe it would work even though it's really weird to ask anything like that. Are there any plans for releasing something in the near future for making something like this more easy and natural?



> +1 device type sensor is good idea like :
> 
> * door sensor : are there doors / windows open? yes the window of the kitchen
> * temperature sensor : what is the temperature in the kitchen? It's 21°C

Yes it would be really good if they implemented something like this.

**Comment by Fleker** [comment]
I can't comment on future releases, but I will pass on the suggestion of a sensor.

**Comment by i8beef** [comment]
Please vote up my original issue on this too! There's plenty of us looking for a proper open/close trait right now!

https://github.com/actions-on-google/smart-home-nodejs/issues/99

**Comment by chearmstrong** [comment]
@Fleker Is there any news/updates on this - is there planse to add sensor traits?

**Comment by i8beef** [comment]
Someone has accumulated a lot of the rumored / partially implemented stuff in the Google API [here](https://github.com/actions-on-google/smart-home-nodejs/issues/253). No word yet on release date / finalization / documentation of any of these though.

**Comment by Fleker** [comment]
As this is not directly related to the sample, I've copied this request over to the public issue tracker.

https://issuetracker.google.com/issues/136103089
