### ISSUE TITLE
ColorAbsolute

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#188]
Hi - 
noticed you've deprecated ColorSpectrum & ColorTemperature (is there a mailing group i can get onto to get notified of this stuff?). 
Documentation says for temperature that it sends:
"params": {
            "temperature": 4000
          }

But it's still sending:
"params": {
{ color: { name: 'warm white', temperature: 3000 } }
}
please advise on whether it will change ?

**Comment by Fleker** [comment]
[ColorAbsolute](https://developers.google.com/actions/smarthome/traits/colorsetting) was only recently added. We did not announce it, and the deprecated traits should still work in lieu of migrating.

I'll look into whether the documentation is incorrect. The trait is designed to merge both color traits together with minimal migration work being necessary.

**Comment by madgeni** [comment]
Thanks @Fleker - appreciate the deprecated traits still work, but makes sense to migrate ahead. 

Agree that it's working, and didn't take much effort, but it would be useful to know how to keep up with changes when released (or prior), and that i'm implementing them correctly (hence the doc comment)

**Comment by Fleker** [comment]
Okay I've confirmed this behavior. We'll update the docs.
