### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by zoic21** [actions-on-google/smart-home-nodejs#189]
Hi,

Is it possible to send a notification to user phone with smarthome ? Like a report state but for notification.

Thank in advance,

**Comment by Fleker** [comment]
No, notifications are not a supported feature you can do directly through smart home. If the user set up the device with a companion app, you could send notifications through that way instead.

**Comment by mikaelwecode** [comment]
What about this? 

https://developers.google.com/actions/reference/smarthome/rest/v1/devices/reportStateAndNotification

"It also optionally takes in a list of Notifications that may be created, which are associated to this state change."

**Comment by Fleker** [comment]
That's a feature that is available to a few EAPs, although I don't believe it will work for most projects.

**Comment by mikaelwecode** [comment]
What is EAPs?  Do you know when this will be available for use?

**Comment by Fleker** [comment]
There are some early access partners who will try out new features and APIs before they're generally available for all developers. I don't have timelines on when this feature will be available.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed.

If you think the resolution is in error, please re-open the request with fresh information.
