### ISSUE TITLE
Testing Actions in Simulator says "Action is not available"

### ISSUE THREAD

**Issue by shivalipawar** [actions-on-google/smart-home-nodejs#190]
I have followed the steps mentioned in the READ ME for this project but when i go to test this actions on Simulator in Actions on Google it returns "_Sorry this action is not available for your app.In the simulator, you are only able to invoke actions that you have added to your app_"

**Comment by Fleker** [comment]
The correct order of operations is

1. Initialize the action for testing
2. Account linking in the Assistant mobile app
3. Sync your devices
4. Simulate on your device or in the simulator

However, in the simulator, it will suggest "talk to my test app" but that won't work. Instead you can directly type commands that will be routed to your action.

**Comment by Fleker** [comment]
"Talk to my SmartHomeProj" will not work because it's not a conversational action. You can just type "turn on my light" and it'll work.

**Comment by shivalipawar** [comment]
Ok thanks that helped.

**Comment by shivalipawar** [comment]
If we have our existing cloud which connects to our security device then should we use this sample as starter project? OR
Should we enable our cloud to handle "Add Request Sync" , "Add Report state" methods and on actions console project just add our cloud url?
Also how can DialogFlow be used in this case?

**Comment by Fleker** [comment]
If you have an existing cloud, you could look at this code as a reference, but you may just want to look at JSON request and responses and implement those in your existing code.

In the console you only put in your fulfillment URL. The Request Sync and Report State capabilities are outbound API calls, going from your server to the home graph. You should add those in, but they are not URLs that you put into the console.

Dialogflow is not used at all for smart home projects. Grammars are handled out of the box.

**Comment by Fleker** [comment]
At the moment, there is no "Security Panel" type. You would need to pick another device type, which would only change how the device is displayed, with particular traits like [OnOff](https://developers.google.com/actions/smarthome/traits/onoff) or [Toggles](https://developers.google.com/actions/smarthome/traits/toggles). Though neither would be ideal for you, that would unblock you for development.

**Comment by Fleker** [comment]
1. You'll need to look at the server headers to see what it may need in terms of CORS.

2. The `/smart-home-api` is the endpoint that would be appended to the base URL. For example.com, it refers to `example.com/smart-home-api`.

3. The Google Assistant runs natural language processing on user queries and creates the necessary JSON requests to accomplish this task.
