### ISSUE TITLE
Keeping test account live?

### ISSUE THREAD

**Issue by i8beef** [actions-on-google/smart-home-nodejs#191]
Is there any way to keep Google Actions from expiring our projects? I've tried the Google Actions test button, gactions with a `./gactions test --action_package action.json --project YOURPROJECTID --preview_mins 9999999`, etc... and eventually it always expires and I have to rerun one of these.

Is there anyway to keep these active?

**Comment by Fleker** [comment]
There's no way to keep a test draft active indefinitely. You would need to rerun the command periodically or submit the project for review and full deployment.

**Comment by i8beef** [comment]
Ok, thanks. Will document and provide scripts for my users to just automate running gactions every little bit. What's the maximum length of time here? A month?

**Comment by Fleker** [comment]
gactions supports a [`--preview_mins` flag](https://developers.google.com/actions/tools/gactions-cli#supported-arguments) although I believe it is 30 days by default.

**Comment by i8beef** [comment]
Right, which is what I and others have tried using, but it seems to have some undocumented maximum. As you see above, I used `9999999`, which is a little over 6944 days... but it is clearly expiring way before that. So I'm looking for guidance to give others on how often we need to run this to renew our personal Google Actions.

**Comment by i8beef** [comment]
I also see that the actual `gactions test --help` documentation states that flag is deprecated. And the Google documentation on the site (https://developers.google.com/actions/tools/gactions-cli) claims its still in play. It also claims that these don't expire though...

**Comment by Fleker** [comment]
I've filed an issue to correct the documentation.
