### ISSUE TITLE
German Modes not working?

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#192]
Hi,

unfortunately I can't get Modes working. I try it with a vacuum device which should suction modes like: quiet, balanced, turbo, maximum. See my SYNC response (device section only) below:

`
{
   "id":"walle",
   "deviceInfo":{
      "manufacturer":"DeviceManufacturer",
      "model":"vacuum.v1"
   },
   "name":{
      "name":"Wall-E"
   },
   "willReportState":true,
   "traits":[
      "action.devices.traits.OnOff",
      "action.devices.traits.Brightness",
      "action.devices.traits.StartStop",
      "action.devices.traits.Dock",
      "action.devices.traits.Locator",
      "action.devices.traits.Modes"
   ],
   "attributes":{
      "pausable":true,
      "availableModes":[
         {
            "name":"suction",
            "name_values":[
               {
                  "name_synonym":[
                     "saugkraft",
                     "saugstärke"
                  ],
                  "lang":"de"
               }
            ],
            "settings":[
               {
                  "setting_name":"quiet",
                  "setting_values":[
                     {
                        "setting_synonym":[
                           "ruhe",
                           "ruhe-",
                           "ruhemodus",
                           "leise"
                        ],
                        "lang":"de"
                     }
                  ]
               },
               {
                  "setting_name":"balanced",
                  "setting_values":[
                     {
                        "setting_synonym":[
                           "balanced",
                           "normal"
                        ],
                        "lang":"de"
                     }
                  ]
               },
               {
                  "setting_name":"Turbo",
                  "setting_values":[
                     {
                        "setting_synonym":[
                           "turbo"
                        ],
                        "lang":"de"
                     }
                  ]
               },
               {
                  "setting_name":"maximum",
                  "setting_values":[
                     {
                        "setting_synonym":[
                           "max",
                           "maximum"
                        ],
                        "lang":"de"
                     }
                  ]
               }
            ],
            "ordered":true
         }
      ]
   },
   "customData":{
      "device":"walle"
   },
   "roomHint":"Schlafzimmer",
   "type":"action.devices.types.VACUUM"
}
`

My command...
> Stelle Wall-E auf leise
English: Set wall-e to quiet

Response:
> Der Staubsauger Wall-E unterstützt diesen Modus nicht.
English: The vacuum wall-e doesn't support that mode.

I already relinked the account but it still doesn't work. Has anyone tried the German modes successfully?

Thanks,
Dominik

**Comment by dominikkarall** [comment]
Hi,
any updates on this one? German modes are still not working. English modes worked for me, so it seems to be an issue with the language integration.

**Comment by dominikkarall** [comment]
Any updates on this one? Currently I get "The agent returned an empty TTS." as response.

**Comment by Fleker** [comment]
I'll check the investigation.

**Comment by VeegY** [comment]
Hey there guys, I have the same problem as described above (with other settings to the mode-trait).
Response went from "x does not support this mode" to "The agent returned an empty TTS" for me, too.
I just wanted to quickly leave some information whether they help or not:
* Neither the query nor the execute response get through to the backend when using a phrase containing a mode (as a note: mode refers to the device trait: modes)
* Implementing the report state does not fix the problem (I thought the homegraph may need to know the current mode or w/e)
* I checked about three times that I use the correct name, name_synonym, setting_name and setting_synonym specified in [this list](https://developers.google.com/actions/reference/smarthome/traits/modes)
* [The validator](https://developers.google.com/actions/smarthome/tools/validator/) returns no errors

**Comment by Fleker** [comment]
No update at this time.

**Comment by dominikkarall** [comment]
Is this a general problem, or only limited to some accounts? I saw that there are other developers working on German modes as well and I'm wondering that it is working for them?

**Comment by Fleker** [comment]
The original issue appears to no longer be reproducible.
