### ISSUE TITLE
Could you add the build script?

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#194]
I want to build the project to run on another machine. 

Thanks

**Comment by Fleker** [comment]
Do you have any questions about the build process?

**Comment by wyx2000** [comment]
I am still using the old version with Polymer 1.0, but I just checked the current version doesn't have build script in the package.json,  see below. How do I build the project so I can run it in another machine?

  "scripts": {
    "start": "node index.js isLocal",
    "lint": "eslint --fix \"frontend\\src\\*.html\" \"cloud\\*.js\" smart-home-app.js",
    "test": "npm run lint && npm audit"
  },

**Comment by Fleker** [comment]
There is no such version. This is a code sample, primarily for demonstrating how the APIs work.
