### ISSUE TITLE
Page doesn't display in samsung galaxy phone.

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#195]
Tried chrome on S8, doesn't show any device on the page

**Comment by Fleker** [comment]
What do you mean "doesn't show any device"? Is the page devoid of anything, or devoid of all content? Which browser are you using? Perhaps the browser doesn't support specific features.

**Comment by wyx2000** [comment]
I figured out it is the iron-list issue. And I am still using the old version with Polymer 1.0, now the project is on Polymer 2.0. 
I wonder when the project will be upgraded to Polymer 3.0 though
