### ISSUE TITLE
Report State Implementation

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#196]
After my smart home submission We have shipped our devices to the below address but in response they have asked to implement REPORT STATE in smart home.
Allion USA
...

https://developers.google.com/actions/smarthome/report-state
I don't know how frequent this report state api will be called and aslo what the request json be like for report api. How can i get the auth token and all from request.

**Comment by Fleker** [comment]
Report state is a required feature for smart home going forward. The documentation at that page should show you how to do it. It should be called every time your device's state is changed client-side, and after every EXECUTE intent.

You will send a call to the Assistant each time your state is changed.

The docs show an example if you're using Java, and if you're using the Node.js library we have an easy `app.reportState` method you can call.

The data you pass in should resemble your response to a QUERY intent, with a device and its states. [This blog post](https://medium.com/google-developers/implementing-report-state-for-your-smart-home-service-d377ce9c1126) can also help demonstrate how to do it.

**Comment by raju102** [comment]
ok. My understanding was like the report state will be called from google side with fixed interval.
That's why i have asked about the  request parameter for report state.
So the report state has to be pushed from our side to google home graph for each execute and query request .
Thanks. i will proceed with implementation and will revert back

**Comment by raju102** [comment]
Report State response {
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}
This is the response i am getting when trying to update report state
Report State request {"requestId":"8034705255809090050","agentUserId":"2152552","payload":{"devices":{"states":{"757022":{"on":true,"online":true,"brightness":"50"}}}}}
This is the report state json i am sending..From where can i get the agentUserId???? Apart from agentUserId rest of the details are valid still i am getting "Requested entity was not found"

**Comment by Fleker** [comment]
The agent user id should match the value that you return in the [sync response](https://developers.google.com/actions/smarthome/create#actiondevicessync). If it doesn't match, you may experience a 404 error.

**Comment by raju102** [comment]
okay.. i have given a unique id in sync and now 404 error has gone.
this is my request 
{"requestId":"4541501065340057826","agentUserId":"100431460070862371976","payload":{"devices":{"states":{"757044":{"on":true,"online":true,"brightness":"1"}}}}}

Response : 

Report State response {
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by Fleker** [comment]
I think you're reporting brightness as a _string_ when it should be an _integer_. Try doing the same thing but without the quotes.

**Comment by Fleker** [comment]
Yeah, it's possible that the home graph hasn't synced the user id immediately after a SYNC. We recommend waiting for a brief period, like a minute or so, after sync before you start sending states.

**Comment by matmartic** [comment]
After searching for some time, I found this issue and it helped me understand why my reportState was constantly returning a 404/"Requested entity not found". As per the documentation,

> The ReportState API should also be called right after a SYNC intent. 

Even with a timeout of a few seconds, it would still fail. I assumed the error was elsewhere until I crossed off everything else that could have gone wrong and came back to this. After a timeout of a minute after the SYNC response (as per the suggestion), it finally works. 

My question is : @Fleker What would you suggest for a clean way to wait for a minute? Currently I'm using a simple setTimeout. But a setTimeout often feels like a last resort / patchwork solution.. Any other solutions come to mind?

**Comment by symdeb** [comment]
Using the Python example sending ReportState. Code returns with Report State has been done successfully but nothing happens in the GUI in the mobile app. EXECUTE, QUERY and SYNC all work fine. If on purpose. using wrong devideId's the API returns an error thus the API seems to correctly read the data.  did also set "WillReportState" to try in SYNC. Does not fix it.

**Comment by paulschuetz** [comment]
> After searching for some time, I found this issue and it helped me understand why my reportState was constantly returning a 404/"Requested entity not found". As per the documentation,
> 
> > The ReportState API should also be called right after a SYNC intent.
> 
> Even with a timeout of a few seconds, it would still fail. I assumed the error was elsewhere until I crossed off everything else that could have gone wrong and came back to this. After a timeout of a minute after the SYNC response (as per the suggestion), it finally works.
> 
> My question is : @Fleker What would you suggest for a clean way to wait for a minute? Currently I'm using a simple setTimeout. But a setTimeout often feels like a last resort / patchwork solution.. Any other solutions come to mind?

I really do not understand how it feels like we are the only ones facing this problem. Again wasted hours of work...

**Comment by raju102** [comment]
Hi Fleker
It seems like the scene's are not getting listed in google home app. During the discovery response i'm giving the type as "action.devices.types.SCENE" which i think is an inbuilt type supported by google. How can i debug this issue??

**Comment by Fleker** [comment]
@raju102 can you open a new issue, as your issue does not appear to be related.

**Comment by kirantpatil** [comment]
> okay.. i have given a unique id in sync and now 404 error has gone.
> this is my request
> 
> ```
> {"requestId":"4541501065340057826","agentUserId":"100431460070862371976","payload":{"devices":{"states":{"757044":{"on":true,"online":true,"brightness":"1"}}}}}
> ```
> 
> Response :
> 
> Report State response
> 
> ```
>  {
>   "error": {
>     "code": 400,
>     "message": "Request contains an invalid argument.",
>     "status": "INVALID_ARGUMENT"
>   }
> }
> ```
> 
> i think that brightness key is causing this issue..when i removed brightness key it worked.
> so how can i update brightness value to home graph??

Hi Raju,

How did you get that unique agentUserId from google account ?

Thanks.

**Comment by raju102** [comment]
> > okay.. i have given a unique id in sync and now 404 error has gone.
> > this is my request
> > ```
> > {"requestId":"4541501065340057826","agentUserId":"100431460070862371976","payload":{"devices":{"states":{"757044":{"on":true,"online":true,"brightness":"1"}}}}}
> > ```
> > 
> > 
> > Response :
> > Report State response
> > ```
> >  {
> >   "error": {
> >     "code": 400,
> >     "message": "Request contains an invalid argument.",
> >     "status": "INVALID_ARGUMENT"
> >   }
> > }
> > ```
> > 
> > 
> > i think that brightness key is causing this issue..when i removed brightness key it worked.
> > so how can i update brightness value to home graph??
> 
> Hi @raju102,
> 
> How did you get that unique agentUserId from google account ?
> 
> Thanks.

The agentUserId i am using is the userId that we generate in our system

**Comment by chishi2612** [comment]
Hi @raju102,
I have an error code 404 after reporting state:
`reportState {"agentUserId":"5922c5885510bd56a11633ad","requestId":"0.12485499186044247","payload":{"devices":{"states":{"5cd15e4886b05a7efb623e86":{"on":false}}}}}`
the response: 
`{
 "error": {
     "code": 404,
     "message": "Requested entity was not found.",
     "status": "NOT_FOUND"
 }
}
`

althrough my agentUserid is the same as sync request. 

Do you use firebase in your project?

**Comment by raju102** [comment]
> 5922c5885510bd56a11633ad

no i don't.. "5922c5885510bd56a11633ad" is this the same agentUserId you gave in sync device response.

**Comment by chishi2612** [comment]
> > 5922c5885510bd56a11633ad
> 
> no i don't.. "5922c5885510bd56a11633ad" is this the same agentUserId you gave in sync device response.

Hi @raju102, 
yes. the same my sync device response: 
`{"requestId":"8183422332663779881","payload":{"agentUserId":"5922c5885510bd56a11633ad","devices":[{...}]`

This is my code:
`expressApp.post(/smarthome', function (request, response) {
        console.log('post /smarthome', request.headers);
        let reqdata = request.body;
        console.log('post /smarthome', reqdata);

        if (!reqdata.inputs) {
            response.status(401).set({
                'Access-Control-Allow-Headers': 'Content-Type, Authorization',
            }).json({error: 'missing inputs'});
        }
        for (let i = 0; i < reqdata.inputs.length; i++) {
            let input = reqdata.inputs[i];
            let intent = input.intent;
            if (!intent) {
                response.status(401).set({
                    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
                }).json({error: 'missing inputs'});
                continue;
            }
            switch (intent) {
                case 'action.devices.SYNC':
                    console.log('post /smarthome SYNC');
                    sync(request, response);
                    break;
                case 'action.devices.QUERY':
                    console.log('post /smarthome QUERY');
                    query(request, response);

                    break;
                case 'action.devices.EXECUTE':
                    console.log('post /smarthome EXECUTE');
                    exec(request, response);
                    break;
                case 'action.devices.DISCONNECT':
                    console.log('post /smarthome DISCONNECTED');
                    disconnect(request,response);
                    break;
                default:
                    console.log(intent);
                    response.status(401).set({
                        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
                    }).json({error: 'missing intent'});
                    break;
            }
        }
    });`

**Comment by raju102** [comment]
> 5922c5885510bd56a11633ad

are you hard coding the agentUserId string (5922c5885510bd56a11633ad)

**Comment by chishi2612** [comment]
no i don't. I get user id from token of our system.

**Comment by chishi2612** [comment]
@raju102 i don't know does google save my user id after syncing request?

**Comment by raju102** [comment]
> @raju102 does google save my user id (agentUserId) after syncing request?

yes they do. For reporting state change for a device we need to give agentUserId + state change response form your cloud. Requested entity was not found occurs because  {"devices":{"states":{"5cd15e4886b05a7efb623e86":{"on":false}}}}}  "5cd15e4886b05a7efb623e86" this device is not in the google home graph. i don't thing this response is due to wrong agentUserId it's due to wrong Id you give in for discovery

**Comment by chishi2612** [comment]
This is my device in sync:
`{"requestId":"8183422332663779881","payload":{"agentUserId":"5922c5885510bd56a11633ad", devices:[{"id":"5cd15e4886b05a7efb623e86","type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"name":"Switch"},"attributes":{},"deviceInfo":{"manufacturer":"MY COMPANY"}}]}`
do you think it 's wrong?

**Comment by chishi2612** [comment]
@raju102  I try only requestSync with this userId. I get the same error: 
`{
 "error": {
   "code": 404,   
   "message": "Requested entity was not found.",
   "status": "NOT_FOUND"
  }
}`

is there the way to force save my agentUserId in google system?

**Comment by raju102** [comment]
> @raju102 I try only requestSync with this userId. I get the same error:
> `{ "error": { "code": 404, "message": "Requested entity was not found.", "status": "NOT_FOUND" } }`
> 
> is there the way to force save my agentUserId in google system?

 "willReportState": true  this key value is missing in your json..Also after sync request you need to report the state to google 
https://developers.google.com/actions/smarthome/develop/report-state.
But just keep a delay for 5 sec reporting state...
                   setTimeout(function() {
                    app.reportState(requestId, reportSyncJson, agentId);
                  }, delayInMilliseconds);

**Comment by raju102** [comment]
> > @raju102 I try only requestSync with this userId. I get the same error:
> > `{ "error": { "code": 404, "message": "Requested entity was not found.", "status": "NOT_FOUND" } }`
> > is there the way to force save my agentUserId in google system?
> 
> "willReportState": true this key value is missing in your json..Also after sync request you need to report the state to google
> https://developers.google.com/actions/smarthome/develop/report-state.
> But just keep a delay for 5 sec for reporting state...
> setTimeout(function() {
> app.reportState(requestId, reportSyncJson, agentId);
> }, delayInMilliseconds);

**Comment by chishi2612** [comment]
Hi @raju102 
thanks for responding. This is my stupid mistake. I used another service account. :(
Now i have new problem: I only control my device when click button in google home app in ios, but using voice commands, no request send to my server. @Fleker can u support me this problem? 
thanks

**Comment by Fleker** [comment]
That seems like an issue that should be made in a new issue. From the current description, it's not clear at all what is happening.
