### ISSUE TITLE
Help/Inputs Needed :For executing this example in server less (like AWS lambda)

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#197]
i am checking and studying the example to run in the server less environment like AWS lambda..
If there is any inputs/guidance please let me know.

**Comment by Fleker** [comment]
You may want to look at using the [Actions on Google Node.js library](https://github.com/actions-on-google/actions-on-google-nodejs).

**Comment by sakthisg** [comment]
Thanks nick for the info!
1. Can we use actionssdk for smart home control also?
2. Are all the functions in the smarthome sample shall we implement using
actionssdk?

**Comment by Fleker** [comment]
No, you cannot use Actions SDK for smart home. Also, you can't use Dialogflow. Smart home is independent of either tool, as the grammars are predefined. You would be using the [`smarthome`](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/smarthome.smarthomeapp.html) service.

**Comment by sakthisg** [comment]
Thanks!

**Comment by sakthisg** [comment]
I have studied the interface for smarthome what is mentioned..I need more
information on how to do account linking using oauth using smart home
interfaces?

**Comment by sakthisg** [comment]
I have studied the interface for smarthome what is mentioned..I need more
information on how to do account linking using oauth using smart home
interfaces?

**Comment by sakthisg** [comment]
Ok. Thanks for the info!
