### ISSUE TITLE
Should not the devices be in one iron-list?

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#198]
Same as version 1, devices now put into different iron-list categorized by type, this doesn't arrange the page layout well.

**Comment by Fleker** [comment]
Right now the iron-lists are one-per-device type. So yeah it's not the best UI. I'm working on a major revamp of the frontend to make the devices display in a more logical manner, although it's not the highest priority as that does not block the sample usage.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed.

If you think the resolution is in error, please re-open the request with fresh information.

**Comment by Fleker** [comment]
This is still a valid issue.

**Comment by Fleker** [comment]
The sample has now been significantly updated. All devices are of the same element, and they all appear in a unified grid.
