### ISSUE TITLE
new Mode names

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#201]
Want new name and name synonyms you can use for the Modes trait.
I want to control home alarm system, it has four modes, On/Off/Panic/Ring?

**Comment by Fleker** [comment]
You can take a look at all of the available modes in our [reference pages](https://developers.google.com/actions/reference/smarthome/traits/modes). It does show "Off" as an available mode. I will make a note to add the other three requested.

**Comment by Fleker** [comment]
So I will put in a request to add `On`, `panic`, and `ring` as new mode settings.

**Comment by Fleker** [comment]
This was submitted and should be available now.
