### ISSUE TITLE
How to remove a device from home graph

### ISSUE THREAD

**Issue by ahayworth** [actions-on-google/smart-home-nodejs#202]
Apologies if this is the incorrect forum, but I'm having a hard time figuring out the right thing to do here. Assume the following scenario, which is based on something I'm experiencing today. I add a switch called "Living Room Fan" to my IoT backend, and in my next `SYNC` response I include the following data:
```
{
  'id': 'switch.living_room_fan',
  'name': { 'name': 'Living room fan' },
  'traits': [ 'action.devices.traits.OnOff'] },
  'type': 'action.devices.types.SWITCH',
  'willReportState': false
}
```

All is well. I can ask the assistant to 'turn on the living room fan' and I receive an `EXECUTE` request for the `OnOff` trait for this device. However, I wish to represent it to the assistant properly as a fan, not a switch, so that it shows up correctly on various surfaces with the right icons. On the next `SYNC` request, I have changed the data in my IoT backend and I now report the following:
```
{
  'id': 'fan.living_room_fan',
  'name': { 'name': 'Living room fan' },
  'traits': [ 'action.devices.traits.OnOff'] },
  'type': 'action.devices.types.FAN',
  'willReportState': false
}
```
Notably, I include nothing about `switch.living_room_fan`, I only send information about `fan.living_room_fan`.

Now, if I ask the assistant to 'turn on the living room fan,' the assistant responds, 'sorry, I'm not sure which living room fan you'd like to turn on.' Notably, if I ask the assistant 'turn on the living room fanS,' (plural), I receive a _single_ `EXECUTE` request for `fan.living_room_fan` and the `OnOff` trait. Nothing is sent for `switch.living_room_fan` (as expected). The assistant responds in the singular: 'Sure, turning on the living room faN.'

It seems to me that by sending a new device with a different `id` but same `name`, home graph gets confused. The docs around the `SYNC` response [do not indicate](https://developers.google.com/actions/smarthome/create#response_format) that the name should be unique.

What is the right way to report to the home graph that a device no longer exists? If I report state with `online: false`, would that fix it? Notably, un-linking and re-linking my action within the assistant app (and thus triggering a new `SYNC` request/response cycle) doesn't actually seem to fix anything - when I ask the assistant to 'turn on the living room fan,' I receive the same 'sorry I'm not sure which...' response.

How should I implement this device status (present -> permanently not present) transition?

**Comment by Fleker** [comment]
It seems like there may be a caching issue. The names do not need to be unique, although that could create an ambiguity. You should also be able to give them nicknames in the Google Home app to disambiguate them that way instead.

I will investigate this issue.

**Comment by ahayworth** [comment]
Thanks! Let me know what I can do (if anything) to help out.

**Comment by ahayworth** [comment]
@Fleker - just curious, was the problem resolved? My duplicate devices eventually went away, but I was curious if there was ever a root cause identified?

(Of course, I know you probably can't share what that cause _is_, I'm more curious if one existed at all).
