### ISSUE TITLE
Unable to report state for OnOff Trait

### ISSUE THREAD

**Issue by iSukhi** [actions-on-google/smart-home-nodejs#203]

**Comment by iSukhi** [comment]
I am using the following code as provided in sample code in codelab. 
const postData = {
  requestId: 'ff36a3cc', /* Any unique ID */
  agentUserId: '123', /* Hardcoded user ID */
  payload: {
    devices: {
      states: {
        /* Report the current state of our washer */
        [event.params.deviceId]: {
          on: snapshotVal.OnOff.on,
          isPaused: snapshotVal.StartStop.isPaused,
          isRunning: snapshotVal.StartStop.isRunning,
        },
      },
    },
  },
};

return app.reportState(postData)
  .then((data) => {
    console.log('Report state came back');
    console.info(data);
  });

But I am getting error  :**TypeError: Cannot read property 'deviceId' of undefined at exports.reportstate.functions.database.ref.onWrite**

And my event returns only : ** {"before":{"OnOff":{"on":false}},"after":{"OnOff":{"on":true}}}**

rest of the code is same as given in smart washer example.

**Comment by Fleker** [comment]
So the codelab does not work as-is?

**Comment by appblend** [comment]
any solution now?

**Comment by Fleker** [comment]
Is this still happening? It seems like OP closed it, so the issue might be resolved?

**Comment by andresvelezperez** [comment]
Add "context" to onWrite((event,context) and [context.params.deviceId]

```
/**
 * Send a REPORT STATE call to the homegraph when data for any device id
 * has been changed.
 */
exports.reportstate = functions.database.ref('/{deviceId}').onWrite((event,context) => {
  console.info('Firebase write event triggered this cloud function');
  
  const snapshotVal = event.after.val();
  
  const postData = {
    requestId: 'ff36a3cc', /* Any unique ID */
    agentUserId: '123', /* Hardcoded user ID */
    payload: {
      devices: {
        states: {
          /* Report the current state of our washer */
          [context.params.deviceId]: {
            on: snapshotVal.OnOff.on,
          },
        },
      },
    },
  };

  return app.reportState(postData)
    .then((data) => {
      console.log('Report state came back');
      console.info(data);
    });
});
```
