### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#204]
I modified the project to add way to control my X10 and also 315MHZ devices like power socket, home monitoring by arduino.
I found it is better to have one device-connection to communicate with client side instead of the current one device-connection http streaming for each device. Also the current one device-connection for one device doesn't support multi client side neither. What I changed is one device-connection for one client, and store with request session id as key.
Another change I would like is all devices are under one iron-list, the current multi iron-list doesn't arrange page well. I still could not figure out how to do it though.

**Comment by Fleker** [comment]
We're working on improving the quality of the sample.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed.

If you think the resolution is in error, please re-open the request with fresh information.
