### ISSUE TITLE
Support add a lock mode

### ISSUE THREAD

**Issue by cmbannan** [actions-on-google/smart-home-nodejs#207]
Please add 'lock' as an 'availableModes' entry as seen here:  https://developers.google.com/actions/reference/smarthome/traits/modes

Applicable values for this mode would be 'lock', 'unlock' and 'jammed'.
'lock' would have setting_synonym values of 'lock' and 'locked'
'unlock' would have setting_synonym values of 'unlock' and 'unlocked'

**Comment by Fleker** [comment]
Closing this issue as the proper way for this will be a dedicated trait rather than trying to put it into a mode, especially as 'jammed' would result in a potentially odd UX.
