### ISSUE TITLE
Toogle name request: Boost

### ISSUE THREAD

**Issue by RodrigoEspinosa** [actions-on-google/smart-home-nodejs#209]
In Hive, we want to implement "boost" as a toggle for UK thermostats.

**Comment by chearmstrong** [comment]
> In Hive, we want to implement "boost" as a toggle for UK thermostats.

Just for clarity, then `name` will be _boost_ and will have these `name_synonym`s:

- _boost heating_
- _heating boost_
- _boost mode_
- _boost heating mode_
- _heating boost mode_

**Comment by RodrigoEspinosa** [comment]
I believe _heating_ won't be necessary as part of any synonym as the action should cover and match that to the devices for us.
