### ISSUE TITLE
Mode Setting Request

### ISSUE THREAD

**Issue by bperry-prolitec** [actions-on-google/smart-home-nodejs#211]
We have an in-market scent diffuser (http://aeraforhome.com) with intensity settings from 1-10. Please add numeric settings, or enable setting_synonym so that we can leverage other settings. Thank you...

**Comment by Fleker** [comment]
You may want to look at the [FanSpeed](https://developers.google.com/actions/smarthome/traits/fanspeed) trait, as that may be close to what you're hoping to achieve.

**Comment by VeegY** [comment]
@bperry-prolitec can you confirm that using numeric values in the FanSpeed trait works? I am having trouble getting it up and running.

Thanks in advance :)
