### ISSUE TITLE
Account linking failed

### ISSUE THREAD

**Issue by sam0910** [actions-on-google/smart-home-nodejs#212]
Please help me to link.
I've read all issues about this, but I could not solve it.

Error messages below,

**#1, Google Assistant app, I recieved ,
      "Bad response from IdP in Auth Code Exchange"**
> /login  { redirect: '',
  client_id: 'ZxjqWpsYj3',
  redirect_uri:
   'https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fiotlab-rev3',
  state:
   'AICAm6zrU93XwxIZxF1tWbMVw1gOsf6ANPaqZBHMHrF5kIc-b4e83smGdZ9lmG5TQptpJB03BGj_8u2vUIV41tlf3pK78MDzYau9xA_AVHeibIrA87vg8AT3GaftbVCzxV1AzA2nyfmoQOu4OcgUouP61EKNNBPW-SOmybgeCUyw81ii9FFY2vcJZF5hAeU_rCtXqvZs7oE___I7uUe0_9IN53EsBOu5RH8_anKtdTeTj4KqvXkWhbcCPfOUUJAfagRRuQRTvi-qAoTcEnsX4foyPkn56uIR_KyQjCtTmhXTsSNJRwQ2SLqkzQOGice1AxPRx4u2RZh3ZW-bCO6qgg0FvkP73M6ZIhcLcTI4Zrl1f9eUM3g--EH1MEY-FfWzqkzydGtoOJWgyaYV-Oi4XLsbR6iHwNcyHTi5Xq-8kGdL4DZuyDEgmhoGh9TTVCZh0_RP9ebayuHEa02rGZZ7rKc0Gg5-V8jPEmHswjLrrLOy_AtxnRPKFmf-heAs2OkF-HPIop8w6n-Xxmm072dIpnC1KCYoO2bG-4wUsDJDCd7smBHUKu-L8RRP4iwzfKEfTZ3tU8TinCNDSmurMamorpi0iwlISiThJQ',
  username: 'rick',
  password: 'oldman' }
getUser rick
logging in  { uid: '1234',
  name: 'rick',
  password: 'oldman',
  tokens: [ 'psokmCxKjfhk7qHLeYd1' ] }
login successful  rick
authCode successful  6raceai0ob8000000000000000
POST /login 302 1.524 ms - 1466
/token query {}
/token body { grant_type: 'authorization_code',
  code: '6raceai0ob8000000000000000',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/iotlab-rev3' }
missing required parameter
POST /token 400 1.099 ms - 26
----------------------------------------------------------------------------------------
![unnamed3](https://user-images.githubusercontent.com/9714538/48661452-4278e700-eab5-11e8-8451-8f4407f78d04.jpg)

**Comment by sam0910** [comment]
I solve it, I've changed the 'auth-provider.js' file , following Pull Request issue.
It says "Client ID issued by your Actions to Google(in this sample ZxjqWpsYj3) remain constant it will work"
is Client ID variable values in production mode? 
Is Client ID someone's id of my website user?

**Comment by wyx2000** [comment]
client id/client secret is your app(smart-home-nodes run on your server) gives Actions on Google (google home) to identify, so when your app receives a call from Actions on Google, it knows it is the Actions on Google.
So you can generate any client id/secret and fill them in Actions on Google, when a call come in, you just compare client id/secret sent with your stored pair, once match, you know the call is from Actions on Google, not other application

**Comment by Fleker** [comment]
The client id and secret are placed in the Account Linking section of the Actions console.

**Comment by sam0910** [comment]
Thank you so much, wyx2000 and Fleker.
I understood it :)
