### ISSUE TITLE
Example Data structure of Query call on Actions on Google is wrong?

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#213]
I tried to test traits modes, but could not make Google Home recognize the test device, then I found out the example are all wrong, it missed a properties tag, for example, the same response of Query on traits OnOff is like below

![image](https://user-images.githubusercontent.com/1753969/48663728-42430200-ea49-11e8-9f04-180a19318ace.png)

But that doesn't work, Google Home cannot pick device with that response, instead the below works with properties tag added
 
![image](https://user-images.githubusercontent.com/1753969/48663752-88986100-ea49-11e8-8f1c-beb0c4116244.png)

And the above is the structure in smart-home-nodejs

**Comment by Fleker** [comment]
I think there may be some confusion between this sample project, which communicates to the intermediate server before sending things along to the Google Assistant. The documentation is correct, and what this project sends. But to get it from the frontend to the server it uses an intermediate format.
