### ISSUE TITLE
New Mode / Toggle Names

### ISSUE THREAD

**Issue by jakewm** [actions-on-google/smart-home-nodejs#215]
I am requesting the following toggle be added:
name: wrinkle guard; name_synonym: wrinkle guard, wrinkle shield, wrinkle release, wrinkle protect

I am also requesting the following mode settings be added:
setting_name: Convect Bake; setting_synonym: convect bake, convection bake
setting_name: Convect Roast; setting_synonym: convect roast, convection roast

**Comment by Fleker** [comment]
The changes have been implemented and will be rolling out soon. You can view all [modes](https://developers.google.com/actions/reference/smarthome/traits/modes) and [toggles](https://developers.google.com/actions/reference/smarthome/traits/toggles) on our reference pages.

**Comment by jakewm** [comment]
Fantastic!

Thank you so much.
