### ISSUE TITLE
Question: Can we use Actions SDK with json for smarthome?

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#216]
Shall we create a smarthome control using actions SDK ?
as below:
```
{
    "actions": [{
        "name": "actions.devices",
        "deviceControl": {
        },
        "fulfillment": {
          "conversationName": "automation"
        }
    }],
    "conversations": {
        "automation": {
            "name": "automation",
            "url": "****"
        }
    }
}
```

**Comment by Fleker** [comment]
We recommend not using Actions SDK but instead using the Actions console to configure your project.

**Comment by sakthisg** [comment]
Is there any specific reason for not recommending this method?

**Comment by Fleker** [comment]
The console is a bit cleaner to use, and gives access to every URL that you'd need to set, not just the fulfillment URL (you'll also need to set up account linking, which isn't in the actions.json).

**Comment by sakthisg** [comment]
Thanks Fleker!
