### ISSUE TITLE
Smart Home Test Google Account giving 500 error

### ISSUE THREAD

**Issue by abhitheawesomecoder** [actions-on-google/smart-home-nodejs#217]
I am trying to test a smart home Google action in Google assistant App but it's giving 500 error even before authentication (login with Google/Account linking process)

**Comment by abhitheawesomecoder** [comment]
Well, I set Google as oauth provider and not using my oauth server at all

**Comment by Fleker** [comment]
You cannot use Google Sign-In for smart home actions.

**Comment by Fleker** [comment]
You need to use an OAuth server, which is different from OAuth sign-in.

In the latter, you authenticate with Facebook. In the former, the Google Assistant needs to authenticate with you.

There are services like Auth0 which can be employed as OAuth as a service.
