### ISSUE TITLE
Report State doesn't work well?

### ISSUE THREAD

**Issue by wyx2000** [actions-on-google/smart-home-nodejs#218]
I expect when I report state, the status of device on my Google home will change.
Here is what I sent 
Report State request {"requestId":"ff366a3cc","agentUserId":"1234","payload":{"devices":{"states":{"2":{"on":true}}}}}
And I got response like below
Report State response {
  "requestId": "ff366a3cc"
}
does that look right? but I don't see the switch status change, any idea?

**Comment by Fleker** [comment]
Yes it looks like, off-hand, that your request is correct. You do appear to get a `200 OK` response back, as you have a valid response.

How do you expect the switch status to change?

**Comment by wyx2000** [comment]
When I go to Google Home on my android, I see all devices added from my smart-home project under each rooms. Like below,

![image](https://user-images.githubusercontent.com/1753969/48859595-56517100-ed73-11e8-98eb-dc33b76170df.png)

Here I cannot see status of each device even simple one like on/off status. I actually have two question here:
1, When I expect to see on/off status on this page? I mean when Google home will support it.
2, Will device other than on/off like those with traits.modes show different control here? I expect a dropdown or something that I can pick different mode? but I did get what I expected when I tested.

Then I go to the detail page of one on/off device, like below. 

![image](https://user-images.githubusercontent.com/1753969/48859617-6406f680-ed73-11e8-9487-faf898f42627.png)

When I go to this page, Google home does a Query, that makes sense. And I expect when I report state with on and off, the status on this page should be updated, but I didn't see any change. Unless I go to the list page and come back in

**Comment by Fleker** [comment]
These are small nits and feature requests in the app, and don't affect you from a development perspective. I can't say when potential features may be added in the future.

**Comment by wyx2000** [comment]
what about the report state, should not it work there? otherwise how do we tell if report state works?

**Comment by Fleker** [comment]
If you're getting a 200 status back from the API, you can be assured that your call was successful. The implementation in the app / smart display may be improved over time.

**Comment by wyx2000** [comment]
So the report state is not being used anywhere?

**Comment by Fleker** [comment]
It is being used in certain places like on smart displays to provide a realtime status of your home.

**Comment by madgeni** [comment]
So it works on the Home Hub?

**Comment by madgeni** [comment]
so you do! very nice - will this lead to notifications/routines - and will it be released to the Home app?

**Comment by Fleker** [comment]
Routines should work already. Notifications are separate. Updates to the Home app will happen, but I don't have a specific timeline or what features will be added.

**Comment by Fleker** [comment]
Right now a routine will do everything synchronously only. I can't speak to what will happen in the future.

**Comment by wyx2000** [comment]
i don't get what is in the video. It seems changing in smart device reflected on a device. I thought google home app is the one that read from homegraph. While report state is for device server to sync state to homegraph
________________________________

**Comment by symdeb** [comment]
Guess a (semi)-realtime QUERY would create a lot of network traffic. Wondering what the use case of  ReportState is if a QUERY is always needed to update the state.  Only the graph records an event for ReportState,  Whis there no a "RequestQUERY" ? Besides wondering why RequestSYNC uses an API token (much more simple to implement and in many languages) and ReportState needs JWT (limited to Python and JAVA).

**Comment by Fleker** [comment]
For new projects, report state data may not be used in the mobile application at the moment, although the data may be stored correctly.

A regular/periodic QUERY intent would not scale well for larger partners. Reporting the state proactively replaces the need to manually request a QUERY.

RequestSync works with both an API key and a JWT, although the improved security is beneficial generally. JWTs can be generated using a few languages, including Node.js.

**Comment by Watermanman** [comment]
Hi, i got same response from report state.`{  "requestId": "6862331498743849049" }`
How do i check home graph status? is HomeGraph will show some devices list after call report state api successful?
I currently only report state after EXECUTE intent and use the report state dashboard, but nothing show on web page.

**Comment by ftballguy45** [comment]
Its getting close to being 2021, how does the Google Home app not use the report state in a real time manner? This is boiler plate stuff for any kind of real world app nowadays with status. Come on Google! Indeed this is still an issue as of this very moment

**Comment by slaesh** [comment]
still two years later :(

**Comment by ftballguy45** [comment]
This is still an issue, and why was it closed??

**Comment by slaesh** [comment]
guess cause this nodejs-lib does the "right call" .. but unfortunately the google-home-app does not use the home-graph api at all :(
so no realtime updates..

BUT there must be a way. somehow. I got a third-party device with a button and if I press this button the google-home-app does update its state without any interaction of me required.. but for now, no one could answer me how to do the same ...

see this google issue: https://issuetracker.google.com/issues/238499831
