### ISSUE TITLE
Request support for exclusive patterns for washing machines and refrigerators

### ISSUE THREAD

**Issue by chengang7** [actions-on-google/smart-home-nodejs#220]
Hello, I recently developed the support of smart appliances for washing machines and refrigerators, but when I set their device modes, I didn't know how to set them up. Look at the mode names that are supported, it's not what I want, or it's not comprehensive. I would like to set the following schema names, if possible, whether they can be supported, or when custom names can be opened, because this is very important for development.
Here are the patterns I want to support:
Refrigerator:
1.frozen
2.cool
3.smart
4.holiday
5..
Washing machine:
1.standard
2.fastWash
3.hygiene
4.wool
5.babyWash
6.singleDehydration

**Comment by Fleker** [comment]
Are these supposed to be mode names, mode settings, or toggles?

**Comment by chengang7** [comment]
Hi, Fleker! What I'm talking about is mode settings that want to be supported. They can be categorized under the name of mode, I think so.
These are the mode settings I want to support:
Refrigerator:
1.smart
2.holiday
3.cool
4.frozen
Washing machine:
1.cottons
2.blend
3.rinse_wash
4.quick_wash
5.wool
6.babyWash
7.standard
8.synthetics
9.hygiene
Thats all...
Because I'm developing the action of Whirlpool's smart appliances. Unfortunately, I don't know how to set the mode of smart appliances through your api, so can you give me some help? Thank you!

**Comment by chengang7** [comment]
> Are these supposed to be mode names, mode settings, or toggles?

Hi, Fleker! What I'm talking about is mode settings that want to be supported. They can be categorized under the name of mode, I think so.
These are the mode settings I want to support:
Refrigerator:
1.smart
2.holiday
3.cool
4.frozen
Washing machine:
1.cottons
2.blend
3.rinse_wash
4.quick_wash
5.wool
6.babyWash
7.standard
8.synthetics
9.hygiene
Thats all...
Because I'm developing the action of Whirlpool's smart appliances. Unfortunately, I don't know how to set the mode of smart appliances through your api, so can you give me some help? Thank you!

**Comment by chengang7** [comment]
I am  requesting the following mode settings be added:
setting_name: smart; setting_synonym: smart, intelligence
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation
setting_name: holiday; setting_synonym: holiday,vacation

**Comment by Fleker** [comment]
Okay.

**Comment by Fleker** [comment]
The changes have been implemented and will be rolling out soon. You can view all [modes](https://developers.google.com/actions/reference/smarthome/traits/modes) and [toggles](https://developers.google.com/actions/reference/smarthome/traits/toggles) on our reference pages.

Note that some of the suggestions have already been implemented, such as `standard`.
