### ISSUE TITLE
Info needed on the SYNC response

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#221]
Hi,
While respond to the action.devices.SYNC request, we need to fill the agentUserId in the payload field.
How to get the info, i understand it should be unique number.  can you give some details on this?

**Comment by Fleker** [comment]
The agent user id is the ID of the user with respect to your agent.

Here's an example.
Let's say you bought a fan from Nick Corp. You create an account using an email address and set up the fan in Nick Corp's cloud.

Later, you want to sync devices to your Google Assistant. Nick Corp needs a unique identifier to know, when a list of devices come back, who that should be linked to. Nick Corp needs to provide a user id. This can be the email address directly, a hash of the email, or some item that links a collection of devices to a user.

This id is used for API requests like Report State and Request Sync. To report the state of a device, you need both the device ID and the user ID.

From the perspective of the home graph, this user ID can be any string. It doesn't really matter, as long as it's something that you can refer back to later.
