### ISSUE TITLE
[iObroker] Support needed for integration still no solution provided

### ISSUE THREAD

**Issue by DutchmanNL** [actions-on-google/smart-home-nodejs#222]
Since more than a year one of the biggest iOT systems is willing and trying to get an integration with the googleHome solution, unfortunaltly still no success and we have the feeling no priority or attention is provided to the subject.

iObroker has a growing community with > 25.000 active systems worldwide and its a shame that one of the biggest OpenSource iOT systems cannot be integrated to GoogleHome.

We need assistent in troublehoosting and follow-up steps, several high qualified engineers are waiting for response and ways to troubleshoot the issue with google.
We are already succesfull with integration to Alexa and other iOT system only google home is missing which is a shame for both sides (google and the iOb community)

Please help !

**Comment by GermanBluefox** [comment]
You can close this issue.

**Comment by Fleker** [comment]
Closing issue. If there are any further issues, please create a new issue.
