### ISSUE TITLE
Smart Home Fan type On/Off configuration

### ISSUE THREAD

**Issue by pver** [actions-on-google/smart-home-nodejs#223]
I'm trying to configure a Fan type device (action.devices.types.FAN) with traits: OnOff and FanSpeed. 
After responding to the SYNC intent, I can see the Fan device appear in the assistant app, but for some reason it can't be controlled (neither OnOff nor FanSpeed). 

I expected to see at least the On/Off button when clicking on the device (as for instance seen for Lights, Outlet and Switch device types having the OnOff trait). 
Instead it only shows the 'device settings' window.
Is this assumption correct, or can't the OnOff be controlled from the app for Fans?

Also note, the Fan icon shows a little gear icon in the top right corner, as if the device is not fully configured?
![smartfan](https://user-images.githubusercontent.com/1618378/48959074-5d3ed600-ef63-11e8-9d8d-36fedfa33e1d.png)

I get the same result with the example SYNC response from the docs: https://developers.google.com/actions/smarthome/guides/fan#sample_sync_request_and_response

I noticed the action.devices.types.FAN type is not (yet?) included in the list of device types in the assistant SDK: 
https://developers.google.com/assistant/sdk/reference/device-registration/model-and-instance-schemas
not sure if this could be related?

**Comment by pver** [comment]
Also worth mentioning: using voice control, the fan is switched on and off fine, so I think it's just the app that doesn't support showing the on/off yet for fan devices?

**Comment by pver** [comment]
Not sure if this is the right place for such assistant app related issues for smart home devices? 
Otherwise, feel free to point me to a more suited place/project for this :-)

**Comment by Fleker** [comment]
There should be a place in the app itself to send feedback. I'm not aware of any issue tracker for it.

This isn't an issue with the smart home API or your fulfillment. It's a limitation of the app.

**Comment by pver** [comment]
Ah indeed, didn't think of the feedback option as I thought it's not so developer oriented. But I'll give that a try, thanks @Fleker !
