### ISSUE TITLE
New Toggle: Garage (de)

### ISSUE THREAD

**Issue by egs2003** [actions-on-google/smart-home-nodejs#226]
I am requesting the following toggle be added for an one button garage door:

name: "garage"
name_synonym: ["öffne", "auf", "schließe", "ab", "stop", "fahre", "fahre auf", "fahre ab"]
lang: "de"

**Comment by Fleker** [comment]
You want something like

> "Hey Google, set the garage to true?"

Would [OnOff](https://developers.google.com/actions/smarthome/traits/onoff) make more sense in your case, or something like open/close (see #99)?

**Comment by egs2003** [comment]
No, I want something like "Hey Google, open the garage please?" Because I have just a one button garagdoor opener, I want a command for all states. Open, Close and so on. My logic behind will press the button every time I say 
"Hey Google, open the garage please"
"Hey Google, close the garage"
"Hey Google, drive the garage door"

My idea is using a switch combined a toggle. So everytime I set the toggle, my logic will push the garage door opener und reset the toggle after about 30 seconds.

**Comment by egs2003** [comment]
How can I use the new toogle? Where can I find all new available toggles? I checked the reference page (https://developers.google.com/actions/reference/smarthome/traits/toggles). But there is no garage toggle

**Comment by Fleker** [comment]
There is now an [OpenClose trait](https://developers.google.com/actions/smarthome/traits/openclose).
