### ISSUE TITLE
Temperature Sensor

### ISSUE THREAD

**Issue by egs2003** [actions-on-google/smart-home-nodejs#227]
I have a temperature sensor in my living room. I have the following code implemented.

id: device.id,
        type: "action.devices.types.THERMOSTAT",
        traits: [],
        name: {
          name: "Wohnzimmer"
        },
        attributes : {
            thermostatTemperatureUnit : "C",
            availableThermostatModes: "off"
        }

If I ask "Wie ist die Temperatur im Wohnzimer" I get the answer about the temperature and also the current State of the thermostat. I want get the current temperature without the information if the thermostat state is on or off.

Is there a solution?

**Comment by Fleker** [comment]
There's currently no trait to handle sensor-only data. There's a tracking issue in #135.
