### ISSUE TITLE
New Mode Request

### ISSUE THREAD

**Issue by jakewm** [actions-on-google/smart-home-nodejs#228]
In our conversation action a frequent command we see is the consumer asking to preheat the oven.  Most ovens default to 'Bake' cook mode and '350' degrees if you were to walk up and press start.  When we receive the 'preheat' mode in our CA we do the same thing and send 'bake', '350' to the oven.
For this reason I'm requesting that 'preheat' be added to the supported list of modes.

setting_name: preheat; setting_synonym: preheat.

I believe this is another mode that can be utilized by many smart appliance companies.

**Comment by Fleker** [comment]
The changes have been implemented and will be rolling out soon. You can view all [modes](https://developers.google.com/actions/reference/smarthome/traits/modes) and [toggles](https://developers.google.com/actions/reference/smarthome/traits/toggles) on our reference pages.
