### ISSUE TITLE
availableThermostatModes in Italian

### ISSUE THREAD

**Issue by matts4v** [actions-on-google/smart-home-nodejs#229]
Hello,
I've seen there are recently added new availableThermostatModes such fan-only, eco, dry ecc, but I'm not been able to call this modes in italian, but the standard modes like heat/cool are working fine. Are these new modes available in other languages? How can I invoke these modes?
Thank you

**Comment by Fleker** [comment]
We've added some additional translations for thermostat modes in Italian. They should be rolling out and be ready in the next few days.
