### ISSUE TITLE
Home app - Thermostats not working?

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#231]
Hi - 
is there an issue with thermostats in the Home app? 
When i open one, it reports the device ambient temperature, but the slider is disabled, and it says Other at the bottom.
It works fine in the Home Hub, and when I query it in Google Assistant, I get the response and the slider appears (and works).

**Comment by pver** [comment]
Slightly unrelated, but it would be great for smart home action developers to have an issue tracker for all home app related issues/feature requests. No internal strings you can pull for this by any chance? :-) 
I've already hit the feedback button in the app several times but it's hard (if not impossible) to follow up on what happens with them

(Thermostats are working fine for me by the way, it's one of the most complete device types available in the home app at the moment)

**Comment by madgeni** [comment]
Hi @pver - that's good to know - I wonder why they aren't working for my app :(

**Comment by pver** [comment]
What thermostat modes do you support for your thermostat device?
I'm using On, Off, Heat, Cool as supportedModes

**Comment by madgeni** [comment]
Fixed it! Thanks for the hint - actually it was the query causing the issue - if i passed 'on' it doesn't work, but if i pass back 'heat' it works

**Comment by pver** [comment]
👍 great to hear :)

**Comment by madgeni** [comment]
hey @pver - while I have you, do you use Scenes? Do they show in the Home app for you?

**Comment by pver** [comment]
I use Scenes indeed, but unfortunately does don't show up in the Home app (I definitely hope this will become available in future versions of the Home app).
But you can, however, control them using voice, so the app definitely knows about them.

They are also included in the device count when you go to the list of linked services. And you can see them when navigating to the Account window (from the most right icon at the bottom in the Home app menu), then selecting 'Settings' > 'Home control'. There you have a list of all devices and this list reveals the Scenes as well. You can't control them from there, but the user can rename the Scene if he/she wants to.

**Comment by Fleker** [comment]
I've brought up the request for a public tracker.

**Comment by pver** [comment]
That's great, thanks @Fleker !
