### ISSUE TITLE
In the Home Control add the test Actions, tips "Accounts now linked", but Google Assistant haven't added any devices yet

### ISSUE THREAD

**Issue by jiemao11** [actions-on-google/smart-home-nodejs#233]
Hello, I'm doing the smart home provider sample test. I meet this same problem that others had been put forward, but i cann't find out how to resolve. So i submit a new one. 
I have runned the server in local pc, and connect it with the brower, and add some lights.
Then i test in my assistant. I have found my project, logined in, input username & pwd. But it print "Account now linked",  when exist, assistant shows that "You haven't added any devices yet".

I want to add the action to home control.
Looking forward your help. Thank you.

**Comment by Fleker** [comment]
You see the message "You haven't added any devices yet" on your phone?

**Comment by jiemao11** [comment]
Yes, always.
