### ISSUE TITLE
Smart-bed Request

### ISSUE THREAD

**Issue by Exovite** [actions-on-google/smart-home-nodejs#234]
Hey,
we are working in a smart-bed project for the spanish market.

We would like to do a request for some actions for the bed like _lift the feet_, _lift the back_, _lift the bed_, _low the feet_, _low the back_, _low the bed_...

We need it to be in both, Spanish and English.

Thank you very much!

**Comment by Fleker** [comment]
As this is not directly related to the sample, this is being moved to the public issue tracker.
https://github.com/actions-on-google/smart-home-nodejs/issues/234
