### ISSUE TITLE
My own endpoint Port troubles.  3000 or 443 for https?

### ISSUE THREAD

**Issue by hleeowen** [actions-on-google/smart-home-nodejs#236]
I made this work using ngrok.  I now want to run my own endpoint.  I've given the command: 

node cloud/smart-home-provider-cloud.js smart-home="https://MY-DOMAIN-HERE.com"

The problem is that it tries to run it at port 3000.  Google wants https:// for the oauth and token URLs.  Https runs at 443.  
How do I get the ports to align so I can see this at https (443) rather than 3000?  I tried to change the 3000 value in the cloud/smart-home-provider-cloud.js file but that didn't work.
Where should this code sample live in relation to my html/www path on the server?
How do I get apache to see your code at 443 rather than my normal directory spot?

Forgive me if this is a dumb question.  I'm having trouble solving this.  Thank you for any info you can provide.

**Comment by Fleker** [comment]
You can always change the port in [config-provider.js](https://github.com/actions-on-google/smart-home-nodejs/blob/master/smart-home-provider/cloud/config-provider.js#L19).

**Comment by Fleker** [comment]
And it works fine if you do 3000, but you then aren't able to serve content?
