### ISSUE TITLE
Mode Trait: New setting name / synoyms [De/En]

### ISSUE THREAD

**Issue by VeegY** [actions-on-google/smart-home-nodejs#239]
Hey there,

We are currently working on a smart home integration for a smart fan. We would like to be able to support all modes the fan offers to its customers. 

Apart from the setting names we can already use we furthermore need:
* rush airing (De: "stoßlüften")
* aerate (De: "durchlüften")

If it is easier for you, it would be completely fine for me to just add those words (as "setting_synonyms") to an already existing "setting_name" shared by german and english (e.g. turbo/maximum)

In addition it would be awesome to either have a "sleep" copy in the german mode settings list or just have the synonym "schlafen" and "schlafmodus" in the german quiet mode setting.

If this request is not possible or if there are any questions, please let me know
Thanks in advance! :)

**Comment by Fleker** [comment]
These modes have been added: https://developers.google.com/actions/reference/smarthome/traits/modes
