### ISSUE TITLE
Actions on Console: Need an information..How to get the Account linking logs..

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#240]
Hi.
Is there any way to check the logs (normal case without error),  while i do the account linking?
I have checked in LogsViewer i could not get the response from oAuth. For my account linking i have used the amazon oAuth server . For my analysis, i need the logs received from oAuth. Is there any way?

**Comment by Fleker** [comment]
If you're using a service like Amazon's for OAuth, you would need to check with them for logging.

**Comment by sakthisg** [comment]
Hi Fleker, The basic reason for asking the same is, i need to get the agentuserid. Currently in a scenario, i have completed the OAuth - Account Linking using amazon. But during the SYNC response i could not find agentuserid, as smarthome receives only intent and other  parameter. Let me know if you have inputs...

**Comment by Fleker** [comment]
The `agentUserId` is a value that you provide, it's not given to you.

**Comment by sakthisg** [comment]
Yes, i have learned it. Using the OAuth - Access token, i need to get an AgentUserid (unique id) from OAuth Provider. I have found that from Amazon API gateway to my handler, the Authorisation headers are removed. I am checking with Amazon. Thanks a  lot for your response.
