### ISSUE TITLE
New 'effect' toggle

### ISSUE THREAD

**Issue by RouNNdeL** [actions-on-google/smart-home-nodejs#241]
I'd like to request a new toggle.
Name: effect
Synonyms: effect, effects, light effect, light effects, led effects

**Comment by Fleker** [comment]
This is now available. It can be viewed in the [documentation](https://developers.google.com/actions/reference/smarthome/traits/toggles).

**Comment by RouNNdeL** [comment]
Awesome, thank you

**Comment by RouNNdeL** [comment]
Hi, sorry for the inconvenience, but after testing I realized that the Google Home always responds with the toggle name, making it sound weird "Ok, turning on effect on the light". Could you rename it to 'effects'?
