### ISSUE TITLE
SYNC not working any more, strange Home App behaviour, account broken?

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#242]
Hi,
I had already everything working within my project and yesterday evening the SYNC didn't work any more. I just deleted cache from my Home App and installed it fresh, but now I get the message, that 'the screen can't be loaded and I should check my internet connection'.
![screenshot_20181223-201059](https://user-images.githubusercontent.com/16180589/50386856-db6fd300-06ef-11e9-9a71-d097164553e7.png)

Very strange, it seems that in my account something is broken which prevents me from using any further smart home action.

Can you please cleanup my account?

As I'm just developing the Action for FHEM (www.fhem.de) I would appreciate if you could support me quickly. Many thanks!

Regards,
Dominik

**Comment by dominikkarall** [comment]
![screenshot_20181223-150254](https://user-images.githubusercontent.com/16180589/50384366-3e4b7500-06c4-11e9-86a7-f779db370b99.png)

Clicking on Mein Zuhause doesn't work as well...

**Comment by dominikkarall** [comment]
I created another Google account to continue testing and it works, so please fix my account. There is definitely an issue somewhere which needs to be fixed to prevent end users damaging their account.

Unfortunatelly my second account is also broken now. I think it has something to do with Homegraph. I'm working since weeks on the project and since I tried the report state implementation the issues started.

**Comment by Fleker** [comment]
Can you elaborate on the issues you are seeing, such as providing system logs on the device? What happens if you try to connect one of your test accounts? Any system or server logs/errors?

**Comment by dominikkarall** [comment]
After a longer chat with Google support the issue was solved by removing the access from Google to 'Google Assistant Enabled Devices' on the following account site:
https://myaccount.google.com/permissions?utm_source=google-account&utm_medium=web

Nevertheless, such an issue should never occur for end users. Therefore I still think that there is a bug in one of the backend services.

I'm going to close this issue but would reopen it if it happens again.
