### ISSUE TITLE
request new mode

### ISSUE THREAD

**Issue by menson-yang** [actions-on-google/smart-home-nodejs#244]
Hi my dear Google friends, 

I am requesting that 'defrost'  and 'ferment' be added to the supported list of modes.

setting_name: Defrost; setting_synonym: defrost.
setting_name: Ferment; setting_synonym: ferment.

The hardware of our oven support this feature, also, it's the common function of the oven device type for different model and brand.

Thanks in advance !

**Comment by Fleker** [comment]
These mode settings are available.

**Comment by menson-yang** [comment]
Thanks Nick !
