### ISSUE TITLE
DeviceType: StandMixer ； Traits：TimeCook Request

### ISSUE THREAD

**Issue by menson-yang** [actions-on-google/smart-home-nodejs#245]
Hi my dear Google friends,

we are working in a smart cooking project and there are two types of devices, the first one is StandMixer, another one is Oven.

Firstly,  I am requesting the 'StandMixer'  be added to the supported list of device type. 
    Device TYPE: StandMixer ; Device TYPE SYNONYM: Mixer.
We would like to do a request for some actions for the mixer like:
    knead the flour, etc.
    whip/beat the egg white, etc.
    whip/beat the butter, etc.
    set standmixer on [speed 4] for [10 minute], etc.
    set standmixer on [LOW, MEDIUM, HIGH] for [10 minute], etc.

Secondly, I am requesting the TimeControl/TimeCook  be added to the supported list of device traits, so we can do a request for some actions like:
    set oven on [200 degree] for [30 minute], etc.
    set standmixer on [speed 4] for [10 minute], etc.
    set standmixer on [LOW, MEDIUM, HIGH] for [10 minute], etc.

Thanks in advance!

**Comment by Fleker** [comment]
This issue has been moved to the public bug tracker: https://issuetracker.google.com/issues/136103829
