### ISSUE TITLE
Report State DISCONNECT

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#246]
Hi,
I have a question regarding the handling of DISCONNECT for Report State. Usually several Google accounts can link to one 3rd party smart home account.
E.g.
 Google account 1 linked to smart home account A
 Google account 2 linked to smart home account A

If Google account 1 unlinks the smart home account, I would receive a DISCONNECT for smart home account A and stop sending Report State. How do I get the information, that there is still one Google account (Google account 2 in the example above) connected and therefore I should continue sending Report State? Is there a way to get IDs of the Google accounts which are linked to my account?

**Comment by Fleker** [comment]
You get access tokens which identify the specific accounts.

**Comment by dominikkarall** [comment]
The access tokens I get are only for the accounts in my smart home environment, but where do I get the Google ones?

**Comment by pver** [comment]
I think @dominikkarall has a point, I didn't think of that either until now. 
Maybe it's more clear with example account names: suppose Bob and Alice are living together and have Philips Hue lights. They have one account they used when registering their Philips Hue installation: bob_and_alice@someprovider.com 

They now both want to control it from there phones so they both link there google accounts to the single bob_and_alice@someprovider.com account:
- bob@gmail.com =>  bob_and_alice@someprovider.com
- alice@gmail.com => bob_and_alice@someprovider.com

They will both share the same agentuserid and the access tokens will both point to the single bob_and_alice@someprovider.com account on the Philips Hue action side.

When Bob now unlinks from the Philips Hue action, a DISCONNECT will be send with the token refering to bob_and_alice@someprovider.com, but somehow the action needs to know there is still another account that is linked to it (alice@gmail.com) and still requires state updates through the Report State mechanism.

At the moment it's not possible to know this (unless keeping a counter that increases on every SYNC for the same Philips Hue account and decreases on every DISCONNECT, and stop Report State when the counter is at 0)

**Comment by dominikkarall** [comment]
Thanks for the detailed explanation @pver, that"s exactly the issue I was thinking of. SYNC counter doesn't work either as a work around, as re-SYNCs can happen several times.

I was thinking about handling error 404 and stop reporting on that error, but that"s not the best solution. Maybe Google can provide us a separate error code which states that no more report state is needed for that agentUserId.

**Comment by Fleker** [comment]
A 404 will happen if the agent user id is not found in the home graph.

If two Google accounts sync to one account on your service, you should generate two separate refresh tokens and access tokens.

When you disconnect with one access token, you remove that refresh token and still have one left, so there's still one linked account.

**Comment by Fleker** [comment]
You are able to use [Stackdriver to retrieve errors](https://developers.google.com/actions/smarthome/logging) and can [pass errors back to your server](https://medium.com/google-developers/how-to-connect-stackdriver-to-your-smart-home-server-for-error-logging-8a7a477241c2).

**Comment by dominikkarall** [comment]
Sorry, but using the error log to handle failed SYNCs sounds really strange. I can understand that I should use the error log to analyse errors, but I don't think that the error log should be used as an API.

Actually it would make more sense if Google could send ERROR and ACK POST messages with request ID and error description to the fulfillment URL.
