### ISSUE TITLE
missing required parameters

### ISSUE THREAD

**Issue by awais786327** [actions-on-google/smart-home-nodejs#248]
What am i doing wrong in this ? this occurs when trying to link account in google assistant, also having  message **Could not update the setting, check your connection** 

![image](https://user-images.githubusercontent.com/12613564/50482473-8d691100-0a08-11e9-9743-07792ab740ea.png)

This is my action console project and i have used these credential in project

![image](https://user-images.githubusercontent.com/12613564/50482635-6b23c300-0a09-11e9-9a33-8ae112232973.png)

![image](https://user-images.githubusercontent.com/12613564/50482570-1122fd80-0a09-11e9-93c3-2352523639a3.png)

searched already related issues regarding this but still not find appropriate answer what i need to do !
thanks in advance

**Comment by Fleker** [comment]
How are you using the "Web client"?

**Comment by Fleker** [comment]
The tokens you create won't affect the auth. It's either an auth issue or a sync issue.

**Comment by awais786327** [comment]
@Fleker these are my project configurations, i was so tired to change **token, auth, and fulfillment URL** each time So, Instead of **ngrok** i decided to deployed my app to **heroku** and it is working there as expected, you can check online
[https://smart-home-automation.herokuapp.com](https://smart-home-automation.herokuapp.com)

![untitled](https://user-images.githubusercontent.com/12613564/50556793-7a538b00-0cff-11e9-98a3-d245296a63fe.png)

These are the Action Console setting,

![untitled](https://user-images.githubusercontent.com/12613564/50557294-c275ac00-0d05-11e9-8d4c-89cced764503.png)

The problem is only when i tap test app account linking don't know whats wrong with this

![image](https://user-images.githubusercontent.com/12613564/50557386-8c84f780-0d06-11e9-8899-f6a2f9f5a643.png)

2018-12-31T09:23:31.872120+00:00 app[web.1]: /token query {}
2018-12-31T09:23:31.872518+00:00 app[web.1]: /token body { grant_type: 'authorization_code',
2018-12-31T09:23:31.872521+00:00 app[web.1]:   code: 'kcy9n50kbwg00000000000000',
2018-12-31T09:23:31.872522+00:00 app[web.1]:   redirect_uri:
2018-12-31T09:23:31.872524+00:00 app[web.1]:    'https://oauth-redirect.googleusercontent.com/r/smarthomeautomation' }
2018-12-31T09:23:31.872636+00:00 app[web.1]: **missing required parameter**
2018-12-31T09:23:31.875626+00:00 app[web.1]: [0mPOST /token [33m400 [0m4.206 ms - 26[0m

This is the complete **log file**,
[smart-home-automation-logs-1546248217870.txt](https://github.com/actions-on-google/smart-home-nodejs/files/2718112/smart-home-automation-logs-1546248217870.txt)

i am stuck at this point about 1 week, i can share project with you..

**Comment by awais786327** [comment]
@Fleker no error there! now what should i do ?
`[
  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": "awais3227443@gmail.com"
      },
      "serviceName": "appengine.googleapis.com",
      "methodName": "google.appengine.v1.Applications.CreateApplication",
      "resourceName": "apps/smarthomeautomation",
      "resourceLocation": {
        "currentLocations": [
          "us-central1"
        ]
      }
    },
    "insertId": "-v2bjppdb0hg",
    "resource": {
      "type": "gae_app",
      "labels": {
        "version_id": "",
        "module_id": "",
        "project_id": "smarthomeautomation"
      }
    },
    "timestamp": "2018-12-26T19:12:06.327Z",
    "severity": "NOTICE",
    "logName": "projects/smarthomeautomation/logs/cloudaudit.googleapis.com%2Factivity",
    "operation": {
      "id": "42e05485-3c9c-469f-9d80-60b745c8caaa",
      "producer": "appengine.googleapis.com/admin",
      "last": true
    },
    "receiveTimestamp": "2018-12-26T19:12:07.289977900Z"
  },
  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "status": {},
      "authenticationInfo": {
        "principalEmail": "awais3227443@gmail.com"
      },
      "requestMetadata": {},
      "serviceName": "appengine.googleapis.com",
      "methodName": "google.appengine.v1.Applications.CreateApplication",
      "authorizationInfo": [
        {
          "resource": "apps/smarthomeautomation",
          "permission": "appengine.applications.create",
          "granted": true
        }
      ],
      "resourceName": "apps/smarthomeautomation",
      "resourceLocation": {
        "currentLocations": [
          "us-central"
        ]
      }
    },
    "insertId": "-jetkuydap3o",
    "resource": {
      "type": "gae_app",
      "labels": {
        "module_id": "",
        "project_id": "smarthomeautomation",
        "version_id": ""
      }
    },
    "timestamp": "2018-12-26T19:11:53.013Z",
    "severity": "NOTICE",
    "logName": "projects/smarthomeautomation/logs/cloudaudit.googleapis.com%2Factivity",
    "operation": {
      "id": "42e05485-3c9c-469f-9d80-60b745c8caaa",
      "producer": "appengine.googleapis.com/admin",
      "first": true
    },
    "receiveTimestamp": "2018-12-26T19:11:53.757197541Z"
  }
]`

**Comment by Fleker** [comment]
I guess I'd need to run through setup again to see if I can reproduce the error. In the meantime, you may want to check with the codelab github.com/Google codelabs/smarthome-washer which should also work and has similar authorization

**Comment by awais786327** [comment]
i already tried smart washer is working sounds weird i know, but this smart home example is not, don't know why it continuously throwing the same error when i am doing everything step by step 👎

**Comment by awais786327** [comment]
i already tried smart washer is working sounds weird i know, but this smart home example is not, don't know why it continuously throwing the same error when i am doing everything step by step 👎 
**Could not update the setting, check your connection**
