### ISSUE TITLE
Report State and changing light colors

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#250]
Hi,
is there a definition how to handle lights which change their light color very quickly?

For example, there might be a Hue light which uses a 'party' scene. It changes the color, brightness, etc. all the time, even within a second. How should such lights be handled with report state? I don't think that it makes sense to report about 10 states within a second.

Thanks!

**Comment by dominikkarall** [comment]
Any updates on this? Same applies to measured temperature for thermostats. How often should it be updated? In some cases it might happen that the temperature jumps between 21.24 and 21.25 degrees and I have to report it every minute about 20 times. Humidity is the same.

**Comment by Fleker** [comment]
The goal of proactively reporting the state is to show the user useful information on their phone or smart display. If a color is changing frequently, then they shouldn't expect to see the same color right immediately. If they're looking at the temperature, the accuracy of the thermostat display is to the whole degree.

Report state should be used during meaningful changes in the device state, such if it settles on one color or changes by a whole number degree.
