### ISSUE TITLE
Timing issues?

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#252]
I'm implementing my smart home action with Google Cloud Functions and at the beginning I had very bad response times (6-12s) on first SYNC. Could it be, that bad response times on SYNC make the Google account, which tries to link the action, react strange on further linking requests?

Sometimes the SYNC was hanging and after a few refreshes on the Home app account linking page it showed up as connected. I have the feeling, that trying to connect/link the account several times even if one of the connect requests is in process the account gets 'damaged'. Furthermore I never get the roomHint working with that account on future SYNC requests, even if the action was unlinked before.

If I create a completely new Google account and try to link my action with that one everything works perfect as long as the timings are good. I have already 2 Google accounts which don't let me link any action (even Philips Hue) anymore.

**Comment by Fleker** [comment]
There is a timeout for SYNC responses, but if there is a timeout, it should not 'damage' your account or affect the action in any way.
