### ISSUE TITLE
About Display name reserved

### ISSUE THREAD

**Issue by Fun-Huan** [actions-on-google/smart-home-nodejs#254]
OK, i Got a display name "**A**" in a Assistant Action , and i want to use it in another Assistant Action which in **different** Google account. 
    So I delete the Action in **first account**, and add the same display name in another account. But it **warning** that "Could not reserve your pronunciation 'A' because: Your pronunciation is already reserved by another Assistant Action". 
   Is that mean I can't use this display name any more?
   I still want to use this display name. thank you.

**Comment by Fun-Huan** [comment]
Can anyone help me?thank you very much

**Comment by Fun-Huan** [comment]
> I'm surprised that you were able to get "A" as a name, as the console is only supposed to allow names with two or more words.

I am sorry to let you misunderstand it. "A" is NOT the real name, The real name is belong my company.So i can't make it public.

**Comment by Fun-Huan** [comment]
> Thanks for clarifying. There is a [7-day grace period for deleted projects](https://stackoverflow.com/questions/24801168/how-to-delete-project-from-google-developers-console), so it won't immediately be available. Alternatively, if you do rename the display name in the original project, it should no longer be reserved.

Thank you very much.This helps me a lot.

**Comment by chethansai** [comment]
> > Thanks for clarifying. There is a [7-day grace period for deleted projects](https://stackoverflow.com/questions/24801168/how-to-delete-project-from-google-developers-console), so it won't immediately be available. Alternatively, if you do rename the display name in the original project, it should no longer be reserved.
> 
> Thank you very much.This helps me a lot.



> Thanks for clarifying. There is a [7-day grace period for deleted projects](https://stackoverflow.com/questions/24801168/how-to-delete-project-from-google-developers-console), so it won't immediately be available. Alternatively, if you do rename the display name in the original project, it should no longer be reserved.

https://cloud.google.com/resource-manager/docs/creating-managing-projects?visit_id=637198127026538708-2384402513&rd=1#restoring_a_project

this sholud help you in restoring your project for name change

**Comment by pbartos** [comment]
What if I already deploy it to the alpha? Change the display name and redeploy did not help. The display name is still reserved.

**Comment by pbartos** [comment]
Solved with support contacted via https://support.google.com/actions-console/contact/support
