### ISSUE TITLE
SYNC data validator contradicts documentation

### ISSUE THREAD

**Issue by peterkappelt** [actions-on-google/smart-home-nodejs#255]
Don't know wether this is the right place for this question.

I'm using your sync data validator (https://developers.google.com/actions/smarthome/tools/validator/) to check messages. However, it reports errors on data that should be OK according to the documentation:

* It reports
  - `data.payload.devices[1].attributes.availableThermostatModes - auto is not a valid value`
  - `data.payload.devices[1].attributes.availableThermostatModes - purifier is not a valid value`
  - `data.payload.devices[1].attributes.availableThermostatModes - eco is not a valid value`
  for the SYNC line `"availableThermostatModes":"off,heat,on,auto,purifier,eco"`. Documentation says, these mode should be supported: https://developers.google.com/actions/smarthome/traits/temperaturesetting
* It reports `data.payload.devices[0].attributes.availableFanSpeeds.speeds[0].speed_values[0].lang: da is not a valid value` for the fan speed trait, where I added danish as a supported language. However, Danish is listed as supported: https://developers.google.com/actions/smarthome/traits/#supported-languages

What should I trust here? I suppose the documentation is up to date, while the sync validator is a bit after?

**Comment by Fleker** [comment]
The documentation is going to be more reliable. These seem to be omissions in the validator, which I'll be sure to fix. We try to make sure all of our SYNC responses in the docs will work, but the doc responses are not always comprehensive.

**Comment by Fleker** [comment]
Both issues have been fixed.
