### ISSUE TITLE
Smart home Mode Traits - information needed

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#259]
Hi,
I have set of modes for my display device. I have used the "action.devices.traits.Modes" for my display device. I have added the available modes with name and setting_name as per the Documentation.  SYNC response has been sent with the mode traits and attributes. But when i invoke the set mode to setting_name, is it not recognised. Is there any sample phrases for making this trait work?

**Comment by Fleker** [comment]
From the [codelab](https://codelabs.developers.google.com/codelabs/smarthome-washer/#6)

> "Set the washer to a large load"

_Set the <device> to <setting> <mode>_

There are also similar variants of the phrase that should work.

**Comment by Fleker** [comment]
Modes are supported for all device types, but only specific modes [listed in the documentation](https://developers.google.com/actions/reference/smarthome/traits/modes) will work.

**Comment by Fleker** [comment]
No. Assistant SDK is a separate process from smart home. Assistant SDK has more flexibility, but requires the device itself to have microphones.

If you are looking for specific modes and toggles, you can request them here in a new issue and it'll be handled in a few days. If you are looking for new traits and grammars, you can also request them here but these will take a longer time.

**Comment by sakthisg** [comment]
OK..thanks Fleker!
