### ISSUE TITLE
ColorSetting - in app changes?

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#263]
Hi - 
had some feedback from users that the Home app should be allowing color change for lights - is this right? Am i doing something wrong? 
My lights are reporting:
 "traits": [
                "action.devices.traits.OnOff",
                "action.devices.traits.Brightness",
                "action.devices.traits.ColorSetting"
            ]

**Comment by Fleker** [comment]
I don't know if the Home app supports a GUI for color changes. The Home Hub (smart display) might. I personally haven't seen such a feature in the app.

**Comment by madgeni** [comment]
Same - it works in the Home hub for sure.

**Comment by madgeni** [comment]
Just coming back to this - if I enable Hue in the home app, I get access to 'colour' options on my lights. How do i add this for my own app?

**Comment by Fleker** [comment]
It should be enabled automatically if your device supports the ColorSetting trait, following the guidelines in the [documentation](https://developers.google.com/actions/smarthome/create#touch-controls) (which will need to be updated with this additional trait).

**Comment by madgeni** [comment]
Thanks @Fleker - So it's reporting colorsetting as a trait in the discovery (as above) - and when I open the device in the app, the query returns:

{
   "521": {
      "spectrumRGB": 7720446,
      "brightness": 100,
      "on": true,
      "online": true
   }
}

What am i missing?

**Comment by Fleker** [comment]
Devices with the ColorSetting trait should show up as a touch control for Light types. This will be implemented in the docs soon.

**Comment by dominikkarall** [comment]
I can confirm that just the use of ColorSetting isn't enabling the feature in the home app. Native Hue works, but my own app doesn't. Controlling via voice works and therefore I assume that the trait is properly implemented.

**Comment by madgeni** [comment]
I wonder if it's tied to the inability to query color state? Home just starts an internet search

**Comment by Fleker** [comment]
Okay I'm seeing with a test project that it may not rolled out to every project right now.

**Comment by madgeni** [comment]
That's disappointing - especially for those of us with customers who are aware of it as an option. Any chance of an ETA?

**Comment by Fleker** [comment]
We're looking into the behavior.

**Comment by mirkokurt** [comment]
Hi, I'm experiencing the same issue, are there any updates on this topic?

**Comment by Fleker** [comment]
ColorSetting should now exist as a picker for all Actions.

**Comment by dominikkarall** [comment]
Unfortunately it still doesn't work for my action "FHEM Connect". I just resynced.
