### ISSUE TITLE
too many error in error log

### ISSUE THREAD

**Issue by abhitheawesomecoder** [actions-on-google/smart-home-nodejs#264]
![error-google-action](https://user-images.githubusercontent.com/3944526/51101343-4a78ad00-1800-11e9-9ba4-31fd0b8231b9.png)
I am getting too many error like below. I suspect these are hacking attempts. because when I am normally testing my google action its working fine. You can see there are 2 to 3 attempts in 1 minute. How to deal with this?

E  SYNC: Request ID 1261818286606417973 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 14215194235674494510 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 12101627294419496282 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 17326090188924339690 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 7128223364940431880 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 2441732611283690783 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 15540960382592936486 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 8488448783153378233 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 13641388532760866750 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 730002831356036412 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 15807088624844975658 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 937447837347773791 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 6178994816762376493 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 10748910853597903091 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 1585573250441264721 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 5809097433644544606 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 13890046057724044332 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 8897388149488071862 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 1440401273016843364 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 16793552590111395692 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 2832167909599048316 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 14060063900940228217 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 10636092416581229044 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 9241972336735715037 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 12705368288347476638 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 846970492760639909 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 16753203560015270082 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 5266140754186631717 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 10602058268258454523 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 6922599987660531587 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 7339667930167915686 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 11033442845712225296 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 4562209006544432810 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 11635421288507264432 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 17720760607021496808 failed with code: BACKEND_FAILURE 
E  SYNC: Request ID 14328870472505335243 failed with code: BACKEND_FAILURE 
 SYNC: Request ID 2799967384180649588 failed with code: BACKEND_FAILURE E 
 SYNC: Request ID 6602524478766030858 failed with code: BACKEND_FAILURE E 
 SYNC: Request ID 6831553142596407202 failed with code: BACKEND_FAILURE E

**Comment by Fleker** [comment]
These may be user authentication or syncing errors. It's unlikely that it was a brute force attack, as it is generating request IDs. The default logging may not be sufficient to identify who and why errors are happening.
