### ISSUE TITLE
sync duplicates with deleted devices

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#265]
I have several users who are removing devices from their system, but Google is retaining them no matter what. Is there any method for clearing out the Homegraph?

**Comment by Fleker** [comment]
We'll investigate this.

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
