### ISSUE TITLE
multiple devices of same type at different room - Info needed.

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#267]
Hi
in a Home, i am having a device and it is at Living Room. This is send as a part of SYNC request. this has got linked with my account. it is working as expected.  Later i have bought same device type..i would like add to  Kitchen. How to link this new device with my account and how to control the new device? What is the protocol to be followed to link the account with multiple devices of same device type.? Thanks in advance for the clarification!

**Comment by Fleker** [comment]
To link a particular device to that company's account, you would need to follow the device instructions for setup.

After you link a new device, that company should send a [request sync](https://developers.google.com/actions/smarthome/request-sync) which will cause a new SYNC request to be sent with new devices. Alternatively, you could say "Hey Google, sync my devices", which will also 
create a new SYNC request.

Devices are identified with a unique id, not by device type, so you could have multiple instances of the same device in your home.
