### ISSUE TITLE
Request for smart light product 

### ISSUE THREAD

**Issue by benobell** [actions-on-google/smart-home-nodejs#268]
Hi, we are in need of custom trait states for a string light product. 
Currently we can only use On/Off and Brightness settings. 
We don't use the RGB/HSV for colors as that is defined by the firmware. 
here is a list of commands we would like to have multiple states use: 

**Effects State:**
- Starry Night
- Glimmer
- Sparkle
- Steady
- Chasing

**Color/Theme State:**
- Pure White
- Warm White
- Polar White
- Soft White
- Antique White
- Incandescent White
- Gold
- Red
- Orange
- Golden Yellow
- Acid Yellow
- Chartreuse
- Green
- Mint
- Turquoise
- Blue
- Royal Blue
- Lavender
- Pink
- Fuschia
- Purple
- Multicolor
- Red & White
- Red & Green
- White & Blue
- Red & Blue
- Pink & Purple
- Pink & Green
- Red & Turquoise
- Red, Turquoise, and Chartreuse
- Red, White,  and Chartreuse
- Red, Blue,  Green, Yellow
- Christmas  (TBD)
- Valentine
- St. Patrick's
- Mardi Gras
- Easter
- Independence   Day
- Halloween
- Thanksgiving
- Multichange
- Christmas Lightshow
- Rainbow Wave
- Frozen Fire
- Color Frenzy

**Beat Detection State:**
- Beat Detection Off
- Standard Beat Detection
- Dance Party Beat Detection

Best Regards
Beno

Beno Bell
Senior Software Engineer
Creativity, Inc.

**Comment by Fleker** [comment]
Thanks for reaching out.

Effects and Beat Detection could be added as modes. Colors will be sent as [RGB and name](https://developers.google.com/actions/smarthome/traits/colorsetting#sample-execute-request-and-response), and the list of colors is pretty extensive. If you really want additional colors, those could be added and paired with hex values. Some of the colors that are a pattern would need to either be a mode or a new trait.

If these work, I'll create internal feature requests for these.

**Comment by benobell** [comment]
Hi Nick,
thanks for the reply.

regarding single color commands  Do you need to know an RGB value for any colors above that are not on your list? I expect our firmware developer to have their internal RGB settings and they just need to know the name but other appliances need the RGB correct?

Can you please tell me if using mixed color commands such as "red, white and blue" will cause any issues to other appliances? or should these be modes that are specific to the smartlights h/w only?
IE 
"turn lights red, white and blue"
vs. 
"turn smartlights red, white and blue"

Do you know roughly how long these requests take to implement and when custom mode names will be available? 

thanks in advance.
regards
Beno

Beno Bell
Senior Software Engineer
Creativity, Inc.

**Comment by Fleker** [comment]
Mixed color commands shouldn't cause issues, although I'll ask for the best way to implement the feature.

**Comment by Fleker** [comment]
Color patterns will be done as a mode, which will allow you to specify different colors and patterns as strings, and you won't need the direct hex values. The requests will likely be handled in the next week.

**Comment by benobell** [comment]
Hi Nick,
thanks so much for your feedback. I believe we have a better understanding now.
Is there a link to a complete list of colors/rgb values available?

Please confirm the following is valid:
We should use google's list of built in color names/rgb and our smartlights firmware will use those RGB values so that we will always match google's colors for all other devices. IE Google turn my lights "pumpkin" will turn all the lights in house/room pumpkin including our smartlights.

When we specifically target our smart lights within the utterance "Google set noma lights blah" we can do the same individual colors list as we do globally but we also will have 3 individual custom modes (effects, themes and lightshow) that can also be triggered.

IE
"Google turn noma lights pumpkin" (color trait)
"Google set noma lights effect to chasing" (effect mode trait)
"Google Set noma lights to valentine" (theme mode trait)
"Google Set noma lights to rainbow wave lightshow" (lightshow mode trait)
"Google set noma lights to red and white" (theme mode trait)
"Google set noma lights to white and red" (same as above but variation in order of colors)
"Google set noma lights to white and red" (same as above but variation in order of colors)

Please also tell me if we can give you synonyms for the below items (updated request list) - thanks in advance.
best regards 
beno

**Effects Mode:**

- Starry Night
- Glimmer
- Sparkle
- Steady
- Chasing

**Themes Mode**

- Multicolor
- Red & White (+ White and Red)
- Red & Green (+ Green and  Red)
- White & Blue (+ Blue and White)
- Red & Blue (+Blue and Red)
- Pink & Purple (+ Purple and Pink)
- Pink & Green (+Green and Pink)
- Red & Turquoise (Turquoise and Red)
- Red, Turquoise, and Chartreuse (+ reordered variations as above)
- Red, White, and Chartreuse (+ reordered variations)
- Red, Blue, Green, Yellow (+ reordered variations)
- Christmas (TBD)
- Valentine
- St. Patrick's
- Mardi Gras
- Easter
- Independence Day
- Halloween
- Thanksgiving

**LightShow mode**

- Multichange
- Christmas
- Rainbow Wave
- Frozen Fire
- Color Frenzy

**Comment by Fleker** [comment]
No more information from you is needed. Thanks.

**Comment by benobell** [comment]
Hi Nick,
I'm just checking in on progress of custom mode request.
Have you received any ETA?

best regards
beno

**Comment by Fleker** [comment]
Most of the modes should be available, minus the color collections. We'll continue work on these.

**Comment by Fleker** [comment]
We've added the color modes. The settings should be available to use in a couple of days. You can look at all available modes in the reference docs: https://developers.google.com/actions/reference/smarthome/traits/modes
