### ISSUE TITLE
Request for new types: PC, Intercom

### ISSUE THREAD

**Issue by ClusterM** [actions-on-google/smart-home-nodejs#271]
Hi.
Can I request for new device types?
I'm using Assistant to turn on/off my PC. So it will be good to see something like "**action.devices.types.PC**" or "**action.devices.types.COMPUTER**".

Also I have intercom, it has auto-answering system. What about "**action.devices.types.INTERCOM**"?

Also will be nice to see some device type to control Christmas tree or/and some Christmas leds/decorations :)

**Comment by Fleker** [comment]
Thanks for the suggestion. In the meantime, you can use the OnOff trait along with any other device type.

**Comment by ClusterM** [comment]
Yes, i'm using it now.
