### ISSUE TITLE
Different command results for same device

### ISSUE THREAD

**Issue by pver** [actions-on-google/smart-home-nodejs#272]
Hi,

An EXECUTE intent can have multiple commands for the same device. 
Suppose there are 2 commands and the first one succeeds, but the second one fails. How can this be reported in the response to the execute intent?

We could use 2 groups in the 'commands' Array in the response: one for the ERROR of the second command and one for SUCCESS for the first command, both with the same device id)
Is this a correct approach? 
I think those groups can't be correlated by Google to the corresponding commands, because there's no reference to the specific commands in the response. Or do you correlate which command succeeded by checking the per-trait states?

**Comment by Fleker** [comment]
There's no good way to handle such a case, as execution responses are only specific to a device-level, not command-level.

**Comment by pver** [comment]
Thanks for the info Nick! Do you have any insights in how other actions handle this? Do they revert the partial commands that were successful? Or do they just report the entire list of commands as failed and leave the device state as-is?

**Comment by Fleker** [comment]
Is this question hypothetical or are you running into such a case?

**Comment by pver** [comment]
More of an implementation detail actually: since multiple commands can arrive for one device, we also need to make multiple calls to that device. So one could succeed, but another one can fail.
But I think for now we can just return an error in that case and leave the successful state as is, since the HomeGraph will be correct (using the Report State updates)
