### ISSUE TITLE
Google Home Reportstate starter doubt

### ISSUE THREAD

**Issue by justusaypejose** [actions-on-google/smart-home-nodejs#273]
Hi all, 
I'm trying to implement Reportstate. I have a few basic doubts.
1. Is Reportstate invoked immediately after the Google Home app execute intent is completed?
2. So Home graph will be updated only after any Google Home action, for example switch off from Google Home app will invoke the Reportstate.
3. Is Reportstate invoked only from Google Home action, or do we proactively update the home graph from our own custom server?
4. If above case is true, then in request JSOn, what do we provide as requestId?

Please assist.
Thank you.

**Comment by justusaypejose** [comment]
Thank you for the response. Let me try working on it.

**Comment by ldgmaia** [comment]
Do you have an example showing how the Home app would flow? For example, how and when to call reportState, requestSync? As far as I understand, this sample here does not use reportState and requestSync using the app.requestSync and app.reportState, but rather a version made by it directly calling the URL of HomeGraph. I would like to have a simpler version showing only the basics for controlling a device.

**Comment by Fleker** [comment]
We are working on a refreshed sample with better usage of the library. In the short-term, you should be able to look at the [codelab](https://github.com/googlecodelabs/smarthome-washer), which uses the AoG library and shows when these calls should be made (on changing devices/changing state).

**Comment by ldgmaia** [comment]
> We are working on a refreshed sample with better usage of the library. In the short-term, you should be able to look at the [codelab](https://github.com/googlecodelabs/smarthome-washer), which uses the AoG library and shows when these calls should be made (on changing devices/changing state).

I was going through this example in this exactly moment, but still, I think is a little out of date because it is still using "app.onSync((body) =>" instead of "app.onSync((body, headers) =>".

Sorry to bother you so much, but I really need this working ASAP.

**Comment by Fleker** [comment]
The codelab is not outdated. The second parameter is just not needed.

You should _request sync_ when you need to request a sync, such as changing the devices that a user has, or if you change the device attributes.

You should _report state_ when the device's state changes, such as flipping a switch manually to turn on a light, or just after an EXECUTE.
