### ISSUE TITLE
Can we add smart speaker as a device to be controlled?

### ISSUE THREAD

**Issue by silent-lad** [actions-on-google/smart-home-nodejs#274]
Scenario :-
I have many smart speakers in my hotel and want to get their state by QUERY using smart home .can they be connected to this as i cannot see them in device type ,if not can any of you suggest an alternative?

**Comment by silent-lad** [comment]
@Fleker i want to know which smart speaker is up (or connected to internet)

**Comment by Fleker** [comment]
Connected smart speakers should be available in your account's list of devices. You should be able to click on each device and it should tell you if it's available or disconnected.

**Comment by silent-lad** [comment]
Thanks ,it resolved my issue .Sorry for the naive question was kinda too much into actions-on-google library i totally forgot there are some out of the box features too .

**Comment by silent-lad** [comment]
@Fleker It only works if the app and google home are on the same wifi ..is it possible to get that info remotely?

**Comment by Fleker** [comment]
I don't believe it is possible.
