### ISSUE TITLE
Two-factor authentication devices not working from Google Home app

### ISSUE THREAD

**Issue by andrei-tatar** [actions-on-google/smart-home-nodejs#275]
Hi,

I've been playing around with the 2FA challenges for the smart-home devices (https://developers.google.com/actions/smarthome/two-factor-authentication).  
Tried both pin and ack and they work fine with the Google Assistant via voice (either phone or Google Home device). 

The problem is that if I want to change the state of the device via Google Home app on my phone (clicking off/on), it does nothing. There seems to be no documentation about how it should behave, but I imagined a popup dialog or something would ask for confirmation or security code.

Is this a bug?

Andrei T.

**Comment by Fleker** [comment]
I'll file an issue internally.

**Comment by Fleker** [comment]
2FA challenges are current not supported with touch, so touch controls will not work on 2FA-enabled traits.

**Comment by DewGew** [comment]
Does Two-factor authentication support other langauge? 
It work on english correct. I tryed in swedish it works 1 time of 100 tryes.

**Comment by Fleker** [comment]
Moving this issue to the public bug tracker: https://issuetracker.google.com/issues/136103093
