### ISSUE TITLE
400 error comes through in reportState res

### ISSUE THREAD

**Issue by FranceJ** [actions-on-google/smart-home-nodejs#276]
If an otherwise fine data push to a sensorState via the smarthome reportState has a missing parameter, like agentUserId, then promise from reportState will still resolve and the resolved variable will contain a descriptive 400 error.

This is contra to the docs which claim that getting into the res statement of the promise is equivalent to a successful push.

**Comment by Fleker** [comment]
Can you provide a code snippet of what you're doing specifically? A 400 error shouldn't resolve the promise, so I wonder where the check is being ignored.

**Comment by Fleker** [comment]
So the HTTP request itself returns a 200, but the response of the request has a different error code?

**Comment by andrei-tatar** [comment]
This happened on my service as well. 400 http status code with the same exact response. I think the linking somehow expires after some time. Or you clicked "test" again. Unlinking and linking again seems to solve the issue (at least for me).

**Comment by FranceJ** [comment]
The HTTP request is handled entirely by the reportState method of the smarthome package. It doesn't really expose the response code directly aside from via the response and error objects as far as I can see. 

I'm skeptical that I'm getting a 200 response code at all in this situation; reading into the smarthome.ts apiCall function it looks like unless there is an error on `req` it is just resolving on end and passing the buffer info through. So, perhaps a 400 can come in in this situation and trigger the resolve path of the Promise as I've seen happen in my app.

Also, this kind of error does not show up in the Google Cloud Platform stackdriver logs for the Google Assistant Action logs. 

Responding to what @andrei-tatar said above, this was triggered by me accidentally passing an unknown for agentUserId and was easily fixed. It's more that an error was coming through the response path of a promise that is the issue.

**Comment by Fleker** [comment]
Okay I'm able to reproduce. I'll make a patch to the Node.js library.

**Comment by Fleker** [comment]
This is fixed [in the library](https://github.com/actions-on-google/actions-on-google-nodejs/commit/47b806b6a7740d5339209a27fe69024d106baa8c) in version 2.6.0.
