### ISSUE TITLE
Check the HomeGraph status

### ISSUE THREAD

**Issue by Watermanman** [actions-on-google/smart-home-nodejs#277]
How do i check HomeGraph content? is it will show some devices list after call report state api successful?
I currently only report state and got response`{  "requestId": "6862331498743849049" }` after EXECUTE intent request, but report state dashboard was not show anything. 
![image](https://upload.cc/i1/2019/01/21/4GZyrQ.png)
this is my report data
`{   
    "requestId" : "6862331498743849049",
    "agentUserId": "test-user123",
    "payload": { 
        "devices": { 
            "states": {
                "100041":{
                    "on" : true
                }
            }
        } 
    } 
}`

**Comment by Fleker** [comment]
Yes if you set up the sample correctly it should return a list of devices and their current states as in the home graph.

**Comment by Watermanman** [comment]
This is my response of SYNC intent
`{"requestId":"6862331498743849049","payload":{"agentUserId":"test-user123","devices":[{"id":"100041","type":"action.devices.types.OUTLET","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":[],"name":"light","nicknames":[]},"willReportState":false,"customData":{"id":8,"idname":"nodeid"}}]}}`

this is my report data
`{ "requestId" : "6862331498743849049", "agentUserId": "test-user123", "payload": { "devices": { "states": { "100041":{ "on" : true } } } } }`

finally i got response from report state
`{ "requestId": "6862331498743849049" }`

Is it looks correctly?

I tried report other agentUserId or devicesID, but it always got 404 not found.
I think the HomeGraph already has my device?

**Comment by Fleker** [comment]
That looks correct. A valid response will just give you the request ID back. I'm not sure why you aren't seeing anything. Maybe you can look at network requests through the browser dev tools and see if the problem is in the network or in the display of data.

**Comment by Watermanman** [comment]
Thanks for reply, i check report state dashboard by browser dev tools, it always get 404 response, i think it build not correct.

**Comment by Fleker** [comment]
Yeah if there's a 404, then there's something wrong with how the project was set up. Check that the endpoints were created.
