### ISSUE TITLE
please add following modes(ja)

### ISSUE THREAD

**Issue by kazamachan** [actions-on-google/smart-home-nodejs#279]
name:mode
name_synonym:モード

setting_name: Low
setting_synonym: 音控えめ、音控え目

setting_name: quiet
setting_synonym: 音控えめ、音控え目、マナー

setting_name: manner
setting_synonym: マナー

**Comment by Fleker** [comment]
It seems like _low_ [is already available](https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings_10). The other settings will be added.

**Comment by kazamachan** [comment]
I know Low is already available.I want to add setting_synonym「音控えめ、音控え目」
there are only 「低, 低め」

**Comment by Fleker** [comment]
I understand.

**Comment by Fleker** [comment]
These requests have been added. Check out the documentation to learn more: https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings_10

**Comment by kazamachan** [comment]
Sorry,I tried that.
But it was not OK.
「低, 低め」was OK but 「音控えめ、音控え目」was not OK.
What is the cause?
sample speak：
「devicename のモードを低めにして」it was OK
「devicename のモードを音控えめにして」it was not OK
it means 「set mode to low for (devicename)」
I just changed [setting_synonym]parts and speak.

**Comment by kazamachan** [comment]
additional infomation：
manner was OK.
「devicename のモードを**マナー**にして」it was OK
