### ISSUE TITLE
i can not use toggles

### ISSUE THREAD

**Issue by kazamachan** [actions-on-google/smart-home-nodejs#280]
Can I get advice how to use toggles.
I Can not use toggles.but i can use mode .
I do not know why i can not use toggles.

**Comment by Fleker** [comment]
So this happens if, in Japanese, you use the query pattern "Turn on the <toggle> master of the <device name> master"?

When you give that query, do you see any request coming to your server, or does it fail before that?

**Comment by kazamachan** [comment]
I used the query "Turn on silent for cleaning master"
sorry,my english is not so good.

It failed before coming to server.
execute intend request didn't come to server.

**Comment by Fleker** [comment]
Can you try giving the command in English? If it works there, then there may need to be some improvements to the grammar in Japanese.

**Comment by kazamachan** [comment]
sorry、what i say to use quiet toggle in English.
i said 「turn on silent for "device name"」but speaker said「i can't help that yet」
it was ok 「start to clean」「start "device name"」

**Comment by Fleker** [comment]
For a toggle defined as:

```
{
    "name": "quiet",
    "name_values": [{
      "name_synonym": ["quiet", "silent", ...],
      "lang": "en"
    }, {
      ...
    }]
  }
```

The command _Turn on quiet for the (device name)._ should work.

**Comment by kazamachan** [comment]
I tried english version on today.
It was OK、but I don't know why.
I tried 【Turn on quiet for the (device name)】before.
And I tried japanese version on today too.
It was OK too.....
but i tried same source and same speaking before...

**Comment by kazamachan** [comment]
I tried toggle on today.
It was OK in English and  Japanese.
does toggle require  english of name values?
I added english,and I could use toggle.

it was OK

           "availableToggles": [
              {
                "name": "quiet",
                "name_values": [
                  {
                    "name_synonym": [
                      "quiet","silent"
                    ],
                    "lang": "en"
                  },
                  {
                    "name_synonym": [
                      "サイレント"
                    ],
                    "lang": "ja"
                  }
                ]}
            ]
          }

it was not OK

           "availableToggles": [
              {
                "name": "quiet",
                "name_values": [
                  {
                    "name_synonym": [
                      "サイレント"
                    ],
                    "lang": "ja"
                  }
                ]}
            ]
          }

**Comment by Fleker** [comment]
Based on the [supported languages](https://developers.google.com/actions/smarthome/traits/#supported-languages) list, Japanese should work. I'm not sure why it does not work with Japanese only.

**Comment by kazamachan** [comment]
Thank you for your reply. 
It is okay because I can use toggle,now.
However, I think there is something wrong.
There was someone around me who experienced the same phenomenon. 
So I told him to add an English version. 
He could solve it by adding English version.
