### ISSUE TITLE
Information needed:  Request Sync - response takes 4 seconds.

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#282]
Hi,
I have followed the link to implement Request SYNC.https://developers.google.com/actions/smarthome/request-sync. it is informative and helpful. Using the curl -i -s -X POST -H "Content-Type: application/json" -d "{agentUserId: \"agentUserId\"}" \
"https://homegraph.googleapis.com/v1/devices:requestSync?key=API_KEY" . I have got the response. It took almost 4 secs - 5 secs to get a response from googleapi. Is it a known issue? What is the maximum time and minimum time to get a response for request SYNC?

**Comment by Fleker** [comment]
The latency is going to be dependent on many factors, so I couldn't really provide a minimum and maximum time.

**Comment by sakthisg** [comment]
The  response handler has the time out of 3 secs if the googleapi not responding within the time limit. What is your suggestion to set the time timeout value? Ideally 3 secs are more than enough for internet responses...Here i observe always it is 4-5 secs. Please suggest!

**Comment by Fleker** [comment]
What response handler are you using? Can you increase the timeout to something longer, maybe 10 seconds?

**Comment by sakthisg** [comment]
The report sync is implemented in AWS lambda. Lambda has default time out
as 3 seconds. The fetch method in the sample is not returning within 3
seconds. It takes almost 5 seconds. If I change the timeout in Lambda to 5
seconds. This works. Please let me know what is the maximum latency?

**Comment by Fleker** [comment]
There are numerous factors that can affect latency and there isn't any publicly available documentation on API speeds.

**Comment by sakthisg** [comment]
OK thanks.!
