### ISSUE TITLE
about Account linking with OAuth

### ISSUE THREAD

**Issue by kazamachan** [actions-on-google/smart-home-nodejs#283]
When the access token becomes expired Reacquire the access token by using the refresh token. 
Is it correct?
Will all of this process be done automatically by google?
Does not the application need to implement processing?

**Comment by Fleker** [comment]
Yes, when the access token expires, Google should call your token endpoint again with the refresh token to obtain a new access token. This is part of the OAuth specification.

**Comment by kazamachan** [comment]
thank you.
