### ISSUE TITLE
please Delete following modes(ja)

### ISSUE THREAD

**Issue by kazamachan** [actions-on-google/smart-home-nodejs#284]
I'm sorry.
Last time I requested the following contents,Could you delete it?

・setting_synonym: 音控えめ、音控え目（in setting_name: Low）

As a reason turned out to be an inappropriate language as Low.
It is dangerous because there is a possibility that Japanese users who are developing Google will be adversely affected.
Please delete it  as soon as possible.

I can not apologize enough,I' sorry.

**Comment by Fleker** [comment]
日本語で書いてくれてもいいですよ

**Comment by kazamachan** [comment]
前回、以下のモード追加を依頼しました。

#279
・setting_synonym: 音控えめ、音控え目（in setting_name: Low）

こちらを削除していただきたいです。
その理由としてはLowとして適切ではないという事で
他の日本の開発者及び利用者に悪影響を及ぼす可能性があると判断したからです。
もう少し考えてから依頼するべきでした。
大変申し訳ございませんが、削除をお願いします。

実際、試したところ利用できなかったので
ドキュメント上の削除のみでいいと思います。
同時に申請した「マナー」に関しては利用できました。
ありがとうございます。

個人スキル向上用として申請していた点もあり
大変申し訳ございませんが、削除お願いします。
