### ISSUE TITLE
New Toggles request

### ISSUE THREAD

**Issue by luisgabrielroldan** [actions-on-google/smart-home-nodejs#285]
Hi Guys, I'm working on an Air conditioner controller device, can you add the next toggles?

## Spanish (es)
name | name_synonym
------------ | -------------
Turbo | turbo, super
swing_v | abanico vertical
swing_h | abanico horizontal
display | pantalla
bluetooth | bluetooth
luz | luz

## English (en)
name | name_synonym
------------ | -------------
swing_v | vertical swing
swing_h | horizontal swing
display | screen
bluetooth | bluetooth

To be honest is really weird have to use existent toggle names. Is there a good reason for that? (Just curious)

**Comment by Fleker** [comment]
These have been added and will be rolling out.
