### ISSUE TITLE
Can't start testing the project on Action on Google.

### ISSUE THREAD

**Issue by jacksun101** [actions-on-google/smart-home-nodejs#286]
I've followed the instructions carefully couple times, but still can't get it working on Action on Google. When I clicked the TEST button, it just shown the message as below.

GoogleFulfillment 'actions.fulfillment.devices' is not supported

And test is not enabled. So, there is nothing shown in the smart home service list of Google Home app. Please help.

**Comment by Fleker** [comment]
This is happening in the console, like an error appearing in the top-right corner?

**Comment by jacksun101** [comment]
Yes,it's an alertbox in the top-right corner.

**Comment by pepperkick** [comment]
Same issue here, I am also unable to test any smart home actions as they do not show up in services list of google home.

![google](https://user-images.githubusercontent.com/8415891/52906287-be2e2f80-326e-11e9-8f88-16951256d7d6.JPG)
.

**Comment by Thorada** [comment]
Hello, same issue as @pepperkick or @jacksun101.
I have this error on the developer console : POST https://console.actions.google.com/m/actions/agents/draft/createlocalizeduserpreview , error 400 -->
![image](https://user-images.githubusercontent.com/2726230/52933584-2571df80-3354-11e9-8411-7795b174c512.png)

**Comment by nickimola** [comment]
Same happens to me.
Any update?

**Comment by asturel** [comment]
Same issue, I just modified the fulfillment url, now I cannot even control my home devices :(

**Comment by adriendomoison** [comment]
Is there a workaround at the moment? Since we can't use the "Start-Testing" to deploy any change on the fulfillment URL? I'm not even sure why "Start-Testing" has to be used to make the change 😬

**Comment by adriendomoison** [comment]
As @asturel mentioned, in the meantime, you can use [gactions cli](https://developers.google.com/actions/tools/gactions-cli) 

For example, if you are doing the washer project:
```
cd ~/path/to/smarthome-washer/washer-start
mv ~/Downloads/gactions .
chmod +x gactions
./gactions init
./gactions test --action_package action.json --project <washer-project-id>
```

**Comment by ldgmaia** [comment]
Any news about this issue @Fleker ?

**Comment by Fleker** [comment]
We're investigating.

**Comment by ctsks** [comment]
any update for this issue?

**Comment by ctsks** [comment]
got a mail from supporting team , Its fixed :)

**Comment by pergolafabio** [comment]
Can you share that email? What was the cause?

**Comment by jacksun101** [comment]
Dear  KS SHIN,

I just login Action on Google, and test my Smart Home Action, it's working
now.

Thanks,
Jack

**Comment by Fleker** [comment]
Yeah it appears that the underlying issue has been resolved. Thanks for verifying.
