### ISSUE TITLE
Available speed synonym

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#287]
Hi, there

I'm curious whether my own speed_synonyms can be defined/used in the supported language.
OR I should used already defined speed synonyms of FanSpeed trait
It's mentioned like the following as per Google developer guide, but haven't found any pre-defined synonyms. 

**Device attribute: availableFanSpeeds** 
Speed Array containing the name of each speed and a subarray for **speed_values** with **language-specific synonyms**. For example, the speed_name "S4" could correspond to the speed_synonym strings "highest" and "maximum" given the language code "en".
- speed_values Contains names and supported languages:
- speed_synonym Strings. User-friendly names for the speed, in each language supported.
lang String. Supported language for the names (see Supported Languages/Language Codes).

**Comment by Fleker** [comment]
Any fan speed name should work for both English and other supported languages.
