### ISSUE TITLE
ID for the user on Google's side

### ISSUE THREAD

**Issue by chearmstrong** [actions-on-google/smart-home-nodejs#288]
Is there a way to identify the Google user that a request comes from? We need to be able to persist some state, which will be specific to the Google user.

To give some context:

2 Google users could complete account linking using the same user in our cloud.
How can we easily identify which user this was?

``` text
Google User 1 <----
                  |
                  |----> Our user
                  |
Google User 2 <----
```

Note: We're unable to do modifications to the schema of our access token.

**Comment by Fleker** [comment]
You can't identify the Google user. You get an access token that relates to the account on your side. You'd need to have two user accounts, one for each user, to identify the request as you'd want.

**Comment by chearmstrong** [comment]
@Fleker Just to give some more context - this is for handling disconnect. For example, if 2x Google users have linked with the same account, we don't want to stop sending state updates when user 1 unlinks, if user 2 is still linked.

However, 2 users/accessTokens is not currently possible on our side for this scenario. It's possible now for 2x Google users to complete account linking with the same account on our side - there's nothing to prevent this. For example, you could have 2 people in the same household, who want to control their devices, but use their own Google account. I think that's a realistic scenario.

Also, a related question, we have a scenario like this, and send state updates. The same `agentUserId` would apply to both Google users. Hoiw do you know which user, or do you assume both?

**Comment by Fleker** [comment]
This is a similar question to #246, which would ideally consist of an OAuth system that would surface different refresh and access tokens to different Google accounts connected to a single user account.
