### ISSUE TITLE
supported modes for availableThermostatModes of TemperatureSetting

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#289]
Hi there
according to spec of TemperatureSettings trait, only specific known modes are supported...
_Currently supports specific known modes from the following list; more and custom ones will be added as needed. These modes all have local expansion aliases (off == "standby", etc)._

In case thermostat supports modes like Hotwater & Away, is it possible to use these modes for availableThermostatMode? 
- Hotwater mode: make hot water with preset temperature for shower 
- Away mode: it's like energy saving mode but think a bit different 
  it's used especially when people go out for long time in Winter and heater runs at minimum....

they are all already defined mode setting names in Mode (https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings)

Thanks in advance!

**Comment by Fleker** [comment]
Thermostat modes are different from the Modes trait. You can try to mix them and use both in one device, but you may run into issues with grammars. With regards to the [TemperatureSetting](https://developers.google.com/actions/smarthome/traits/temperaturesetting) itself, only the modes listed on the page are the specific modes for thermostats.
