### ISSUE TITLE
Trait "Rotation" for Type "Blind" in German missing

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#290]
Hi There,

the Trait "Rotation*" for Type "Blinds*" is not working for german (english is working to rotate the "slats of the blinds"):
* https://storage.googleapis.com/hc-eap/SmartHome%20Rotation%20Schema.pdf
* https://storage.googleapis.com/hc-eap/SmartHome%20Blinds%20Guide.pdf

I tried everything to "rotate" in german, but nothing is working.
Here a screenshot:
![grafik](https://user-images.githubusercontent.com/47856261/53174152-6171a280-35e9-11e9-9bf8-b23f4a206889.png)

Name in English:
tilt, rotate, 

Name_Synonyms in German:
Singular: wende, kipp, kippe, neige, rotiere, drehe
Plural: wenden, kippen, neigen, rotieren, drehen

**Comment by Fleker** [comment]
There is no public Rotation trait.
