### ISSUE TITLE
Mode Settings Request

### ISSUE THREAD

**Issue by dntj** [actions-on-google/smart-home-nodejs#291]
Hi,

We have some smart lighting effects we've recently rolled out and we'd like to make these available via the Google voice UI.  To do so we need appropriate names for our mode settings to be supported.  Is it possible to add mode settings of "move", "morph" and "flame" (with synonym "flicker").

Thanks!

**Comment by Fleker** [comment]
The settings should be available to use in a couple of days. You can look at all available modes in the reference docs: https://developers.google.com/actions/reference/smarthome/traits/modes

**Comment by delfick** [comment]
Hi, I'm implementing these effects in our integration. It seems I can say "set light effect to off" and that works, but if I use move/morph/flame/flicker, then it doesn't seem to recognise the command.

I can see these settings on the page you linked to though. Does this mean they are documented but not yet available?

**Comment by Fleker** [comment]
It does take a few days from documentation for the settings to be available.

**Comment by Fleker** [comment]
It does take a few days from documentation for the settings to be available.

**Comment by delfick** [comment]
I understand now why flame/flicker wasn't working.

I was saying 

```
                {
                  "setting_name": "flame",
                  "setting_values": [
                    {
                      "lang": "en",
                      "setting_synonym": [
                        "flame",
                        "flicker"
                      ]
                    }
                  ]
                }
```

instead of 

```
                {
                  "setting_name": "flicker",
                  "setting_values": [
                    {
                      "lang": "en",
                      "setting_synonym": [
                        "flicker",
                        "flame"
                      ]
                    }
                  ]
                }
```
