### ISSUE TITLE
Open/Close trait in different languages

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#292]
Hi - can we get Open/Close rolled out to all the other languages? 
For example, the feedback i've had is that 'Close' isn't recognised in Dutch - Close = sluit

**Comment by Fleker** [comment]
There is currently no public open/close trait. While you may find preliminary or early documentation, keep in mind that the API can change and it may not be entirely done. Things like internationalization may not be completed.

**Comment by madgeni** [comment]
Ok cool - i'm on the EAP - can I ask for some timescales to be added to that documentation? Thanks
