### ISSUE TITLE
SYNC: Request ID ... update devices failed: INTERNAL

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#293]
Hi,
I just unlinked my test smart home action and tried to link it again resulting in the following error:
  
`SYNC: Request ID 12388994885275428456 update devices failed: INTERNAL`

Could you please let me know why that happens and how I get my action linked again?

**Comment by Fleker** [comment]
Seems like an internal failure. It's hard to say if the issue is intermittent or frequent right now.

**Comment by ctsks** [comment]
Encountered the same error when linking account and found out the cause was "roomHint" tag
I'm using Node.js client library, it seems roomHint is not supported...

**Comment by Fleker** [comment]
Yes it does seem like that field is currently not in [the Node.js API](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/smarthome_api_v1.smarthomev1syncdevices.html). I will file a bug to add this in.

**Comment by dominikkarall** [comment]
In my case it was not because of roomHint as I don't use the library, I couldn't find the issue yet. I'm investing...
