### ISSUE TITLE
New Mode Request: Fan Direction

### ISSUE THREAD

**Issue by JordanHoang** [actions-on-google/smart-home-nodejs#294]
Hello!

I'm working on a Smart Home Action for a smart fan that allows the user to choose between 'Summer Mode' and 'Winter Mode', which determines the direction the fan spins. I was wondering if it would be possible to add a mode related to fan direction. I know there's already a `reversible` property, but I think supplementing that with allowing the user to explicitly choose the direction would help the user experience. Perhaps something like this:

```
{
    name: 'fanDirection',
    name_values: [{
      name_synonym: ['direction', 'fan direction', 'mode'],
      lang: 'en'
    }],
    settings: [{
      setting_name: 'summerMode',
      setting_values: [{
        setting_synonym: ['forward', 'summer', 'summer mode'],
        lang: 'en'
      }]
    }, {
      setting_name: 'winterMode',
      setting_values: [{
        setting_synonym: ['backward', 'winter', 'winter mode'],
        lang: 'en'
      }]
    }],
    ordered: false
}
```

Please let me know if there's any other information that would help. Thank you!

Best,
Jordan Hoang

**Comment by Fleker** [comment]
I'll add in a summer/winter mode, but adding a forward/backward synonym may be a bit unusual and could create a grammar conflict if we added dedicated forward/backward modes in the future.

**Comment by JordanHoang** [comment]
Thanks Nick! I totally understand your reasoning for the forward/backward synonym. That's more of an internal value for us. Using 'summer (mode)' and 'winter (mode)' will be perfectly fine. Thanks!

**Comment by Fleker** [comment]
The settings should be available to use in a couple of days. You can look at all available modes in the reference docs: https://developers.google.com/actions/reference/smarthome/traits/modes

**Comment by JordanHoang** [comment]
Thanks again for adding it, and the quick response time!

**Comment by JordanHoang** [comment]
@Fleker 

Seems like the `fan_position` mode still isn't working. I'm not sure if it has something to do with my JSON when syncing, or my wording on my commands.

My commands are something like "Set Bedroom fan direction to summer mode" where Bedroom is the name of the device.

And my JSON response is this:

`"attributes": {
        "availableModes": [
            {
                "name": "fan_position",
                "name_values": [
                    {
                        "name_synonym": [
                            "fan position",
                            "fan direction",
                            "direction"
                        ],
                        "lang": "en"
                    }
                ],
                "settings": [
                    {
                        "setting_name": "summerMode",
                        "setting_values": [
                            {
                                "setting_synonym": [
                                    "summer",
                                    "summer mode"
                                ],
                                "lang": "en"
                            }
                        ]
                    },
                    {
                        "setting_name": "winterMode",
                        "setting_values": [
                            {
                                "setting_synonym": [
                                    "winter",
                                    "winter mode"
                                ],
                                "lang": "en"
                            }
                        ]
                    }
                ],
                "ordered": false
            }
        ],
        "reversible": true
    }
`

Any help is appreciated! Thank you!

**Comment by JordanHoang** [comment]
Also, let me know if you'd prefer me to open a new issue for this.

**Comment by Fleker** [comment]
I did not encounter any issues.

"set the <device> fan position to Summer" ended up setting the mode as expected.

**Comment by JordanHoang** [comment]
Looks like it's working now. Thanks Nick!
