### ISSUE TITLE
suction mode trait doesn't work, how to trigger it?

### ISSUE THREAD

**Issue by andyfires** [actions-on-google/smart-home-nodejs#295]
Hi dears,

I'm currently working on implementing an action for vacuum robot, I want to providing changing the suction power of the vacuum with four levels, quiet, normal, power, full. I've wrote the code but during testing, I cannot trigger an action for google action to send request to my backend service. The filed attributes in SYNC response is like bellow:

```
  "attributes":{  
    "pausable":true,
    "availableModes":[  
      {  
        "name":"suction",
        "name_values":[  
          {  
            "name_synonym":[  
              "suction"
            ],
            "lang":"en"
          }
        ],
        "settings":[  
          {  
            "setting_name":"quiet",
            "setting_values":[  
              {  
                "setting_synonym":[  
                  "quiet"
                ],
                "lang":"en"
              }
            ]
          },
          {  
            "setting_name":"Normal",
            "setting_values":[  
              {  
                "setting_synonym":[  
                  "normal",
                  "normal mode",
                  "default"
                ],
                "lang":"en"
              }
            ]
          },
          {  
            "setting_name":"High",
            "setting_values":[  
              {  
                "setting_synonym":[  
                  "high"
                ],
                "lang":"en"
              }
            ]
          },
          {  
            "setting_name":"large",
            "setting_values":[  
              {  
                "setting_synonym":[  
                  "full"
                ],
                "lang":"en"
              }
            ]
          }
        ],
        "ordered":true
      }
    ]
  }
```

The question is I tried in google assistant in several ways like 'set my vacuum's suction to normal', 'adjust the suction mode of my vacuum to quiet',  or 'increase my vacuum's suction', etc. But it didn't work, I didn't see any request in my backend service. Is my request sentence wrong? What sentence should I use to trigger that? I've read the mode query issue, I met the same problem too.

Thank you very much.

**Comment by Fleker** [comment]
Only settings that are in this table can be used: https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings

**Comment by andyfires** [comment]
yes, I used the model settings in this table except 'quiet', which I found existing in supported language except English, I thought that might be a document mistake. Is 'quiet' the cause that why it didn't work?

**Comment by andyfires** [comment]
I tested by removing 'quiet' from the model setting list, and it worked. So I think the problem should be 'quiet' is not supported in English. I opened a new issue for requesting new model setting name and close this one.
