### ISSUE TITLE
New Mode Setting Request

### ISSUE THREAD

**Issue by andyfires** [actions-on-google/smart-home-nodejs#296]
Hello Dear,

Request for adding a new model setting 'quiet' in English.

{"setting_name":"quiet","setting_values":[{"setting_synonym":["quiet", "silent'],"lang":"en"}]}

#295

**Comment by andyfires** [comment]
issue #295 is how I found the problem, I marked it as related and closed.

**Comment by Fleker** [comment]
In English, the setting_name is "Turbo_Silence", with "quiet" and "silent" as the values.
