### ISSUE TITLE
New Mode Name/Settings & Device Trait

### ISSUE THREAD

**Issue by jason7sc** [actions-on-google/smart-home-nodejs#297]
Our company is attempting to integrate adjustable furniture with Actions on Google, however, no mode names or mode settings provide position control.  Would it be possible to add the following mode name and settings?

Also, we'd be interested in a new range control trait (or similar) that could be used to specify a numerical range of operation for one or more peripherals on a device.  A generic trait like this could be used across a wide variety of devices that may not conform to traits like brightness, temperature control, doors, windows, etc.  We're happy to provide more insight if that's something of interest.

Edit: If possible, we'd also like to propose the addition of a "massage" mode name.

```
{
    "availableModes": [{
      "name": "position",
      "name_values": [{
        "name_synonym": ["position"],
        "lang": "en"
      }],
      "settings": [{
        "setting_name": "upright",
        "setting_values": [{
          "setting_synonym": ["upright","read","tv"],
          "lang": "en"
         }]
       },
       {
        "setting_name": "lounge",
        "setting_values": [{
          "setting_synonym": ["lounge"],
          "lang": "en"
         }]
       },
       {
         "setting_name": "flat",
         "setting_values": [{
           "setting_synonym": ["flat","reset"],
           "lang": "en"
         }]
       },
       {
        "setting_name": "zero gravity",
        "setting_values": [{
          "setting_synonym": ["zero gravity","zero g"],
          "lang": "en"
        }]
      },
      {
        "setting_name": "anti-snore",
        "setting_values": [{
          "setting_synonym": ["anti-snore"],
          "lang": "en"
        }]
      }],
       "ordered": false
    }]
}
```

**Comment by Fleker** [comment]
The settings should be available to use in a couple of days. You can look at all available modes in the reference docs: https://developers.google.com/actions/reference/smarthome/traits/modes

**Comment by jason7sc** [comment]
Wow, awesome! Thank you, we really appreciate it. 

I edited this issue after I posted it.  I originally forgot to include a "massage" mode name as well.  Could that be added at some point as well?  It can wait until another batch of updates are processed, if necessary.  I apologize for the confusion.

Thanks again!

**Comment by Fleker** [comment]
Massage has just been added. It may take a few days to roll out.

**Comment by jason7sc** [comment]
Thanks! However, I'm only seeing massage in the "mode settings" section.  Would it be possible to add that to the "mode names" section?  Ex: "Set [device] massage to [low, med, high]."

```
{
    "availableModes": [{
      "name": "massage",
      "name_values": [{
        "name_synonym": ["massage"],
        "lang": "en"
      }],
      "settings": [ etc... ]
}
```

**Comment by Fleker** [comment]
Yeah

**Comment by Fleker** [comment]
Massage has also been added as a mode name.
