### ISSUE TITLE
Request new mode setting options: time duration

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#298]
We are happy with the mode name "sleepTimer", but we can't find any valid mode settings could be used for "sleepTimer", which could be 30 minutes? an hour? two hours, etc. 

Thanks

**Comment by Fleker** [comment]
We now have several settings related to time documented: https://developers.google.com/actions/reference/smarthome/traits/modes


Setting | Synonms
-- | --
H1 | 1 hour, one hour
H2 | 2 hour, two hour
H4 | 4 hour, four hour
H8 | 8 hour, eight hour
W2 | 2 week, two week
W3 | 3 week, three week
W4 | 4 week, four week

**Comment by izone-airstream** [comment]
Awesome, Thanks mate.
