### ISSUE TITLE
What settings could be used by mode sleepTimer please?

### ISSUE THREAD

**Issue by q1yh** [actions-on-google/smart-home-nodejs#299]
Hi, we are happy with the sleepTimer in mode, but we cannot figure out what settings could be used by that? Thanks

**Comment by Fleker** [comment]
A mode can have any settings, as long as they are in this list: https://developers.google.com/actions/reference/smarthome/traits/modes

sleepTimer could have settings of off, on, or maybe Wool. While they may not all make sense, it does provide a fair amount of flexibility.

**Comment by q1yh** [comment]
Sorry, I forgot to mention that's for AC_Unit. For most AC_Units, the sleep timer has settings of Off, 0.5hr, 1hr, 2hrs, etc. Can we use an amount of time in the settings?

**Comment by Fleker** [comment]
Modes only support the string phrases, not specific lengths of time.
