### ISSUE TITLE
Request new devices type: garage door and blind

### ISSUE THREAD

**Issue by q1yh** [actions-on-google/smart-home-nodejs#300]
Hi, we request device types of garage door and blinds, which would have open/close or start/stop, direction(up/down), position settings. Thanks

**Comment by Fleker** [comment]
[Blinds](https://developers.google.com/actions/smarthome/guides/blinds) are now a type, as well an [OpenClose](https://developers.google.com/actions/smarthome/traits/openclose) trait which can open and close as a percentage in preset directions.

**Comment by pergolafabio** [comment]
@Fleker  , just a question, can you also do a STOP command if you open/close a cover?

**Comment by Fleker** [comment]
I don't know.
