### ISSUE TITLE
ColorSetting query not triggering

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#301]
Hi, 
In UK English, the query "what colour is my light?" isn't recognised.
I can set them but can't query them

**Comment by Fleker** [comment]
This verbal query is currently not supported.

**Comment by madgeni** [comment]
It's in the documentation - can it be updated

**Comment by Fleker** [comment]
I'm going to seek more guidance on the current state of querying for colors.

**Comment by madgeni** [comment]
Thanks @Fleker - appreciate it :)

**Comment by ctsks** [comment]
Querying commands "what color is the desk lamp?" from document is still not working...
@Fleker have you found any guidance on the current state of querying for colors?

**Comment by Fleker** [comment]
It's not supported yet.

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general issue with the Smart Home platform/documentation, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
