### ISSUE TITLE
Request controlling slider for "official" type blinds

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#302]
Hello there,

so it seems like the OpenClose trait is now official?
https://developers.google.com/actions/smarthome/traits/openclose

For type Blinds:
https://developers.google.com/actions/smarthome/guides/blinds

We are a big company doing the blinds and want to use the google home app or via a smart display (google home hub) to controll the blinds via a slider. Currently it only works via voice command. The pictogram is not functional:
![grafik](https://user-images.githubusercontent.com/47858747/54276128-cc7d1c00-458c-11e9-8665-26b062842387.png)

Any plans to implement this feature? It is strongly requested for the european market

**Comment by madgeni** [comment]
Also, is this available in all supported languages?

**Comment by Fleker** [comment]
A feature request has been filed for a slider.

Blinds as a type should be available in all supported languages.

**Comment by AlexForReal** [comment]
Thank you @Fleker 
Do you know how to prioritize this request more? We are able to sell a lot of bundles with google home (hub) per supported countries

**Comment by Fleker** [comment]
I'll update the feature request, but won't guarantee a time frame to this being addressed.

**Comment by pergolafabio** [comment]
also vacuum domain WITH zone cleaning should be usefull

**Comment by AlexForReal** [comment]
Any news about a touch control for shutters or blinds?
Maybe on smart displays first?

**Comment by Fleker** [comment]
Moving this issue to the public bug tracker: https://issuetracker.google.com/issues/136112642
