### ISSUE TITLE
Smart Home & Touch Controls: visual cards never update after successful Execute commands

### ISSUE THREAD

**Issue by davidmcgowan** [actions-on-google/smart-home-nodejs#303]
According to the documentation, visual assistants and the Google Home app display graphical interfaces for certain traits without any development work.

https://developers.google.com/actions/smarthome/create#touch-controls

However, I have implemented a smart home action which uses the brightness trait to dim and brighten a users lights. I am succesfully reporting the states of the users devices to Home Graph after the original sync and every execute request but the visual display never seems to update after a successful Execute command.

I notice that directly after a successful execute that Google Smart Home makes a query request to my fulfillment api, is this correct? Seems as though it is using the values returned in the query for the graphical interface.

Anyone had similar issue?

**Comment by Fleker** [comment]
After an execute, you should do report state. It may also do a query. These two may be useful in updating the visual response.

But I'd have to check with the sample to see if the behavior is working as intended.

**Comment by Fleker** [comment]
The visual display is currently not updating in real time based on reported state.

**Comment by davidmcg1985** [comment]
Thanks for your feedback @Fleker 

OK so just to confirm this is a known issue/bug?

**Comment by davidmcgowan** [comment]
Thanks for your feedback @Fleker 

OK so just to confirm this is a known issue/bug?
