### ISSUE TITLE
Questions regarding Report State / Request Sync

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#304]
1) is Request Sync a requirement for public launch of service like Report State?

2) Report state should be called right after EXECUTE and SYNC intent as per Spec.
but I don't think RS is necessary for the response to QUERY as QUERY Intent does not trigger device state changes. If state of devices change, RS will be called proactively. 
Is my understanding of RS right? 

======Spec. =======
_Report State should be called even if the new state of the device has already been returned in the response to an EXECUTE or QUERY intent. The ReportState API should also be called right after a SYNC intent._

3) EXECUTE and QUERY  Intents are sequentially triggered when voice commands are made from Google Assistant/Home apps. Why QUERY Intent is triggered right after EXECUTE?
AS Report State is called right after EXECUTE, there will be the most recent states of device in Google Graph. Can QUERY Intent be ignored?

**Comment by Fleker** [comment]
I do not believe request sync is a launch requirement as users can always say "sync my devices".

Yes, report state is used to report the devices current state. If that hasn't changed then you don't need to report anything. 

Is query called after execute? I don't believe that happens.

You shouldn't ignore any request, as it's easier to respond to all of them then try to check which ones wouldn't be necessary.
