### ISSUE TITLE
Custom mode respond without mode name

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#306]
Hi, 
In our case, the responses we received after custom mode settings are lack of mode name. For example:
Command 1: set A/C unit sleep timer to on.
Response 1: You got it, setting the A/C unit to on.
Shouldn't it be: You got it, setting the A/C unit sleep timer to on.

Command 2: set A/C unit power saving to on.
Response 2: Sure, setting the A/C unit to on.
Expected: Sure, setting the A/C unit power saving to on.

Is that we missed something or it is designed as it is? Cheers

**Comment by Fleker** [comment]
Can you try an example with a [Toggle](https://devsite.googleplex.com/actions/reference/smarthome/traits/toggles) to see if you get a match that way?

**Comment by izone-airstream** [comment]
Yes, for toggle we can get the toggle name from the response such as: 
"Ok, turning on power save on A/C unit". 

That only missing on custom mode response.

**Comment by Fleker** [comment]
Is it possible to just use toggles for your action?

**Comment by izone-airstream** [comment]
For power saving, yes, we could use the toggle. But for sleeptimer, it looks like we have no choice but only the custom mode.  

It is not a critical issue, but from the view of user experience, we recommend to put mode name in response. 

Cheers.

**Comment by izone-airstream** [comment]
Find another response issue which could be fixed easily. When calling sleep timer, the response repeat the time twice. Example:
"Hey Google, set A/C unit sleep timer to 1 hour"
"Ok, set A/C unit sleep timer to 1hour 1hour".

**Comment by Fleker** [comment]
Does this happen for other settings as well?

**Comment by izone-airstream** [comment]
For us, it only happens when using "sleep timer" mode, with "1 hour", "2 hour", "4 hour", etc.

**Comment by Fleker** [comment]
I'm unable to reproduce this behavior.
