### ISSUE TITLE
What is the trait to support humidity?

### ISSUE THREAD

**Issue by wyxcoder** [actions-on-google/smart-home-nodejs#307]
A device to display both temperature and humidity?

**Comment by Fleker** [comment]
The [TemperatureSetting](https://developers.google.com/actions/smarthome/traits/temperaturesetting) trait supports temperature, and has a humidity state as well.

**Comment by wyxcoder** [comment]
I guess I am asking what device type that can display both temperature and humidity on google home?

**Comment by Fleker** [comment]
I don't believe there is any graphical display of humidity at the moment. [This section](https://developers.google.com/actions/smarthome/create#touch-controls) of the docs will be updated as touch controls on the platform evolve.

**Comment by AlexForReal** [comment]
Is there a plan to put all the supported types and traits into the Google Home App as Touch Controls?
Touch controls are highly needed if you don't always want to control via voice (like Apple Homekit is putting a lot of effort into touch controls to control the whole home via 1 app).

E.g. putting also like mentioned here "Humidity" as touch control (displaying) into the Google Home App

**Comment by Fleker** [comment]
I can't share the entire roadmap, but we do want to make sure it's easy to control devices across many surfaces.
