### ISSUE TITLE
Why thermo device doesn't refresh on google home?

### ISSUE THREAD

**Issue by wyxcoder** [actions-on-google/smart-home-nodejs#308]
I add thermo device, first I cannot see temperature unless I click into it which is not convenient. Second , when I click into it, I don't see temperature refreshed, I have to leave and click back in. Seems that should be the basic feature to have it auto refreshed.

**Comment by Fleker** [comment]
Is your device implementing [report state](https://developers.google.com/actions/smarthome/report-state) to proactively update the device's state?

**Comment by wyxcoder** [comment]
Yes, I did implement report state. See below, seems it returns ok, but the display doesn't change. Unless I go in again

Acurite in (3:14:14:35): Channel: 5776452, Temp: 39, Humidity: 39
Update DB from Acurite signal: 5776452, thermostatHumidityAmbient -> 39
Report State request {"requestId":"ff366a3cc","agentUserId":"1234","payload":{"devices":{"states":{"7":{"on":false,"online":true,"
thermostatTemperatureAmbient":48,"thermostatHumidityAmbient":22,"thermostatMode":"cool"}}}}}
Report State request {"requestId":"ff366a3cc","agentUserId":"1234","payload":{"devices":{"states":{"8":{"on":false,"online":true,"
thermostatTemperatureAmbient":39,"thermostatHumidityAmbient":39,"thermostatMode":"cool"}}}}}
Report State response {
  "requestId": "ff366a3cc"
}

Report State response {
  "requestId": "ff366a3cc"
}


![Screenshot_20190318-142132_Home](https://user-images.githubusercontent.com/47443766/54564736-c5d61680-4989-11e9-89ad-cfd799a5691f.jpg)

**Comment by Fleker** [comment]
Updating live is not currently supporting

**Comment by HayTran94** [comment]
Hello @Fleker, so how about `outlet`? Does it support for live update in google home app when homegraph receive reportState event?

**Comment by Fleker** [comment]
Updating live generally is not available, even if the home graph gets the new state.

**Comment by HayTran94** [comment]
Hello @Fleker, 
So what is the purpose of `reportState` function?

**Comment by Fleker** [comment]
Report state can be used to obtain a live view of device states, which can be useful on visual surfaces like smart displays and phones. It can also enables relative queries for things like Brightness to work without a circuitous route to the cloud server and back just to get the current brightness and then set it.
