### ISSUE TITLE
Keyword "ON" now needed? not needed before

### ISSUE THREAD

**Issue by pergolafabio** [actions-on-google/smart-home-nodejs#309]
Hi

we are using HomeAssistant/Openhab to push light/switches/.... to google smart home
already using it like almost a year, but since a few weeks we now need to say the keyword "ON" to actually turn something ON, this was not needed before... is this a issue? or now working as designed?  what changed?

as an example
lets say: "kitchen" is the name of  a kitchen light, exposed a a "light"

before we could say this to turn on/off the kitchen light
hey google, kitchen => this turned on the kitchen light
hey google, kitchen ON => this also turned on the kitchen light
hey google, kitchen OFF=> this turned off the kitchen light

NOW

hey google, kitchen => i got some google results from the 10 nearby kitchen stores
hey google, kitchen ON => this turned on the kitchen light
hey google, kitchen OFF=> this turned off the kitchen light

i dont need google results of 10 nearby kitchen  stores, i need google to turn on the kitchen light
this is tested in NL and ENG as primary language
tested with devices exposed as switches/lights

how can i resolve this?

**Comment by Fleker** [comment]
This was never intended to happen, so this issue will be closed.

If you are looking for unique ways to control devices in your home, you can go to the Routine section of the Google Assistant settings.

**Comment by pergolafabio** [comment]
ah, but when is routines available in dutch language?

thnx
