### ISSUE TITLE
New toggle: shading

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#310]
Hi,
I would like to request a new toggle for blinds:
EN
shading | shading, shading mode
DE
shading | Beschattung, Beschattungsmodus

The toggle should allow users to set their blinds to shading (not completely dark).

**Comment by Fleker** [comment]
Is "shading" an on/off property, or is a scale like brightness?

**Comment by dominikkarall** [comment]
I would say that the configuration could be like brightness to scale, but in the daily usage I would say it is an on/off property.

Nevertheless, it might also make sense to add shading as an parameter to the OpenClose trait.

**Comment by Fleker** [comment]
I think in this case you could just grab the OnOff and Brightness traits and use them as-is.

**Comment by dominikkarall** [comment]
I don't think that OnOff is a good solution, as it would require to say "turn the blinds on/off" which actually makes no sense. I would recommend to say "turn on shading for the blinds" which would require a toggle.

**Comment by Fleker** [comment]
The toggle `shade` will be available in a few days.

**Comment by dominikkarall** [comment]
Could you please add the German translation as well?
DE
shade | Beschattung

Thx!

**Comment by Fleker** [comment]
Forgot about that. Added the German translation.
