### ISSUE TITLE
Request a new trait: Message Trait

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#311]
Hi there,
Thinking of this trait for a while, in fact it is a very common interface for a smart device. 

The usage for a message trait is mostly for machine-human interaction, user can get notifications or messages from smart devices, such as:
"Coffee maker needs to be serviced"
"Aircon filter needs to be cleaned"
"Vacuum bag is full, please empty it".... etc.

Then from any interface of smart home (google assistance, google home, etc) can read messages like: "Hey google, read the messages from my coffee machine".

Cheers

**Comment by Fleker** [comment]
You mean like [errors and exceptions](https://developers.google.com/actions/reference/smarthome/errors-exceptions)?

**Comment by izone-airstream** [comment]
Yes, they all send information from smart devices, the difference is that messages are not limited to passive errors or exceptions, they could be active like: 
"Hey buddy, your pizza is ready. yours, Oven"

Pure discussion, just feel errors and exceptions are not enough for a "smart" device. :)

**Comment by Fleker** [comment]
This issue has been moved over to the public bug tracker. https://issuetracker.google.com/issues/136103091
