### ISSUE TITLE
Custom mode names

### ISSUE THREAD

**Issue by BrandonShega** [actions-on-google/smart-home-nodejs#312]
Hello!  We're currently working with Google on implementing a Smart Home Action project for our smart shower here at Moen.  We have a sense of presets which are a set of user defined settings i.e

Preset 1
- Temperature: 100
- Outlet A: On
- Outlet B: Off
- Pause: True

We've been directed by members of Google to include these as the `Scene` type, the problem with this is that all scenes and devices get flattened in the SYNC response so there isn't really a way to determine which scenes go with which device in the response for the case a user has more than one shower.  If they activate the "Workout" scene for example, how does Google know which shower to activate it on?

We've implemented this currently with Amazon using their mode controller, so presets are basically modes that the shower can be in, since it can only be in one at a time.  This would be a way to implement the same thing on the Google side except for that we can't use custom names or settings, what does the time line look like for that? Is this something that might be beta testable to see if it fits our needs?

We're really looking to get Google Smart Home working with our product within the near future and this is really the only thing that's stopping us so far.

Please let me know if there are any questions.

Thanks,
Brandon

**Comment by Fleker** [comment]
Custom modes aren't available, and there's no public timeframe on such a feature.

You can use individual modes, although a scene would be the right way to do this. Alternatively, users can create custom routines that wrap several commands together.
