### ISSUE TITLE
No possibility to remove just 1 product. Only whole linked account

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#313]
Hi there,

is there are possibility to remove just specific products and not the whole linked account with 3rd party?

I want to delete e.g. this plug only and not the complete range of products from the 3rd party:
![grafik](https://user-images.githubusercontent.com/47858747/54748165-286d2380-4bd1-11e9-9ee7-fbb16217e8ed.png)

This is currently not possible? Any plans to implement it?

**Comment by Fleker** [comment]
This is not possible. If you want to disconnect a particular device, you should do it through the linked device account.
