### ISSUE TITLE
404 response for Report State - need clarification

### ISSUE THREAD

**Issue by chearmstrong** [actions-on-google/smart-home-nodejs#314]
The docs say:

>404 - Failure: The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible. Typically, this means that we cannot find either the user (agentUserId) or the device. It may also mean that the user has not yet linked with Google, or you didn’t send the agentUserId in the SYNC response.

How do I know if the problem because the the `agentUserId` can't be found, or because the device that can't be found?

**Comment by Fleker** [comment]
You should be keeping track, on your server, of user IDs that have linked to Google, and those who have later received a DISCONNECT intent.

**Comment by chearmstrong** [comment]
@Fleker We are doing this. However, we found in some cases, if we started to send state before the linking/SYNC was fully complete, we would get 404.

In this scenario we are retrying a few times.

It was more to know if we could tell why we got 404, so we know the next action to take.

For example, if it’s 404 because the user doesn’t exist - should we update the list on our side.

**Comment by Fleker** [comment]
It is possible that you will need to wait several seconds after syncing to report state for the first time.

In the case of getting a 404 for a particular userId, you should update something on your side, like a boolean field, to not report state for that user ID again until you are asked to SYNC that user again.
