### ISSUE TITLE
OpenClose for blinds: invert openPercentage?

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#316]
The OpenClose trait works a little bit strange for blinds.

Example (tested in German):
Set the blinds to 90%

Actually the result is that the blinds are set to 90% open. So not the blinds are 90% visible, but the blinds are nearly completely open.

From user perspective this sounds really strange, as you think that 100% means closed and not open for blinds. Of course, if you think about a door it's the other way around (100% = open, 0% = closed).

I would suggest to include an invert attribute to the OpenClose SYNC response so that the result of "set the blinds to 90%" results in openPercentage = 10%.

**Comment by Fleker** [comment]
From my POV, I'd interpret 90% to mean 90% open, so it seems to be a matter of opinion.

But in your service, you can set it up so that when you get an EXECUTE with 90%, you handle it in the way that you want.

**Comment by dominikkarall** [comment]
I would not prefer to change it in my service, as that would lead to wrong QUERY and ReportState (and maybe to wrong icons in the app in the future?).

Example:
- user sets blinds to 90% (90% open)
- openPercent = 90 is received by my service
- I would need to respond with SUCCESS openPercent = 10, which might be handled by Google as no SUCCESS as it is not the openPercent value I received in the EXECUTE json
- user receives as an answer, that the blinds will be 10 percent opened, which is pretty confusing for the user as he asked before to set the blinds to 90% and therefore the answer should include the number (90) the user requested. I can't send back 90, as the response from Google Assistant includes the word 'open'.
- user asks which state the blinds are
- I would need to report openPercent=10, so that the user gets the right answer
- ReportState would also need to be faked to 10%

So the EXECUTE values would always differ from the QUERY and ReportState values.

If I think of an slider in the Home App like brightness for blinds, it can't work that way as well. Would you drag the slider to the left (0%) to have the blinds closed or to the right (100%)? I would say the slider should go to the right (100%) to close the blinds.

**Comment by Fleker** [comment]
I'll file a ticket internally for this request.

**Comment by proppy** [comment]
Closing as obsolete.
