### ISSUE TITLE
New mode/trait request

### ISSUE THREAD

**Issue by SergeyKiselev1995** [actions-on-google/smart-home-nodejs#317]
Hi!
I'm working on action for smart humidifier. We have main mode named "easy".
Easy mode can have values from 1 to 6.
Is it possible to create mode with this name and numeric values?
I already use fan speed trait in the action and it has quite different concept then easy mode for smart humidifier

Thank you!
Sergey

**Comment by Fleker** [comment]
There is currently mode values for 'memory X'


memory 1 | memory 1, memory one, memory position 1, memory position one, custom 1, custom one, memory, program 1, program one, one
-- | --
memory 2 | memory 2, memory two, custom 2, custom two, memory position 2, memory position two, program 2, program two, two
memory 3 | memory 3, memory three, custom 3, custom three, memory position 3, memory position three, program 3, program three, three
memory 4 | memory 4, memory four, custom 4, custom four, memory position 4, memory position four, program 4, program four, four

Would this kinda be what you're looking for, but expanded?

**Comment by SergeyKiselev1995** [comment]
> There is currently [mode setting values](https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings) for 'memory X' with '_number_' as a synonym
> 
> key	synonyms
> memory 1	memory 1, memory one, memory position 1, memory position one, custom 1, custom one, memory, program 1, program one, one
> memory 2	memory 2, memory two, custom 2, custom two, memory position 2, memory position two, program 2, program two, two
> memory 3	memory 3, memory three, custom 3, custom three, memory position 3, memory position three, program 3, program three, three
> memory 4	memory 4, memory four, custom 4, custom four, memory position 4, memory position four, program 4, program four, four
> Would this kinda be what you're looking for, but expanded?

Hello.
As i understand we can say something like "Set device mode to memory 1".
If i'm right then it seems like it's something that i need.
Then it would be great to have settings with values from "easy 1" to "easy 6"

Thank you

**Comment by Fleker** [comment]
Okay. Added a mode called "easy". You can use settings of "memory 1" to "memory 6", with "one" to "six" as synonyms.
