### ISSUE TITLE
Up/Down trait for volume?

### ISSUE THREAD

**Issue by pergolafabio** [actions-on-google/smart-home-nodejs#318]
hi, is there an easy way to say Up/Down?

like we have for switch on/off , blinds open/close

Up and down is useful to control stuff like volume increase...
is that possible?

before, we could turn ON a switch, without saying the word "ON"
so if i created 2 switches with names : 
Volume UP
Volume Down 
i was able to say "Hey Google, Volume Up"
now i need to say "Hey Google, Volume Up ON"

this is changed lately by google, we now NEED to say the ON word to turn something ON

Routines would help to solve this, but its not rolled out in our language

**Comment by Fleker** [comment]
A Volume trait is related to #148. Up/Down is like OpenClose with the directions of Up and Down.
