### ISSUE TITLE
Allow client_id and client_secret to taken from `Authorization` header.

### ISSUE THREAD

**Issue by itpcc** [actions-on-google/smart-home-nodejs#320]
Currently, Google action's account linking allows the client to let "Google to transmit clientID and secret via HTTP basic auth header". 

![image](https://user-images.githubusercontent.com/3356814/55213836-32bd9c00-5227-11e9-985d-42eb7a755203.png)

If the option's checked, when the user makes a SYNC request, Google'll return `client_id` and `client_secret` via neither request's query string nor request's POST body. But those value with return via `Authorization` request's header as a base64 encoded string.  So, the application can't find those value and return 400 error because 'missing required parameter'.

I'd like to make a PR a patch to allow using those values from the request's header as I mentioned. I've tested my code and it works as I intended.  So, I can make PR as soon as I approved.

If you have any questions regarding this issue. Please reply to this issue.

Regards, 

Edit: Just to clarify, the following functions are affected by this issue:

- `smart-home-provider/cloud/auth-provider.js`
  * `handleAuthCode`
  * `app.all('/token')`

**Comment by Fleker** [comment]
How do your auth changes work? Does the sample still work whether or not the box is checked?

**Comment by itpcc** [comment]
`How do your auth changes work? `

I just create a function to decode Authorization string (if it was submitted). Then, allow `clientId` & `clientSecret` to take value from that header **if the value submit via neither query string nor request body.** So, if Google submits a value from either one of those, it should work just like the good old day!

`Does the sample still work whether or not the box is checked?`

I tried to uncheck and save the config. Unfortunately, Google still submits those value via header. So, I don't think unchecking work.

**Comment by Fleker** [comment]
You may need to re-enable testing to verify that unchecking stops submitting the value (or maybe there's a bug). It looks like you may be handling both cases already though, which is good.

The PR can be useful in the short-term. We're going to be refactoring the sample soon, which will have some implications for this change, so it depends if you'd want to do it now or rebase it later.

**Comment by itpcc** [comment]
Yeah, as I mentioned earlier, even when I uncheck that option, Google still submits value via header. 🤔
![image](https://user-images.githubusercontent.com/3356814/55240516-9cf83000-526b-11e9-8f54-345a8b7f0eb9.png)

Since I already finish the code patching, I'll make a PR just to make sure it won't make some headache in the future.

Thank you for your attention.
