### ISSUE TITLE
OpenClose for blinds not working properly since yesterday's NLP update

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#321]
Hi There,

we are rolling out to sell massiv bundles with Google Home mini and our products to customers next week in germany, austria and switzerland, but we have currently 1 usability experience bug for voice recognition for german language.

You updated your NLP (natual Language Processing) yesterday.

Now Google can differentiate in german between a 
"blind" - german synonym - "Jalousien"
 and a 
"roller shutter" (not working in english) - german synonym - Rollladen
 (roller shutter has currently no icon):

![grafik](https://user-images.githubusercontent.com/47858747/55230192-57157a80-521f-11e9-84e1-b450bdf7ffd6.png)

the keyword for type "blind" is working properly. I can say "_Ok Google, open the blinds_"
But the keyword to identify a "roller shutter" is only working, if you use the word "all" within the sentence: "_Ok Google, öffne < **alle** > Rollläden_"

![grafik](https://user-images.githubusercontent.com/47858747/55230540-677a2500-5220-11e9-9c1e-395e449ca8f0.png)

You need now to use the word "all" to open it with "Rollladen".
It should work also without the word "all" like the same way as with "Jalousien".

Could you fix this issue? It's very important

**Comment by Fleker** [comment]
What is the device type of your roller shutters? The docs don't have a type for shutters, so if they're all using the BLINDS type, I'm not sure why the icon would be different.

If you're working with Google support on this implementation, you may want to consult them directly for support.

**Comment by proppy** [comment]
Closing as obsolete.
