### ISSUE TITLE
Channel Trait for Smart Remote

### ISSUE THREAD

**Issue by gesaracino** [actions-on-google/smart-home-nodejs#323]
Hello,
I would like to have a public documented action.devices.traits.Channel trait for smart ir remote controls

**Comment by Fleker** [comment]
I'll file a feature request internally.

**Comment by gesaracino** [comment]
Hi Fleker,
is there any update? :-)

**Comment by RouNNdeL** [comment]
The channel trait already exists, however it's not listed in the official documentation. See: https://github.com/actions-on-google/smart-home-nodejs/issues/253#issuecomment-451878240. You can also check out my DIY implementation of different Smart Remote traits here: https://github.com/RouNNdeL/smart-home/blob/master/includes/devices/IrRemote.php

**Comment by Aymkdn** [comment]
Do you know what is the voice trigger? I tried the same ones as Alexa but no luck. I tried in both English and French... "OK Google, change channel to 200 on device"

**Comment by RouNNdeL** [comment]
A simple "Hey Google, change the channel to 200 on the TV" works for me. Maybe you need to implement the device as `action.devices.types.REMOTECONTROL` for the trait to work properly

**Comment by Aymkdn** [comment]
Thanks, I'll try that !

**Comment by RouNNdeL** [comment]
I haven't done a `SYNC` for quite a long time now. I hope that after they secured the unofficial docs they didn't somehow disable those traits as well. Let me know if it works for you.

**Comment by gesaracino** [comment]
"Go channel <channel number> on <name of the device>"
"Switch to <channel number> on <name of the device>"

Both work for me

**Comment by RouNNdeL** [comment]
Just to add to the available phrases: 
"Next channel on _device_" and "Previous channel on _device_" send a `action.devices.commands.relativeChannel` action.

After you've mentioned the device you can also omit its name and just say "Next channel".

**Comment by Fleker** [comment]
Moving this issue to the public bug tracker: https://issuetracker.google.com/issues/136103830

**Comment by RouNNdeL** [comment]
@Fleker, are we supposed to open new issues no the public tracker?

**Comment by Fleker** [comment]
The public bug tracker will be a better place for platform issues/requests going forward, while this issue tracker can be geared more towards issues with the sample.
