### ISSUE TITLE
ColorSetting states used in report state 

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#324]
Hi,

When we use https://smart-home-test-suite.firebaseapp.com/ to test the report test. We failed to pass the color temperature and color report state tests. We found out that in order to pass the test, we need to use the deprecated ColorSpectrum and ColorTemperature state: 
spectrumRGB instead of spectrumRgb,
temperature instead of temperatureK.

Which is quite confusing, since we use colorsetting trait and in colorsetting trait's page it clearly says States are spectrumRgb and temperatureK. But nowhere say we should use spectrumRGB and temperature as state's key in Report State. 

Can google clarify that what state's key should be use for report state for colorSetting trait? Since the 3rd-party lab would charge if two tests are failed, so we don't want to submit the test before there is still something uncertain.

Cheers.

**Comment by Fleker** [comment]
There is a note in the [ColorSetting documentation](https://developers.google.com/actions/smarthome/traits/colorsetting#sample-query-request-and-response):

> Note: When using Report State for the ColorSetting trait, the state names must be capitalized as spectrumRGB and spectrumHSV.

We should update the page to note temperature as well.

**Comment by izone-airstream** [comment]
Thanks Nick, got it.
