### ISSUE TITLE
Color Name of ColorSetting in Report State

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#325]
Hi,
When sending the report state for colorsetting trait, we send both spectrumRGB and name of the color. But we check the homegraph, only spectrumRGB is set, there is no color name even we submit that. 
But from Nick's Medium blog, I do see there was color name in homegraph.  

Cheers.

**Comment by Fleker** [comment]
Can you provide the payload that you're sending, as confirmation?

**Comment by izone-airstream** [comment]
Sure. We use gRPC. The report sent was:

Report state request:
request_id:"e044c417-f3fb-40ef-8762-131c9b67cb9e" 
agent_user_id:"xxx" 
payload:<
  devices:<
    states:<
      fields:<key:"lamps38" value:<
        struct_value:<
          fields:<key:"brightness" value:<number_value:100 > > 
          fields:<key:"color" value:<
            struct_value:<
              fields:<key:"name" value:<string_value:"Blue" > > 
              fields:<key:"spectrumRGB" value:<number_value:255 > > 
          > > > 
          fields:<key:"on" value:<bool_value:true > > 
          fields:<key:"online" value:<bool_value:true > > 
        > > > 
      > 
    > 
>

Report state result: 
request_id:"e044c417-f3fb-40ef-8762-131c9b67cb9e"

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
