### ISSUE TITLE
ReportState for OpenClose Trait not working?

### ISSUE THREAD

**Issue by mikevlz** [actions-on-google/smart-home-nodejs#326]
Hi, We have a door-window sensor. I've found that the most suitable is the TYPE: BLINDS  and the TRAIT OpenClose with queryOnlyOpenClose attribute.
So, I sync this sensor with 
 **openDirection: "OUT"
 queryOnlyOpenClose: true**
I've also managed to report state of the sensor upon device update(i.e. door opens -> openPercent => 100, openDirection: "OUT". The result of request is 200/OK status, but SMART HOME application shows nothing about the state of the sensor, neither dashboard app shows any updates on the device in home-graph. On the other hand, if I send state of the plug, I see it in the dashboard. I can tell more, that if I send state for both plug/socket and door sensor - only plug seems to get updated in home-graph.
The question is how to check the state of "BLINDS"? 

device state is reported as follows:
{'967': {'openState': {'openPercent': 100, 'openDirection': 'OUT'}}}
Seems like a valid JSON for OpenClose trait.
Another question on ReportState is, whether I should see all data in Google SmartHome app on Android phone.
I have a switch with embedded thermometer and humidity sensor. I sync it as a SWITCH with OnOff and TemperatureSetting traits. It also gets queryOnlyTemperatureSetting  attribute. I see current temperature in dashboard but not in app. I can control it as a switch, so that it turns on connected equipment. documentation says that I can mix traits as long as I implement correct sync/state/exec answers.  So I wonder if i should see current temperature or humidity in Google Home App

**Comment by Fleker** [comment]
I'll look into the reporting issue. Can you query the state with a regular query successfully?

With regards to your question about the mobile app, you can take a look on our documentation for [touch controls](https://developers.google.com/actions/smarthome/create#touch-controls). Not every type/trait is supported as a graphical interface.

**Comment by mikevlz** [comment]
Thanks for reply.
As for second part:
```
            {
                "id": "845",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.TemperatureSetting",
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "name": "mia_room"
                },
                "willReportState": true,
                "roomHint": "Doors at WORK",
                "attributes": {
                    "queryOnlyTemperatureSetting": true,
                    "temperatureUnitForUX": "C",
                    "availableThermostatModes": "off,on"
                }
            },
```
The docs state that touch controls are supported for SWITCH(it is SWITCH, yeah!) and for OnOff/TemperatuerSetting traits(It is OnOff/TemperatureSetting). Should work, but it doesn't. It displays button for OnOff trait, but it doesn't show Temp/Humidity.
As per BLINDS: it is synced:
``` 
{
                "id": "967",
                "type": "action.devices.types.BLINDS",
                "traits": [
                    "action.devices.traits.OpenClose"
                ],
                "name": {
                    "name": "Датчик двери на столе(Недоступно более 48 часов)"
                },
                "willReportState": true,
                "roomHint": "Коридор",
                "attributes": {
                    "queryOnlyOpenClose": true,
                    "openDirection": "OUT"
                }
            },
```
QUERY with Postman locally with device 967 OPEN:
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "payload": {
        "devices": [
            {
                "967": {
                    "openState": {
                        "openPercent": 100,
                        "openDirection": "OUT"
                    }
                }
            },
            {
                "1014": {
                    "openState": {
                        "openPercent": 0,
                        "openDirection": "OUT"
                    }
                }
            }
        ]
    }
}
```
The same with closed:
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "payload": {
        "devices": [
            {
                "967": {
                    "openState": {
                        "openPercent": 0,
                        "openDirection": "OUT"
                    }
                }
            },
            {
                "1014": {
                    "openState": {
                        "openPercent": 0,
                        "openDirection": "OUT"
                    }
                }
            }
        ]
    }
}
```
I don't see any query in webserver logs, when I select blinds control(open-close sensor).

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
