### ISSUE TITLE
Removing last device from smart home un-link the accont

### ISSUE THREAD

**Issue by affanshahab** [actions-on-google/smart-home-nodejs#327]
We are developing smart home application and user is able to sync/query/execute. Whenever new device is added or removed, we call requestSync from backend to sync the googleAssistant with latest data. Removing last device also un-link the user account. We have noticed adding a new device after removing the all devices doesn't reflect changes on googleAssistant. User has to link the account again to get latest data.

**Comment by affanshahab** [comment]
Proving further findings on it: 
DISCONNECT intent handler doesn't get called when this happens

**Comment by affanshahab** [comment]
@Fleker any update on this?

**Comment by Fleker** [comment]
This is the current behavior.

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the
content of this GitHub repository.

For filing developer bugs and feature requests with the Actions on Google Smart
Home platform, please follow the instructions at https://developers.google.com/assistant/smarthome/support.
