### ISSUE TITLE
Help needed for implementing reportStateAndNotification

### ISSUE THREAD

**Issue by affanshahab** [actions-on-google/smart-home-nodejs#328]
We are developing smart home application where user send the EXECUTE command and server process it. Our devices takes time to process the request which is unknown and can take from a second to 5 minutes. We return the response immediately with status PENDING. How can we send the notification to googleAssistant upon success or completion of request? We are already reporting state to homegrapgh but it doesn't intimate the user immediately. I came across [this part of documentation](https://developers.google.com/actions/reference/smarthome/rest/v1/devices/reportStateAndNotification) but unable to understand how can we implement it with actions-on-google library? Even if we follow HTTPS calls, how do we get followup token and evenId?

**Comment by izone-airstream** [comment]
If your server process it, when the process it completed, you can update to homegraph. The request-id is for each session, I think the key is you keep your agent-user-id in the life of your server process, so you can know which agent-user-id's data needs to be updated.

**Comment by affanshahab** [comment]
@izone-airstream we do that. But the main problem still there. Reporting state to homegraph doesn't send notification to google-assistant that task has been completed. It just saves the data and return to user when queried. So basically its a PULL not PUSH. How can I push it after 2 minutes to user that the command they executed has been successfully completed.

**Comment by izone-airstream** [comment]
AFAIK, there isn't any in smart home. You may need to write your own actions/applications to do that.

**Comment by affanshahab** [comment]
@izone-airstream I think so too, but check [this ](https://developers.google.com/actions/reference/smarthome/rest/v1/devices/reportStateAndNotification) part of documentation, it appears that this is what I am trying to do but I am unable to find any example or guide whatsoever

**Comment by izone-airstream** [comment]
Em, interesting. Then just try to send something in notification's payload, to see what happens.

**Comment by affanshahab** [comment]
I think of that too, but unable to find example for notification object? What data that notificiationObject must/should contain and in which format? and where do I get followupToken?

**Comment by Fleker** [comment]
If you want to push the state to the home graph, you should use report state. This will not produce a visible or audible notification to the user however.

The full gRPC method is called `reportStateAndNotification`, but the notification part is only available to a handful of partners so we have omitted creating any examples of its usage. (As per #189) As such, we only talk about the reportState side of the method.

**Comment by affanshahab** [comment]
Hello @Fleker , thanks for responding. I get that.

Can you please guide me a little, if this is even possible in anyway? using gPRC whatsoever. If yes, how is that? Appreciate your time

**Comment by Fleker** [comment]
I really don't think you can use it, just a handful of explicitly enabled projects.

**Comment by affanshahab** [comment]
How to get ourselves enabled as well? Who should we write this application to?

**Comment by Fleker** [comment]
This is only for a handful of partners, and it's not an open access program.

**Comment by affanshahab** [comment]
Alright, thanks
