### ISSUE TITLE
Additional Request for smart light product

### ISSUE THREAD

**Issue by benobell** [actions-on-google/smart-home-nodejs#329]
Hi,
thanks so much for your previous help with related #268.

I would now like to request an addition to the custom mode names and settings names that we had previously asked for in #268.

Please add "St Patrick's", "St Patrick's Day" to the current synonyms for the voice to work (note apostrophe is required). 
and also I would like to add "Canada Day" with additional synonym "Canada"

best regards
beno bell
Senior Software Engineer
Creativity, Inc.

**Comment by Fleker** [comment]
Submitted the change. It should be available a couple of days.
