### ISSUE TITLE
Trait to set speed/levels

### ISSUE THREAD

**Issue by benobell** [actions-on-google/smart-home-nodejs#330]
Hi,
I am in need of a smart home "speed" trait that I can invoke using a phrase such as 
"Alexa set the smartlights to speed 5" 
This is to control the "effect speed" of the smartlights.

I have speed values of 1 -> 10.
I was not able to get the fanspeed trait to work for this functionality. It appears others have also tried and failed based on online searches.
Instead I added the synonyms "one" -> "ten" into an existing custom mode "effects"
so now I have "Alexa set the smartlights to effect one" 
The above utterance works BUT for only for the numbers one -> four. 
I do not know why the other numbers (6->10) are not being recognized.
Is it possible to have utterance:
"Alexa set the smartlights to speed one"  (one through ten) or something similar?

Please advise.

best regards
beno bell
Senior Software Engineer
Creativity, Inc.

**Comment by Fleker** [comment]
Is this for Alexa or Google Assistant?

Synonyms "one" to "four" do exist for Google Assistant right now as mode settings (and "five" and "six" should be available soon as per #317). Is there a specific reason why the FanSpeed trait does not work as expected?

**Comment by benobell** [comment]
Hi Nick,
Google assistant. 
I tried using the fan trait but it didn't work and gave no indication why not. I checked the user groups and seemed other had difficulties too and I did not find any solution. A working example would help. 
Please note type is a light not a fan. Could that be the issue?

Anyway I need to set a speed for the light effects at speeds 1->10. 
I will gladly use fanspeed if I can get it to work.
The desired utterance would be something like "Ok Google, set Noma light to speed five"

**Comment by benobell** [comment]
Hi Nick,
So here's my OnSync. pasted at end of this (I removed the end section with custom modes).
I am able to successfully trigger slow, medium and fast. (Yay!)
But the numbers don't work. and increase/decrease are not working either. 
I'm looking to have the ability to select 1 -> 10 in speed settings. 

When I try the utterance "ok google set the noma light to speed 3" -" I hear "actually noma light doesn't support that functionality"
When I try the utterance "ok google increase the light speed" -" I hear "actually noma light doesn't support that functionality"
When I try the utterance "ok google set the noma light speed to slow" - correct response received = "ok setting the noma light speed to slow"


app.onSync((body) => {
  return {
    requestId: 'ff36a3cc-ec34-11e6-b1a0-64510650abcf',
    payload: {
      agentUserId: '123',
      devices: [{
        id: 'nomalight',
        type: 'action.devices.types.LIGHT',
        traits: [
              'action.devices.traits.OnOff',
              'action.devices.traits.Brightness',
              'action.devices.traits.ColorSpectrum',
              'action.devices.traits.Modes',
              'action.devices.traits.FanSpeed'
        ],
        name: {
          defaultNames: ['Noma Light'],
          name: 'Noma Light',
          nicknames: ['Noma Light']
        },
        deviceInfo: {
          manufacturer: 'Gemmy',
          model: 'smartlight',
          hwVersion: '1.0',
          swVersion: '1.0.1'
        },
        
        willReportState: false,
        
        attributes: {
          pausable: false,
          colorModel: 'rgb',

availableFanSpeeds: {
  speeds: [{
    speed_name: 'S1',
    speed_values: [{
      speed_synonym: ['slow', 'one', '1'],
      lang: 'en' }  
      ]
    },
    {
    speed_name: 'S2',
    speed_values: [{
      speed_synonym: ['two', '2'],
      lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S3',
      speed_values: [{
        speed_synonym: ['three', '3'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S4',
      speed_values: [{
        speed_synonym: ['four', '4'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S5',
      speed_values: [{
        speed_synonym: ['medium','five', '5'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S6',
      speed_values: [{
        speed_synonym: ['six', '6'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S7',
      speed_values: [{
        speed_synonym: ['seven', '7'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S8',
      speed_values: [{
        speed_synonym: ['eight', '8'],
        lang: 'en' } 
      ]
    }, 
    {
      speed_name: 'S9',
      speed_values: [{
        speed_synonym: ['nine', '9'],
        lang: 'en' } 
      ]
    }, 
{
      speed_name: 'S10',
      speed_values: [{
        speed_synonym: ['fast', 'ten', '10'],
        lang: 'en' } 
      ]
    }, 
  ],
  ordered: true
},
reversible: false,

**Comment by Fleker** [comment]
Okay I can reproduce this and have filed a bug on it.

**Comment by benobell** [comment]
Hi Nick,
Any update on this? 
We are currently failing certification due to this problem (and one other issue).

**Comment by Fleker** [comment]
I currently do not have an update.

**Comment by VeegY** [comment]
Hey Nick, hey @benobell ,
Is there any update on this? Did you find a workaround? 
Im currently in the in the same process of certification and I am not able to get fanSpeed to work. 
I do also use numbers and get the same response  ("...doesn't support that functionality.")
If providing insight to my problems may help this bug, please let me know.
Any help appreciated!

**Comment by Fleker** [comment]
We're aware of this limitation.

**Comment by nicklasbring** [comment]
Any news ? 
I have the same problem

**Comment by devunwired** [comment]
Closing this issue as the original poster has been inactive and it's not related to the content of this GitHub sample. To report a bug or feature request with the Actions on Google Smart Home platform, please use the [Google Smart Home](https://issuetracker.google.com/issues/new?component=655104&template=1284148) public issue tracker.

For development support questions, please post on our community forums:
- Reddit: https://www.reddit.com/r/GoogleAssistantDev/
- StackOverflow: https://stackoverflow.com/questions/tagged/google-smart-home
