### ISSUE TITLE
Add custom mode "EVAP"/"Evaporator" for thermostat

### ISSUE THREAD

**Issue by sandhu-ken** [actions-on-google/smart-home-nodejs#331]
Hi,
I am working on creating google actions for a thermostat  device that supports following modes:
evap/on/off/heat/cool/program/thermo/manual/vent/boost/mid/econ/fan

Some of these are already available in availableThermostatModes, some others in custom mode settings under availableModes. Can I get the missing modes (evap/program/thermo/vent/mid/econ) added so that I can use them?
Regards,
Ken

**Comment by Fleker** [comment]
Can you elaborate on what some of those modes are meant to be?
