### ISSUE TITLE
Open/Close "Open Cover" working "Cover Open" is not working

### ISSUE THREAD

**Issue by pergolafabio** [actions-on-google/smart-home-nodejs#332]
Hi, see comment here, in HA they are making use of this new trait

https://github.com/home-assistant/home-assistant/issues/22740#issuecomment-481123355

The following Google Assistant commands work fine:
Open bedroom blinds - ok
Close bedroom blinds - ok
Bedroom blinds down - ok
Bedroom blinds up - ok
Bedroom blinds close - ok

The following Google Assistant command doesn't work:
Bedroom blinds open - Sorry, there was an error for the Bedroom blinds.

is this an issue on google side or in the code?

thnx for info

**Comment by pergolafabio** [comment]
created also a ticket for the "covers open" here : 

https://github.com/home-assistant/home-assistant/issues/22740#issuecomment-481123355

**Comment by pergolafabio** [comment]
Hey, already an update for this?

**Comment by Fleker** [comment]
Not at the moment.

**Comment by pergolafabio** [comment]
ok, but is it confirmed as a grammer or you dont know it yet? can be maybe caused on our side with wrong coding?

**Comment by pergolafabio** [comment]
owke, thnx in advance

**Comment by Fleker** [comment]
When I try this, I don't see it failing, but it does seem to think that I am closing the device.
