### ISSUE TITLE
Scenes not listing in home app

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#335]
Hi Fleker
It seems like the scene's are not getting listed in google home app. During the discovery response i'm giving the type as "action.devices.types.SCENE" which i think is an inbuilt type supported by google. How can i debug this issue??

**Comment by raju102** [comment]
"type": "action.devices.types.SCENE",
                        "traits": [
                          "action.devices.traits.Scene"
                        ],

This is the response that we are giving to google.

**Comment by FelipeGalante** [comment]
Could you please post the full JSON sent by your action to Google?

**Comment by devunwired** [comment]
This question does not seem related to the Node.js sample code in this repository. Please direct any general development questions regarding the smart home platform to the `google-smart-home` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home).

**Comment by veonua** [comment]
https://issuetracker.google.com/issues/139412509
