### ISSUE TITLE
Arm/Disarm trait, new PANEL device

### ISSUE THREAD

**Issue by hankdesu** [actions-on-google/smart-home-nodejs#337]
Hi, I got some implementation on conversation actions, it's about talk to invocation to **arm/disarm**,
but I also want to implement on smart home actions, so that I could directly say arm/disarm the panel, I got a list from [here](https://github.com/actions-on-google/smart-home-nodejs/issues/253#issuecomment-450634033), but it looks like undocumented and also can't knew any other information about **action.devices.traits.ArmDisarm**, Hope that trait and type will be added in the near future
Thanks.

**Comment by Fleker** [comment]
What is a "panel" in this context?

**Comment by hankdesu** [comment]
Like a control center, when panel is arm mode, it will trigger several devices like door detect sensor, camera into detection mode, if someone detected by these devices, panel will know it, and ring the  alarm bell which inside the panel, and if we could implement two way authentication on these new trait/type, that would be great, like if user want panel to be arm mode, user must tell assistant the pin code.
Thanks!

**Comment by DewGew** [comment]
Its already working.
I use "action.devices.traits.ArmDisarm" with two way authentication with pin and "action.devices.types.SECURITYSYSTEM" and it works great in english. On ly thing missing is touch control in google home app.

**Comment by hankdesu** [comment]
@DewGew Could you provide how you implement it, and if I want to submit these actions with undocumented traits and types for production, it would be ok?

**Comment by hankdesu** [comment]
@DewGew , Did you ever use type/traits SCENE to implement two factor authentication with pin?
Because I  encounter some difficulties, When I talk to google home to start the mode, The  expectation of response should be  'Can I have your security code' , but  my google home just disappear, nothing happen, I don't know why, but ackNeeded is work, and if I use another traits, after I said my pin like '1234', smart home actions didn't  call my fulfillment api to do EXECUTE commands second time, Thanks!
