### ISSUE TITLE
get token id when request EXECUTE command

### ISSUE THREAD

**Issue by haydoiday228** [actions-on-google/smart-home-nodejs#339]
I have a problem with google home project.
I can controller all devices but how to know the account is request EXECUTE command? I don’t see google home send token id?
Please help me!

**Comment by Fleker** [comment]
As part of the request, you'll receive an access token for the provided user as part of the OAuth implementation. You can use the access token to get the user identifier.

**Comment by haydoiday228** [comment]
Firstly, I thank you very much.
But when I request using voice, example: turn on the living room light.
Google assistant only send me body value such as:
{
    "inputs": [
        {
            "context": {
                "locale_language": "en"
            },
            "intent": "action.devices.EXECUTE",
            "payload": {
                "commands": [
                    {
                        "devices": [
                            {
                                "id": "HRRSH0000000000033c71bf059588"
                            },
                            {
                                "id": "HRRSH0000000000033c71bf0597e0"
                            }
                        ],
                        "execution": [
                            {
                                "command": "action.devices.commands.OnOff",
                                "params": {
                                    "on": true
                                }
                            }
                        ]
                    }
                ]
            }
        }
    ],
    "requestId": "15344660332271691735"
}

how to get token id?
thank you!

**Comment by Fleker** [comment]
In addition to the request body, you will get request headers.

**Comment by haydoiday228** [comment]
I using 
console.log("DATAevent.headers: " + event.headers); and  console.log("DATAevent.headers: " + JSON.stringify(event.headers)); functions. It result 
DATAevent.headers: undefined and DATAevent.headers: undefined.
how to get it, please help me. thanks you

**Comment by Fleker** [comment]
What is an `event` in this context? You should be getting request headers in addition to a request body.
