### ISSUE TITLE
Uable to get SYNC request after successfull account linking : stackdriver error SYNC: Request ID 8548661928849770471 failed with code: INTERNAL_ERROR 

### ISSUE THREAD

**Issue by Lxido** [actions-on-google/smart-home-nodejs#340]
the console stackdriver  log is this :+1: `{
 insertId:  "1lzw0tcg2xlyxvv"  
 logName:  "projects/testsmarthome-648a6/logs/actions.googleapis.com%2Factions"  
 receiveTimestamp:  "2019-04-24T13:36:50.274761403Z"  
 resource: {
  labels: {
   action_id:  "SMART_HOME_SYNC"    
   project_id:  "testsmarthome-648a6"    
   version_id:  ""    
  }
  type:  "assistant_action"   
 }
 severity:  "ERROR"  
 textPayload:  "SYNC: Request ID 8548661928849770471 failed with code: INTERNAL_ERROR"  
 timestamp:  "2019-04-24T13:36:50.265392966Z"  
}`
2.my server can't receive any SYNC request ,after successfull account linking
3. is my android system error? make the INTTERNAL_ERROR flag?
4. i try many times! but the stackdirver log alway the same result;

**Comment by Lxido** [comment]
## the console stackdriver log is this 
` { insertId: "1lzw0tcg2xlyxvv" 
logName: "projects/testsmarthome-648a6/logs/actions.googleapis.com%2Factions" receiveTimestamp: "2019-04-24T13:36:50.274761403Z"
 resource: 
      {
            labels: { action_id: "SMART_HOME_SYNC" project_id: "testsmarthome-648a6" version_id: "" 
      }
 type: "assistant_action" } 
severity: "ERROR"
 textPayload: "SYNC: Request ID 8548661928849770471 failed with code: INTERNAL_ERROR" timestamp: "2019-04-24T13:36:50.265392966Z" 
}
`
## my server can't receive any SYNC request ,after successfull account linking
## is my android system error? make the INTTERNAL_ERROR flag?
## i try many times! but the stackdirver log alway the same result;

**Comment by Lxido** [comment]
can  anybody help me,?

**Comment by Fleker** [comment]
Is there an issue with your fulfillment URL that may mean that it is not being called, or maybe an issue getting an authorization token?

**Comment by Lxido** [comment]
yeah ！ thanks。。the reason is my repsonse of authorization token is wrong，should be json，but i return  header 302 redirect

**Comment by Lxido** [comment]
i got SYNC request now

**Comment by Lxido** [comment]
but request body is null，should be this
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "inputs": [{
      "intent": "action.devices.SYNC"
    }]
}
```
but i got nothing

**Comment by Lxido** [comment]
![image](https://user-images.githubusercontent.com/17773920/56778329-52d18280-6808-11e9-9c1b-3fca26b54410.png)

**Comment by sky9971** [comment]
I'm also facing the same issue while trying to link account, below is the stackdriver log

`{ 
 insertId: "1ubusoyg3tiik82"   
 logName: "projects/mansaa-smart-home/logs/actions.googleapis.com%2Factions"   
 receiveTimestamp: "2019-04-26T08:38:31.552561849Z"   
   resource: { 
    labels: { 
   action_id: "SMART_HOME_SYNC"     
   project_id: "mansaa-smart-home"     
   version_id: ""     
  } 
  type: "assistant_action"    
 } 
 severity: "ERROR"   
 textPayload: "SYNC: Request ID 18265477000653367970 failed with code: INTERNAL_ERROR"   
 timestamp: "2019-04-26T08:38:31.520518688Z"   
}`


Also on the google home app, after account linking the assistant handoff shows 
> account linking failed
@Fleker can you please look into this as well and suggest what is going wrong?

**Comment by Lxido** [comment]
@sky9971  i fix that question！i know the reason，but now i have another question

**Comment by sky9971** [comment]
@Lxido can you please guide me out of this?
here's my email akash@mansaa.io

**Comment by Lxido** [comment]
@sky9971 
# the reason is response is wrong！，the repsones of token request is json，json format is like that
 ```
{ 
 "access_token":"'.$token.'",  
 "refresh_token":"'.$token.'",  
 "id_token":"dmcxd329ujdmkemkd349r", 
 "token_type":"Bearer",  
 "expires_in":3600 
}; 
```

**Comment by Lxido** [comment]
you should check your responses @sky9971

**Comment by Lxido** [comment]
now i got another question.
when i get the Sync request or  devices.Query. i found the request post body is null, i can't get post data,because it just nothing

**Comment by Lxido** [comment]
![image](https://user-images.githubusercontent.com/17773920/56796234-ae216600-6844-11e9-8a1b-82ff5d7ba2a2.png)
# now  you can seee the POST is null.
# it's my talk to google assistent 'turn off the light'
# i get the request from google home.but POST data is null,i can't how to do next,just get the request

**Comment by sky9971** [comment]
@Lxido I did checked my token endpoint and verified the response. the response is in json format.
Are you sure it is because of token response?

**Comment by Lxido** [comment]
@sky9971 now i get sync request after chage the json response .

**Comment by Lxido** [comment]
so i think question is the json response;

**Comment by sky9971** [comment]
@Lxido  @Fleker 
I tried to link the action from two different phones first from nexus 5 and second from iPhone 6.
iPhone app shows "Mansaa Smart Home Linked" in the toast at the bottom of the screen but does not show any devices whereas the android app shows "account linking failed" in the assistant handoff screen.
A little brief intro to what I'm doing
My authroization url is something like : www.xyz.com/auth
As the actions calls this url for oauth setup, it is redirecting to my login page on www.abc.com/login with the help of location header 302 status code.
I the user is able to login and generate auth grant code. I'm passing that to Google's actual redirect url when the user clicks on authorize button.

**Comment by Fleker** [comment]
If you're having account linking questions, then you should investigate account linking issues as that issue is different from the original issue here.

@Lxido how do you know the request is coming from the Google Assistant if the request is empty?

**Comment by sky9971** [comment]
Hi @Fleker  I got your point but I am also getting the sync request failed with internal_error code.
I'll also look into investigating account linking, but for the mean time can you please help me with this internal_error code in sync request? In understanding what is the causing this?

**Comment by Fleker** [comment]
Account linking occurs before any other requests like SYNC are made. If account linking does not work, then that's the first point to start.

**Comment by Lxido** [comment]
@Fleker  the device list is already add the` google home`。
### i try to trigger the `turn on` the device command，then my backend  received the request and `print the original data`，and found  that the request content is `empty`。
### as shown int the screenshot above

**Comment by Lxido** [comment]
- ![image](https://user-images.githubusercontent.com/17773920/56842661-49105380-68ca-11e9-936b-5b1c42fd992b.png)
- i sync the devices list or turn on the device was all trigger this uri。
- then my backend receive the request is empty，not just like official example：
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "inputs": [{
        "intent": "action.devices.SYNC"
    }]
 }
```

**Comment by Lxido** [comment]
i can receive all trigger request,for example,sync devices turn on device ,turn off device,but backend always got those request is empty

**Comment by Lxido** [comment]
- original header
```
  ["header"]=>
  array(9) {
    ["https"]=>
    string(2) "on"
    ["host"]=>
    string(21) "api-de.ifanscloud.com"
    ["connection"]=>
    string(5) "close"
    ["content-length"]=>
    string(3) "386"
    ["content-type"]=>
    string(30) "application/json;charset=UTF-8"
    ["google-assistant-api-version"]=>
    string(2) "v1"
    ["authorization"]=>
    string(39) "Bearer 9ef2dbb95aed2a6a0346f04b6a104fc2"
    ["user-agent"]=>
    string(85) "Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)"
    ["accept-encoding"]=>
    string(15) "gzip,deflate,br"
  }
```
- request content is
```
  ["request"]=>
  NULL
  ["cookie"]=>
  NULL
  ["get"]=>
  NULL
  ["files"]=>
  NULL
  ["post"]=>
  NULL
  ["tmpfiles"]=>
  NULL

```

**Comment by Lxido** [comment]
@Fleker can you help me ,thanks

**Comment by Fleker** [comment]
It's not clear what's happening here, as you definitely should be getting a request body. I think there should be some other parameter you should be accessing. What language/framework are you using?
