### ISSUE TITLE
how can i get the user profile   during account linking 

### ISSUE THREAD

**Issue by Lxido** [actions-on-google/smart-home-nodejs#342]
- during the oauth process
- how can i get the google user profile 
- like this：
- ![image](https://user-images.githubusercontent.com/17773920/56857975-f86e2880-69a5-11e9-88d9-1acbbfddc214.png)

**Comment by Lxido** [comment]
- There are two processes
    - Ouath and token
- I want to get the user's profile after getting the ouath request.

**Comment by Fleker** [comment]
You don't get the user's Google profile. In the smart home case, the Google Assistant acts as the client. As the client, they send requests to your server for authorization. You, as the OAuth provider, pass user profile information to the Google Assistant (the user's devices and `agentUserId`). The Google Assistant uses these to make requests.

As you are the provider, not the client, you do not get profile information back.

If you are using [Report State](https://developers.google.com/actions/smarthome/report-state), where you need a JWT, you just use a service account key, which does not require user-specific information.
