### ISSUE TITLE
new toggle name

### ISSUE THREAD

**Issue by xtconan** [actions-on-google/smart-home-nodejs#343]
we request toggle name 'Group', name_synonym like 'group trigger', 'all'.

This is function name for trigger different devices in same function together. for smart IR remote controller, like you use this toggle to make devices do the same thing in different rooms.

**Comment by Fleker** [comment]
Wouldn't such a request already be possible in the Google Assistant natively. For example, I can say "turn on all the lights" or "turn on everything in the living room" and every device will be controlled?
