### ISSUE TITLE
Two-factor authentication with pin - English not work

### ISSUE THREAD

**Issue by hankdesu** [actions-on-google/smart-home-nodejs#345]
Hi, when I implement two-factor-authentication with pin(use English), I found that no matter how I said my pin clearly, it just not work, but when I change my language to Deutsch, it work perfectly, could you help me to solve this issue?
![image](https://user-images.githubusercontent.com/20940871/56885721-b9240280-6a9f-11e9-8ea7-6e7729b01d3b.png)
![image](https://user-images.githubusercontent.com/20940871/56885764-d5c03a80-6a9f-11e9-9961-f11d8f0854e9.png)

Thanks!

**Comment by Fleker** [comment]
In English it appears to space each number out. Can you try entering the pin with a keyboard and see if that works?

**Comment by hankdesu** [comment]
Hi, I test two cases, you could view the results in below image, Both of these cases, I use keyboard to entering my pin, but it's not work, Did I correct? Or I have to modify input? Thanks for your help!
![image](https://user-images.githubusercontent.com/20940871/56939885-a233ed80-6b3d-11e9-8093-2cf3eadc455b.png)

**Comment by Fleker** [comment]
Are you using a GSuite account, or a regular Gmail account? 2FA does not work for GSuite accounts.
