### ISSUE TITLE
Synonym for Swedish "tänd" should map to turn on light

### ISSUE THREAD

**Issue by elupus** [actions-on-google/smart-home-nodejs#346]
Currently the swedish words "tänd" and "släck" map to turn on/off. The words are only valid in the context of lights.
You say: "tänd i köket" and mean "turn on lights in kitchen". It is interpreted currently as "turn on kitchen". This mean all devices turn on, when you only meant lights.

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the
content of this GitHub repository.

For filing developer bugs and feature requests with the Actions on Google Smart
Home platform, please follow the instructions at https://developers.google.com/assistant/smarthome/support.
