### ISSUE TITLE
 Report State dashboard deployment issue

### ISSUE THREAD

**Issue by pratapvivek007** [actions-on-google/smart-home-nodejs#347]
Hey Folks,
Currently I am trying to deploy the "Report State Dashboard". but while using the command (mvn appengine:deploy) I am getting the below error.
=============================
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:18 min
[INFO] Finished at: 2019-05-02T15:57:29+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project dashboard: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Can anyone help to fix this issue.
More info
1- I am using Window 10 cli to deploy
2-C:\Users\HP>gcloud --version
Google Cloud SDK 244.0.0
app-engine-java 1.9.73
app-engine-python 1.9.85
bq 2.0.43
cloud-datastore-emulator 2.1.0
core 2019.04.26
gsutil 4.38
3-C:\Users\HP>mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T00:30:29+05:30)
Maven home: C:\Users\HP\Desktop\gcp\apache-maven-3.6.1\bin\..
Java version: 10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

4- link which i am following to implement the report state dashboard (v.0.1.1)
https://github.com/actions-on-google/smart-home-dashboard/releases

**Comment by Fleker** [comment]
This is unrelated to this repo.
