### ISSUE TITLE
Routines report error with smart home devices

### ISSUE THREAD

**Issue by dominikkarall** [actions-on-google/smart-home-nodejs#348]
Hi,
I'm the developer of the "FHEM Connect" smart home action. We identified an issue when using routines to control smart home devices.

**Example (tested in German):**
German: Schalte die Kaffeemaschine ein
English: Switch on the coffee machine

That works without any issues. When I add the action to switch on the coffee machine to a **routine** it reports following error:
"Es tut mir leid, ich kann das Gerät **the** Kaffeemaschine moment nicht erreichen. Bitte versuch es später noch einmal"
"Sorry, I can't reach the device coffee machine. Please try again later"

Nevertheless, the coffee machine is switched on with the routine as well (so it works), but the reply from Google is incorrect. There is no error in the Google Assistant error log in the Google Cloud Console.

Please let me know if you need more information to fix that issue. Thanks!

**Comment by Fleker** [comment]
Is it related to a timeout issue in your fulfillment? Even if the function is successful, there's a limited amount of time that the Assistant expects the fulfillment to respond.

**Comment by dominikkarall** [comment]
No, there is no timeout. The request to my fulfillment is exactly the same as when initiated directly.

**Comment by Fleker** [comment]
But did it take a longer time to respond?

**Comment by dominikkarall** [comment]
It took 344ms to reply, that should be fine.

**Comment by Fleker** [comment]
Is this a custom routine or a ready-made routine (like Good Morning)?
Is this done through a menu toggle, ie. "Adjust lights, plugs, and more" or a direct text-based command?

**Comment by dominikkarall** [comment]
Hi Nick,
after some more investigation I found the issue...I missed to send back the device id in the JSON object. I fixed it and now it works. Sorry for bothering you and thanks for your support!
