### ISSUE TITLE
Usage and health analytics are currently unavailable for Smart Home actions.

### ISSUE THREAD

**Issue by izone-airstream** [actions-on-google/smart-home-nodejs#349]
When the usage data will be available again? Thanks

**Comment by Fleker** [comment]
Usage will be available again at a later date.

**Comment by claudiopastorini** [comment]
Is there any news regarding Usage and Health Analytics?

**Comment by izone-airstream** [comment]
Dont' know. Eventually we implement the usage analytics by ourselves.
And we also use the Google Cloud's Homegraph API metrics data to monitor the service health. see: https://console.cloud.google.com/apis/api/homegraph.googleapis.com/metrics
