### ISSUE TITLE
 how to build response data when request data get 2 intents ；for example，the request data request['intent'] :‘sync and query‘’

### ISSUE THREAD

**Issue by brewlin** [actions-on-google/smart-home-nodejs#350]
## i found the request data  is like that ：
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "inputs": [{
      "intent": "action.devices.SYNC"
    }]
}
```
## maybe when i got the request like this: how to build the response data:
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "inputs": [{
      "intent": "action.devices.SYNC"
    },{                                                          //there are  2 intent,!!! how can i  handle this
      "intent": "action.devices.QUERY"
    },]
}
```

**Comment by Fleker** [comment]
Have you ever received two intents in one request? At the moment, I've only ever seen one item within the `inputs` array.

**Comment by brewlin** [comment]
### I am a bit confused, 
### many of the requested data will only contain one` object`, like this :
```
{
    "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
    "inputs": [{
      "intent": "action.devices.SYNC"  //there is  one  intent  
    }]
   //why not this => "inputs" : {   "intent":"action.devices.SYNC"   }
}

```
but it is represented by an array.
## For example, in the screenshot above, 'inputs' will only receive an intent, but it will be represented by an array.
### Also at ‘action.devices.EXECUTE’’’
```
           "execution": [{
             "command": "action.devices.commands.OnOff",
             "params": {
               "on": true
             }
           }]
```
### There are only one operation to execute a command, but it is also represented by an array.
### Will there be multiple different `command` cases at a time?

**Comment by Fleker** [comment]
There are several instances where you'll get an array with only one entry. I've never seen one get more than one `input`.
