### ISSUE TITLE
npm run create-firebase-config -> fails

### ISSUE THREAD

**Issue by chrisjshull** [actions-on-google/smart-home-nodejs#351]
Just following the readme I tried

```
cd frontend
npm install
npm run create-firebase-config
npm run serve
```

but this fails with 

> Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add

Please improve instructions.

**Comment by Fleker** [comment]
First you'll need to create your Google Cloud project and then run `firebase use --add <project id>`.

The README will be updated.

**Comment by pratapvivek007** [comment]
I think , the README file is not instructed properly.
When I run the command as firebase use --add <project id> ,
it is erroring as firebase command is not found , 
Do we need to install firebase tool ?

**Comment by Fleker** [comment]
Yeah I added two additional steps as you will need to install firebase-tools globally through npm, ie. `npm install -g firebase-tools`, then `firebase login`.
