### ISSUE TITLE
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (webcomponents-lite.js, line 0)

### ISSUE THREAD

**Issue by chrisjshull** [actions-on-google/smart-home-nodejs#354]
Following instructions in readme, when I load the frontend in my browser I get:

> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (webcomponents-lite.js, line 0)

**Comment by Fleker** [comment]
Are you running a local version or a hosted version of the HTML?
