### ISSUE TITLE
New 'uv' toggle

### ISSUE THREAD

**Issue by cutememphiss** [actions-on-google/smart-home-nodejs#355]
I'd like to request a new toggle.
Name: uv
Synonyms: UV, UV mode

This toggle name is already appeared in an example in your Smart Home Air Purifier Guide.
But we can't actually use it.
Please add it.
Thanks.

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039) so we can track it properly.
