### ISSUE TITLE
git clone sso://devrel/samples/assistant/smarthome/frontend

### ISSUE THREAD

**Issue by pratapvivek007** [actions-on-google/smart-home-nodejs#356]
Hi Folks,
Whiling following the new readme file ( instruction) , I am unable to clone .
git clone sso://devrel/samples/assistant/smarthome/frontend

Can you guide me how can i clone it.

thanks,

**Comment by Fleker** [comment]
That's a typo. You should be cloning from https://github.com/actions-on-google/smart-home-frontend

**Comment by pratapvivek007** [comment]
Thanks @Fleker
