### ISSUE TITLE
Awning, Pergolas, Shutters no Icon (+ NLP problem)

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#357]
Hello There,

so there is now officially released the profiles awning, pergola and shutter (+blinds).

The language processing has still some problems to differentiate between shutters and blinds in english and also german.

Shutter - Rollladen
Blinds - Jalousien

If I say: "Ok Google, open shutters", it will open the blinds
If I say: "Ok Google, open the blinds", it will open the blinds
same thing for german.

Aditionally in german we have now very big problems with controlling shutters.

If you have several shutters in one room, it doesn't work at all:

"open shutters in living room" - "öffne Rollläden im Wohnzimmer" 
is not working.
Last week it was working, but had still bugs:
see issue tracker: 
https://github.com/actions-on-google/smart-home-nodejs/issues/321

![grafik](https://user-images.githubusercontent.com/47858747/57369308-8065e680-718d-11e9-919f-0b70dd3f9f3a.png)
As you can see, there is also no image for awning, pergola and shutters. Only blinds.

**Comment by Fleker** [comment]
Moving this issue to the public bug tracker: https://issuetracker.google.com/issues/136103094
