### ISSUE TITLE
Issue with close/open all shutters

### ISSUE THREAD

**Issue by zoic21** [actions-on-google/smart-home-nodejs#359]
Hello,

Since 1 or 2 week I have an issue (in french) with "ferme tous les volets"  (close all shutters) and "ouvre tous les volets" (open all shutters). 2 weeks ago it's perfectly work (I received in one request the order for each shutter). But now I have "I don't find 'all shutters' devices"...

Is it a bug ? Or it's "normal" ?

Thank in advance

**Comment by Fleker** [comment]
I have reproduced this bug.

**Comment by nopap** [comment]
Confirmed here as well. All shutters or one specific shutter, Home always replied it cannot find the device .

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the
content of this GitHub repository.

For filing developer bugs and feature requests with the Actions on Google Smart
Home platform, please follow the instructions at https://developers.google.com/assistant/smarthome/support.
