### ISSUE TITLE
Issue with thermostat increase temperature in French

### ISSUE THREAD

**Issue by bobnmt** [actions-on-google/smart-home-nodejs#360]
Hello,
I'm having an issue with the french command for increasing the temperature. 

When I ask Google "Augmente x de 2 degrés", which mean "Increase x from 2 degrees", the response is "Ok, je baisse la température de x." and send to the server the temperature with a decrease instead of the increase.

I tried in english and it works perfectly.

Thanks for the help

**Comment by Fleker** [comment]
I have reproduced this issue.

**Comment by Fleker** [comment]
This should be fixed soon.
