### ISSUE TITLE
New traits: Alarm Clock/ Timer

### ISSUE THREAD

**Issue by peterkappelt** [actions-on-google/smart-home-nodejs#361]
Hi,

lately, we were brainstorming some new products and new features.

It would be cool if there was a trait that allows to set third-party timer devices (just like Google Home's internal timer) or alarm clocks.

**Comment by Fleker** [comment]
A new [Timer trait](https://developers.google.com/actions/smarthome/traits/timer) was just launched.

**Comment by peterkappelt** [comment]
I think it wasn't there when I looked it up the last time.

Thanks a lot!
