### ISSUE TITLE
New mode request

### ISSUE THREAD

**Issue by chenliuyun** [actions-on-google/smart-home-nodejs#363]
Hi!
I'm working on action for smart fan. We have two wind mode named "Classic Wind" and"Natural Wind".So please add following mode:

name: wind mode
name_synonym: wind mode
name_synonym(ja): モード

setting_name: Classic Wind
setting_synonym: Classic Wind、Classic Mode
setting_synonym(ja): 標準モード

setting_name: Natural Wind
setting_synonym: Natural Wind、Natural Mode
setting_synonym(ja): 自然風モード

And, is there any plan to support sensor and TV  device type?
Thank you!

**Comment by chenliuyun** [comment]
Hello，any update? @Fleker 
Thanks

**Comment by Fleker** [comment]
Thanks. We have added this mode. It should be available in the next few days.

**Comment by chenliuyun** [comment]
Thanks. We have update the sync respond and tried the commands ( set xx to natural wind | nature | natural | classic mode | classic wind | classic ) , but it do not work. @Fleker

**Comment by Fleker** [comment]
It does not seem like the changes have rolled out entirely yet.

**Comment by chenliuyun** [comment]
Hi, sorry for reopen this issue.
We tried the command again, but it still do not work.
Could you confirm when this change is available.
And please provide some example phrase.
Thanks.
