### ISSUE TITLE
Timer trait on Light device

### ISSUE THREAD

**Issue by dtemes** [actions-on-google/smart-home-nodejs#364]
We are trying to use the Timer trait with a Light device but so far we always get the response that the light does not support that functionality:
- "ok google, switch on the kitchen light for one minute"
- "Actually the kitchen light doesn't support that functionality"

We are setting these traits in the sync response: ["action.devices.traits.OnOff","action.devices.traits.Timer"]

**Comment by Fleker** [comment]
Are you able to give a more generic command like "set the kitchen light timer to one minute"?

**Comment by dtemes** [comment]
Yes, same result, "Actually the kitchen light doesn't support that functionality"

**Comment by Fleker** [comment]
Can you provide your sync response for the device so that I can try to reproduce the error?

**Comment by dtemes** [comment]
This is the syn response for the device:
`{"id":"00000000FF180130FFFFFF1801300100|room-8|-LRgIxcm5deU-m9Qp-lg","type":"action.devices.types.LIGHT","traits":["action.devices.traits.OnOff","action.devices.traits.Timer"],"willReportState":true,"room_hint":"PanelNew","name":{"defaultNames":["Luz"],"name":"right light","nicknames":["right light"]},"deviceInfo":{"manufacturer":"xxxxxxx","model":"app-luz","hwVersion":"1.0","swVersion":"1.0.1"},"attributes":{"colorModel":"rgb"},"customData":{"appType":1}}`

**Comment by Fleker** [comment]
Okay, I've reproduced and filed an error internally.

**Comment by Fleker** [comment]
I tested this out today and was able to get the timer to work successfully.
