### ISSUE TITLE
POST /smarthome 500

### ISSUE THREAD

**Issue by mjoelmendes** [actions-on-google/smart-home-nodejs#365]
hi, I'm the following problem, can anyone help me?

![Capturar](https://user-images.githubusercontent.com/9480073/57785344-7f9ef880-7729-11e9-8117-efffc1c6442f.PNG)

**Comment by Fleker** [comment]
Based on the error for permission being denied, did you [download a service account key](https://github.com/actions-on-google/smart-home-nodejs#add-request-sync-and-report-state)?

**Comment by mjoelmendes** [comment]
Ok is solve  , tanks
