### ISSUE TITLE
[Error] You may specify one with an environment variable named  "GOOGLE_CLOUD_PROJECT"

### ISSUE THREAD

**Issue by guilhermelirio** [actions-on-google/smart-home-nodejs#366]
I have this error. I followed the README.

` UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
Error: Sorry, we cannot connect to Cloud Services without a project
 ID. You may specify one with an environment variable named
 "GOOGLE_CLOUD_PROJECT".`

**Comment by Fleker** [comment]
Is there more information on what command you performed or if there is a stacktrace including the code line of the error?

**Comment by guilhermelirio** [comment]
After installing gcloud, the error is this at the moment:

![60390675_368371107123364_8304501412084056064_n](https://user-images.githubusercontent.com/23419633/57858960-68631800-77c8-11e9-919a-0cdf9014ae65.jpg)

**Comment by ThigoPSI** [comment]
https://github.com/actions-on-google/smart-home-nodejs/issues/365

**Comment by guilhermelirio** [comment]
> 
> 
> #365

Yes, i have the smart-home-key.json inside src folder.

**Comment by Fleker** [comment]
I think it may be related to the Firebase initialization pointing to the default credentials while running in a local tunnel (Ngrok). Can you try the following:

Update the Firebase Admin init in `src/firestore.ts`, line 26, to:

```
const serviceAccount = require('./service-account-key.json');
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: `https://${googleCloudProjectId}.firebaseio.com`,
});
```

Then running `yarn build` and `yarn start:local` to apply the changes.

**Comment by guilhermelirio** [comment]
> 
> 
> I think it may be related to the Firebase initialization pointing to the default credentials while running in a local tunnel (Ngrok). Can you try the following:
> 
> Update the Firebase Admin init in `src/firestore.ts`, line 26, to:
> 
> ```
> const serviceAccount = require('./service-account-key.json');
> admin.initializeApp({
>     credential: admin.credential.cert(serviceAccount),
>     databaseURL: `https://${googleCloudProjectId}.firebaseio.com`,
> });
> ```
> 
> Then running `yarn build` and `yarn start:local` to apply the changes.

I'm change service-account-key.json to smart-home-key.json and ocorred this error:

`Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
`

**Comment by Fleker** [comment]
I made a typo. You should keep the filename the same (`smart-home-key.json`) and set the `serviceAccount` constant to that (`const serviceAccount = require('./smart-home-key.json');`)

**Comment by guilhermelirio** [comment]
> 
> 
> I made a typo. You should keep the filename the same (`smart-home-key.json`) and set the `serviceAccount` constant to that (`const serviceAccount = require('./smart-home-key.json');`)

Exactly what I did, and gave the above error. =/

**Comment by Fleker** [comment]
Does the error message include where this permission error is being thrown?

**Comment by Fleker** [comment]
Hang on, the service key by default doesn't have Firebase permission. You'd need to go in the console to IAM, then select the service account and give it the additional role **Firebase** > **Firebase Admin SDK Administrator Service Agent**. 

Then it should be able to read from Firestore, so then it can process the `Authorization` header, then respond to the SYNC request.

Alternatively, deploying to App Engine will be able to pull the credentials by default.

**Comment by guilhermelirio** [comment]
Works!!!

- Navigate to the [Google Cloud Console API & Services page](https://console.cloud.google.com/apis/credentials)
- Select Create Credentials and create a Service account key

  1. Select App engine default service account
  2. Rename to defaul-service-key.json and save inside `src/` folder, like this: `src/default-service-key.json`

- Change `src/firestore.ts` and replace in lines 25 to 28:

`const serviceAccount = require('./default-service-key.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: `https://${googleCloudProjectId}.firebaseio.com`,
})`

- Run `npm run build`
- Run `npm run start:local`

**Comment by Fleker** [comment]
Okay, thanks for verifying the flow. I will have to update the README.
