### ISSUE TITLE
Gunicorn 500 error

### ISSUE THREAD

**Issue by manikdutta** [actions-on-google/smart-home-nodejs#367]
Its working fine before we implemented gunicorn web server in flask rest api.
But after integrate gunicorn webserver we are getting the follwing error:

     sessions:
      { ipk0xtwr9ko00000000000000: '{"cookie":{"originalMaxAge":null,"expires":null,"secure":false,"httpOnly":true,"path":"/"}}',
        '2e5ropb3gz0g00000000000000': '{"cookie":{"originalMaxAge":null,"expires":null,"secure":false,"httpOnly":true,"path":"/"}}' },
     generate: [Function] },
  sessionID: 'ipk0xtwr9ko00000000000000',
  session:
   Session {
     cookie:
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true,
        secure: false } },
  route: Route { path: '/login', stack: [ [Object] ], methods: { post: true } } }
login undefined
Status: 500
Headers: {"server":"gunicorn/19.9.0","date":"Thu, 16 May 2019 07:49:36 GMT","connection":"close","content-type":"text/html","content-length":"290","access-control-allow-origin":"*"}
Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/src/app/smarthome/cloud/auth-provider.js:161:25)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:137:22)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)

**Comment by Fleker** [comment]
It seems like there's a problem with your Gunicorn webserver, because it's returning a 500 page. You should take a look at resolving this first. As it is returning a 500 and HTML, the JSON parsing that is performed in `auth-provider.js` fails, and causes the system to crash.
