### ISSUE TITLE
Could not load the default credentials

### ISSUE THREAD

**Issue by tungds** [actions-on-google/smart-home-nodejs#368]
I follow the guide. But when I choose a device from client, a message is : "Could not load the default credentials" throws in my server using ngrok.
I set environment to "/path/json" in windows. But the error same.

> { userId: '1234',
>   data:
>    { id: 't0e',
>      type: 'action.devices.types.LIGHT',
>      traits:
>       [ 'action.devices.traits.Brightness',
>         'action.devices.traits.OnOff',
>         'action.devices.traits.ColorSetting' ],
>      defaultNames: [ 'Smart Light 0' ],
>      name: 'Smart Light 0',
>      nicknames: [ 'table lamp' ],
>      roomHint: 'Living Room',
>      attributes: { colorModel: 'rgb' },
>      willReportState: true,
>      states: { on: false, online: true, brightness: 90, color: [Object] },
>      hwVersion: '1.0.0',
>      swVersion: '2.0.0',
>      model: 'L',
>      manufacturer: 'L',
>      deviceId: 't0e' } }
> (node:15052) UnhandledPromiseRejectionWarning: Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

And I follow by the link suggestion in error message but nothing change. 
When I deploy client. No login page is shown. And the page with choose device is shown. If I click user icon a toast "Welcome undefined" is shown.
Cound you help me?

**Comment by Fleker** [comment]
Do you download a service account key from the Google Cloud console? When adding a new device, it will try to run a Request Sync request, but does require that key to run.

The login page has been removed in recent revisions to the sample in favor of a simple pass-through of login credentials, with the implementation being rewritten to make it easier to plugin your own auth system. As such the user name is always "undefined" (that's a bug).

**Comment by tungds** [comment]
Yes. I download the service account json file and add to src/ follow your guide
![Capture](https://user-images.githubusercontent.com/5845119/57871519-b2cdae80-7833-11e9-976d-2dde0fe5f706.PNG)
But nothing change.
Then, I follow the link : https://developers.google.com/accounts/docs/application-default-credentials. But error the same.
I guess I missing somethings in my Google project. So you could view my google cloud project test for me?
Thanks!

**Comment by Fleker** [comment]
I think this is related to #366, where you need to make a change or two to the roles your service account can have, which then needs to be connected to an updated Firebase Admin initialization

**Comment by tungds** [comment]
That's right. I resolved problem by read #336 
And a bit change in index.ts to:
`jwt = require('./default-service-key.json')`

Thanks!

**Comment by SGauthamRaj** [comment]
Hi team,
I'm getting this error Error: Could not load the default credentials., how to resolve this in MAC.
Could you please help me.
