### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by mjoelmendes** [actions-on-google/smart-home-nodejs#370]
Hi, I'm using smart-home-node and smart-home-frontend.
I run smart-home-nodejs with the following npm run start command: local, do step Set up Account linking
 of your tuturial, and everything works ok, only that appears without devices.
Then I run the smart-home-frontend with the commands:
cd frontend
npm install
npm run create-firebase-config
npm run serves
then I access the http://127.0.0.1:8081/ and cycle on "+" add a device and it appears me the following error:

**EEROR:**
![1](https://user-images.githubusercontent.com/9480073/57880261-38dafc80-7816-11e9-9cd0-cf932a3d4e30.PNG)

**SERVERS:**
![2](https://user-images.githubusercontent.com/9480073/57880301-50b28080-7816-11e9-95b3-f47971202528.PNG)

![3](https://user-images.githubusercontent.com/9480073/57880308-57d98e80-7816-11e9-9c08-9d28e2b19737.PNG)

PLEASE Can someone tell me what's wrong? because I'm following the tutorial to the letter..

**Comment by Fleker** [comment]
Seems to be the same issue as in #369

**Comment by mjoelmendes** [comment]
yes no but not only now

**Comment by mjoelmendes** [comment]
moved to #369
