### ISSUE TITLE
issue with type shutter in german

### ISSUE THREAD

**Issue by AlexForReal** [actions-on-google/smart-home-nodejs#371]
Hi There,

since 2-3 days the type shutter is not working anymore in german.
Every keyword with "shutter" synonym "Rollladen, Rolladen, Rollläden" is not working.

open shutters in living room - öffne Rollläden im Wohnzimmer
Is not working anymore.

**Comment by Fleker** [comment]
If I enter "öffne Rollläden", it seems to respond with "Gerne, das gerät sink window wird geöffnet", which refers to a different device than the one I want to control. I've raised the issue internally.

**Comment by pergolafabio** [comment]
Is this resolved? I have the same in dutch... I have exposed synonyms/aliasses from Home Assistant... But I can't control those names... 
I can only control the shutter by it's actual name...

If I want to control the shutter with it's alias, it asks em to link this new smart device

**Comment by Fleker** [comment]
I don't have an update.

**Comment by pergolafabio** [comment]
but is it confirmed as a bug?

**Comment by Fleker** [comment]
We're aware of this.

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the
content of this GitHub repository.

For filing developer bugs and feature requests with the Actions on Google Smart
Home platform, please follow the instructions at https://developers.google.com/assistant/smarthome/support.
