### ISSUE TITLE
New mode request

### ISSUE THREAD

**Issue by dlabbe** [actions-on-google/smart-home-nodejs#372]
Hi!
I'm working on an action for some smart lights. We want to have some preset lighting effects.
So please add following modes:

name: movie
name_synonym: movie, film, tv

name: romantic
name_synonym: romantic, sexy

name: nightlight
name_synonym: night-light

Thank you!

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039) so we can track it properly.
