### ISSUE TITLE
Created a Google Home integration last year before requestSync was a thing

### ISSUE THREAD

**Issue by matwithonet1** [actions-on-google/smart-home-nodejs#373]
I just implemented the requestSync, which is really nice for when someone adds a new device on their account associated with my service. The bad thing is, I can't seem to find a way to force all my users to "re-sync" so that their agentUserId is now sent in my sync request. Is there something I'm missing? Is there a way to do this?

**Comment by Fleker** [comment]
Yeah if you don't have a user id for someone you can't request a sync, and there's no resync for everyone option. You'd have to ask them to relink their account or manually trigger a sync, ie. "OKG, sync my devices"
