### ISSUE TITLE
Issue with smart home test suite

### ISSUE THREAD

**Issue by KingYL** [actions-on-google/smart-home-nodejs#374]
I was testing my action using smart home test suite a few days ago, and it worked fine.But now    something is wrong with it, and there is some bug info in the web console, as follows:
```
Getting device list...
ERROR: TypeError: e is not iterable

```
it seemed that smart home test suite didnot find my devices, but actually i linked my action with Google Assistant App and got my devices.
What's more, i cannot set the device's nickname and room of this action while other actions(not belong to me) work well.
And when i built another action project with the same configurations such as fulfilment url, and everything worked well.
I didnot know what happened, and I'd like to know if it's possible that an action being testing is blocked by Google for some reasons? Can anyone help me ?

**Comment by KingYL** [comment]
Now there is no TypeError, but no request to my server after starting test the first Utterance (setup).I am confused.
Device Type: OUTLET
Device Trait: action.devices.traits.OnOff

**Comment by Fleker** [comment]
Maybe there was an error in setting the project to a test state?

**Comment by KingYL** [comment]
Update：
I saw some info in chrome's developer console, it seemed that the test suite sent a voice command 'turn on xxx(my device name)' successfully, but it did not trigger a fulfilment request to my server, while Google Assistant App could work. It looked like that the voice command was not recognized as a device command correctly...what can i do?

**Comment by KingYL** [comment]
> Maybe there was an error in setting the project to a test state? We'll look into it.

I just started test in the simulator as usual and could use the action with Google Assistant App, is there any other test state need to be set?

**Comment by Fleker** [comment]
If the simulator is enabled, then it should work. There may be an edge case with your specific device name that is causing the command to not work.
