### ISSUE TITLE
New toggle request for ja

### ISSUE THREAD

**Issue by chenliuyun** [actions-on-google/smart-home-nodejs#375]
Hi Guys, I'm working on an Fan device , could you add the swing toggles for Ja?

name    |   name_synonym
swing(en)  | swing, swing function, vane, oscillator
swing(ja)   | 首振り

**Comment by chenliuyun** [comment]
any update ? @Fleker
 And [issue 363](https://github.com/actions-on-google/smart-home-nodejs/issues/363) still can not work , could you confirm it again ? 
Thanks.

**Comment by Fleker** [comment]
The change was submitted, so I'm not sure why you cannot access it.

**Comment by Fleker** [comment]
This toggle has also be added.
