### ISSUE TITLE
my-app.js:1870 Uncaught TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#376]
![AddShutter](https://user-images.githubusercontent.com/50698561/58414476-62482380-8073-11e9-8d25-f73b88a21ffa.JPG)

**Comment by ThigoPSI** [comment]
help me

**Comment by Fleker** [comment]
How did you run into this error?

**Comment by ThigoPSI** [comment]
I found this to create new device
![AddShutter_1](https://user-images.githubusercontent.com/50698561/58627054-2eb50580-82ce-11e9-9f08-a279dde3d82c.JPG)
![AddShutter_2](https://user-images.githubusercontent.com/50698561/58627061-31175f80-82ce-11e9-90ee-232ca6a04413.JPG)

**Comment by ThigoPSI** [comment]
did you not understand?

**Comment by Fleker** [comment]
I'm investigating
