### ISSUE TITLE
 Question about google assistant

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#378]
Hey Fleker, I really like your example! but now I'd like to know how can I move to something more serious, that is, I wanted to know what I have to do to start using this as a company?

**Comment by Fleker** [comment]
The sample gives you a look at the requests and responses that you would receive on your server. For a company, you'd have to build a webhook on your server to handle these requests with valid responses.

**Comment by ThigoPSI** [comment]
so how do I put my company name on the list of names in the google home app?


I have seen the example but only allows 1 user


here is my email, for any kind of help:
ioline.ghome@gmail.com

**Comment by Fleker** [comment]
When you create a project, you can change the **Invocation Name** and fill out other details regarding your company. When your Action is ready, you can follow the [Test and submit an Action](https://developers.google.com/actions/smarthome/develop/testing-submitting) guide on submitting your Action for review.

**Comment by ThigoPSI** [comment]
Is this the only option?

**Comment by Fleker** [comment]
What other option would you want?

**Comment by ThigoPSI** [comment]
A faster option, since we are waiting for some time for the answer.

**Comment by Fleker** [comment]
You can use the [smart home test suite](https://developers.google.com/actions/smarthome/tools/smart-home-test-suite) to do an immediate verification.

**Comment by ThigoPSI** [comment]
what is the agent user id?

http://prntscr.com/nxk74x

**Comment by ThigoPSI** [comment]
Fleker I'm sorry, I'm not making myself understand.

I'm a developer of IOLine LDA. And what I want and put the company in this tab of google home, so our end customers have access to our products in google home.



![Screenshot_2019-06-05-14-15-42-690](https://user-images.githubusercontent.com/50698561/58959461-11d07480-879d-11e9-9608-0004c6cc8f63.jpeg)

**Comment by Fleker** [comment]
The agent user id is the user id on your server. If I log into your service with an email address, the agent user id might be the email address, or a unique, stable user token.

Once you pass certification, you will appear in the list.

**Comment by ThigoPSI** [comment]
After passing the verification step, what do you recommend me to do?

**Comment by Fleker** [comment]
Once you have verified your implementation works. Submit the Action for review and provide the self-certification results. The [Testing and Deploying](https://developers.google.com/actions/smarthome/develop/testing-submitting) docs provide more details on the process.

**Comment by ThigoPSI** [comment]
could you send me the link where the verification is done?

**Comment by Fleker** [comment]
You perform your own verification that it works through the [self-certification tool](https://developers.google.com/actions/smarthome/tools/smart-home-test-suite). Then you submit your Action, send the results of the certification, and the smart home team will follow up on the approval process.

**Comment by ThigoPSI** [comment]
now I understand! I'll have to make a login page right?

**Comment by Fleker** [comment]
Yes you'll need some sort of authentication.

**Comment by ThigoPSI** [comment]
Ok boss, I already created it, now the question is where to insert!

**Comment by ThigoPSI** [comment]
The example you provided is only for one user and in that case it will be for thousands of users.

**Comment by Fleker** [comment]
Replace the auth and token functions with your OAuth endpoints. Here's blog post on how you could use [Auth0](https://medium.com/google-developers/authenticating-smart-home-actions-for-the-google-assistant-with-auth0-b6fda3d2ee3d) for example.

**Comment by ThigoPSI** [comment]
sorry this link didn´t work
![Screenshot_2](https://user-images.githubusercontent.com/50698561/59048342-81b62c00-887d-11e9-87b8-d7ac39baf188.png)

**Comment by Fleker** [comment]
Medium has been having some issues this morning. The link seems to be working reliably for me now, but you may need to wait a bit longer for their service to come back up.

**Comment by FoxFireHD** [comment]
I have a question, I went through all these steps, but now I do not know what to do with the OAuth server, I have an html page where users can sign up and log in but I do not know how to proceed now!
Do you think you can help me?

**Comment by Fleker** [comment]
I'm not sure what your question is exactly. The sample and blog post show how to do part of the work in mapping access tokens to a user identifier. After that, you follow the guides to handle smart home requests.

**Comment by ThigoPSI** [comment]
Could you send me these guides?

**Comment by FoxFireHD** [comment]
Where did you get that link?
![quest](https://user-images.githubusercontent.com/51461719/59099945-8251cf80-891c-11e9-9e6f-6c627094be22.png)

**Comment by Fleker** [comment]
The blog post is [here](https://medium.com/google-developers/authenticating-smart-home-actions-for-the-google-assistant-with-auth0-b6fda3d2ee3d). You're currently in the sample, which has a [getUser](https://github.com/actions-on-google/smart-home-nodejs/blob/master/src/auth-provider.ts#L33) and [getUserId](https://github.com/actions-on-google/smart-home-nodejs/blob/master/src/firestore.ts#L38) to translate between an authorization token to a user id.

The fulfillment is something that you provide, and in my case it is a Google Cloud Function.

**Comment by FoxFireHD** [comment]
I don't know where to get the filling link, I used to get it from your example, now i placed the example link and it has an error on the ngrok

**Comment by Fleker** [comment]
Don't use the URL from the screenshot. You need to create your own fulfillment. If you have more specific errors, please file a new issue.

**Comment by ThigoPSI** [comment]
Where do I create the new link?

**Comment by ThigoPSI** [comment]
Where do I create the new link?

**Comment by Fleker** [comment]
You create your own fulfillment. If you use this sample, or even if you follow [the codelab](https://codelabs.developers.google.com/codelabs/smarthome-washer/#0), you'll see how to create a fulfillment URL.
