### ISSUE TITLE
Request for new Toggle and synonyms

### ISSUE THREAD

**Issue by sdzai** [actions-on-google/smart-home-nodejs#379]
We need the following new toggle for the smart device that we are developing.

**New toggle**
Name: burst
Synonyms: burst, spray, disperse, release

Thanks!

Edit: Also, what is the estimated turn around time on these types of requests?

**Comment by Fleker** [comment]
I tend to process new requests every Wednesday, and it takes a few days after that for the changes to roll out, depending on the server build schedule.

**Comment by sdzai** [comment]
Can I also please request an update to the toggle in the original post to add the synonym "mist".

**Update to toggle**
Name: burst
Synonyms: burst, spray, disperse, release, _**mist**_

**Comment by Fleker** [comment]
This update has been submitted, and should roll out in a few days.
