### ISSUE TITLE
Question regarding agentUserId

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#381]
According to the description of agentUserId, it's unique Id on the agent's platform.
I'm wondering whether that value can be shared between multiple google user accounts.
for example, our IoT platform allows household members share single family code
meaning each family member has its own account but share the same family code as they live in the same place, and control the same IoT devices.
: 1 Family Code - N x accounts
Thus, each one of family members can log in from Google Assistant with their IoT service accounts.
I guess that agentUserId maps to Google accounts - IoT service account (access token) like 1:1:1
If family code can be used for the value of agentUserId (that is a shared code between family members), maybe the number of updating report state calls could be minimized.
is this right? possible?

===============================================================
agentUserId: String (up to 256 bytes). Required. Reﬂects the unique (and immutable) user ID on the agent's platform. The string is opaque to Google, so if there's an immutable form vs a mutable form on the agent side, use the immutable form (e.g. an account number rather than email).

**Comment by Fleker** [comment]
Yes, you could potentially have one agent user id for multiple Google accounts.
