### ISSUE TITLE
Report State implementation right after Sync

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#382]
As per spec. The ReportState API should also be called right after a SYNC intent.
We're sending states of devices right after SYNC, but keep getting 404 error,
Maybe the HomeGraph hasn't synced the agentUserId immediately right after a SYNC, 
=> we tried to sleep like 3 seconds before calling the RS API then it worked
I don't think this is the right approach, Is there any recommendation or guide on how to handle this?

**Comment by Fleker** [comment]
It may take some time after the initial SYNC for devices to be available in the Home Graph. It may take around half a minute, although we're aware this is not a great experience.

**Comment by ctsks** [comment]
Thanks @Fleker !
then we will set up around half a minute of time sleep and test
