### ISSUE TITLE
Decrypt Error occurred when log in from Assistant

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#383]
We're experiencing some strange problem when log in from Google Assistant.
- showing text message like "Decrypt error when parsing state" 
It was working fine, but redirect url started showing that error message
We have multiple test accounts, for some of them working fine as expected, but for others it does not work at all.
Is there something happening at Google Side?

**Comment by Fleker** [comment]
I've never seen that before. Is this happening during report state? Is there an issue with the service account you're using to generate the JWT?

**Comment by Fleker** [comment]
Two devs seem to have the same issue appear today during the initial account linking. @kanakamedalasumanth states that it happens in the Google Assistant app but not if the account is linked in the Home app.

**Comment by ctsks** [comment]
It seems working fine now!
