### ISSUE TITLE
Wrong TTS for error code: degreesOutOfRange

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#384]
We're using brightness trait, and if the value of brightness exceed supported range
we return degreesOutOfRange error code
- degreesOutOfRange : The requested degrees are out of range for <device(s)>.

however from Assistant TTS like "Sorry, I didn't get any response" is generated,
I guess something wrong here, Can you please whether error code degreesOutOfRange is taken care of as expected.

**Comment by Fleker** [comment]
Can you post the JSON response you sent?

**Comment by ctsks** [comment]
Please check the JSON response sent for degreesOutOfRange errorCode
we're using the same format for valueOutOfRange, deviceNotFound etc. but works fine.

{
	"requestId": "15051368211049198962",
	"payload": {
		"commands": [{
             "ids": ["657D5EFB-C89D-3B04-9842-728227FA3B15"],
             "status": "ERROR",
             "errorCode": "degreesOutOfRange",
             "debugString": null
           }
         ]
       }
     }

**Comment by proppy** [comment]
Do you still have this issue? (going thru the backlog)
