### ISSUE TITLE
Question on Relative commands for Brightness

### ISSUE THREAD

**Issue by ctsks** [actions-on-google/smart-home-nodejs#385]
Relative commands like "Brighten the light" without specifying brightness value can be made from Assistant if RS is implemented as per Spec.
I've tested that command, sometimes the value of brightness is 15, sometimes 20..
Curious how relative commands works, 
There must be some kind of criteria of generating the value for relative commands.
- brighten the light
- dim the light
maybe the brightness value is generated as per the user's history?

**Comment by Fleker** [comment]
The brightness delta is found through some method. It's not guaranteed to be the same, but I'm not really sure how it's chosen.

**Comment by ctsks** [comment]
I see... it will be great if how relative command works for both developers  and actual users

**Comment by Fleker** [comment]
Is this something that matters from a developer perspective? The intention of sending the absolute brightness is to make the relative commands insignificant.

**Comment by ctsks** [comment]
No problem from our developer perspective, maybe QA team will look at how relative commands work... 
Anyway thanks for your explanation
