### ISSUE TITLE
"Decrypt error when parsing state"

### ISSUE THREAD

**Issue by kanakamedalasumanth** [actions-on-google/smart-home-nodejs#386]
From the last night, we are facing the issue with account linking while adding the devices. 
While successful login it should redirect to the google assistant app but instead it gives an error: "Decrypt error when parsing state" 
![WhatsApp Image 2019-06-07 at 4 58 09 PM](https://user-images.githubusercontent.com/3605941/59101053-80e8cd00-8945-11e9-9d23-7a189ae42865.jpeg)

**Comment by Fleker** [comment]
When is this happening? Is it the same error as #383?

**Comment by kanakamedalasumanth** [comment]
Yes it is the same as #383

**Comment by kanakamedalasumanth** [comment]
I have tested this it is not working on google assistant app but it's working on the Home app

**Comment by Fleker** [comment]
I'll close this issue and move to #383 for triage.
