### ISSUE TITLE
Dutch language issue - Blinds

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#390]
Hi there -
am getting feedback from several users about blind percentage controls no longer working in Dutch:

"It seems to be a language issue.. previously it was working in dutch language and now this seems not to be working anymore and (in English) I also explicitly need to say set luxaflex to 50% while before luxaflex 50% also was working..."

**Comment by Fleker** [comment]
Can you share the exact queries that you're getting in Dutch? I'll see if I can reproduce. Can you reproduce this?

**Comment by proppy** [comment]
Closing as obsolete.
