### ISSUE TITLE
OAuth0 error

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#391]
Can anyone tell me why this happened?

![Screenshot_2019-06-12-12-29-51-781](https://user-images.githubusercontent.com/50698561/59348227-81e77900-8d0e-11e9-8690-8bd0f2b26610.jpeg)

**Comment by Fleker** [comment]
That seems to be an Auth0 issue.

**Comment by ThigoPSI** [comment]
I'm not getting on very well with OAuth!!!
Do you think you can help me?

I wanted to put my HTML on this page that is giving error
http://prntscr.com/o0xgzo

**Comment by Fleker** [comment]
Well it doesn't seem [like an Auth0 service outage](http://status.auth0.com/), so it's unclear what is happening just from your screenshot.

**Comment by ThigoPSI** [comment]
The only error I think is this
http://prntscr.com/o0y6pq
