### ISSUE TITLE
new mode Request

### ISSUE THREAD

**Issue by vencu** [actions-on-google/smart-home-nodejs#392]
Hi 

we are trying to add the  following utterances  for TV trait which is not supported by TV trait  natively so planed to add through mode trait but still missing the following in mode list.Can you add the following key words in mode list
 Is exist any framework to add any key word so that works with generic utterance
  ex: set living room tv  to enter

name | name_synonym
Menu | menu
Exit | exit
Enter | enter
Back | back
Guide | guide
Ok | ok
Option | option
Reverse | reverse
Source | source
Extra one | extra one
Extra two | extra two
Up | up
Down | down
Left | left
Right | right
Red | red
Green | green
Blue | blue
Yellow | yellow

**Comment by Fleker** [comment]
I'll pass along your request. I think this would be pretty awkward to say with a mode.

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039) so we can track it properly.
