### ISSUE TITLE
firebase authentication

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#394]
I wonder if I can use Firebase authentication, put it on my web page, and use it in actions on Google?

**Comment by Fleker** [comment]
Yeah you could do that. However, Firebase Authentication does not have an OAuth server in the backend, so you would need to do your own token management.

**Comment by 99bit** [comment]
@ThigoPSI have you done it by using only firebase i want to know how you did it or any tutorial for that
