### ISSUE TITLE
New Toggle and Toggle Name Synonyms Request

### ISSUE THREAD

**Issue by jakewm** [actions-on-google/smart-home-nodejs#395]
I am requesting the following name_synonyms be added to the **Light** toggle. 
name_synonyms: dispenser light, fridge light, refrigerator light
Many refrigerators have dispenser lights that at times are used as night lights.
I'd also like to request the synonym fast cool be added to the **RapidFridge** toggle.
Finally I'd like to request a new toggle named **control lock** with the synonyms control lock, child lock, child guard.  Many appliances offer this capability and we have it enabled in our mobile apps.

**Comment by Fleker** [comment]
Fridge lights are used as night lights? How does that work? The only fridge lights I know of would be inside, and you wouldn't want the fridge open too long.

I'll file a request to add it.

There's also an existing child lock toggle, and the extra grammars can be added to it.
