### ISSUE TITLE
Tunnel c00e6eec.ngrok.io not found

### ISSUE THREAD

**Issue by quangtuma** [actions-on-google/smart-home-nodejs#398]
Hey everyone, can you help me about this issue, please? I'm newbie

**Comment by Fleker** [comment]
It seems like you're using Ngrok, which generates a new URL every time you run the server. If you generate a new URL, you'll need to be sure to update the Actions console with the new URL.

**Comment by quangtuma** [comment]
Thanks for your reply Fleker, but I  have serveral doubts. Web portal URL is http://localhost:8081 for adding new device, right? And I set right webhook, auth, token on action on gg. But when I add device on app GG home, this link to ngrok URL, but as I mentioned, it's still not found.

**Comment by quangtuma** [comment]
This is my Web portal.
![fix](https://user-images.githubusercontent.com/44046981/59744285-719a4580-929c-11e9-8e16-9501afcc8bcd.PNG)

**Comment by quangtuma** [comment]
And my ngrok URL
![image](https://user-images.githubusercontent.com/44046981/59744404-b3c38700-929c-11e9-8388-31e56d1b9755.png)

**Comment by Fleker** [comment]
The ngrok URL will change everytime you run the start command. You'll need to copy the 3 URLs, update the console, then enable testing. You may need to disable and then re-enable testing.

**Comment by quangtuma** [comment]
I try hard update URLs on Action on GG, but it's still not effective. Because I'm a hardware engineer, and newbie in smart home action GG. If you have little time, can you help me by configuring through teamview?
Thanks a lot!

**Comment by quangtuma** [comment]
I try also App Engine, but i don't understand configuring at gcloud CLI step which i set. When I run deploy, git window display "not recognized glcoud", I try so much

**Comment by Fleker** [comment]
Have you downloaded the [gcloud CLI](https://cloud.google.com/sdk/gcloud/).

**Comment by quangtuma** [comment]
Yes, i set it, but after adding a device on google home, navigate to google app engine link, not found, 404 error

**Comment by quangtuma** [comment]
Amazing!! I tried ngrok successfully. The possible cause is asynchronous work between testing enable and adding a device on GG Home, Thank you so much, Nick!

**Comment by xaugat** [comment]
helo sir... i updated the ngrok url and it runs in web but in my flutter app it shows my old ngrok url and when i update it in flutter code .. it shows the same old url and tunnel not found error while running the api... please help

**Comment by Fleker** [comment]
That seems like a Flutter issue.

**Comment by doyskie7** [comment]
This comment is helpful!
Thanks mate Fleker

**Comment by SyncAnonymousID** [comment]
hello,
with the previous versions of kali linux this tutorial has been working very efficiently,
but since the 2020 released version, this shellphish doesnt seem to work at all,
it's like this,
i enter all the commands, everything goes smoothly until it comes to the links,
i choose 1 or 2 for facebook it insta or whatever and after a short while the links are generated,
when i copy and paste them in any browser the page is showing this tunnel error : 
Tunnel 484c0355.ngrok.io not found

So what can i do to fix this issue?

**Comment by JK-Love** [comment]
![image](https://user-images.githubusercontent.com/63699609/79337009-51d4bc00-7f57-11ea-8003-130a9c990315.png)
 Only my LAN network can be accessed. I send the link to my friends or I use a 4G network that can't be accessed
i don't know what happend
help~~

**Comment by hitchou** [comment]
no issue ???

**Comment by angelos567** [comment]
> ![image](https://user-images.githubusercontent.com/63699609/79337009-51d4bc00-7f57-11ea-8003-130a9c990315.png)
> Only my LAN network can be accessed. I send the link to my friends or I use a 4G network that can't be accessed
> i don't know what happend
> help~~

Yes sir I have same issue how you solve this problem.pls help me😥😥

**Comment by JK-Love** [comment]
> > ![image](https://user-images.githubusercontent.com/63699609/79337009-51d4bc00-7f57-11ea-8003-130a9c990315.png)
> > Only my LAN network can be accessed. I send the link to my friends or I use a 4G network that can't be accessed
> > i don't know what happend
> > help~~
> 
> Yes sir I have same issue how you solve this problem.pls help me😥😥

okey  you should use ubuntu open it

**Comment by jkwarner990** [comment]
> > > ![image](https://user-images.githubusercontent.com/63699609/79337009-51d4bc00-7f57-11ea-8003-130a9c990315.png)
> > > Only my LAN network can be accessed. I send the link to my friends or I use a 4G network that can't be accessed
> > > i don't know what happend
> > > help~~
> > 
> > 
> > Yes sir I have same issue how you solve this problem.pls help medisappointed_relieveddisappointed_relieved
> 
> okey you should use ubuntu open it
i also have same issue plz help

**Comment by kali5555** [comment]
the same Tunnel 8e70616ef60f.ngrok.io not found why is not found on internet please help

**Comment by WaldenLiang** [comment]
> the same Tunnel 8e70616ef60f.ngrok.io not found why is not found on internet please help

Download the ngrok here. https://ngrok.com/

**Comment by matrixboy44** [comment]
not working i have same error please help 
icant find my link on wan
