### ISSUE TITLE
Response validation

### ISSUE THREAD

**Issue by mstn** [actions-on-google/smart-home-nodejs#400]
I would like to validate responses automatically.

I know about the [validator tool](https://developers.google.com/actions/smarthome/tools/validator/), but I would prefer something that can be integrated into my code. I think it could be useful for testing and other scenarios.

For example, Alexa provides a [JSON schema](https://github.com/alexa/alexa-smarthome/wiki/Validation-Schemas). I am wondering if something similar exists for Google actions.

Thanks!

**Comment by Fleker** [comment]
I understand the desire to have a standalone validation script. The JSON schema starts out pretty straightforward, with the few standard fields. It starts to get more complex when handling different traits and their attributes, so I don't think you would be able to use a JSON-LD file to guarantee your response is valid.

**Comment by mstn** [comment]
Thanks for your reply. The JSON schema was just an example. I understand that it could be hard or impossible to fully specify the validation criteria in JSON-LD. Wouldn't it possible at least to distribute the code behind the [validator tool](https://developers.google.com/actions/smarthome/tools/validator/)? It works only for SYNC, afaict, but it would be great anyway.

**Comment by Fleker** [comment]
If you look through DevTools, you can see [the minified code](https://google-developers.appspot.com/actions/smarthome/tools/validator/smart_home_validator_compiled.js), which does have everything. You could use Puppeteer to automate the flow of opening the webpage as well.

The request to distribute the full code is something I'll note. I wonder if anyone else would want this as well.

**Comment by mstn** [comment]
Ok, thanks. I will play with the minified code. Is the licence Apache 2.0 also for it?

**Comment by Fleker** [comment]
There's no license in the file header.

**Comment by proppy** [comment]
We recently started working on this repository: https://github.com/actions-on-google/smart-home-schema which could provide the basis of what was requested here.

Let's continue the discussion there (since this repo is more about the Node.js backend for the sample).
