### ISSUE TITLE
Syncing being misheard - consistently weird

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#401]
Recently, instead of "Hey Google, sync my devices" - it is now hearing "Hey Google, sync my device's" - and then providing me links for setting up connectivity for a device via bluetooth.

Is this just me?

**Comment by Fleker** [comment]
It always works for me.

**Comment by madgeni** [comment]
Doesn't work on any Google device for me, getting some users complaining also

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the
content of this GitHub repository.

For filing developer bugs and feature requests with the Actions on Google Smart
Home platform, please follow the instructions at https://developers.google.com/assistant/smarthome/support.
