### ISSUE TITLE
Account linking failed

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#405]
What did I do wrong?

[index.zip](https://github.com/actions-on-google/smart-home-nodejs/files/3320461/index.zip)

**Comment by Fleker** [comment]
I don't know. Where is it failing?

**Comment by ThigoPSI** [comment]
Just one thing, do I need to use google cloud for webhook? I think that's where my problem is.

**Comment by Fleker** [comment]
You can use any public HTTPS service for a webhook.

**Comment by ThigoPSI** [comment]
I'm trying to use node.js webhook and it's not working

http://prntscr.com/o60pwd

**Comment by ThigoPSI** [comment]
this is the mistake

[ghome.zip](https://github.com/actions-on-google/smart-home-nodejs/files/3321617/ghome.zip)

**Comment by Fleker** [comment]
Unfortunately account linking is one of the harder things to debug, especially remotely. You may need to go a bit slow, making sure specific parts of the flow work before moving to the next step.

**Comment by ThigoPSI** [comment]
if using google cloud were not already having these problems?

**Comment by Fleker** [comment]
That shouldn't make a difference.

**Comment by ThigoPSI** [comment]
I think my problem is, as I only use the webhook link, and I leave the other 2 links out, it does not detect that it's being used

**Comment by Fleker** [comment]
You do need to provide all three links in the console before testing.
