### ISSUE TITLE
New mode setting request 'Out'

### ISSUE THREAD

**Issue by Dekaizer** [actions-on-google/smart-home-nodejs#406]
I could not find a corresponding mode setting, so I propose adding it.
Mode setting: 
setting_name = Out
setting_synonym = out, gone out, out mode, out setting

Represents user being not present for a short while, ergo not having gone on vacation but merely left the house to f.ex go to the store.

Thanks in advance!

**Comment by Fleker** [comment]
Wouldn't that be the same as an Away mode?

**Comment by Dekaizer** [comment]
The way I understand it, Away represents going long periods away like a vacation/holiday (usually for many days or weeks).

Out would represent going away for less than a day like going the store or whatever.

The distinction would be especially useful for thermostats who would have no reason to be heating the building if the user is Away for many days, but if the user is merely at the store for a few hours they would likely want their building heated when they return.

**Comment by Fleker** [comment]
This has been submitted, and should roll out in a few days.
