### ISSUE TITLE
How to create simply login and authentication with multiple user?

### ISSUE THREAD

**Issue by quangtuma** [actions-on-google/smart-home-nodejs#409]
Hi Pro, 
Can u instruct me about how to create simply login and authentication with multiple user? Or give me links for that.
And I don't know about folder containing login.html file? Do I have to configure it by myself? 
![image](https://user-images.githubusercontent.com/44046981/60235004-83996b00-98d0-11e9-9025-0e3c5b6d8e6c.png)

**Comment by Fleker** [comment]
Yeah the sample has been changed, so there is no longer a login page to use.

To handle multiple users, you would present a login page and have a POST callback which checks the user credentials and then assigns them a refresh token which can uniquely identify them.

It's not necessarily easy to implement, and can have severe security implications if done improperly, so it's not something that this sample provides.

**Comment by quangtuma** [comment]
Hi Fleke, I did adding a login.html, but not work, 
![image](https://user-images.githubusercontent.com/44046981/60717130-4033a200-9f4b-11e9-97a4-da4c7c22d544.png)

**Comment by Fleker** [comment]
The Smart Home Frontend sample does not have a login page.

**Comment by quangtuma** [comment]
Yes, but I added fullly login page in above link, but any action of expressApp.post('/login,..) still don't work,

**Comment by Fleker** [comment]
This seems like an issue with [registering express routes](https://expressjs.com/en/api.html#app.use).

**Comment by proppy** [comment]
Closing as obsolete.
