### ISSUE TITLE
SYNC get 429 error

### ISSUE THREAD

**Issue by thangta** [actions-on-google/smart-home-nodejs#413]
Hi I got 429 error response after run app.onSync. Pls help

{
    "error": {
        "code": 429,
        "message": "Resource has been exhausted (e.g. check quota).",
        "status": "RESOURCE_EXHAUSTED"
    }
}

sometime I also get a 404 response

**Comment by Fleker** [comment]
When do you get the 429? Is that part of the database calls?

**Comment by thangta** [comment]
I am calling app.Sync method before SYNC Intent return.

**Comment by Fleker** [comment]
I'm not sure what you mean by that.

**Comment by arihantdaga** [comment]
I am getting the same today as soon as i am reloading the front end. I am not able to update anything. Getting either error 429 or permission_denied error. I checked the quotas in google cloud console, there arent any problems. I have enabled all required apis also. 
Can someone point me in right direction as where to look

**Comment by Fleker** [comment]
A 429 is `resource exhausted`, meaning that you're calling the API endpoint too frequently.

**Comment by Fleker** [comment]
Maybe the sample is calling it too often. Either way, in a production environment you'd probably want to be more aware of when the APIs are being run.
