### ISSUE TITLE
No modes in app

### ISSUE THREAD

**Issue by Dekaizer** [actions-on-google/smart-home-nodejs#414]
Hello, I have created a custom switch device in the app that is meant to alternate between three modes:
Home, Away and Out (eco for now)  from https://developers.google.com/actions/smarthome/reference/traits/modes.
None of these show up in the app, or can be changed through assistant commands.

Is this intentional, as it seems fruitless to create these modes when the user is unable to do anything with them.

**Comment by Dekaizer** [comment]
It looks like this despite me not using the On/Off property for this switch that is meant to alternate between modes instead. [https://imgur.com/a/8KpybsJ](url)

**Comment by Fleker** [comment]
Not everything has a visual control. Modes don't. But they should still be controllable via voice.

**Comment by madgeni** [comment]
modes were working for me also, but are not being recognised by voice
