### ISSUE TITLE
Smarthome Action duplicate Device ID

### ISSUE THREAD

**Issue by thangta** [actions-on-google/smart-home-nodejs#415]
Hi,
Why may action on google have been duplicated device ID in Query intent

{"inputs":[{
"intent":"action.devices.QUERY",
"payload":{
"devices":[{
"id":"HRRSH0000000000013c71bf0595d4"
},
{
"id":"HRRSH0000000000013c71bf0595d4"
}]
}
}],
"requestId":"8763701785803186478"
}

{"inputs":[{
"intent":"action.devices.QUERY",
"payload":{
"devices":[{
       "id":"HRRSH0000000000013c71bf0597e0"
   },
   {
       "id":"HRRSH0000000000013c71bf0595ec"
   },
  {
       "id":"HRRSH0000000000013c71bf0597e0"
  },
  {
       "id":"HRRSH0000000000013c71bf0595ec"
  } 
 ]}
}],
"requestId":"61145857407304674"
}

**Comment by Fleker** [comment]
I don't know why this may happen.

**Comment by devunwired** [comment]
Hi @thangta , this repository is for issues related to the Smart Home Node.js sample code. It looks like from post that you are having issues with an action project you have already built.

I would recommend filing an issue in the [public tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) with more details about your Smart Home project (including the project ID) and perhaps a sample SYNC response, as it's possible the issue stems from the data returned during SYNC.
