### ISSUE TITLE
AC Unit doesn't support FanSpeed

### ISSUE THREAD

**Issue by tranmanh90** [actions-on-google/smart-home-nodejs#416]
I used FanSpeed for AC unit but, Assistant response "Ac unit doesn't support  that functionality"
This is attributes:

        attributes: {
            availableFanSpeeds: {
                speeds: [{
                        speed_name: 'S1',
                        speed_values: [{
                                speed_synonym: ['low'],
                                lang: 'en'
                            }
                        ]
                    },
                    {
                        speed_name: 'S2',
                        speed_values: [{
                                speed_synonym: ['medium'],
                                lang: 'en'
                            }
                        ]
                    },
                    {
                        speed_name: 'S3',
                        speed_values: [{
                                speed_synonym: ['high'],
                                lang: 'en'
                            }
                        ]
                    }
                ],
                ordered: true
            }
        }

**Comment by Fleker** [comment]
That should work. What queries are you saying?

**Comment by tranmanh90** [comment]
I solved this issuse, but I faced a new issuses. Please give me an advice
I am working with AC Unit. 
- To change temperature, I tried to to speech to google assistant "set the ac unit to 25" but Google Assistant response => "Actually, the ac unit doesn't support that functionality"
What the voice command should I talk to Assistant?
- To change mode, I tried to to speech to google assistant "set the ac unit mode to dry/ set the ac unit to dry mode/ ..." but Google Assistant response => "Actually, the ac unit doesn't support that functionality"
What the voice command should I talk to Assistant?
With type and traits as below:
--------------------------------------------------------
        type: 'action.devices.types.AC_UNIT',
        traits: [
            'action.devices.traits.OnOff',
            'action.devices.traits.FanSpeed',
            'action.devices.traits.TemperatureSetting'
        ]
-----------------------------------------------------------
And with attributes as below:
-----------------------------------------------------------
      attributes: {
          temperatureTemperatureUnit: 'C',
          availableThermostatModes: 'cool,auto,heat,dry',
          availableFanSpeeds: {
            speeds: [{
              speed_name: 'FAN_LO',
              speed_values: [{
                speed_synonym: ['low', 'chậm', 'thấp'],
                lang: 'en' }
                ]
              },
              {
              speed_name: 'FAN_MED',
              speed_values: [{
                speed_synonym: ['medium', 'trung bình', 'vừa'],
                lang: 'en' }
                ]
              },
              {
                speed_name: 'FAN_HI',
                speed_values: [{
                  speed_synonym: ['high', 'nhanh', 'cao'],
                  lang: 'en' }
                ]
              },
              {
                speed_name: 'FAN_AU',
                speed_values: [{
                  speed_synonym: ['auto', 'tự động'],
                  lang: 'en' }
                ]
              },
            ],
            ordered: true
          },
          reversible: false
        }
--------------------------------------------------------

**Comment by tranmanh90** [comment]
@Fleker Can you help me the question above. 
Many thanks,

> I solved this issuse, but I faced new issuses. Please give me an advice
> I am working with AC Unit.
> 
> * To change temperature, I tried to to speech to google assistant "set the ac unit to 25" but Google Assistant response => "Actually, the ac unit doesn't support that functionality"
>   What the voice command should I talk to Assistant?
> * To change mode, I tried to to speech to google assistant "set the ac unit mode to dry/ set the ac unit to dry mode/ ..." but Google Assistant response => "Actually, the ac unit doesn't support that functionality"
>   What the voice command should I talk to Assistant?
>   With type and traits as below:
> 
> ```
>     type: 'action.devices.types.AC_UNIT',
>     traits: [
>         'action.devices.traits.OnOff',
>         'action.devices.traits.FanSpeed',
>         'action.devices.traits.TemperatureSetting'
>     ]
> ```
> 
> ## And with attributes as below:
> ```
>   attributes: {
>       temperatureTemperatureUnit: 'C',
>       availableThermostatModes: 'cool,auto,heat,dry',
>       availableFanSpeeds: {
>         speeds: [{
>           speed_name: 'FAN_LO',
>           speed_values: [{
>             speed_synonym: ['low', 'chậm', 'thấp'],
>             lang: 'en' }
>             ]
>           },
>           {
>           speed_name: 'FAN_MED',
>           speed_values: [{
>             speed_synonym: ['medium', 'trung bình', 'vừa'],
>             lang: 'en' }
>             ]
>           },
>           {
>             speed_name: 'FAN_HI',
>             speed_values: [{
>               speed_synonym: ['high', 'nhanh', 'cao'],
>               lang: 'en' }
>             ]
>           },
>           {
>             speed_name: 'FAN_AU',
>             speed_values: [{
>               speed_synonym: ['auto', 'tự động'],
>               lang: 'en' }
>             ]
>           },
>         ],
>         ordered: true
>       },
>       reversible: false
>     }
> ```

**Comment by Fleker** [comment]
Yeah I see your question.

**Comment by Fleker** [comment]
I was able to reproduce the errors at first using the sample, but then I went into the database and explicitly defined certain values in the `states` map:

* thermostatHumidityAmbient: 100
* thermostatMode: "off"
* thermostatTemperatureAmbient: 23
* thermostatTemperatureSetpoint: 25

Then the queries worked as expected.

**Comment by tranmanh90** [comment]
> I was able to reproduce the errors at first using the sample, but then I went into the database and explicitly defined certain values in the `states` map:
> 
> * thermostatHumidityAmbient: 100
> * thermostatMode: "off"
> * thermostatTemperatureAmbient: 23
> * thermostatTemperatureSetpoint: 25
> 
> Then the queries worked as expected.

Thank you so much, I worked for me
