### ISSUE TITLE
Enable Dialogflow,I've lost my smarthome action

### ISSUE THREAD

**Issue by sam0910** [actions-on-google/smart-home-nodejs#417]
I enabled to Dialogflow API to learn and apply my existing smarthome project.
After that, the ActionsOnGoogle console change to some kind of Dialogflow mode.
![cap11](https://user-images.githubusercontent.com/9714538/60906722-cedd5180-a2b2-11e9-9ace-4ebd0b836c3e.JPG)

I can not find my smarthome Action ,I've setup before with fulfillment url ..../smarthome
Other informations are display as saved before(include Account Linking)
It only displays Conversational Fullfillment Type Action.

I've disabled Dialogflow API and delete a test agent as well, But It still shows  Conversational Fullfillment Type Action.
GAE logs shows the /smarthome requests are still coming and working well.
But I lost my SmarHome console ,cannot modify the Action with fullfillment url.

I intent to apply dialogflow actions for using Google Assistant could set schedule for my devices by Assistant speech command. My project base on fully GoogleFlatform , Firebase with G.A.E, Cloud IoTCore, Cloud Functions and Firestore.

Is it possible? and Where can I find the Smarthome Action?

**Comment by Fleker** [comment]
You aren't meant to be able to switch to Dialogflow. How did you do that? I don't think the console is configured to switch back.

**Comment by sam0910** [comment]
I just enable Dialogflow API on existing smart home project. What should I do? Do I make a new project and set up again? 
The project is under review for production.

**Comment by sam0910** [comment]
Cannot combine the Dialogflow on SmartHome project?

**Comment by Fleker** [comment]
You cannot have one Action that uses smart home and Dialogflow.

**Comment by sam0910** [comment]
Thank you so much for you help. always.
