### ISSUE TITLE
Request New Mode Name

### ISSUE THREAD

**Issue by mgsantini** [actions-on-google/smart-home-nodejs#418]
Requesting a new mode be implemented to support faucet device types (and potentially other device types):

Name: Warmup
Synonyms: warm up, warmup, warm-up (any alternatives that may be translated from speech)

**Comment by Fleker** [comment]
Would this be similar to the [TemperatureSetting](https://developers.google.com/actions/smarthome/traits/temperaturesetting) trait?

**Comment by mgsantini** [comment]
It is different in that it will turn on the device and run until a specific temperature is obtained. This temperature is not part of the invocation, as it is stored elsewhere. The warmup command shall be generic without a degrees supplied.

**Comment by Fleker** [comment]
If you have the OnOff and TemperatureSetting traits, you should be able to do that. You can do relative queries like "make the faucet warmer" to adjust the temperature in a natural way.

**Comment by mgsantini** [comment]
We essentially need this as a synonym to preheat. It is used in a similar way. We have a custom action that accepts either syntax and we'd need this Smart Home action to be the same. Therefore, both the syntaxes should be allowed: 

Set faucet mode to preheat
Set faucet mode to warmup

This isn't to be used as a means to increase or decrease temperature. It is to obtain a set static temperature. For example, if the preheat temperature is defined to be 90 degrees, the command will turn the faucet on until hardware determines temperature has been met. If this can be obtained with temperature traits, I'll see about using that.

**Comment by Fleker** [comment]
You should be possible to take advantage of the thermostat trait with two modes: off and heat. You could play around with some of the attributes like commandOnlyTemperatureSetting which would indicate that you don't have state data.

**Comment by mgsantini** [comment]
If I use the TemperatureSetting trait, that will give me more modes to use. However, I'm still missing the key word(s) we are seeking. Our client has trained the user base to use preheat and warmup interchangible. In today's custom action, phrases like "... to preheat <device name>" or "... to warm up <device name>" will perform this action. The Smart Home action is initially going to use 'modes' to fulfill this task, until the faucet device type supports a preheat/warmup trait. The TemperatureSetting trait does expose new modes to use, but still fails to bring out the ones the client is seeking. The Modes trait supports 'preheat', but we just need 'warm up/warmup' added (either as a new mode or synonym to preheat).

**Comment by Fleker** [comment]
I think "preheat the device" may map to the OnOff intent for the Oven type (at least for Ovens). Can you try that?

**Comment by proppy** [comment]
Closing as obsolete.
