### ISSUE TITLE
Request New Mode Name For Thermostats

### ISSUE THREAD

**Issue by insrat** [actions-on-google/smart-home-nodejs#419]
Name: Schedule
Synonyms: Schedule, schedule

Name: Free
Synonyms: Free, free

Name: Timing
Synonyms: Timing, timing

Name: Constant
Synonyms: Constant, constant

**Comment by devunwired** [comment]
Thanks for your request!
We would like to ensure that these requests are properly tracked and assigned, so please file this through the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039).
