### ISSUE TITLE
Request new types/traits

### ISSUE THREAD

**Issue by tranmanh90** [actions-on-google/smart-home-nodejs#420]
Hi actions on google team,

Now we are developing smart devices such as Television, Sensor, Settop box, ... but currently. The lib has not supported these types yet.
 Can we request actions on google support these types? Or can you provider us to early access the EAPs on these traits and types ?

Thanks,

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [device type request form](https://issuetracker.google.com/issues/new?component=655104&template=1294884) so we can track it properly.
