### ISSUE TITLE
Dutch Mode settings request

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#421]
Can I have the Dutch equivalent of Memory 1 - 6:

geheugen een
geheugen twee
geheugen drie
geheugen vier
geheugen vijf
geheugen zes

thanks

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039) so we can track it properly.
