### ISSUE TITLE
cursor control

### ISSUE THREAD

**Issue by lowel0** [actions-on-google/smart-home-nodejs#422]
Hi,

I am creating an assistive technology application which uses infra-red beamers.  The infra-red beamers are used to control TVs, DVD players etc, emulating the remote control.

So far the only facility lacking is the ability to reproduce the cursor controls.  It would be great to be able to have a command, similar to the "volume" trait which would allow relative positioning as achieved by the cursor buttons on a remote control. e.g. "Move TV cursor up 2 steps".  Is this already possible or something that could be introduced?

Thank you very much.

**Comment by devunwired** [comment]
Thanks for reporting this! Please submit your request using the official [trait request form](https://issuetracker.google.com/issues/new?component=655104&template=1295013) so we can track it properly.
