### ISSUE TITLE
Smart Home app not request sync intent

### ISSUE THREAD

**Issue by ctnha** [actions-on-google/smart-home-nodejs#423]
I am very happy when my smart home application is approved.
However, there was a serious error, after the authenticated user and the Exchange Token Endpoint returned the authorization_code correctly but the Sync request was not called.
Oauth2 exchange token end point result json logs:
`{ 
token_type: 'Bearer',
access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5oYWN0LmhnaUBnbWFpbC5jb20iLCJpYXQiOjE1NjMzNzc4NTksImV4cCI6MTU2MzQ2NDI1OX0.L7l92F90M3SFfT8YPFYBdX8eqUtE_lsw0eFZLcFjqLE',
refresh_token: 'nhact.hgi@gmail.com',
expires_in: 86400 
}
POST /token 200 5.282 ms - 60
`

Google Assistant Action Logs Viewer
`{
 insertId:  "jftr1zg4vzpvsj"  
 logName:  "projects/ctn-smart-home-d0537/logs/actions.googleapis.com%2Factions"  
 receiveTimestamp:  "2019-07-17T15:37:42.505494556Z"  
 resource: {
  labels: {
   action_id:  "SMART_HOME_SYNC"    
   project_id:  "ctn-smart-home-d0537"    
   version_id:  ""    
  }
  type:  "assistant_action"   
 }
 severity:  "ERROR"  
 textPayload:  "SYNC: Request ID 16828839853855407032 failed with code: OPEN_AUTH_FAILURE"  
 timestamp:  "2019-07-17T15:37:42.473425172Z"  
}`

I verified by creating a new smart home project with the same configuration in test mode, it works perfectly. 
I am very grateful for your help.

**Comment by Fleker** [comment]
It seems like there may be an issue with your authentication implementation. If it's already been approved, you may want to contact the Google representative and let them know of the issue to see if there is something in the production version of the Action that isn't behaving as expected.

**Comment by ctnha** [comment]
Thanks @Fleker. I'm waiting for a response from Google. Can I use faketoken for the official Smart Home application? I configured a test application and an official application they are the same token enpoint URL and the same fulfillment URL. 
App test works well, the official app call faketoken to exchange refresh_token, response new access_token but does not request Sync.
this my code
![image](https://user-images.githubusercontent.com/10706263/61472533-d980a080-a9ae-11e9-96ac-6f06e5af4612.png)
If you can help me, I will provide fulfillment URL and token enpoint URL for you!

**Comment by devunwired** [comment]
Hello @ctnha, we are currently tracking a few developer concerns with smart home account linking. Can you post your issue on the [official issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) so we can track it better?

**Comment by ctnha** [comment]
Thanks @devunwired. I like to find a glass of water in the desert :d

**Comment by devunwired** [comment]
Closing here as this issue has been moved to the public smart home tracker.

**Comment by ctnha** [comment]
The official issue tracker solved my problem. It worked. Thank for all.
