### ISSUE TITLE
Toogle name "master"

### ISSUE THREAD

**Issue by pradipshenolkar** [actions-on-google/smart-home-nodejs#425]
We are the manufacturers of smart home switches. We have a master switch on each switchboard, which controls (either turns all on or turns all off). None of the existing toggle names fit this criteria. Currently we treat master switch as normal switch, but then for commands like "turn on all living lights" it doesn't work, since master switch controls rest of the switches on the switchboard.

**Comment by Fleker** [comment]
If all the switches are in the Living Room, could you just call the master device "Living Room Master Switch" and give it the OnOff trait?

**Comment by proppy** [comment]
Closing as obsolete.
