### ISSUE TITLE
Couldn't update settings. Please check your connection.

### ISSUE THREAD

**Issue by manikdutta** [actions-on-google/smart-home-nodejs#428]
While i am trying to sign in AOG test account this error occurred.

The log is:
login successful  8910911970
authCode successful  36ipa97hxzw000000000000000
GET /oauth?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fintelliosmarthome&client_id=ZxjqWpsYj3&response_type=code&state=AB8b_TMBu32CycxEP_15Dc-wBdrQ-cR7a4KwMA1GE6xjTXCtHzMuIu1VCqkjJtTbWSc7oB--ZAqkG1442toCcVF_N6x-bzfP_nlSC_9ztHqeQ--6uj5uNmzjm7t2JYGQeyYkVeKThzQhjGC9ebHRrjQJXCCfzH6rO3R0LRZLsqD7T44BOR_iq3P_lQ5iDeZ1aVntxmCLsDaxEKMj5V0owdWKhu39kqdK4YwMQOUa1BQ8aAoBKK6UByYwXJehsS5v4xogiTKNqi0L4IaMVb8n_2aq69NewpztnRsx9Kk7iaUYRDYgd2aKdYh3mw56doNtg3PAAgk70LtyKGu_w1pyDbI_HyfYdA5FH0vwOuc42JQqhFjiFjedvRgYvYcguTFf9liT1j8GPw-sLP84Lz3UkItmiCIdiyYWgu-NOzF_QKmz7SnkL9SoGvJR3gm4Q-eQM0FNgq3OaYugmcHkcqSq3b6Qyo5vTXVHv3uOsC7F803rOfGCOMR64W9FiCPkca4fvnBFYcpteXsCNJ077Uq_9msxLAx8eLbW_3vhX7npPIc0wGc1fR7PQn9c7BKECvdltLdqE5JHdhqs&user_locale=en-GB 302 1.451 ms - 1434
GET /service-worker.js 304 0.990 ms - -
/token query {}
/token body { grant_type: 'authorization_code',
  code: '36ipa97hxzw000000000000000',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/intelliosmarthome',
  client_id: 'ZxjqWpsYj3',
  client_secret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
client { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
handleAuthCode {}
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getAccessToken =  { uid: 'jEIFDigfqRDxs3g02RmjnQ',
  accessToken: '2wdj8wjy2qe000000000000000',
  refreshToken: '2wdj8wjy2qe000000000000000' }
return getAccessToken =  { token_type: 'bearer',
  access_token: '2wdj8wjy2qe000000000000000',
  refresh_token: '2wdj8wjy2qe000000000000000' }
respond success { token_type: 'bearer',
  access_token: '2wdj8wjy2qe000000000000000',
  refresh_token: '2wdj8wjy2qe000000000000000' }
POST /token 200 1.654 ms - 112

.......................................
Please help me

**Comment by Fleker** [comment]
It's not clear what error is happening.

**Comment by Fleker** [comment]
It's not clear what error is happening.

**Comment by Fleker** [comment]
It's not clear what error is happening.

**Comment by manikdutta** [comment]
In google assistant app after signing in it's showing "Couldn't update settings. Please check your connection.". Sync is not happening.

**Comment by devunwired** [comment]
Hi @manikdutta, this repository is for issues related to the Smart Home Node.js sample code. It looks like from your log output that you are having issues with an action project you have already built and published. Can you clarify if you are having this problem running the sample or your own project code?

I would recommend either asking a question on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home) if this is an issue you encountered while developing, or filing and issue in the [public tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) if this is something you've experienced after your action was published.
