### ISSUE TITLE
Additional synonym

### ISSUE THREAD

**Issue by benobell** [actions-on-google/smart-home-nodejs#429]
Hi Nick,
Can you please add additional synonym "static" to the mode name "steady"  - thanks in advance

steady           steady, study, static

best regards
Beno Bell
Senior Software Engineer
Creativity, Inc.

**Comment by devunwired** [comment]
Thanks for your request!
We would like to ensure that these requests are properly tracked and assigned, so please file this through the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039).
