### ISSUE TITLE
Norwegian translations for existing modes.

### ISSUE THREAD

**Issue by Dekaizer** [actions-on-google/smart-home-nodejs#430]
Can you add the following Norwegian translations for existing modes?
**Mode Names**
mode : modus

**Mode Settings**
Home: hjemme, hjemme modus
out: ute, gått ut, ute modus
Away: borte, borte modus, dratt vekk, ferie, ferie modus
Eco: Øko, øko modus
antifreeze: antifrys, anti-frys
comfortable: komfort, behagelig, komfort modus

Thanks in advance.

**Comment by devunwired** [comment]
Thanks for your request!
We would like to ensure that these requests are properly tracked and assigned, so please file this through the official [mode/toggle request form](https://issuetracker.google.com/issues/new?component=655104&template=1295039).
