### ISSUE TITLE
Error in updated nickname/name of the device

### ISSUE THREAD

**Issue by catherinewm** [actions-on-google/smart-home-nodejs#432]
When I tried to change the name/nickname of the device in the frontend web it encounter an error 
returned:
{ userId: '1234', deviceId: 'g8u' , name: "Smart Fan 3 ABC"}
{
 "error": {
    "code": 400,
    "message": "Request contains an invalid argument"
    ...
  }
}

**Comment by Fleker** [comment]
Must be a bug in making the request sync api.

**Comment by proppy** [comment]
Closing as obsolete.
