### ISSUE TITLE
Add new mode settings

### ISSUE THREAD

**Issue by Talakh** [actions-on-google/smart-home-nodejs#435]
Hi, now i can use mode settings (H1, H2, H4, H8) only for 1, 2, 4, 8 hours. Can you add settings for 3, 5, 6, 7 hours?
![image](https://user-images.githubusercontent.com/23129676/62944464-6b7c9d00-bde5-11e9-94e1-f352a1649308.png)

**Comment by Fleker** [comment]
Can you post this on the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1295039)?

**Comment by Talakh** [comment]
@Fleker, yes of course, thank you
