### ISSUE TITLE
How to get updated when user changes device name from Google Assistant app

### ISSUE THREAD

**Issue by neesonqk** [actions-on-google/smart-home-nodejs#436]
I notice that the user is able to change the device's name from Google Mobile app (Assistant etc.), however, there seems isn't any api or callback to inform the integrated backend to update this to database accordingly, let's say, if this user unlink then relink his account to google which will trigger a SYNC command, the names of devices will be restored to the default names.

Is there any way to sync this two places?

**Comment by FelipeGalante** [comment]
I'm with the same problem.
I read the documentation, but as you said, couldn't find any API to send the changes to my backend.
I'm doing some testing and trying some stuff. If I have success, I'll let you know and I'll post my finds here as well

**Comment by devunwired** [comment]
This issue does not seem related to the Node.js sample code contained in this repository. Please direct any general development questions regarding the smart home API to the `google-smart-home` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home).

**Comment by Fleker** [comment]
There is no sync mechanism from Google to your backend for device names, so they will be reset. Ideally, a person will never need to unlink your service.

**Comment by neesonqk** [comment]
@Fleker If this the case, I have another scenario which would be very annoying, let's assume, a person purchased a smart lamp from our shop, then he linked this to Google Assistant and rename it as 'My Living Room Lamp' from there, however, he never modify the lamp's name in our own app which still retains the default name like 'My Lamp', then few days later, he purchased one more smart lamp from our shop and added to his account, here is the problem, after he added a new device a SYNC request would be fired to google to re-sync all devices, if not wrong this SYNC request will reset 'My Living Room Lamp' to 'My Lamp'.

If he has 10 lamps in total he then has to rename all over again after a new device added. 

I haven't tested this out so not very sure if it works in this way, but if it works in this way then the sync mechanism from Google seems very necessary.

**Comment by devunwired** [comment]
Have you looked into the [HomeGraph API](https://developers.google.com/actions/smarthome/reference/rpc/)? The [Sync](https://developers.google.com/actions/smarthome/reference/rpc/google.home.graph.v1#google.home.graph.v1.HomeGraphApiService.Sync) call allows you to query the devices for a given user in Home Graph, which should report any updated device metadata (such as names).

This functionality is not integrated into the webhook, but if you are unable to manage the needs of your use case with the HomeGraph API, consider filing a feature request in the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148).

**Comment by neesonqk** [comment]
@devunwired Ah I think I missed out this HomeGraph API, though it is not integrated with webhook, yeah I think I am able to manage the needs of my case through this API, many thanks!

**Comment by Fleker** [comment]
When the user resyncs, or you call the Request Sync API, the Home Graph uses the device IDs to know what things to update. User controlled fields like the room and names will not be overridden.
