### ISSUE TITLE
mode name convention

### ISSUE THREAD

**Issue by veonua** [actions-on-google/smart-home-nodejs#439]
as far as I understand only modes on the https://developers.google.com/actions/smarthome/reference/traits/modes
supported,

do I understand it right that I should use 
name: "Fan Speed", but also "fan_position",

are names case sensitive?

are _name_synonyms_ free form or they should be exactly as in table?
eg. can I use 

```
name: "mode",
name_values: [{
      name_synonym: ["mode", "power", "level"],
      lang: "en"
    }],
```

**Comment by Fleker** [comment]
Yes, the names are case sensitive, and you should return them in a case sensitive way.

The synonyms too must come from the list. In your example, it would not work as expected. "mode" 
and "Level" are separate mode names, and "power" is a separate mode setting. You can't mix and match.

**Comment by veonua** [comment]
This list requires cleaning and refactoring.
It's quite hard to work with in the way how it is now,

For example "set power to low" and "set mode do quiet" are synonyms for many type of devices. But in current schema there are two separated modes. 

Especially it's funny that all languages except English has "silent"

**Comment by Fleker** [comment]
Yes we're aware that the list is a bit convoluted. At the same time, it would be difficult to resolve due to backwards compatibility.

**Comment by veonua** [comment]
so now it is possible to use any word as name_synonym?

**Comment by Fleker** [comment]
Yes any names are valid.
