### ISSUE TITLE
Any chance to add public support for rooms in actions

### ISSUE THREAD

**Issue by veonua** [actions-on-google/smart-home-nodejs#440]
went through all of Google Home docs and can't see how instruct vacuum to clean specific rooms with voice commands. AKA "Hey Google, clean the living room.”

https://www.theverge.com/circuitbreaker/2018/9/6/17817220/irobot-roomba-i7-robot-vacuum-empties-itself-maps-house

**Comment by devunwired** [comment]
This sounds like a great feature request for the platform! Feel free to file it in the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) so we can assign it to the right people to evaluate.

**Comment by Fleker** [comment]
To do this, you must use the [StartStop](https://developers.google.com/actions/smarthome/traits/startstop) trait and pass in the room names to the "availableZones" attribute. Then you will receive the zone in the EXECUTE request. The phrase "vacuum the living room" maps to a StartStop command if the device type if a Vacuum.

**Comment by veonua** [comment]
Thank you, Nick

I thought it could be part of https://developers.google.com/actions/smarthome/traits/locator

Are availablezones could be any string, or there are predefined names as mode and toggle names

* Please use standard naming, now we have "rooms" in Scene docs, "location" and "zones".

**Comment by Fleker** [comment]
Available zones can be any set of names that you want, and not just limited to rooms. (Sprinkler systems may have several logical zones for different plants or parts of your lawn)

The Locator trait is for finding things.

**Comment by veonua** [comment]
Sending robots to places and finding them usually connected. 

Zones worked fine, thank you

**Comment by jcyh0120** [comment]
> Available zones can be any set of names that you want, and not just limited to rooms. (Sprinkler systems may have several logical zones for different plants or parts of your lawn)
> 
> The Locator trait is for finding things.

Could you provide an example phrase for a sprinkler with target zone?
I tried saying: smart sprinkler "room name".

But didn't get the zone parameter printed out in DEBUG request.
