### ISSUE TITLE
ReportState - App GUI not updating ?

### ISSUE THREAD

**Issue by symdeb** [actions-on-google/smart-home-nodejs#441]
After a lot of time spent to implement the JWT, access token request etc..  got the ReportState call finally working. Example request is:

{  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcx",   "agentUserId": "1836.15267389",  "payload":     {  "devices":    {       "states":        {         "123":        {      "on": false,                "online": true            },         "456":        {    "on": false, "online": true,   "brightness": 10,                  "color":    {   "name": "cerulean",    "spectrumRGB": 11655    }   }  }  }   } } 

The ReportState call responses with HTTP 200 and the request ID in the call
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcx"
}
The AgentUserID (entity)  and the devices name are the same as returned in SYNC. (and WillReportState is set to true). After this call the controls in the Android app are not updating to the new state. Tried to change the requestID as well, but did not help. No SYNC , EXECUTE or any other event is send to my API endpoint as well after this call . only changing the value of the controls in the app do send the event to my API endpoint.

**Comment by devunwired** [comment]
Hi @symdeb, thanks for reporting this!
I would recommend first verifying your implementation using the **Report State Dashboard** as described in the [Test Report State](https://developers.google.com/actions/smarthome/develop/report-state#test-report-state) portion of the documentation. This will enable you to ensure that the calls you are making are properly updating the Home Graph.

If are still seeing this issue in the Google Home app after verifying that Home Graph has the correct state, then it may be a platform issue we need to investigate. Please file an issue using the
[public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148).

Closing this instance as unrelated to the sample code in this repo.

**Comment by symdeb** [comment]
Dear Dave,

I am following all the steps and so far with success,until almost the last
step I bumped into this

Run mvn compile

   1. You should see the file target/appengine-staging/app.yaml

The maven compile went fine, but there is no yaml file generated. My target
folder is:

[image: image.png]

I am running on windows 10 Pro

Thanks!

**Comment by symdeb** [comment]
Never mind. The reason was  I used at gloud init  the project used for Home
Actions. and not the one created for the dashboard.

[image: image.png]
Thanks

**Comment by symdeb** [comment]
Well, after redoing the whole process on a Ubuntu machine,there might
something to mind, because it was not related to gcloud init.

*A. https://github.com/actions-on-google/smart-home-dashboard
<https://github.com/actions-on-google/smart-home-dashboard>*

- Run mvn compile

   1. You should see the file target/appengine-staging/app.yaml

- 2. Deploy the sample with mvn appengine:deploy

   - It will be available at http://<your-project-id>.appspot.com

It seems those two steps should be in reverse order. Only after deploy I
did find the staging folder.

*B. https://developers.google.com/actions/smarthome/develop/report-state
<https://developers.google.com/actions/smarthome/develop/report-state>*

http://<your-project-id>.appspot.com

On the dashboard, do the following:

   - Choose your Account Key File
   - *Add your Access Token*
   - *Add your Fulfillment URL*
   - Add your agentUserID

The app only shows the Account key and AgentUserID, There is no box for the
fulfillment url and Access Token.
I think it is also worth mentioning to upload the  service account.json
file of the application key / serviceaccount for the Home Action, not the
project created for the GCP dashboard.

Thanks!

**Comment by symdeb** [comment]
Dear Google,
One more thing. When I am on the dashboard page, presing F5 or CTRL-F5
results in the below error, and to get the status of the device the
json file nand AgentId need to be re-entered. This is not really a
smooth process for testing.
Thanks
Whitelabel Error PageThis application has no explicit mapping for
/error, so you are seeing this as a fallback.
Mon Aug 19 14:05:35 UTC 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by symdeb** [comment]
Dear Dave,

I see the refresh button in he dashboard now, this works great.

I sendtReportState and the dashboard updates correctly.
The android app however does not.Any ideas ?

Thank you.

**Comment by symdeb** [comment]
Build the dashboard . Sending a ReportState from my cloud  by a scripts and and can see the changes there (attachment), but the status of the control (on/off) in the GUI is not updating and no intents are incoming on the API endpoint. . When changing the state is the app itself I receive the EXECUTE intents. Is this normal behavior that the GUI does not update upon ReportState ?

![after_report_state](https://user-images.githubusercontent.com/19564066/63569839-96b57800-c5ad-11e9-8525-010ea8acd841.PNG)

**Comment by symdeb** [comment]
To clarify , the reference to the "App" and "GUI"  is a reference to the devices shown in the mobile Google Home App. The dashboard REFRESH does update the state correctly. Issue filed a week ago in an Google issue tracker (but that seems not a public viewable tracker). Is it normal the status of the devices shown in the mobile app do not update upon a ReportState ?

**Comment by Fleker** [comment]
Yes, at the moment the mobile app does not refresh automatically.
