### ISSUE TITLE
no structure hint?

### ISSUE THREAD

**Issue by littlesohkt** [actions-on-google/smart-home-nodejs#444]
Is there any field for structure hint when sync?

It show errors when I enter structureHint

**Comment by devunwired** [comment]
You can see all the available attributes for a `SYNC` response in the [documentation](https://developers.google.com/actions/smarthome/develop/process-intents#response_format). Note that hints are only currently supported for rooms.

If you would like to file a feature requests to add support for this, please use the [public issue tracker](https://developers.google.com/actions/smarthome/support). For any additional development questions related to Google smart home, please use the `google-smart-home` tag on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home).
