### ISSUE TITLE
New toggle name suggestion - Relay

### ISSUE THREAD

**Issue by DenisVCode** [actions-on-google/smart-home-nodejs#445]
Hi, I would welcome a toggle "relay" ("Power relay", "Power").
_Example:_
Our device has multiple outputs, one for LED (controlled by OnOff trait) and one for relay (can't use OnOff again, only boolean state so toggle is okay).
It would be more confusing to the user to display it as 2 separate devices, even though that would be a possibility. Other devices could have multiple/similar outputs. 

Or there could be a specification to **what** do we want to turn on in the trait - supply some attributes to the OnOff trait. Have one default and include change it when you hear a keyword. But the solution above would be easier to implement on both sides I think. 

_Example usage:_
Hey Google, turn off relay on Power Controller.
Hey Google, switch power relay off

Thanks!

**Comment by devunwired** [comment]
Thanks for your feedback!
We have an official form on the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1295039) to request new names for modes and toggles. Please file this there so we can track it appropriately.

**Comment by DenisVCode** [comment]
Thanks, will do! Could you please reflect this in the docs? Since there is the Github issue as a recommended way. https://developers.google.com/actions/smarthome/reference/traits/toggles
https://developers.google.com/actions/smarthome/reference/traits/modes

**Comment by devunwired** [comment]
Ah yes! Thank you for pointing that out.
