### ISSUE TITLE
ReportState Dashboard updates, App GUI not

### ISSUE THREAD

**Issue by symdeb** [actions-on-google/smart-home-nodejs#447]
Continue closed item #441 after the request to verify this first in the GCP dashboard app. 

Thus, build the GCP Dashboard. Sending a ReportState from my cloud by a script I can see the changes there (pic), but the status of the [switch] control (on/off) in the mobile Home App GUI is not updating and no intents are incoming in on the API endpoint. When changing the state is the app itself I receive the EXECUTE and QUERY intents. Is this normal behavior that the GUI does not update and no QUERY's are sent upon Google's cloud receiving a ReportState ?

![after_report_state](https://user-images.githubusercontent.com/19564066/63570379-8900f200-c5af-11e9-9048-baa6a4fb058f.PNG)

Response from ReportState
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcx"
}

**Comment by devunwired** [comment]
A similar issue was recently filed in the public issue tracker:
https://issuetracker.google.com/issues/139688477

Please feel free to upvote that issue to track its progress, or add any additional relevant comments that may be specific to your use case.

**Comment by symdeb** [comment]
Been almost two weeks without an response on the tracker.  I am running the dashboard under a different project than the actions/ Oauh2 /account linking integration that does the callbacks, Since I can see the devices in in the dashboard, so it does not look like that is the issue (I have not compiled and linked to the dashboard code to the actions project) .

**Comment by symdeb** [comment]
Not sure why this topic is being closed. This  item should be open unless this "won't be fixed"
The App still does update when sending a ReportState while the dashboard does.
It's also been reported on IOS now. See issue tracker. For example Samsung SmartThings app updates the state of a device immediately when a state change is send to the Gateway.
