### ISSUE TITLE
OAuth consent screen - authorised domains problem

### ISSUE THREAD

**Issue by kiralikbeyin** [actions-on-google/smart-home-nodejs#450]
Issue is not directly related with smart-home-nodejs but it is a part of google actions. Developers like me will face with this after publishing their app.

@Fleker I followed your tutorial https://medium.com/google-developers/authenticating-smart-home-actions-for-the-google-assistant-with-auth0-b6fda3d2ee3d

auth0 uses its own client ID and secret for developing. I have to connect my social connection : https://auth0.com/docs/connections/social/google

When i enter
https://console.developers.google.com/apis/credentials/consent?project=XXXXX
for creating credential it asks "Authorised JavaScript origins" and "Authorised redirect URIs" , i tried to add and this time it says "Invalid Origin: Domain must be added to the authorised domains list before submitting."
so i followed the link https://console.developers.google.com/apis/credentials/consent?project=XXXXX&duration=P1D to add **auth0.com** but i couldnt save

![image](https://user-images.githubusercontent.com/10079333/63721307-a22ccb80-c859-11e9-9eb3-94c058c81fec.png)
_Tracking_ _Number_: _c3902642649216229_

 
This didnt help : https://support.google.com/googleapi/answer/6158849?hl=en-GB

**Comment by kiralikbeyin** [comment]
There is no problem. Maybe this can  explain my problem bettet:
Please try to add your own client ID and key to auth0.com. Default client ID and key is only for development test.
https://auth0.com/docs/connections/social/google

Also note that if you try to save oauth content screen it doesnt save..it doesnt accept URL link of my app's term because it is not in authorized domains.

I didnt changed anything and made an app submit in aog. They didnt approved it because of 1. Your Action violates our Privacy & Security policies. The Terms of Service URL is missing, but is required for actions implementing account linking. Your Terms of Service URL must link directly to the page or document containing your Terms of Service.

I see URL in aog but the same URL in oauth content screen is in red borders..

**Comment by Fleker** [comment]
So I followed the doc and things worked without issue for me. It's not clear why you've run into the issue you did.

**Comment by kiralikbeyin** [comment]
I cant add Authorized Domains in OAuth consent screen https://console.developers.google.com/apis/credentials/consent?project=XXXXX&duration=P1D please can you try?

Re-submitted my app in aog i hope they read testing instructions:

> I am saving Privacy Policy in Privacy and consent of aog but when i check https://console.developers.google.com/apis/credentials/consent?project=xxxxxx&duration=P1D OAuth consent screen --> Application Privacy Policy link is in red borders which doesnt accept https://xxxx.com/xxx-xxx

> My app aprroved several times before with the same link (https://xxxx.com/xxx-xxx) but when i tired to add Authorised domains (xxxx.com and auth0.com) in OAuth consent screen i see red borders : "Invalid domain: URL must be hosted on a domain listed in the 'Authorised domains' section."

<img width="1222" alt="Screenshot 2019-08-29 11 25 29" src="https://user-images.githubusercontent.com/10079333/63924516-18dfe980-ca51-11e9-9889-20f65f163722.png">


<img width="740" alt="Screenshot 2019-08-29 11 28 08" src="https://user-images.githubusercontent.com/10079333/63925060-16ca5a80-ca52-11e9-9cd5-d39fd5cba5ff.png">

**Comment by kiralikbeyin** [comment]
@Fleker nobody read my testing instructions and app was not approved..

"1. Your Action violates our Privacy & Security policies. The Terms of Service URL is missing, but is required for actions implementing account linking. Your Terms of Service URL must link directly to the page or document containing your Terms of Service, and it must be a public document. It must be written in each of the languages your Action is enabled for."

**Comment by Fleker** [comment]
Adding authorized domains works for me. It's not clear what error you're running into. I'd recommend trying to contact support.

**Comment by kiralikbeyin** [comment]
@Fleker 
I created a new project and i can add authorized domains no problem.

I asked help from gcp online chat yesterday...

Today when i tried to add new authorized domain "web.app" and it throws error with a tracking number but it accepts xxx.web.app and saved..

Problem source:
xxx.web.app which is alternative for xxx.firebaseapp.com was published from google 1 month ago and my gcp mixed up something. New project accepts "xxx.web.app" not "web.app" but my real projects shows only wep.app in authorized domains. 

I will give more info next week.

**Comment by Fleker** [comment]
Ah I'm glad that you were able to resolve your issue.

**Comment by kiralikbeyin** [comment]
@Fleker At last i found the solution.
Support email in OAuth consent screen must be gmail account. Other email which comes from AOG console makes problem (i wrote my company email in AOG)

**Comment by uchennapaulemmanuel** [comment]
trying to create authorized domain of localhost:300 instead is show this error "
Invalid domain: must not specify the scheme. (http:// or https://)"
