### ISSUE TITLE
test App disappear in Google Home

### ISSUE THREAD

**Issue by chenliuyun** [actions-on-google/smart-home-nodejs#452]
Hi, I create a Smart Home project for test.
About two weeks ago, everything was fine.
I recently change something, and wanted to test it. But the test app disappeared in the app list. This has happened before, it was fine after I opened the sharing [URL](https://console.actions.google.com/project/switchbottest/simulatorcreate?isDeepLink) to confirm it again.
But this time,the web show like this:
![image](https://user-images.githubusercontent.com/13832263/64090381-6f189980-cd7d-11e9-9272-2f8a6a8f6d79.png)
All buttons are disabled. And the test app still disappear in the Google Home app.
I tried it many times, it is  the same result.
Please help me. Thanks

**Comment by chenliuyun** [comment]
After input a server url in “on device testing” section. Everything is ok.
![image](https://user-images.githubusercontent.com/13832263/64154772-0fe18480-ce64-11e9-90ae-1498ab53c715.png)

**Comment by devunwired** [comment]
Just to clarify for anyone who may come upon this issue in the future, the **On device testing** URL is for use with the [Local Home SDK](https://github.com/actions-on-google/local-home-sdk). It is not related to testing your cloud fulfillment.

What most likely happened here is a temporary error in saving the console project caused an issue in re-enabling the test configuration. Once you were able to save changes in the project again, testing began to work.
