### ISSUE TITLE
Deprecated device types ?

### ISSUE THREAD

**Issue by symdeb** [actions-on-google/smart-home-nodejs#454]
Happened to notice yesterday that the google action docs had a large update. Pages are updated with new device types and traits (as announced on I/O). Also this page was updated https://developers.google.cn/actions/smarthome/guides/ but It seems that PHONE,SOUNDBAR,SPEAKER and TV device types are deprecated but no mention was made of this. 
The deprecation of traits ColorSpecturm and ColorTemperature were listed. Were or is there a summary if or what changes were made to existing devices/traits and attributes ?
P.S: Interestingly,  the definition of device types does not seem the list the trait LightEffects as a recommended trait.. https://developers.google.com/actions/smarthome/guides/light

**Comment by Fleker** [comment]
There has never been pages in the docs for types PHONE, SOUNDBAR, SPEAKER, or TV.

Many smart lights don't have a LightEffect mode. They can implement it if they want, but it may not be expected.

Changes and updates to the platform have been posted in the [Reddit developer community](https://www.reddit.com/r/GoogleAssistantDev/) with the `smart-home` flair.

**Comment by symdeb** [comment]
https://developers.google.com/assistant/sdk/reference/device-registration/model-and-instance-schemas
![image](https://user-images.githubusercontent.com/19564066/64306270-c9576b80-cfc4-11e9-8702-f75a3802d674.png)

**Comment by Fleker** [comment]
Assistant SDK device types are not necessarily meant for smart home device types. For smart home, you should defer to the official docs.

**Comment by proppy** [comment]
Closing as obsolete.
