### ISSUE TITLE
how to add real device in smart home action

### ISSUE THREAD

**Issue by mduzgun** [actions-on-google/smart-home-nodejs#457]
Hi, I created smart home action, I can add virtual device using Google Home App.

I want to add real device to smart home action.

For example, I want to C by GE light to smart home action by using Google Home App. 
How to do it?

**Comment by Fleker** [comment]
If you are a device manufacturer, you will know how to connect to the device. If the device has an API, you can follow that documentation to connect. The platform doesn't provide access to have developers access the devices from other projects.

**Comment by mduzgun** [comment]
Infact, I want to get my device list which are connected Google Home Mini. 

How to get device name-room list in the Google Home?

For example,  C by GE light - kitchen etc. (only name and room info)

**Comment by Fleker** [comment]
There is no developer API to access all the devices for a given user.

**Comment by kiralikbeyin** [comment]
@mduzgun  @culuturk arkadaşlar tam olarak ne yapmak istiyorsunuz yardımcı olabilirim. 
need help?

**Comment by mduzgun** [comment]
@kiralikbeyin indeed, I want to get all connected smart home device list on google home. Is there any your idea?

**Comment by proppy** [comment]
See https://developers.google.com/assistant/smarthome/reference/rest/v1/devices/sync
