### ISSUE TITLE
ArmDisarmTrait error

### ISSUE THREAD

**Issue by DewGew** [actions-on-google/smart-home-nodejs#459]
When I disam or arm my security system. GA says that "There was an error controlling security device" but  i dont get any errors in my payload and the device is switching correct.

Payload:
`{'inputs': [{'payload': {'commands': [{'execution': [{'params': {'arm': False}, 'challenge': {'pin': '1234'}, 'command': 'action.devices.commands.ArmDisarm'}], 'devices': [{'id': 'Security104'}]}]}, 'intent': 'action.devices.EXECUTE', 'context': {'locale_country': 'US', 'locale_language': 'en'}}], 'requestId': '1408569265149581125'}`

Any hint whats the problem? Challenge?

**Comment by Fleker** [comment]
What's your response?

**Comment by DewGew** [comment]
Response:
```
{
  "commands": [
    {
      "ids": [
        "Security104"
      ],
      "states": {
        "currentArmLevel": "Normal",
        "isArmed": false,
        "online": true
      },
      "status": "SUCCESS"
    }
  ]
}

```

**Comment by DewGew** [comment]
I found the issue. I need to change status before sending request to my device. Now its working correct
