### ISSUE TITLE
Harmony remote device type

### ISSUE THREAD

**Issue by i8beef** [actions-on-google/smart-home-nodejs#460]
It appears that some people are starting to see Logitech Harmony Activities lighting up in Google Home. Up to this point, I've been fronting these selections as OnOff traits. I'm curious if there is a device type that aligns with these "Remotes" that is publicly usable, and what the voice syntax for the type? 

https://www.reddit.com/r/googlehome/comments/d87uhm/finally_you_can_start_you_logitech_activities/

**Comment by Fleker** [comment]
There is [no public remote device type](https://developers.google.com/actions/smarthome/guides).
