### ISSUE TITLE
Google Smart Home Not Working

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#463]
we have submitted google smart home twice for google certification. First time it got rejected because we did no implement report state. But device operation through google home was successful and there were no issues.
Second time the rejection reason is google home is not responding for EXECUTE intent. before shipping our devices we tested our devices using google assistant it was working fine. Now when i look in google log i can see two errors

* Back_end FAILURE
* Agent Responded Empty Json

When i say turn on and turn off intents, devices are operated but assistant is not responding back
This was working fine earlier and i have not made any changes

Then i have created a new project with the same back end code and that was working fine. we did not change anything for our side and the newly created project was working and google home was responding also.

**Comment by devunwired** [comment]
I see you also filed this issue on the [public issue tracker](https://issuetracker.google.com/issues/141696612), so I'm closing this instance.
