### ISSUE TITLE
Oauth2 access_token, how to find user more easy : Question

### ISSUE THREAD

**Issue by kiralikbeyin** [actions-on-google/smart-home-nodejs#464]
@Fleker 
In this lib we use faketoken..
When executing or sync etc we get a header from google with authorization and trying to find the user everytime for every action https://github.com/actions-on-google/smart-home-nodejs/blob/7f64994eb120a714f24b50cf1613c7392aeab5a4/src/auth-provider.ts#L33

In a real project my access_token lives 1 hour after that refresh_token works to get new access_token.

I tried to make a global variable for access_token and use it 1 hour for the user BUT when another user makes action global variable changes to his access_token.

Question : How can i hold access_token for 1 hour to a spesific user without searching in database or making a http call to ```https://www.googleapis.com/oauth2/v2/userinfo?alt=json&access_token=``` or something else to find the user from access_token?

**Comment by Fleker** [comment]
The best way is to use a database to store access tokens in a production environment. Keeping it in memory may not scale, and making it global could allow it to leak.

**Comment by proppy** [comment]
Closing as obsolete.
