### ISSUE TITLE
npm run start local, ngrok error feedback.

### ISSUE THREAD

**Issue by Keele520** [actions-on-google/smart-home-nodejs#465]
when npm run start local, always get the error feedback.
Hope to get some advise. Thanks.
![npm run start local ngrok error](https://user-images.githubusercontent.com/56055405/66033697-5d701080-e53a-11e9-83f2-f3ec28e9d24a.png)

**Comment by Fleker** [comment]
This is the same issue as #431, although for some reason I've been unable to reproduce this error on my machine when running that command.

**Comment by Fleker** [comment]
I've been able to reproduce the error.
