### ISSUE TITLE
SERVICE ID NOT FOUND

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#470]
https://developers.google.com/assistant/smarthome/develop/report-state#error_responses

i use this link to retrieve the agentUserID when i replace this link with my email and project id i am getting an error like "service id not configured"

https://gala-demo.appspot.com/app?login_hint=email@gmail.com&service_id=your_project_id_dev
please help me on this

**Comment by devunwired** [comment]
1. Make sure testing is enabled in the Actions console for your project
1. Ensure that you keep the `_dev` suffix on your project id when you replace it in the URL

**Comment by raju102** [comment]
Thanks deve.._dev suffix was missing

i have one more question

One feedback we got after submission is Grouped devices appear after linking. All device grouping should occur only through user interaction with Google Home.
In our platform we have a group concept, where we can add devices to it. For a user in our platform using google home if he has multiple groups with many devices, during device discovery now thos groups will also be listed in google home app. If we avoid this group during discovery it would be difficult for the user to again create a group using GHA..Is it mandatory that we should remove group listing during discovery

**Comment by devunwired** [comment]
Please direct your requests regarding your action review to the review team that provided you the feedback. GitHub is a forum to discuss technical issues with respect to the sample project.
