### ISSUE TITLE
GOOGLE HOME CANNOT ENABLE TEST SIMULATOR

### ISSUE THREAD

**Issue by raju102** [actions-on-google/smart-home-nodejs#473]
Hi
i created a new google home developer account and i configured all actions and Oauth details
but when i try to enable the test simulator it shows "Sorry something went wrong"

**Comment by elupus** [comment]
Same here

**Comment by elupus** [comment]
In my case it's an old draft that used to work. Now and since a while back, I can't start a test on this draft. All previously synced devices worked fine even though I could not start test.

I did the mistake of unlinking account. Now I can't re-linkit.

One oddity is that I receive above mentioned error when starting test, and the test is not indicated as started. If I leave the simulator and return. It looks like the test is running, but I can't find the test instance in Google home, nor did sync command work before I unlinked the account.

**Comment by raju102** [comment]
Yes the same issue is happening here. i cannot run a test on my new draft. in my google home app old version is showing and i am able to run the old version successfully but cannot start a new version

**Comment by devunwired** [comment]
Hello, there were some recent changes to the Actions console which may have affected this. Fixes should now be in place, so please test again and indicate if you are still having issues with your project.

**Comment by elupus** [comment]
It is resolved for me!

**Comment by raju102** [comment]
this issue is still there for me

**Comment by raju102** [comment]
I am not able to create a new test session it says something went wrong

**Comment by raju102** [comment]
![issueGoogle](https://user-images.githubusercontent.com/19406211/68284329-4aa1ac00-00a3-11ea-9e2b-ea085b402b07.png)

**Comment by latchukarthick98** [comment]
Any updates in this issue. In my case I could enable test but the action is not visible in Home Control section of Google Home app. Creating a new project did show up in the actions list. But the old project isn't showing up.

**Comment by kpbala123** [comment]
Hi, 
I am trying to create a new google smart home service and i added a rgb light for testing. For onoff operation and colour change, it works fine. But for brightness change, execute request is not getting from the google action.

**Comment by AndrewBuntsev** [comment]
Looks like Smart Home actions are not allowed in the simulator. The message "We're sorry, but something went wrong. Please try again." becomes more detailed if open the debug tab
"Sorry, this action is not available in simulation"

![image](https://user-images.githubusercontent.com/44885451/102754305-e0d88480-43c0-11eb-9ef0-72171196a601.png)

**Comment by proppy** [comment]
@AndrewBuntsev can you give more details the query that returned this error?

**Comment by AndrewBuntsev** [comment]
It was a month ago, I have already resolved it
