### ISSUE TITLE
how can i put a "agentUser id" to homegraph & there is a problem to help:

### ISSUE THREAD

**Issue by brewlin** [actions-on-google/smart-home-nodejs#474]
# 1. got error when doing test 'Test suite for smart home'
```
Failed to get device list from HomeGraph: Requested entity was not found. 404
```
## 2. submit param to this api always got error:https://homegraph.googleapis.com/v1/devices:requestSync
```
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}
```
## 3. maybe the question is how to put a agentuserId to homegrah
how to connected the agentuserid to homegrah?

now i can't find some api to do this.i just find some query api:
```
https://homegraph.googleapis.com/v1/devices:{api}
query
reportStateAndNotification
requestSync
DELETE https://homegraph.googleapis.com/v1/{agentUserId=agentUsers/**}
```

**Comment by Fleker** [comment]
The agent user ID is something you return in [your initial SYNC response](https://developers.google.com/assistant/smarthome/develop/process-intents#response_format).

**Comment by brewlin** [comment]
# sync response like this:
```
{
	"requestId":"4442832499392385678",
	"payload":
	{
		"devices":
		[
			{
				"id":"250000000218",
				"type":"action.devices.types.LIGHT",
				"traits":
				["action.devices.traits.OnOff","action.devices.traits.Brightness","action.devices.traits.ColorSetting"],
				"name":{"defaultNames":["银河风云Macbee型LED灯"],"name":"灯","nicknames":["250000000218"]},
				"willReportState":false,"attributes":{"colorModel":"rgb"},
				"deviceInfo":{"manufacturer":"深圳市银河风云网络系统股份有限公司",
				"model":"i+rfllamp2","hwVersion":"1.1","swVersion":"1.1"},
				"customData":{"fooValue":12,"barValue":false,"bazValue":"dancing alpaca"}
			}
		],
		"agentUserId":"87157"
	}
}
```
## it doesn't work. 
when i submit param to this api always got error:https://homegraph.googleapis.com/v1/devices:requestSync

**Comment by devunwired** [comment]
You might be receiving this error from the test suite for a few different reasons:

1. The `agentUserId` you entered into the test suite is incorrect.
1. The service account key you uploaded doesn't have access to the project with the `agentUserId` you entered.
1. The `agentUserId` hasn't been linked to the Google Assistant from your service before running the test.

Without the last step, there won't be any data in Home Graph for that `agentUserId` for the test suite to verify (the test suite doesn't send intents to your service, it only verifies Home Graph state).

**Comment by brewlin** [comment]
thanks，wowo！，i don't do anything but it's work, perhaps need wait a moment before test suite to verify
