### ISSUE TITLE
invalid_grant on calling /oauth2/token POST API

### ISSUE THREAD

**Issue by zainbhimani** [actions-on-google/smart-home-nodejs#475]
I have been trying to call reportStateAndNotification API as documented in ,

https://developers.google.com/assistant/smarthome/reference/rest/v1/devices/reportStateAndNotification#ReportStateAndNotificationDevice

For calling this API it is required to pass Bearer access token. In order to get access token it is required to call https://accounts.google.com/o/oauth2/token POST API by passing JWT token. But unfortunately it is giving me following error,
 
{
    "error": "invalid_grant",
    "error_description": "Invalid JWT Signature."
}
 
Here are the steps that I am following to create JWT token,
 
1.  In the below JSON, I have changed iss with my service account key email. iat with current time. exp with current time plus one hour time.
{
  "iss": "<service-account-email>",
  "scope": "https://www.googleapis.com/auth/homegraph",
  "aud": "https://accounts.google.com/o/oauth2/token",
  "iat": <current-time>,
  "exp": <current-time-plus-one-hour>
}
2. I signed this JWT payload with private key define in service account key by calling following JS code,
 
    let secretKey = [private key from service account key]
    let payload = {
        "exp": Math.floor((Date.now() + 1000  60  60)/1000),
        "iat": Math.floor(Date.now()/1000),
        "iss": "[email from service account key]",
        "aud": "https://accounts.google.com/o/oauth2/token",
        "scope": "https://www.googleapis.com/auth/homegraph"
    }
    try {
        // Secret
        var token = jwt.sign(payload, secretKey, (err, jwt) => {
            console.log(jwt); 
        });
    } catch (e) {
        console.log("Error: +++++++++++++++++ ", e);
    }              
 
3. Calling https://accounts.google.com/o/oauth2/token by passing following,

Headers:
Content-Type : application/x-www-form-urlencoded
Authorization : Bearer [JWT]
 
Body:
Grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
Assertion : [JWT]

**Comment by Fleker** [comment]
Is that Javascript? Why not use the [Javascript library](https://github.com/actions-on-google/actions-on-google-nodejs)?

**Comment by proppy** [comment]
Closing as obsolete.
