### ISSUE TITLE
List of all Traits with attributes and commands

### ISSUE THREAD

**Issue by homefefeld** [actions-on-google/smart-home-nodejs#476]
I'm looking for the full list of traits with attributes.  

Obviously, I can get the list of trait from the developer's page:  developers.google.com/assistant/smarthome/traits
but I need to click on individual traits to get the list of associated attributes and commands?
I'm looking for a place where I can get all of them in one shot.
ideally I would like them in a JSON format.
Does anyone have this?

**Comment by Fleker** [comment]
What is your intention with this list?

**Comment by i8beef** [comment]
I have some powershell scripts that scan the Google documentation and generate some enum classes for my implementation. It'll get you DeviceTypes and DeivceTraits that each supports... but not commands. Unfortunately the Google doc site doesn't 100% follow a single standard, so I was never able to get it to grab the command list in a reliable way.

https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/blob/master/src/generateDeviceClasses.ps1

https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/blob/master/src/generateTraitClasses.ps1

Note @Fleker *I* would love to see a structured document published that we could more easily generate this sort of stuff from, ideally one with Google Devices and the Traits they support, and one of Traits and the Attributes, Commands, and State they support... But that's just a selfish desire for something that would make the lives easier for those of us supporting FULL Google Home support across all device types (it got too hard to manually keep up to date with your full list of device types / trait changes, so I had to switch over to generating as much as I could from documentation). Bonus points for specifying "required" / "required if X" information in that doc somehow so we can generate validations....

**Comment by dominikkarall** [comment]
I really like that idea as it's currently impossible to get notified about changes. I always need to click through all traits to see if some new stuff is there, like new attribute, new error option, etc.
Please provide the documentation in some sort of machine readable format (e.g. json). Thx!

**Comment by proppy** [comment]
We recently started working on this repository: https://github.com/actions-on-google/smart-home-schema which could provide the basis of what was requested here.

Let's continue the discussion there (since this repo is more about the Node.js backend for the sample).
