### ISSUE TITLE
Error 500 in all requests

### ISSUE THREAD

**Issue by joaoguilhermee** [actions-on-google/smart-home-nodejs#477]
All of my requests are receiving error 500 from google app engine.
I dont know if is in project or some configuration.

Thanks.

This is my url and I have done only the instructions  steps.
https://my-house-3c6f0.appspot.com/

**Comment by Fleker** [comment]
A 500 is indicative of a server error. When I open that URL I get an error. I think you should review server logs to see if there is a deployment issue.
