### ISSUE TITLE
async callback process

### ISSUE THREAD

**Issue by VargentDi** [actions-on-google/smart-home-nodejs#479]
after reading the 'pending' FAQ and some issues here, still wanna ask if there could be any proper channel for our company to partner to complete 'pending' execution and voice report state

**Comment by Fleker** [comment]
There is no voice-based notification for a state completion.

**Comment by VargentDi** [comment]
hi, thanks for replying to me,
 
just want to be clear, we are working with alexa and they have 'you door is closed' after 'closing your doors', so there is no way for that happen in google smart home?

**Comment by devunwired** [comment]
I would recommend filing a Feature Request in the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) regarding this.

Asynchronous responses to the user are not currently supported, but when using a `PENDING` execution response you should still report the completion via [Report State](https://developers.google.com/assistant/smarthome/develop/report-state). This ensures the latest state is available for future queries or touch control interfaces.
