### ISSUE TITLE
Two-factor authentication language support

### ISSUE THREAD

**Issue by DewGew** [actions-on-google/smart-home-nodejs#480]
What languages doeas Two-factor authentication support?
Swedish and german seems not to work.

**Comment by devunwired** [comment]
Two-factor authentication does not have a specific restricted set of language support, so it's aligned with the existing [supported languages](https://developers.google.com/assistant/smarthome/traits#supported-languages) for smart home.

If you are experiencing issues working with it in a particular language, I would recommend filing an issue on the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) for the platform.

**Comment by DewGew** [comment]
See public issue tracker [here](https://issuetracker.google.com/issues/145684723)

**Comment by DewGew** [comment]
Seems no one has an answer on this issue..
