### ISSUE TITLE
shell error during setup

### ISSUE THREAD

**Issue by adrianoellero** [actions-on-google/smart-home-nodejs#483]
from the shell editor, if I type the following command:

npm run create-firebase-config

I get the following errors:

Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-light@0.0.1 create-firebase-config: `firebase setup:web > ./src/firebase-setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-light@0.0.1 create-firebase-config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adriano_ellero/.npm/_logs/2019-12-22T13_07_44_829Z-debug.log

In the end the log file is empty and I can run any action from google action console (neither with Ngrok nor with Google App Engine.

Any suggestion?
Many thanks in advance

**Comment by Fleker** [comment]
First you will need to create a Firebase project and add it with `firebase use --add` so that it properly associates itself with the Firestore database.

**Comment by proppy** [comment]
Closing as obsolete.
