### ISSUE TITLE
The test suite is stuck 

### ISSUE THREAD

**Issue by brewlin** [actions-on-google/smart-home-nodejs#484]
The test suite is stuck

![image](https://user-images.githubusercontent.com/17773920/71428642-f7d88e00-26fc-11ea-95d7-aa8060c53257.png)
- As shown above, the execution steps have been stuck there, but my backend has not received the request
- I have achieved the report state, but still cannot pass the test. reportstate:`https://homegraph.googleapis.com/v1/devices:reportStateAndNotificatio`

**Comment by Fleker** [comment]
Did you hear the test suite run verbally?

**Comment by brewlin** [comment]
i don't understand

**Comment by brewlin** [comment]
When running the test suit, the backend did not receive the request

**Comment by brewlin** [comment]
Test suite I run on a web page

**Comment by Fleker** [comment]
Have you fulfilled the [prerequisites](https://developers.google.com/assistant/smarthome/tools/smart-home-test-suite)?

**Comment by proppy** [comment]
Closing as obsolete.
