### ISSUE TITLE
It took me almost half a year to publish the review skills, and there is still no progress to date. Has anyone encountered this?

### ISSUE THREAD

**Issue by brewlin** [actions-on-google/smart-home-nodejs#485]
![image](https://user-images.githubusercontent.com/17773920/71428836-5f430d80-26fe-11ea-8240-a2eccad2508e.png)

I waited for a long time to cancel and resubmitted many times.

**Comment by Fleker** [comment]
Did you run [the test suite](https://developers.google.com/assistant/smarthome/tools/smart-home-test-suite)?

**Comment by brewlin** [comment]
yes

**Comment by proppy** [comment]
Closing as obsolete.
