### ISSUE TITLE
support for actions on google developer

### ISSUE THREAD

**Issue by TA2k** [actions-on-google/smart-home-nodejs#486]
Sorry for creating this issue here. But there is no feedback or progress in the official issue tracker.

It feels like there is only a small capacity to improve actions on google.
You created an issue in June but there is no feedback on this basic request.
https://issuetracker.google.com/issues/136103089

Also the number of new traits in the last 6 months is almost zero. I see only statuscode where you can response with predefined exceptions.
There is no possibility to get plain commands send to a nest mini or google assistant.

Something like a changelog for traits is still missing. 

It is really though to support google home instead of focusing only on alexa where you get improvements on regular basis.

**Comment by Fleker** [comment]
We're aware of the request for a Sensor trait.

In the past year there have been [numerous traits and types](https://developers.google.com/assistant/smarthome/traits) added to the platform that you can use including StatusReport, Fill, Cook, and several others. Each time there is an update, it is posted in the [Reddit community](https://www.reddit.com/r/GoogleAssistantDev/search/?q=flair_name%3A%22smart-home%22&restrict_sr=1&sort=new).
