### ISSUE TITLE
Updating Application name - QUESTION

### ISSUE THREAD

**Issue by HomeHomeApp** [actions-on-google/smart-home-nodejs#487]
@Fleker 

Sorry wrting here like an issue but it is not related with this repo. I couldnt find an answer from Google and im trying here...

Android device>Google Home>Add and manage>Set up device>Works with Google>"App name"
My app published 6 months ago. Google actions team said ask to googlenest. (My latest deploy approved from Google actions with updated App name and description and all the other things..)

I also made changes under  Google cloud console > OAuth consent screen and it is verified.

App name changed under https://assistant.google.com/explore/i?intent=ControlAppliancesAndFixtures&category=19&hl=en-US but Android device>Google Home>Add and manage>Set up device>Works with Google>"App name" didnt change.

Any idea where to ask these changes and get a solution?

**Comment by Fleker** [comment]
File a bug here: https://issuetracker.google.com/issues/new?component=655104 and we can direct it to the correct person to handle it.
