### ISSUE TITLE
hello how to show water level, any idea ( automatic water tank level )

### ISSUE THREAD

**Issue by harymk** [actions-on-google/smart-home-nodejs#488]
# Issue Guidelines

This repository contains sample code for the Google [smart home platform](https://g.co/dev/smarthome).
Please restrict filing GitHub issues to those related to the sample code contained here.

If you have issues or feature requests related to Google smart home, please file them using the
[public issue tracker](https://developers.google.com/actions/smarthome/support).
For general development questions related to Google smart home, please use the `google-smart-home` tag
on [StackOverflow](https://stackoverflow.com/questions/tagged/google-smart-home).

**Comment by ToniCorinne** [comment]
The[ `Fill` trait](https://developers.google.com/assistant/smarthome/traits/fill) enables you to report the `currentFillLevel` of a device, as well as the `availableFillLevels` of the device.

**Comment by harymk** [comment]
which device type i can use for this

**Comment by harymk** [comment]
hello

**Comment by Fleker** [comment]
You can use any device type with any set of traits.
