### ISSUE TITLE
DISCONNECT

### ISSUE THREAD

**Issue by VargentDi** [actions-on-google/smart-home-nodejs#491]
hi there

we have created two different smart home project, so we want to allow our customer only link one instead of both of them, how could we issue a disconnect intents

**Comment by VargentDi** [comment]
on our end

**Comment by Fleker** [comment]
I don't think there's a way to do have both projects linked, as each of them would contain different devices and are seen as completely independent.

**Comment by VargentDi** [comment]
thanks for reply 

so we created two different google action projects, each one of them is naming to reflect they are different brand, and login page and log in url will be different

but the fact they are connected to same backend api. So if our customer link both projects on their end, google home will show the exactly same name since it is same door in different smart home actions. only difference is the brand , log in account , credentials and door will be same in our database  

we are trying to avoid such issue, so again my question : is there a way to issue a disconnect intents to our fullfilment to unlink this action project

**Comment by Fleker** [comment]
If you have a singular backend API, then you may be able to tell the customer that they already have an account with the other provider. If you get a disconnect intent, you may be able to unlink both if you can associate the access tokens between the two.

**Comment by proppy** [comment]
Closing as obsolete.
