### ISSUE TITLE
Report State Responding as 401 Unauthorized

### ISSUE THREAD

**Issue by varadujjainkar** [actions-on-google/smart-home-nodejs#497]
Hi Team,

Receiving 401 Unauthorized in the response of ReportStateAndNotification, everything as working as expected till Friday morning. No changes have been made from our side.  

ReportStateAndNotification: https://homegraph.googleapis.com/v1/devices:reportStateAndNotification

**Comment by Fleker** [comment]
Is there something different about the service account key or agent user ID you are using?

**Comment by varadujjainkar** [comment]
Nope! It suddenly stopped working

**Comment by proppy** [comment]
@varadujjainkar are you experiencing this with this sample or your own implementation?

**Comment by proppy** [comment]
Closing as obsolete.
