### ISSUE TITLE
In Action Logs getting error failed with code: BACKEND_FAILURE

### ISSUE THREAD

**Issue by varadujjainkar** [actions-on-google/smart-home-nodejs#498]
![image](https://user-images.githubusercontent.com/22313829/74722769-7f56ff00-525f-11ea-805d-73b55189d2a5.png)

**Comment by Fleker** [comment]
Please provide more information about how you arrived at this issue to see if it can be reproduced.

**Comment by varadujjainkar** [comment]
While performing Queries Command we are getting this logs in Action Logs under logs viewer.

**Comment by proppy** [comment]
@varadujjainkar are you experiencing this with this sample or your own implementation?

**Comment by proppy** [comment]
Closing as obsolete.
