### ISSUE TITLE
Documentation for Traits

### ISSUE THREAD

**Issue by andiaa734** [actions-on-google/smart-home-nodejs#499]
There are now Smart TVs available with Google Assistant. They support Channel, Volume, Input Selector. So, why is there no public documentation for this traits?
It would be very helpful for implementing my personal Smart Home Integration.

**Comment by devunwired** [comment]
These capabilities are not currently available through the Actions on Google developer platform. We provide [reference documentation](https://developers.google.com/assistant/smarthome/traits) only for types and traits that are available to the public developer community.

There are open feature requests for many of the items you mentioned. I would encourage you to star/track these issues for updates on when they might be coming for public use:
* [TV device](https://issuetracker.google.com/issues/139481709)
* [Channel trait](https://issuetracker.google.com/issues/136103830)
* [Volume trait](https://issuetracker.google.com/issues/136103828)
