### ISSUE TITLE
I can't invoke fan speed intent on AC_UNIT

### ISSUE THREAD

**Issue by 99207432** [actions-on-google/smart-home-nodejs#500]
I can't invoke fan speed intent on AC_UNIT,
setting as below:

` "type": "action.devices.types.AC_UNIT",`

` "traits": [
            "action.devices.traits.OnOff",
            "action.devices.traits.TemperatureSetting",
            "action.devices.traits.FanSpeed"
          ]`

```
 "attributes": {
            "reversible": false,
            "availableFanSpeeds": {
              "speeds": [
                {
                  "speed_name": "Low",
                  "speed_values": [
                    {
                      "lang": "en",
                      "speed_synonym": [
                        "low",
                        "slow"
                      ]
                    },
                    {
                      "lang": "de",
                      "speed_synonym": [
                        "niedrig",
                        "schleppend"
                      ]
                    }
                  ]
                },
                {
                  "speed_name": "High",
                  "speed_values": [
                    {
                      "lang": "en'",
                      "speed_synonym": [
                        "high"
                      ]
                    },
                    {
                      "lang": "de",
                      "speed_synonym": [
                        "hoch"
                      ]
                    }
                  ]
                }
              ],
              "ordered": true
            },
            "commandOnlyFanSpeed": true,
            "availableThermostatModes": "off,cool,heat,dry,auto",
            "temperatureTemperatureUnit": "C",
            "commandOnlyTemperatureSetting": true
          }
```
Looking forward to any helpful answer.

Thanks

**Comment by Fleker** [comment]
Can you post the full sync response and the commands you're saying?

**Comment by 99207432** [comment]
Hi Fleker,
 my  full sync response as below,
![image](https://user-images.githubusercontent.com/24696411/75742173-cd7ffe00-5d47-11ea-8064-dbc0ea18e787.png)
![image](https://user-images.githubusercontent.com/24696411/75742297-2fd8fe80-5d48-11ea-9f54-2b18a201c06e.png)
![image](https://user-images.githubusercontent.com/24696411/75742369-5ac35280-5d48-11ea-84b7-139bf8ca9d62.png)

I ask Google Assistant to "set ac speed to low", and I get search result.

**Comment by Fleker** [comment]
I'm reproducing this error on my side; filing a bug.

**Comment by 99207432** [comment]
Thank you for your reply!

**Comment by proppy** [comment]
Closing as this is unrelated to the sample and has already been escalated.
