### ISSUE TITLE
 I couldn't link devices that runs Android 9 and 10.

### ISSUE THREAD

**Issue by syarifuddin1** [actions-on-google/smart-home-nodejs#501]
I ran this setup and logged in using an phone that runs on Android Version 8, I can link the devices and control them but when I ran this setup and logged in using different phones that runs Android 9 and 10, it connects but I couldn't link the devices. What I need to do?

**Comment by Fleker** [comment]
I have not run into any issues linking on specific versions of Android. There may be a discrepancy with the type of phone (and the default browser) or the version of the Home app.
