### ISSUE TITLE
Change deviceID

### ISSUE THREAD

**Issue by syarifuddin1** [actions-on-google/smart-home-nodejs#502]
How do I change deviceId of the devices?

**Comment by devunwired** [comment]
The `deviceId` is reported in your [SYNC response](https://developers.google.com/assistant/smarthome/develop/process-intents#SYNC). To report changes in the SYNC metadata from your smart home Action, you need to use the [Request Sync](https://developers.google.com/assistant/smarthome/develop/request-sync) API to trigger an update.

Note that if you change the `deviceId` in a new SYNC, the platform will treat this as as one device being removed and a new device added.

**Comment by syarifuddin1** [comment]
> The `deviceId` is reported in your [SYNC response](https://developers.google.com/assistant/smarthome/develop/process-intents#SYNC). To report changes in the SYNC metadata from your smart home Action, you need to use the [Request Sync](https://developers.google.com/assistant/smarthome/develop/request-sync) API to trigger an update.
> 
> Note that if you change the `deviceId` in a new SYNC, the platform will treat this as as one device being removed and a new device added.

Yes I do aware of it but I want to assign a custom deviceId that writes to the Firestore. When I tried assign a string replacing the doc id, it does nothing.

export async function addDevice(userId: string,
    data: ApiClientObjectMap<string | boolean | number>) {
  await db.collection('users').doc(userId).collection('devices').doc(data.id as string).set(data)
}

**Comment by devunwired** [comment]
> Yes I do aware of it but I want to assign a custom deviceId that writes to the Firestore. When I tried assign a string replacing the doc id, it does nothing.

If you want to set custom parameters when a device is created, you can use the [Import JSON](https://github.com/actions-on-google/smart-home-frontend/blob/master/src/device-types/importer.js) device to build a device from a custom SYNC payload (including the id value).

Another option is to create the device type you want in the frontend, and then edit the device data directly in Firestore from the [Firebase Console](https://console.firebase.google.com/) to change values like the device id.

**Comment by syarifuddin1** [comment]
> > Yes I do aware of it but I want to assign a custom deviceId that writes to the Firestore. When I tried assign a string replacing the doc id, it does nothing.
> 
> If you want to set custom parameters when a device is created, you can use the [Import JSON](https://github.com/actions-on-google/smart-home-frontend/blob/master/src/device-types/importer.js) device to build a device from a custom SYNC payload (including the id value).
> 
> Another option is to create the device type you want in the frontend, and then edit the device data directly in Firestore from the [Firebase Console](https://console.firebase.google.com/) to change values like the device id.

Thank you for the answer given.
