### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by zoic21** [actions-on-google/smart-home-nodejs#503]
Hello

Yeah I known another link issue but this one is weird. I already have an google smarthome without any issue but we currently review code to improve it so we move to new server with new url.

We configure new URL in new smarthome application in google, on mobile I see my new application for link but when I click on it it's do nothing... No error, no call to my server no log in stackdriver nothing...

I test link with https://gala-demo.appspot.com/ and it's ok, I also test with oauth playground and it's ok (even SYNC it's ok).

Someone have ever see that ? For information same authentification is used for dialogflow and it's ok no problem...

Thank in advance

**Comment by devunwired** [comment]
> We configure new URL in new smarthome application in google, on mobile I see my new application for link but when I click on it it's do nothing... No error, no call to my server no log in stackdriver nothing...

Typically this means one of two things:
1. If you are making a change to your production Actions project configuration to test this, those changes don't propagate and you need to create a new draft project for review.
2. If this is a new draft project, test mode may not be fully enabled. You may need to [enable testing](https://developers.google.com/assistant/smarthome/develop/testing#setup) from both the **Test** tab and under **Develop > Account linking**.

**Comment by zoic21** [comment]
Ok it's change on production with new draft project. With new project it's ok. But how can I validate new evolution on production if I can't test it ?

**Comment by devunwired** [comment]
If you are able to validate your changes with a draft project, then you can use the same configuration in your production console project and submit for review. This is the guidance we have in the [smart home launch guide](https://developers.google.com/assistant/smarthome/develop/launching).

We have heard feedback from a few developers that this can be a bit awkward in some cases, but it is how the Actions console works today as project configuration changes are not propagated automatically after the Actions project is launched.
