### ISSUE TITLE
Issue with change of Fulfillment URL 

### ISSUE THREAD

**Issue by zoic21** [actions-on-google/smart-home-nodejs#508]
Hello

We recently make a new application for google home and it's change url for : 
- oauth
- fullfillment 

After 2 months for validation google approved application this night :-) but oauth go to new url no problem but fullfillment continu to call old url...

Are they any delay ? I see in mail it's can take 48h to pass in deployed status but I check I am in deployed status...

Thank in advance.

**Comment by devunwired** [comment]
Please contact ha-certification@google.com with your project details so the certification team can follow up on deployment status.
