### ISSUE TITLE
Feedback/Request - Smart Home Test Suite

### ISSUE THREAD

**Issue by chearmstrong** [actions-on-google/smart-home-nodejs#510]
The test suite is useful, but I think that having to invoke a device using the synthesized speech isn't always convenient - it's also very time consuming.

It would be extremely useful if there was another (additional) way to test the actions, where the requests is fired off directly to the API (without using audio/speech). This would speed it the process massively - I also think it could help with some continuous testing, as it could be automated.

Is this something you guys could look at - is it possible?

**Comment by proppy** [comment]
I believe this is now implemented, see the `signed in` mode described on https://developers.google.com/assistant/smarthome/tools/smart-home-test-suite
