### ISSUE TITLE
Not able to run the script 

### ISSUE THREAD

**Issue by Verma-v2** [actions-on-google/smart-home-nodejs#512]
I configured everything as per the readme.md instruction but when i tried to run using npm run build I got errors. Here is the complete log:
``

    smart-home-app-sample@0.0.1 deploy C:\Users\santo\Music\smart-home-nodejs-master
    npm run build && gcloud app deploy && gcloud app logs tail -s default

    smart-home-app-sample@0.0.1 build C:\Users\santo\Music\smart-home-nodejs-master
    tsc && cp src/*.json dist/
    'cp' is not recognized as an internal or external command, operable program or batch file. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! smart-home-app-sample@0.0.1 build: `tsc && cp src/*.json dist/` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the smart-home-app-sample@0.0.1 build script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm ERR! A complete log of this run can be found in:
    npm ERR! C:\Users\santo\AppData\Roaming\npm-cache_logs\2020-06-09T20_36_42_824Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! smart-home-app-sample@0.0.1 deploy: npm run build && gcloud app deploy && gcloud app logs tail -s default
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the smart-home-app-sample@0.0.1 deploy script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    ``
    npm ERR! A complete log of this run can be found in:
    npm ERR! C:\Users\santo\AppData\Roaming\npm-cache\_logs\2020-06-09T20_36_43_492Z-debug.log

complete log:
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle smart-home-app-sample@0.0.1~prebuild: smart-home-app-sample@0.0.1
6 info lifecycle smart-home-app-sample@0.0.1~build: smart-home-app-sample@0.0.1
7 verbose lifecycle smart-home-app-sample@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle smart-home-app-sample@0.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\santo\Music\smart-home-nodejs-master\node_modules\.bin;C:\Users\santo\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\santo\AppData\Local\Microsoft\WindowsApps;C:\Users\santo\AppData\Roaming\npm
9 verbose lifecycle smart-home-app-sample@0.0.1~build: CWD: C:\Users\santo\Music\smart-home-nodejs-master
10 silly lifecycle smart-home-app-sample@0.0.1~build: Args: [ '/d /s /c', 'tsc && cp src/*.json dist/' ]
11 silly lifecycle smart-home-app-sample@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle smart-home-app-sample@0.0.1~build: Failed to exec build script
13 verbose stack Error: smart-home-app-sample@0.0.1 build: `tsc && cp src/*.json dist/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid smart-home-app-sample@0.0.1
15 verbose cwd C:\Users\santo\Music\smart-home-nodejs-master
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error smart-home-app-sample@0.0.1 build: `tsc && cp src/*.json dist/`
22 error Exit status 1
23 error Failed at the smart-home-app-sample@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Fleker** [comment]
Run `./node_modules/.bin/tsc` to transpile the Typescript to Javascript. Then copy your JSON files from the `src` directory to the `dist` directory.

Then you can proceed with `gcloud app deploy`.

**Comment by Fleker** [comment]
What version of Typescript is being run? `./node_modules/.bin/tsc --version`

**Comment by proppy** [comment]
Closing as obsolete.
