### ISSUE TITLE
Home Graph Not updating device state

### ISSUE THREAD

**Issue by covid19-code** [actions-on-google/smart-home-nodejs#514]
HomeGraph not updating device state, I'm updating device status on each execution call by calling [reportState](https://developers.google.com/assistant/smarthome/develop/report-state).

All working fine within mobile app and cloud service, just HomeGraph not updating status, thus i'm not able to run [Test Suite For Smart Home](https://smarthome-test-suite.appspot.com/) successfully

**Comment by Fleker** [comment]
Are you getting a valid 200 back from the reportState call? Can you run the [Report State Dashboard](https://github.com/actions-on-google/smart-home-dashboard) and see whether the data is being uploaded correctly?

**Comment by proppy** [comment]
Closing as obsolete.
