### ISSUE TITLE
Is fan type can only be controlled by saying to Google? fan clicking control not support on Home App at present?

### ISSUE THREAD

**Issue by Steven1937** [actions-on-google/smart-home-nodejs#516]
I have linked my fan to Google Home, and I can see my fan on Google Home App. The problem is that I can only control and speed control my fan by saying to Google. I didn't find any button or bar to manually control my fan on Google Home App. Other types of device such as light and socket all can be manually controlled on Google Home App, but I can't find any controlling button for Fan. is there need specific query response for device of fan type? Or Google Home App does not support manually control for Fan type at present?

**Comment by proppy** [comment]
are you experiencing this issue with the sample or your own implementation?
