### ISSUE TITLE
How can I change temperature step of the thermostat type from 0.5degree to 1 degree

### ISSUE THREAD

**Issue by JavaDev99** [actions-on-google/smart-home-nodejs#518]
I use thermostat type and I need to change step of the temperature from 0.5 to 1 degree.
When I says 
`make it cooler`
Google home sends 0.5 degree down but I need to that it will send 1 degree down
I investigated documentation but I didn't find anything helpful
How can I do it?

**Comment by Caprico85** [comment]
This is currently not implemented. Judging by the docs this could be done using [temperatureStepCelsius](https://developers.google.com/assistant/smarthome/traits/temperaturecontrol), I'll see if I can do something about it.

**Comment by JavaDev99** [comment]
Does temperatureStepCelsius setting work with action.devices.traits.TemperatureSetting type or Does it work only with action.devices.traits.TemperatureControl type?

**Comment by Caprico85** [comment]
Good point. Our thermostats use TemperatureSetting, but temperatureStepCelsius is only defined for TemperatureControl. TemperatureSetting does not seem to have something similar. Then I'm currently out of ideas if this is possible.

**Comment by proppy** [comment]
This looks like a feature request for `TemperatureSetting`, I would recommend following the instructions to file an issue on the public issue tracker on https://developers.google.com/assistant/smarthome/support to give it more visibility, as this issue tracker is for filing developer bugs and feature requests with the content of this GitHub repository (Smart Home Node.js sample).
