### ISSUE TITLE
error at create-firebase-config

### ISSUE THREAD

**Issue by rchiarino** [actions-on-google/smart-home-nodejs#522]
Hi, I was just following the README:

### Setup sample service

1. Set up the web portal

```
cd frontend
npm install
npm run create-firebase-config
npm run serve
```

but when I run: 
```
npm run create-firebase-config
```
I got this error:
```
firebase setup:web > ./src/firebase-setup.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-home-frontend@0.0.1 create-firebase-config: `firebase setup:web > ./src/firebase-setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smart-home-frontend@0.0.1 create-firebase-config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

So I have done a bit of research and found that **setup:web** is [deprecated](https://firebase.google.com/docs/cli#management-commands), instead you have to use **apps:sdkconfig** and specify **web** as the platform argument. 

Then I modified the [package.json](https://github.com/actions-on-google/smart-home-frontend/blob/master/package.json), Ln 9, Col 31 to `firebase apps:sdkconfig web > ./src/firebase-setup.js`,

But know I got this:
```
[1m[31mError:[39m[22m There are no WEB apps associated with this Firebase project
```
Inside the generated .js file, 
Went to firebase, configured a WEB, but I still get the same error, so I think im missing something or doing something wrong.
Thanks.

> OS: Windows 10 Home, 19041.630

**Comment by proppy** [comment]
Thanks for the report, we noticed that as well and published a new version of the frontend that should fixes this issue.

(See https://github.com/actions-on-google/smart-home-frontend/commit/5b5dfc403c7e270058d6e4fe68afda7cecb87145 for more details)
