### ISSUE TITLE
Traits for electric consumption report for outlet?

### ISSUE THREAD

**Issue by josecarlosanpedro** [actions-on-google/smart-home-nodejs#525]
Is there a traits for this? I can't find one . Thanks

**Comment by Fleker** [comment]
Do you mean [EnergyStorage](https://developers.google.com/assistant/smarthome/traits/energystorage)?

**Comment by josecarlosanpedro** [comment]
No. EnergyStorage is based on battery right ? but in the consumption. We
want to see how much electricity is used in the specific outlet . like for
the consumption report . how much kilowatt_hour this specific outlet is
used for a day , for a week or for a month. We are building an outlet with
that, so the users can see how much they need to pay with each outlet .

Thanks

**Comment by proppy** [comment]
This issue tracker is for filing developer bugs and feature requests with the content of this GitHub repository (Smart Home Node.js sample).

For filing developer bugs and feature requests with the Actions on Google Smart Home platform, please follow https://developers.google.com/assistant/smarthome/support.

Thanks in advance.
