### ISSUE TITLE
Problems running deploy

### ISSUE THREAD

**Issue by Urigueler** [actions-on-google/smart-home-nodejs#526]
When I call "npm run deploy" from terminal I get near 2000 errors after this commands are executed. 

> smart-home-frontend@0.0.1 lint /home/oriol/Desktop/smart-home-nodejs/frontend
> eslint ./src

Any clues on how to fix this ?

**Comment by jasperrosiers** [comment]
I am experiencing the same issue, having about 2000 errors and 2400 problems. Most of them seem to come from prettier. Did you find a fix yet?

**Comment by proppy** [comment]
I believe this is fixed with https://github.com/actions-on-google/smart-home-frontend/commit/ddab669fd31a68d0c9b9685f97df316d1798c545 can you give it another try?

**Comment by proppy** [comment]
Assuming this was fixed per https://github.com/actions-on-google/smart-home-nodejs/issues/526#issuecomment-758312904, feel free to comment if you still see this issue.

**Comment by hoangtri3796** [comment]
![Capture](https://user-images.githubusercontent.com/39322243/106913278-68424300-6736-11eb-9136-d7c667330da7.PNG)
I checked and followed your guide to fix this problem but it didn't work, still got this issue when running "npm run deploy"

**Comment by proppy** [comment]
@hoangtri3796 can you file a new issue? which platform are you running `npm run deploy` on?
