### ISSUE TITLE
Firebase error on npm run deploy

### ISSUE THREAD

**Issue by Nardol** [actions-on-google/smart-home-nodejs#531]
I followed all the instruction provided in the README file but when running npm run deploy, I have the following error:
"Error: No currently active project.
To run this command, you need to specify a project. You have two options:
- Run this command with --project <alias_or_project_id>.
- Set an active project by running firebase use --add, then rerun this command.
To list all the Firebase projects to which you have access, run firebase projects:list.
To learn about active projects for the CLI, visit https://firebase.google.com/docs/cli#project_aliases

Having trouble? Try firebase [command] --help"
Firstly, I cannot find the firebase binary.
I also tried to modify the deploy command to include my project id but also error.
I didn't find any answer to this question.
What can I do to deploy successfully?
What did I miss in the readme file?

**Comment by Nardol** [comment]
In fact I modified the command to add the firebase login before the deploy --project=<projectid> so I logged in, but after I have the error: Error: Failed to get Firebase project testsmarthome. Please make sure the project exists and your account has permission to access it.
What is wrong here? My project is well-spelled.

**Comment by Nardol** [comment]
In fact it looks like this project is not deployable, there is alway a new error.
After again modifying something I have an error specifying billing is not enabled, i swtiched engine version from 10 to 8 as specified here: https://stackoverflow.com/questions/63932639/400-billing-account-for-project-is-not-found-billing-must-be-enabled-for-activa
And now, I have a 403 when deploying:
"> rollup -c rollup.config.js


src/my-app.js → public...
(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.
created public in 2.4s
✔  hosting: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing . directory for uploading...
i  functions: packaged . (800.08 KB) for uploading
⚠  functions: Upload Error: HTTP Error: 403, Unknown Error

Error: HTTP Error: 403, Unknown Error"
After re-trying, I had the error specifying engine version 8 cannot be used now.
Solving an error creates two new errors...

How could it be possible to deploy this project in fact?
I though the readme file provided all instructions to run this project but it does not seems to be the case.
Or a node version requirement issue?
If someone has successfully deployed and was able to test the project recently, I could be really interested please.

**Comment by proppy** [comment]
@Nardol Thanks for the report, as shown in https://firebase.google.com/support/faq#expandable-9 Firebase Functions now require billing to be turned on for Node.js >= 10, filed https://github.com/actions-on-google/smart-home-nodejs/issues/533 for us to update the documentation.
