### ISSUE TITLE
Need help with reportState implementation

### ISSUE THREAD

**Issue by nazbabu** [actions-on-google/smart-home-nodejs#539]
I'm trying to implement reportState in NodeJs as per the "https://developers.google.com/assistant/smarthome/develop/report-state" documentation. But getting error that the reportState Home graph methods are deprecated in Node.js. Attaching the screenshot of the error details. Please guide what I'm doing wrong here 
![image](https://user-images.githubusercontent.com/84647843/119244506-0c5dc780-bb37-11eb-9d31-9c10219ad25a.png)
![image](https://user-images.githubusercontent.com/84647843/119244601-d79e4000-bb37-11eb-96fc-4d2a1218379f.png)****

**Comment by nazbabu** [comment]
I'm getting "SmartHomeApp.reportState Home Graph wrapper method is deprecated. Use Google APIs Node.js Client for Home Graph: https://www.npmjs.com/package/@googleapis/homegraph". Any idea why I'm getting this error ?

**Comment by Fleker** [comment]
The current `reportState` function will continue to work, but migrating to the separate [HomeGraph](https://www.npmjs.com/package/@googleapis/homegraph) dependency is recommended as it uses a different implementation that scales better and will be automatically kept up-to-date with the updates to the underlying service definition.

The message is not an error, but more of a warning that migration is recommended when you have time.

**Comment by nazbabu** [comment]
Could you please point me to a sample implementation of reportState with new implementation?

**Comment by proppy** [comment]
The docs have been updated to showcase the new client:
https://developers.google.com/assistant/smarthome/develop/report-state#node.js

**Comment by nazbabu** [comment]
How to get the  Auth working ? 
Tried 
const {google} = require('googleapis');
const homegraph = google.homegraph('v1');

const homegraphClient = homegraph({
  version: 'v1',
  auth: new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/homegraph'
  })
});

Now I'm getting following error
TypeError: google.homegraph is not a function
