### ISSUE TITLE
Account linking succeeds, error message is reported in Google Home companion app without SYNC request

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#58]
Realised the last issue was closed - 
same issue here. 
can see `11-06 19:07:38.171  7315 11191 I ActivityManager: START u0 {dat=assistant-handoff://complete/?result_code=SUCCESS&result_message=Accounts+now+linked. cmp=com.google.android.googlequicksearchbox/com.google.android.apps.gsa.assistant.handoff.BrowserControlActivity} from uid 10024 pid 1184 on display 0` - checked my JSON against the validator - all fine, but getting the 'Couldn't update the setting' error on the app.

**Comment by Fleker** [comment]
There's multiple issues with this report. I'm going to use this as a general triage issue.

**Comment by GermanBluefox** [comment]
Just now reset my google home and connected it again. No progress.
I don't need google home, but how can I develop an action without google home?

**Comment by madgeni** [comment]
wanted to update this - in my case, the error was mine. Whilst the JSON payload was correct, i found it only works if it is returned by the original handle, rather than by the function creating the payload.

**Comment by GermanBluefox** [comment]
I must say, that I still have a problem. 

ioBroker has about 10000 installations and I can't connect Google Home to ioBroker. So 10000 ioBroker users will not use Google Home.

I tried another google account too, but the result is the same. **What are the next steps in the investigation?**
My HomeServer and GoogleAction are working with another accounts, but not with mine own.

**Comment by GermanBluefox** [comment]
I asked another people about the logs of Home Server and it is following:
```
return getAccessToken =  { token_type: 'bearer',
  access_token: 'psokmCxKAAA7qHLeYd1',
  refresh_token: 'psokmCxKAAA7qHLeYd1' }
respond success { token_type: 'bearer',
  access_token: 'psokmCxKAAA7qHLeYd1',
  refresh_token: 'psokmCxKAAA7qHLeYd1' }
POST /token 200 2.771 ms - 100
```
here I have no outputs any more, but by other people it continues:
```
post /smarthome { 'x-forwarded-host': 'blabla.de',
  'x-forwarded-proto': 'https',
  'x-forwarded-for': '1.2.3.4',
  host: '2.3.4.5:3000',
  connection: 'close',
  'content-length': '80',
  'content-type': 'application/json;charset=UTF-8',
  'google-assistant-api-version': 'v1',
  authorization: 'Bearer psokmCxKAAA7qHLeYd1',
  'user-agent': 'Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)',
  'accept-encoding': 'gzip,deflate,br' }
post /smarthome { inputs: [ { intent: 'action.devices.SYNC' } ],
  requestId: '12431855741799661390' }
```

**Comment by Stefan300381** [comment]
do I get this right, that this issue here has been closed. Why? I don't see a solution :-( I'd like to underscore GermanBlueFox'es remark about the huge userbase of ioBroker. Amazon's Echo / Alexa product is working fine, but people like to switch to Google Home.

**Comment by Fleker** [comment]
The issue doesn't seem to be tied to specific projects or accounts. I was able to test GermanBlueFox's project without seeing the error. We're still trying to identify why some users see this more than others.

**Comment by madgeni** [comment]
agreed - i've got users who can access their devices, others who can't. Responses to Google are identical (obviously) - so at a loss. Frustrating, as others have said - the randomness of it is causing issues within the community - a lot of them are *desperate* for this to work.

**Comment by niepel1337** [comment]
Hi @Fleker ,
any News?
It's sad to see, that google home is there but we can't use it.
Hope you'll identifyed quickly where the Problem is.

**Comment by Fleker** [comment]
There's a timeout issue happening somewhere. We're still looking into fixes.

**Comment by sveni-lee** [comment]
Hi @Fleker,

**Comment by Fleker** [comment]
As I had stated previously, their project works fine for me. I have not heard any updates from them.

**Comment by GermanBluefox** [comment]
But my account still bring this "no config" error.
It is something with account or device.
How can we investigate it?

2017-12-01 19:07 GMT+01:00 Nick <notifications@github.com>:

**Comment by sveni-lee** [comment]
@GermanBluefox

**Comment by GermanBluefox** [comment]
@sveni-lee I will do that, but I need you gmail address .

**Comment by nibblerrick** [comment]
I like to try, too, I'll send you my address in an PN on the forum.

**Comment by Trapper12** [comment]
Hi guys, first of all many thanks to German Bluefox for trying to connect the Iobroker project to Google. I would use Google home if this project would work (Bluefox did it with Alexa without having such trouble) but now, after nearly a year of discussion and no solution I bought an Amazon echo and installed the Iobroker skill and it works fine. Hooray. Next I will scrap my Google home mini. For me it is incomprehensible that this problem cannot be solved until now. Especially if you look at the struggle between Google and Amazon regarding the smart home, smart skil and so on. For me Google lost and I recommend that all Iobroker users do like me and srap the Google homes and minis. Alexa is working!

**Comment by Stefan300381** [comment]
i must admit that i am confused. whats the current status? are we waiting for someone?

**Comment by Fleker** [comment]
Good morning,
We are still investigating this issue.

This issue will be updated when we have more information.
Thanks for your patience.

**Comment by Trapper12** [comment]
Hi Fleker,
respectfully, what are you waiting for? The problem is fully described and discussed and investigated for so long time now. Google looses customers.

**Comment by huenemeca** [comment]
After reading a lot of comments and pulling some hair out.  I was able to fix my problem.  I found this in my logs:
01-08 19:03:20.697  3100  3735 W Icing   : Ignoring usage report, got bad usage info: Uri too long (max 256)
01-08 19:03:20.832 10035 10035 I chromium: [INFO:CONSOLE(0)] "Navigation is blocked: assistant-handoff://complete/?result_code=FAILURE&result_message=Account+linking+failed", source: https://assistant.google.com/services/auth/handoffs/auth/complete (0)


For me the URL was too long I shortened the url by removing my api password and boom.

It works now.

**Comment by topeysoft** [comment]
When using Android, I saw the message "Account now linked" briefly before redirecting back to Google home interface after completing the Oauth process. But then I get the message  "Couldn't update the settings. Check your connection". I could see on my server that the authorize and token endpoint calls where successful and also the SYNC call came through once with 200 status response and valid payload (I checked the payload using the validator). On iOS, same thing except the SYNC request came through 3 times after the token request and each one with 200 and valid payload. However, I also got "Something went wrong, please try again". So it seems like even though valid payload is returned with 200 status code the process still failed.

**Comment by Fleker** [comment]
@topeysoft can you state which region you are in? US? Europe? Asia?

**Comment by topeysoft** [comment]
Hi Fleker, I'm in the US. 
Also, as an update, I tried it again today with an account that has no device attached to (i.e returns empty array in SYNC response) and it says account link was successful, but it does not show up in the linked accounts list. With that I thought it could be that the payload was still invalid, so I went through each property again and made sure the all required properties are included (per the documentation [here](https://developers.google.com/actions/smarthome/create-app)) still no luck. I added a device to the  account that showed a success message and it stopped working again.

**Comment by Fleker** [comment]
Does your response succeed when using the [SYNC validator tool?](https://developers.google.com/actions/smarthome/tools/validator/)

**Comment by topeysoft** [comment]
No it doesn't

**Comment by Fleker** [comment]
Then you should make sure your response passes the tool, as if it fails there it will not work in production./

**Comment by r4nd0mbr1ck** [comment]
Hi,

I am trying to determine if I am running into the same issue. I have my test project linked and previously synced. However, when I try syncing devices now, I get an error. 

- In the Google Assistant (when using the "Sync my devices" command), I get "An error occurred while syncing <project name>." 

- If I issue a request sync using cURL, I get back a 500 Internal error occurred.

Is there a way for me to look at logs in my Actions on Google project? I couldn't find anywhere that shows debug information.

**Comment by Fleker** [comment]
You should be able to take advantage of logging in StackDriver. You can take a look at [the documentation](https://developers.google.com/actions/smarthome/logging).

**Comment by ash-lat** [comment]
Hi
Its not working for me either, looks like it is not able to sync to /smarthome
keep getting error "POST /smarthome 500 9.289 ms - 1456"
I did enter https://xxxxxxxx.ngrok.io/smarthome to webhook URL in "Smart Home Action" panel
And on google assistant app it links succesfully but throws an error "Something went wrong. Try again"

Attached is log file
[gaerror.txt](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/files/1713219/gaerror.txt)


Just wanted to confirm :- We have to use same client id and secret id as mentioned in config-provider.js? and only change the API key correct?

**Comment by Fleker** [comment]
@ash-lat how are you logging in to the sample? Seems like you're getting some null/undefined exception. Can you break that out to a separate issue as it appears unrelated?

**Comment by ash-lat** [comment]
@Fleker I followed "https://github.com/actions-on-google/actionssdk-smart-home-nodejs#start-testing-on-device"  to log into the sample

I believe it is related to some "Enable Request-Sync API "
so in the agent_user_id I changed it to "213456" instead of "1234" after looking into line#279 in smart-home-app.js
so now my Request Sync API now looks like 
**curl -i -s -k -X POST -H "Content-Type: application/json" -d "{agent_user_id: \"213456"}"  \ "https://homegraph.googleapis.com/v1/devices:requestSync?key=Actual API Key from Home Graph"**
For it to work I changed few spaces up there and had to pass it twice (>) to come out to shell again

But still getting same error ""Something went wrong. Try again" on iOS after succesful login
and "Couldn't update the setting.Check your conncection" on android after succesful login

at the sametime I get below log with error ( POST / 404 3.789 ms - 140) in raspberrypi terminal 
[gaerror2.txt](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/files/1745183/gaerror2.txt)
just like issue #3 

If it is not related to this issue, kindly comment in next post, so I shall open a new issue

Thanks in advance

**Comment by ash-lat** [comment]
@Fleker 
Finally got it working 
This time I forgot to add /smarthome in actions webhook URL "https://xxxxxxxx.ngrok.io/smarthome"

I will open a new issue regarding "bower" getting depricated now

Thanks Again!

**Comment by sresam89** [comment]
Same issue here as well, located in US
using Android, I saw the message "Account now linked" briefly before redirecting back to Google home interface after completing the Oauth process. But then I get the message "Couldn't update the settings. Check your connection". I could also see on my server that the authorize and token endpoint calls where successful and also the SYNC call came through once with 200 status response and valid payload (I checked the payload using the validator).


logs
`login successful  rick
authCode successful  4vej4gmw1e04k44os888884cgo
GET /oauth?response_type=code&client_id=ZxjqWpsYj3&redirect_uri=https://oauth-redirect.googleusercontent.com/r/gatest-5d940&scope=samy+rick+summer&state=CtcCQUJ4dlBibjN5ZDFEMWc4VzQ2Z2VWbVZmWkNwYWhZSWo2TWtKQmhwak81M1pzNmM1MjJ6WDMybFY3LVRyTElXVWJXdDZ2Y191Nkc4VldMYWQteWduQkZGZU9mY2NicU9jMWJhSThkYWtGemduM1Z0RVJDQTkzNnpTUTlSb3p0Uy1wVS11Mnh5eFZWN3RhVHpYMldwa09PdVRvbEZJRUdab01ScnUtYkhSZnpSNXdDamFpREZOQnRLX0JYNnJ2eHExTzZYZ29GZncwLWlfSC1VcnhyYU5FVG5CZXZtbS1fM2V4VTFLRDhkeEhhQUlYMkVqZS16azZCcWJNYWlqUjUzTC11alZUdWczT0tEUnNaTTFqTGxoMEpiLWV5bnlMeGRydG83TjV3MWJYMmhNTXh4MEwyVzhjT3ZSbHpPSDZJOHdaOGp4YUlhaDlWNFloUUFpWXBDem9ETRIcYXNzaXN0YW50LWhhbmRvZmY6Ly9jb21wbGV0ZSI7aHR0cHM6Ly9vYXV0aC1yZWRpcmVjdC5nb29nbGV1c2VyY29udGVudC5jb20vci9nYXRlc3QtNWQ5NDAqEnNyZXNhbTg5QGdtYWlsLmNvbTIQZ2F0ZXN0LTVkOTQwX2Rldg 302 4.918 ms - 1516
/token query {}
/token body { grant_type: 'authorization_code',
  code: '4vej4gmw1e04k44os888884cgo',
  redirect_uri: 'https://oauth-redirect.googleusercontent.com/r/gatest-5d940',
  client_id: 'ZxjqWpsYj3',
  client_secret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
client { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
handleAuthCode {}
getClient ZxjqWpsYj3, hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv
return getClient { clientId: 'ZxjqWpsYj3',
  clientSecret: 'hIMH3uWlMVrqa7FAbKLBoNUMCyLCtv' }
getAccessToken =  { uid: '1234',
  accessToken: 'psokmCxKjfhk7qHLeYd1',
  refreshToken: 'psokmCxKjfhk7qHLeYd1',
  userId: '1234' }
return getAccessToken =  { token_type: 'bearer',
  access_token: 'psokmCxKjfhk7qHLeYd1',
  refresh_token: 'psokmCxKjfhk7qHLeYd1' }
respond success { token_type: 'bearer',
  access_token: 'psokmCxKjfhk7qHLeYd1',
  refresh_token: 'psokmCxKjfhk7qHLeYd1' }
POST /token 200 12.695 ms - 100

`

**Comment by Tdmain** [comment]
> Did your SYNC response include any devices, or was there a formatting error with it?

Where did this conform and why is this here why are accounts missing from me Ross Nicholas oneil thomas. This is my accounts I’m orrery sure. I have docs to prove that
