### ISSUE TITLE
Allow Parameters in OAuth URL

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/smart-home-nodejs#71]
URL parameters in the OAuth url are currently disallowed by Google.  

Per spec if you accept an URL that represents the authorization endpoint than you should accept a query component with existing parameters and retain them when adding more, see [spec](https://tools.ietf.org/html/rfc6749#section-3.1).

Use case:  Auth0 requires the audience parameter to select 'client'. 
#66

**Comment by Fleker** [comment]
Thank you. I'll bring this up with the applicable teams.

**Comment by neuberfran** [comment]
@jenskastensson https://community.auth0.com/t/accesstoken-expiration-for-action-on-google/8823

https://community.auth0.com/t/using-auth0-and-oauth2-to-do-a-google-assistant-app/14900/32
