### ISSUE TITLE
thermostat query reports device as 'off'

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#74]
Hi - querying temp devices works, but always reports the device as 'off', even if i hardcode 'online: true' & 'on: true'
code snippet on my response:
`{"requestId":"7039972611316254476","payload":{"devices":{"473":{"online":true,"on":true,"thermostatMode":"auto","thermostatTemperatureAmbient":0.7}`
any clues on what i'm doing wrong?

**Comment by jenskastensson** [comment]
I had a similar problem with auto mode,  ended up setting it to heating always.

**Comment by madgeni** [comment]
thanks @jenskastensson - if i set it to 'heat' it removes the temperature!!

**Comment by jenskastensson** [comment]
I think I set the available modes in sync to hearing only. What do you
reply in sync?

**Comment by jenskastensson** [comment]
"Heating only"

**Comment by madgeni** [comment]
ah ok, in my sync i have on, off, heat - will try heat only there

**Comment by madgeni** [comment]
no difference

**Comment by Fleker** [comment]
In your query, the `on: true` is irrelevant since that would only be needed for the `OnOff` trait, whereas the Thermostat mode is what is important.

**Comment by madgeni** [comment]
ok, removed that, but still no change - reporting the temp and saying the device is 'off'

**Comment by Fleker** [comment]
In [the documentation](https://developers.google.com/actions/smarthome/traits/temperaturesetting#response):

**off** - "Heating/Cooling activity disabled."
**on** - "If off, on restores the previous mode of the device."

So perhaps the previous thermostat mode has not been set. But _off_ in this case does not mean it is not available, just that it is not cooling or heating.

**Comment by madgeni** [comment]
i've now set the thermostats state to 'on' during scan, but it's made no difference. 
I'd also say that responding with a temperature sensor's (or thermostat's) state, when i've asked for the temperature is odd.

**Comment by Fleker** [comment]
It would make sense to give the temperature along with the current trend. You may know it's 75 degrees, but it gives more context to know if that value is getting higher or lower.

**Comment by madgeni** [comment]
maybe, i guess - but then either I hold state, or Google does. Back to sensors, they won't have a set mode, they will simply understand a temperature. 
I just wonder how useful the thermostat mode is?

**Comment by Fleker** [comment]
In general your cloud service should be responsible for holding the state at the moment.

If you're building a temperature sensor, that is technically not supported by the platform, so you'll have to deal with the current limitations.

**Comment by madgeni** [comment]
moving back to the point of this issue - 
can I get clarity on how to remove the 'device is off' part from 'device is off and temp is 20c'?
I've set the state in the initial sync, and pass back the data during a query - 
`[idx]: { online: true, thermostatMode: 'on', "thermostatTemperatureAmbient": 20 }`

**Comment by Fleker** [comment]
I'm not sure if that capability is available right now, but I will follow up.

**Comment by madgeni** [comment]
hey @Fleker  - any update to this ?

**Comment by Fleker** [comment]
At this moment we don't support general sensors, so you'll still be getting this unusual behavior for the time being.

**Comment by chuneault** [comment]
after hours of test.. I have a solution 

you need to set the same value for setpoint and ambient in QUERY action like this:

"thermostatMode": "heat",
"thermostatTemperatureSetpoint": 25,
"thermostatTemperatureAmbient": 25

and after when I ask for the temp, google report only the ambient degre!!!! 

try it

**Comment by madgeni** [comment]
Thank you very much!!
