### ISSUE TITLE
Temperature values rounding

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#87]
Hi - 
not sure if this is me, but if i pass
`{"requestId":"9156667253918238881","payload":{"devices":{"184":{"thermostatMode":"on","thermostatTemperatureAmbient":21.8}}}}`

Google will respond with "It's currently 22 degrees" - is this expected behaviour? Or am i doing something wrong?

**Comment by Fleker** [comment]
Is this temperature in celcius?

I believe that rounding is expected behavior. It works fine in Fahrenheit as most US thermostats have this level of precision.

**Comment by madgeni** [comment]
Hi, yep, it's in Celsius - I don't understand the precision point - the thermostats usually give me a float with 2 decimal places - but GH is rounding it, which removes that precision. Also, GH converts from F to C.

**Comment by Fleker** [comment]
Assistant may round the number to give a better conversational answer. Saying a long decimal may not make sense. However in Celcius having some extra precision may be useful.

**Comment by madgeni** [comment]
Could it round to 1 decimal place? Then it won't be too long, but gives some precision

**Comment by Fleker** [comment]
I've filed a feature request.

**Comment by proppy** [comment]
Closing as obsolete.
