### ISSUE TITLE
SSL question

### ISSUE THREAD

**Issue by kolayuk** [actions-on-google/smart-home-nodejs#89]
Hi! I planning to expose my smart home backend to internet with public domain, and then to integrate it with google assistant using gactions SDK. But I am not sure if SSL+password protection is secure enough, so I plan to protect it with SSL client certificates on nginx, and my backend will be behind secured nginx. But it seems gactions does not support SSL client certificates isn't it? Or is any way to upload my cert to google to use it in requests?

**Comment by Fleker** [comment]
If you're building a Smart Home you may want to look at the [Smart Home docs](https://developers.google.com/actions/smarthome/) which require an OAuth link between your server and the Google Assistant.
