### ISSUE TITLE
Brighten dim light？

### ISSUE THREAD

**Issue by sunjunlishi** [actions-on-google/smart-home-nodejs#94]
when google assisant to Brighten ,dim or  dim 20% ,or birghten 20%,the cmd is  brightness valuse is same?

**Comment by sunjunlishi** [comment]
![default](https://user-images.githubusercontent.com/11845664/36008131-cc6226ec-0d80-11e8-92d4-7d4ac810eff3.jpg)

**Comment by sunjunlishi** [comment]
brighten two times ,brighten is  14 all the same.

**Comment by Fleker** [comment]
To handle relative brightness changes, you should implement the `QUERY`. The Assistant will query your server to get the current brightness of the light. Then it will send an `EXECUTE` intent with the absolute brightness to set the light.

**Comment by sunjunlishi** [comment]
thanks i will have a try
