### ISSUE TITLE
missing webcomponents-lite.min.js

### ISSUE THREAD

**Issue by orcema** [actions-on-google/smart-home-nodejs#95]
i have only the 

> webcomponents-lite.js

 and 

> webcomponents-lite.**min**.js 

is missing.Does someone else have the same problem ?

**Comment by Fleker** [comment]
Is this giving you an issue?

**Comment by orcema** [comment]
Yes, the login screen didn't load up and i had to change  all the references in the program from 

> webcomponents-lite.min.js

 to 

> webcomponents-lite.js

**Comment by Fleker** [comment]
So was there an error message in the console?

**Comment by orcema** [comment]
the browser got a reply 404 "not found" for this file

**Comment by zoic21** [comment]
I have the same issue, I find how to fiw it : remove ".min" hre : https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/frontend/login.html#L95

**Comment by orcema** [comment]
There are more files concerned, see figure below:
![image](https://user-images.githubusercontent.com/12600222/36031925-a1aa9822-0dac-11e8-9db0-660c29a30eee.png)

**Comment by Fleker** [comment]
Can you determine which version of webcomponents-lite you have installed? It is one of the files that should be installed with Bower.

**Comment by orcema** [comment]
Here is the package.json content for the `webcomponentsjs` folder within `bower_components` folder

> {
  "name": "@webcomponents/webcomponentsjs",
  "version": "1.1.0",
  "description": "Web Components Polyfills",
  "main": "webcomponents-lite.js",
  "directories": {
    "test": "tests"
  },
  "keywords": [
    "webcomponents",
    "web-components",
    "polyfill",
    "shim"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/webcomponents/webcomponentsjs.git"
  },
  "author": "The Polymer Authors",
  "license": "BSD-3-Clause",
  "bugs": {
    "url": "https://github.com/webcomponents/webcomponentsjs/issues"
  },
  "scripts": {
    "build": "gulp",
    "test": "wct"
  },
  "homepage": "https://webcomponents.org/polyfills",
  "devDependencies": {
    "@webcomponents/custom-elements": "^1.0.8",
    "@webcomponents/html-imports": "^1.1.1",
    "@webcomponents/shadycss": "^1.1.1",
    "@webcomponents/shadydom": "^1.0.12",
    "@webcomponents/template": "^1.2.2",
    "@webcomponents/webcomponents-platform": "^1.0.0",
    "babel-preset-minify": "^0.2.0",
    "del": "^3.0.0",
    "es6-promise": "4.1.x",
    "eslint": "^4.16.0",
    "google-closure-compiler": "^20171203.0.0",
    "gulp": "^3.8.8",
    "gulp-add-src": "^0.2.0",
    "gulp-header": "^1.8.9",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.6.4",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-stream": "=1.23",
    "run-sequence": "^2.2.1",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^1.1.2",
    "web-component-tester": "^6.5.0"
  },
  "publishConfig": {
    "access": "public"
  }
}

**Comment by Fleker** [comment]
I guess I'll have to update the imports. webcomponents is now min by default.

https://github.com/webcomponents/webcomponentsjs/issues/765

**Comment by orcema** [comment]
i already updated my files, should i send a pull request?
