### ISSUE TITLE
smart-light.html:98 Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by orcema** [actions-on-google/smart-home-nodejs#98]
Lines 96 and 98 raise errors! I guess for the line 96 it should be 

> this.**$**.light.nameChanged = true;
instead of 
`this.light.nameChanged = true;`

By the way what is the exact purpose of the function **_exec** ?

![image](https://user-images.githubusercontent.com/12600222/36068692-532e8e44-0edb-11e8-88d1-affadcbf4181.png)

**Comment by orcema** [comment]
The call to the super class is missing.

> _exec(nameChanged) {
                **super._exec();**
                if (nameChanged) {
                    this.light.nameChanged = true;
                } else {
                    this.$.deviceIcon.style.color = '#eee';
                }
                this.$.brightness.disabled = !this.device.states.on;

Without this call to the super class, the state change to the lamp is executed on the client web page. If you then ask google for the lamp state, the given response is wrong !

**Comment by Fleker** [comment]
`_exec` is called when changes are made locally, to send those changes to the cloud provider.

You do seem to be correct that the super class method has not been called.

**Comment by orcema** [comment]
if the super class method should be called,why do you need this part of the code ?

> if (nameChanged) {
this.light.nameChanged = true;
} else {
this.$.deviceIcon.style.color = '#eee';
}
this.$.brightness.disabled = !this.device.states.on;

**Comment by Fleker** [comment]
For instance, that is no longer calling [`this._callSmartHomeProviderCloud`](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/smart-home-provider/frontend/src/smart-device.html#L276). Although the current implementation may be redundant in some ways as well.
